### ISSUE TITLE
Is there a way to set a different theme for the code chunks?

### ISSUE THREAD

**Issue by pssguy** [rstudio/blogdown#10]
Like the many alternatives in RStudio?

Another home run BTW

**Comment by yihui** [comment]
Yes, you just pick a Hugo theme that supports highlight.js (or do it yourself), then pick a syntax highlighting theme for highlight.js and insert the correct CSS to the Hugo theme. Before the blogdown documentation is complete, you have to do some research by yourself.

**Comment by pssguy** [comment]
@yihui HaHa. Whenever an expert uses the word 'just' or 'simply' I head for the hills. For instance, tried changing and saving something in the add-on.css of the default theme and when the blog was rebuilt it reverted to former value??

Are you planning to document as a bookdown book?

**Comment by yihui** [comment]
Yes, it will be a bookdown book.

I know I should refrain from using "just" and "simply". Sometimes I just/simply forget it...

**Comment by jsonbecker** [comment]
@pssguy this may be helpful, [the Hugo docs on syntax highlighting](https://gohugo.io/extras/highlighting/)

For my Hugo blog, I have a syntax-highlighter css (in my case, `tomorrow-night-bright.css`) in `themes/jsonbecker/static/css/`

Under `themes/jsonbecker/layouts/partials/` in my `header.html` which is at the top of each post/page I have the following:

```html
<link rel="stylesheet" href="{{ .Site.BaseURL }}/css/tomorrow-night-bright.css">
<script src="{{ .Site.BaseURL }}/js/highlight.pack.js"></script>
  <script>
    hljs.initHighlightingOnLoad();
  </script>
```

Then you can just change what syntax highlight CSS you're using and change that on the header and you're good to go.

**Comment by pssguy** [comment]
@jsonbecker Thanks for info.. BTW I spotted a 'just'

**Comment by pat-s** [comment]
I just adapted the approach from @jsonbecker using the `highlight.js` lib. While this works fine in a real browser (Safari), the RStudio browser does not apply the syntax highlighting when using `blowdown::serve_site()`. 

I added the following at the end of `header.html`, placed `highlight.pack.js` in `themes/.../js` and `dracula.css` in `themes/.../css`

```html
<link rel="stylesheet" href="{{ .Site.BaseURL }}/css/dracula.css">
<script src="{{ .Site.BaseURL }}/js/highlight.pack.js"></script>
<script>
  hljs.initHighlightingOnLoad();
</script> 
```

**Comment by yihui** [comment]
@pat-s How about changing `{{ .Site.BaseURL }}/` to `{{ .Site.BaseURL }}`? i.e. remove the slash.

**Comment by pat-s** [comment]
@yihui Removing the slash did not make a difference (removed it from the .css and .js). [Here](https://github.com/pat-s/Website) is the source repo.

**Comment by yihui** [comment]
@pat-s Not sure what you did exactly, but I just sent you a PR https://github.com/pat-s/Website/pull/1/files

**Comment by yihui** [comment]
Restarting the R session should be enough. Anyway, glad to know it works now.

**Comment by yihui** [comment]
For those who want to seriously hack at Hugo, I strongly recommend you to read this section in the blogdown book: https://bookdown.org/yihui/blogdown/templates.html I just spent a whole week on creating a minimal theme and documenting it to help you understand how things such as syntax highlighting work.

**Comment by kandelvijaya** [comment]
Thanks for the discussion. I finally got the hugo syntax coloring manually.
