### ISSUE TITLE
Figures from RMarkdown

### ISSUE THREAD

**Issue by cpfiffer** [rstudio/blogdown#101]
I'm having a bit of an issue with figures from RMD files. When the site is built into `public`, the figures generated from code chunks goes to `public/post/`, and the html files in the actual post still refers to images as if they were in the shared folder with the directory: `public/2017/05/01/random-post-title/figs`. This is resulting in missing images from public html files. 

I've included the entire directory of my blog post for an example. The directory `web/public/2017/05/01/2017-05-01-credit-risk-neural-networks` is an example of a document that should either have the figures located in the post directory or have the image reference changed. The images are towards the bottom of the post.

[web.zip](https://github.com/rstudio/blogdown/files/968430/web.zip)

I hope this is an actual issue and not just me failing to do due diligence properly. I combed through a fair bit of the documentation and either didn't see anything or didn't understand if I did see anything. I love this repo, by the way, and I'm glad it's so well kept!

**Comment by yihui** [comment]
You should not set `fig.path='Figs/'`. blogdown relies on the default `fig.path` to be able to detect figures.

**Comment by cpfiffer** [comment]
Wow, that was a very stupid error. I must have copy/pasted that in. Thank you for stooping to my level!

**Comment by yihui** [comment]
That is definitely not stupid. I should have documented it (and will do it).

**Comment by cpfiffer** [comment]
Cool, thank you! Again, I absolutely love this module and RMarkdown as a whole. It's an amazing workflow. Blows Jupyter out of the water.
