### ISSUE TITLE
utf8

### ISSUE THREAD

**Issue by tormodb** [rstudio/blogdown#108]
Thanks for this great package. I have managed to put up a first blog using your instructions. I ran into one issue, however. When saving files in UTF8 format (default for my locale), bookdown (I presume) writes the file to a new folder, i.e. about.utf8 rather than about. The original about file is then not being "marked up" but rather renders as:

+++ title = “About” date = “2014-04-09” sidemenu = “true” description = “About me and this site” +++

and the site does now show the correctly marked up file residing in the about.utf8 folder.

**Comment by tormodb** [comment]
May have found the solution by: rmarkdown::render_site(encoding = 'UTF-8')

**Comment by yihui** [comment]
Is there a reason you don't want to use `blogdown::serve_site()`? https://bookdown.org/yihui/blogdown/rstudio-ide.html

**Comment by tormodb** [comment]
I was under the (perhaps wrong) impression that I had to build the site before I could push updates to bitbucket (and on to netlify). I am no programmer, and it is almost 100% certain that any errors are my own fault, but I just wanted to bring your attention to the issue about the automatic creation of the .utf8 folders in the unlikely case you hadn't come across this before.
