### ISSUE TITLE
Support for R Notebooks?

### ISSUE THREAD

**Issue by nickforr** [rstudio/blogdown#11]
Wondered if there were plans to support notebooks as well as plain rmd files?  Briefly tried including these in the template version in the package but they don't render as blogposts.

**Comment by yihui** [comment]
May I ask why do you need the notebook support? The only thing I can think of is the ability to download the Rmd source from the HTML page.

**Comment by nickforr** [comment]
I'd been thinking along the lines of an internal 'blog' site at work for sharing both insights (mainly to those not interested in R, just in the output - so not showing all the code used would be important here) and the underlying code (there's a range of familiarity and experience with R and with git / source control so having somewhere where the notebook code could be easily downloaded could be a helpful way of giving people a head start).

**Comment by mwillumz** [comment]
It's early and I'm patient but this'd be my ideal use also.  Even better if it plays nice with shiny and authentication in connect/shiny pro. 

I see similarities to airbnb's knowledge repo

**Comment by nickforr** [comment]
@mwillumz you've been reading the same blogs as I have!!

**Comment by yihui** [comment]
I see. Showing/hiding source code is relatively easy, and the tricky part is always external dependencies of the Rmd document, such as the data files. If the data is small, we can probably just read it via http(s). I'm not sure how Airbnb solves this problem in their knowledge repo. One possibility, of course, is to ask whomever interested in the analysis to clone the whole repo.

**Comment by nickforr** [comment]
@yihui referencing an issue thread I saw somewhere else where you were involved, when you say 'relatively easy'...how should I interpret that? :-) 
If there is a fairly straightforward way to ensure that rmd code chunks appeared with a conditional button in the html then that would be ideal...

**Comment by yihui** [comment]
Toggling R code chunks can be easily implemented in JavaScript, and I wrote this example a few years ago: https://github.com/yihui/knitr/blob/master/inst/misc/toggleR.js

**Comment by pssguy** [comment]
I'm trying to write a blog (with blogdown) that incorporates code and interactive htmlwidgets. It would certainly be helpful to have anything that makes code for individual posts easier to download and also the ability in the notebook  format to switch between different outputs within one chunk. + the toggling code as mentioned above

**Comment by jsonbecker** [comment]
Pelican lets you copy the md source to the same output directory as the processed HTML. If that's not available in Hugo, I'd be surprised. It might be nice to have a build option that copies the .Rmd file into the landing place in `public` so that with a "show source" option or similar, users can just edit the URL and add .Rmd at the end to see the source (or you could easily add a relative link to the Rmd file in your own post content).

Toggling source in line though shouldn't be that terrible as was already stated though.

**Comment by yihui** [comment]
It is definitely possible to copy the Rmd, and I think a better solution is to add a link that points to the source Rmd in a Github repo (or whatever hosting platform), just like what bookdown does.

**Comment by yihui** [comment]
I have explained how to add a link/button to the Rmd source on Github in this section: https://bookdown.org/yihui/blogdown/templates.html This section is quite substantial, so it may take you a while to digest. But after you understand the minimal theme introduced there, you should be able to understand Hugo much better.

**Comment by nickforr** [comment]
Thanks
