### ISSUE TITLE
specify pandoc extensions for .Rmd?

### ISSUE THREAD

**Issue by cboettig** [rstudio/blogdown#110]
Is it possible to specify pandoc extensions to be used when rendering .Rmd files?  (e.g. I'd love to have `markdown+startnum` as a pandoc option.  

Thanks!

**Comment by yihui** [comment]
Yes, you can use the `md_extensions` argument of `blogdown::html_page` inherited from `rmarkdown::html_document`: https://bookdown.org/yihui/blogdown/output-format.html

**Comment by cboettig** [comment]
Perfect, thanks (guess I forgot to close this!)
