### ISSUE TITLE
empty_site()

### ISSUE THREAD

**Issue by butterflyology** [rstudio/blogdown#111]
Learning `blogdown` and had a request. `blogdown::new_site()` creates a new site but is filled with some unneeded pages that require manual removal. It would be a nice thing to have a function `empty_site` that creates the required backbone for a site but omits the superfluous pages. 

I will have time next month to work on this if anyone thinks this is worthwhile.

**Comment by butterflyology** [comment]
After further review, this issue is trivial. It take 5 seconds to delete the extra pages.

**Comment by yihui** [comment]
I think `new_site(sample = FALSE, theme_example = FALSE)` is what you want.
