### ISSUE TITLE
the location of figure is incorrect

### ISSUE THREAD

**Issue by qiubio** [rstudio/blogdown#113]
Hi Yihui,

Thank you for the great package. I have some trouble in get correct figure links generated by Rmd file.

for example the hyperlink should be /public/post/2017-05-28-post_name_files/figure-html/figure.png
but in the html, the hyperlink still keep as /public/2017/05/28/post_name/2017-05-28-post_name_files/figure-html/figure.png

I test by a Rmd file without Chinese character in the title, there is no problem to see the figure.

did I missing something? Thank you.

**Comment by yihui** [comment]
It might be because you used Chinese characters in your filename.

**Comment by qiubio** [comment]
Yes, I found that. Is it difficult to fix this?

**Comment by yihui** [comment]
It is difficult for me, because this is not my issue but Hugo's. It has to be fixed upstream.

**Comment by qiubio** [comment]
I got it. Thank you for the package. I learned a lot from it.
