### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by sumandoc** [rstudio/blogdown#115]
Hi there,

I am on Windows 10 64 bit system and installed R-3.4.0 patched with Rtools34.

I tried to install blogdown, but I landed with this error.

>
>  devtools::install_github('rstudio/blogdown')
> Downloading GitHub repo rstudio/blogdown@master
> from URL https://api.github.com/repos/rstudio/blogdown/zipball/master
> Installing blogdown
> "C:/PROGRA~1/R/R-34~1.0PA/bin/x64/R" --no-site-file --no-environ --no-save  \
>   --no-restore --quiet CMD INSTALL  \
>   "C:/Users/Suman/AppData/Local/Temp/Rtmp6H3CD6/devtools21045286335e/rstudio-blogdown-a367835"  \
>   --library="C:/Users/Suman/R/win-library/3.4" --install-tests
> 
> * installing *source* package 'blogdown' ...
> ** R
> ** inst
> ** tests
> ** preparing package for lazy loading
> Error in runHook(".onLoad", env, package.lib, package) :
>   cannot open file 'C:/Users/Suman/R/win-library/3.4/bookdown/R/bookdown.rdb': No such file or directory
> Error : unable to load R code in package 'blogdown'
> ERROR: lazy loading failed for package 'blogdown'
> * removing 'C:/Users/Suman/R/win-library/3.4/blogdown'
> Installation failed: Command failed (1)
> 

How to solve it? I am lost. Have tried uninstalling and installing but no luck.

Regards,

**Comment by yihui** [comment]
Could you run [`update.packages(ask = FALSE, checkBuilt = TRUE)`](https://yihui.name/en/2017/05/when-in-doubt-upgrade/) before `devtools::install_github('rstudio/blogdown')`? If it still fails, try `install.packages('bookdown')` and then `devtools::install_github('rstudio/blogdown')`.

**Comment by sumandoc** [comment]
I removed the folder where R packages are installed, in my system the folder *(C:\Users\Suman\R\win-library\3.4)*. And reinstalled devtools and then blogdown. The problem got resolved after that. I am enjoying **blogdown**!! Thanks!

**Comment by yihui** [comment]
Glad to know that.!

**Comment by bennour007** [comment]
THANK YOU SO MUCH. this issue should be documented in the github page of the package :D
