### ISSUE TITLE
Add R command to Rmd in a post

### ISSUE THREAD

**Issue by binxiangni** [rstudio/blogdown#117]
I try to post a Rmd with a chunk of R code:

> library(Matrix)

>showClass("sparseMatrix")

I use build_site() to update the public folder. But error occurs:

> Error in eval(expr, envir, enclos) : could not find function "showClass"

> Calls: local ... handle -> withCallingHandlers -> withVisible -> eval -> eval.

I can't figure out where error comes from, since I knit the Rmd and it works.

**Comment by yihui** [comment]
You need `library(methods)`.
