### ISSUE TITLE
Leaflet tile not showing

### ISSUE THREAD

**Issue by ThierryO** [rstudio/blogdown#119]
I'm trying to display a leaflet map in a blogdown post. The site uses the default hugo-litium-theme. The data of the map shows. The background image is visible in the RStudio preview but not in the browser. Below is a MWE.

    ---
    title: leaflet
    author: Thierry Onkelinx
    date: '2017-06-09'
    slug: leaflet
    categories: []
    tags: []
    ---
    
    ```{r echo = FALSE}
    library(leaflet)
    leaflet() %>%
      addTiles() %>%  # Add default OpenStreetMap map tiles
      addMarkers(lng = 174.768, lat = -36.852, popup = "The birthplace of R")
    ```

I encountered the same problem with html slides using reveal.js. The solution for that problem was to add extra css: https://gist.github.com/perliedman/9d42f6d1d6583e882df7ae9e95252c0d

**Comment by yihui** [comment]
Not reproducible to me. [Is everything up-to-date?](https://yihui.name/en/2017/05/when-in-doubt-upgrade/) e.g. `update.packages(ask = FALSE, checkBuilt = TRUE)`

**Comment by ThierryO** [comment]
updating all packages solved the problem.

**Comment by DataStrategist** [comment]
What could be the issue if leaflet renders perfectly locally, but when pushed to netlify no part of the leaflet renders (even though in "Inspect Element" the widget is clearly visible... just doesn't display anything)? 

Does one need to manually install packages in netlify somehow?

**Comment by mxblsdl** [comment]
Recently struggled with this same problem. Updated all of the packages on my machine and still leaflet was not rendering. Found a solution by using the [widgetframe library](https://cran.r-project.org/web/packages/widgetframe/vignettes/widgetframe_and_knitr.html) and wrapping the leaflet object in a widgetframe.

```
l <- leaflet() %>%
addTiles()

widgetframe(l, width = "100%")
```
I believe this has something to do with the underlying pyramid files that leaflet creates locally to display map tiles. Widgetframe appears to create a folder to store these in while leaflet native just creates temp files.

**Comment by yihui** [comment]
For future visitors to this issue, please see #20.
