### ISSUE TITLE
Different output using blogdown::serve_site() versus blogdown::build_site()

### ISSUE THREAD

**Issue by OliverBLMS** [rstudio/blogdown#120]
I'm using my own webserver to deploy my hugo-based blog. It is indeed as simple as copying the files under the `public/ folder` to the proper (sub)folder on the webserver, in most cases this will be the web folder.

When I build my site with `blogdown::serve_site()` and copy the content of `public/ folder`  I'll get a perfect result. However, I want to use the `baseurl` parameter (for disqus) so I must use the `blogdown::build_site()` function. I do the same proces as above and copy the content of `public/ folder` to my webfolder, but with the result that my site's layout is not correct and I only see text with no markup.

**Comment by OliverBLMS** [comment]
Using `blogdown::hugo_buid()` specifies the correct full paths, e.g. for the social share on twitter/fb/google, but I have still a problem with Disqus, which is still not loading.

 ```
 var disqus_shortname = 'my_name';
  var disqus_identifier = 'http:\/\/knowyourdata.be\/makeovermonday-challenge\/';
  var disqus_title = 'MakeOverMonday Challenge';
  var disqus_url = 'http:\/\/knowyourdata.be\/makeovermonday-challenge\/';
```

**Comment by OliverBLMS** [comment]
documentation of disqus shortname was not clear for me. It is fixed now

**Comment by yihui** [comment]
If you [publish on Netlify](https://bookdown.org/yihui/blogdown/deployment.html) as I recommended, there is nothing to worry about, otherwise you have to read the docs before you DIY:

- https://bookdown.org/yihui/blogdown/workflow.html
- https://bookdown.org/yihui/blogdown/local-preview.html
