### ISSUE TITLE
Not compiling when changing theme

### ISSUE THREAD

**Issue by emdelponte** [rstudio/blogdown#121]
Hi Yihui,
I am getting this error when I change the theme from lithium to the academic. Also fail for other themes. 

Started building sites ...
ERROR 2017/06/13 09:09:16 Error while rendering "page": template: theme/_default/single.html:10:7: executing "theme/_default/single.html" at <partial "article_met...>: error calling partial: template: theme/partials/article_metadata.html:7:24: executing "theme/partials/article_metadata.html" at <$.Site.Params.date_f...>: invalid value; expected string
Serving the directory /Users/emersondelponte/Dropbox/websites/hugo-site at http://127.0.0.1:4321

**Comment by emdelponte** [comment]
I think I got it. Do I need to use the config.toml exactly as it is the example site dir? it did not work anyway. Perhaps need to change some paths.

**Comment by yihui** [comment]
Please read the second paragraph on this page: https://bookdown.org/yihui/blogdown/other-themes.html

**Comment by emdelponte** [comment]
Thanks! great material. Keep up with the good work.
