### ISSUE TITLE
Mathjax does not work in blogdown-yihui-template

### ISSUE THREAD

**Issue by sierxue** [rstudio/blogdown#122]
I tried https://github.com/yihui/blogdown-yihui-template yesterday. When I issue blogdown::serve_site() in Rstudio, everything works like a charm except that mathjax does not work. I looked into the config, and I found differences from that in the default site generated by blogdown::new_site(). First, config file format is different: in blogdown-yihui-template, the file name is **config.yaml**; in the default site, the file name is **config.toml**. Second, in  blogdown-yihui-template, mathjax is not included while it's included in the default site. 

I added the following two lines in config.yaml after the block of configuring highlight.js,
```
MathJaxCDN: "//cdn.bootcss.com" 
MathJaxVersion: "2.7.1" 
```
Unfortunately, this does not work. How to make mathjax workable in blogdown-yihui-template? 

Thanks!

**Comment by sierxue** [comment]
After read https://support.rbind.io/2017/04/25/yihui-website/, and https://github.com/rstudio/blogdown/issues/79, I made a test.Rmd post, then run blogdown::build(), and then run blogdown::serve_site(), in this case, mathjax works, but then in the index.html page, there are duplicated posts. And the I found that there are three files in the "content" directory with the same filename but different format: Rmd, md, and html.

**Comment by yihui** [comment]
I need to update the theme submodule. Please clone the repo again and try it.

**Comment by sierxue** [comment]
It works perfectly now! Thanksss!
