### ISSUE TITLE
R package readme's creating unwanted posts

### ISSUE THREAD

**Issue by ciflikli** [rstudio/blogdown#123]
Hello,

I just built a new website using your package and it's great.

Not completely sure if this is a `blogdown` issue per se, but one of the R packages (`sunburstR`) I use for visualisation creates several directories under the public/post/*_files/ folder. I believe this is intended behaviour as other packages (e.g. `htmlwidgets` etc.) also put some files there.

However, the readme.md ends up getting rendered as an _additional_ post. This is probably not intended behaviour? If possible, how can I make `blogdown` ignore such files? Thank you.

**Comment by yihui** [comment]
You should ignore `_files` in config.toml: https://bookdown.org/yihui/blogdown/configuration.html#options
