### ISSUE TITLE
How to update Hugo by blogdown::install_hugo() on Ubuntu 16.04？

### ISSUE THREAD

**Issue by sierxue** [rstudio/blogdown#126]
Hugo has been installed by blogdown::install_hugo(). The version now is **Hugo Static Site Generator v0.22.1 linux/amd64 BuildDate: 2017-06-16T03:10:29+08:00**.

I would like to upgrade to latest version V0.24, how can I do it?

**Comment by yihui** [comment]
Please see the documentation here: https://bookdown.org/yihui/blogdown/installation.html

**Comment by sierxue** [comment]
Greatly appreciate your help! Following the documentation,  it has been upgraded to Version 0.24 by `blogdown::install_hugo(force = TRUE, version = "latest").`
