### ISSUE TITLE
subpaths for projects in separate repositories

### ISSUE THREAD

**Issue by atyre2** [rstudio/blogdown#128]
In section 3.3 of the book one advantage of GitHub pages over deploying with Netlify is that you can have different repositories as subpaths, e.g. my.domain.net/proj-a/, instead of having to use subdomains for each project. 

I have repositories with R packages that I use pkgdown on, and a book project that uses bookdown. I set the output directory to be a subdirectory under static/ in the website source directory. Using `serve_site()` it appears to work so I can look at mydomain.net/proj-a/ . 

I haven't tried deploying to netlify yet, but is there something I'm missing that makes this a bad idea?

**Comment by yihui** [comment]
I think this should work. You have to make sure the subdirectories under `static/` do not conflict with your main blogdown/Hugo site, i.e., Hugo won't generate any files that could possibly overwrite those generated by pkgdown/bookdown, and vice versa.

**Comment by yihui** [comment]
This has been documented at https://bookdown.org/yihui/blogdown/static-files.html
