### ISSUE TITLE
install_theme() should prefer curl

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/blogdown#13]
install_theme() fails when verifying github's certificate. This is probably a MacOS-specific issue related to the wget port. Could be resolved by changing how `download.file()` `method` is selected in download2() - to prefer `curl` over `wget`.

```
> install_theme('jbub/ghostwriter')
--2016-11-20 12:10:59--  https://github.com/jbub/ghostwriter/archive/master.zip
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
ERROR: cannot verify github.com's certificate, issued by ‘CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to github.com insecurely, use `--no-check-certificate'.
Do not forget to change the 'theme' option in 'config.yaml' to "ghostwriter"
Warning messages:
1: In download.file(url, method = method, ...) :
  download had nonzero exit status
2: In utils::unzip(zipfile) : error 1 in extracting from zip file
```

**Comment by yihui** [comment]
Weird. I also have both wget and curl but wget works okay for me. Anyway, I just switched the order as you suggested. Thanks!

**Comment by petrbouchal** [comment]
Thanks. I tried fixing but you were faster. Also, downloader might be a more elegant solution further down the road?

**Comment by yihui** [comment]
The `download2` function in this package is simple enough and I guess it is not worth introducing a dependency. It has to be there due to a base R bug, and the person who introduced the bug promised to fix it in the future.
