### ISSUE TITLE
Site not rendering fully on Netlify

### ISSUE THREAD

**Issue by bryanwhiting** [rstudio/blogdown#131]
Thanks for the awesome package! Just switched from Jekyll and I'm not going back.

I'm using the [hugo-universal-theme](https://github.com/devcows/hugo-universal-theme). The theme works perfectly locally, but when I deploy it on Netlify using either `hugo_0.19` or `hugo` as the build command, the site doesn't fully render the CSS. Any thoughts?

Here's my [site](www.tailoredata.com)
Here's my [repo](https://github.com/bryanwhiting/tailoredata)

If there's anything else I should include here, please let me know.

Thanks,

Bryan

## Preview locally:

<img width="1233" alt="screen shot 2017-06-29 at 5 42 46 pm" src="https://user-images.githubusercontent.com/18710907/27711872-87234c12-5cf2-11e7-89c0-1b5412562613.png">

## After hosted on Netlify:

<img width="1208" alt="screen shot 2017-06-29 at 5 42 16 pm" src="https://user-images.githubusercontent.com/18710907/27711864-820dc59a-5cf2-11e7-99c8-b9b7e7f46ab3.png">

**Comment by bryanwhiting** [comment]
This is

**Comment by bryanwhiting** [comment]
Sorry - I slipped and clicked the "close" button. This issue is still active.

**Comment by yihui** [comment]
https://bookdown.org/yihui/blogdown/configuration.html#options

**Comment by bryanwhiting** [comment]
Thanks! I realized my baseurl: was wrong in my config file. Updating that to be my custom URL solved the issue.
