### ISSUE TITLE
R Markdown not rendering with Tranquilpeak on Netlify

### ISSUE THREAD

**Issue by bryanwhiting** [rstudio/blogdown#132]
My R Markdown files will build locally, but they're not appearing when the site is published on Netlify.

* Here's my [blog site](https://www.bryanwhiting.com/)
* Here's my [blog repo](https://github.com/bryanwhiting/blog). You'll notice [this Rmd post](https://github.com/bryanwhiting/blog/blob/master/content/post/2017-02-10-ggplot-plotly.Rmd) isn't appearing in the blog site.
* I'm using the [Tranquilpeak theme](https://github.com/kakawait/hugo-tranquilpeak-theme) and the blogdown `build_site()` command locally before I push to GitHub 
* I'm hosting on Netlify using the `hugo_0.19` build command

I noticed @rlucas11 in https://github.com/rstudio/blogdown/issues/92 has success with R Markdown, but I wonder where that site was hosted.

**Comment by rlucas11** [comment]
Mine is hosted here: https://github.com/rlucas11/rlucas11

I'm only working with .Rmd files and they seem to work fine. Take a look to see if that helps.

**Comment by yihui** [comment]
If `build_site()` was successful, you should have `2017-02-10-ggplot-plotly.html` along with `2017-02-10-ggplot-plotly.Rmd`, and the HTML file as well as any new files under `static/` should be pushed to Github.

**Comment by bryanwhiting** [comment]
The `build_site()` command does create `2017-02-10-ggplot-plotly.html` and the folder `2017-02-10-ggplot-plotly/` in `blogdown/`. The `.Rmd` file remains in the `content/post/` folder, and I don't see it anywhere else. In `public/`, the post `2017/02/the-dataviz-battle-plotly-vs-ggplot2/index.html` exists as well ([linked here](https://github.com/bryanwhiting/blog/tree/master/public/2017/02/the-dataviz-battle-plotly-vs-ggplot2)). 

This all looks just like what @rlucas11 has, except my post has a `figures/` folder. @rlucas11, are you using GitHub Pages or Netlify to host?

I tried [two new Rmd posts](https://github.com/bryanwhiting/blog/tree/master/public/2017/07)  as a test to see if maybe `plotly` or my figures were throwing things off. One post has a simple histogram figure, and the other is just plain text. Neither of these are rendering on Netlify, though they both work locally. I don't get a build error on Netlify.

There are no new files created in `static/`. Is this the problem?

**Comment by rlucas11** [comment]
I'm using github to host; but don't know what other differences there are that would cause this.

**Comment by yihui** [comment]
@bryanwhiting You might be using a very old version of blogdown. [When in doubt, update.](https://yihui.name/en/2017/05/when-in-doubt-upgrade/). 

```r
devtools::install_github('rstudio/blogdown')
```

Next time please remember to post your `devtools::session_info('blogdown')`.

**Comment by bryanwhiting** [comment]
Thanks, that's likely the problem, but I'm having hugo version issues now after upgrading everything (see below).


To document, here's what my session_info() was as of the time of my last post (clearly out of date):
```
> devtools::session_info('blogdown')
Session info -----------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2017-07-05                  

Packages ---------------------------------------------------------------------------------------
 package   * version date       source                           
 backports   1.0.5   2017-01-18 cran (@1.0.5)                    
 base64enc   0.1-3   2015-07-28 CRAN (R 3.3.0)                   
 bitops      1.0-6   2013-08-17 CRAN (R 3.3.0)                   
 blogdown  * 0.0.21  2017-02-11 Github (rstudio/blogdown@35dc95a)
 bookdown    0.3     2016-11-28 cran (@0.3)                      
 caTools     1.17.1  2014-09-10 CRAN (R 3.3.0)                   
 digest      0.6.10  2016-08-02 CRAN (R 3.3.0)                   
 evaluate    0.10    2016-10-11 CRAN (R 3.3.0)                   
 highr       0.6     2016-05-09 CRAN (R 3.3.0)                   
 htmltools   0.3.5   2016-03-21 CRAN (R 3.3.0)                   
 httpuv      1.3.3   2015-08-04 CRAN (R 3.3.0)                   
 jsonlite    1.2     2016-12-31 cran (@1.2)                      
 knitr       1.15.1  2016-11-22 CRAN (R 3.3.2)                   
 magrittr  * 1.5     2014-11-22 CRAN (R 3.3.0)                   
 markdown  * 0.7.7   2015-04-22 CRAN (R 3.3.0)                   
 mime        0.5     2016-07-07 CRAN (R 3.3.0)                   
 Rcpp        0.12.8  2016-11-17 CRAN (R 3.3.2)                   
 rmarkdown   1.3     2016-12-21 cran (@1.3)                      
 rprojroot   1.2     2017-01-16 cran (@1.2)                      
 servr       0.5     2016-12-10 cran (@0.5)                      
 stringi     1.1.2   2016-10-01 CRAN (R 3.3.0)                   
 stringr   * 1.1.0   2016-08-19 CRAN (R 3.3.0)                   
 yaml        2.1.14  2016-11-12 CRAN (R 3.3.2)    
```

This morning I've installed the latest R version `3.4.0`, ran `>brew upgrade`,  re-installed blogdown, and ran `blogdown::update_hugo()`, as per your [installation instructions](https://bookdown.org/yihui/blogdown/installation.html).

I now have this as my `devtools::session_info('blogdown')`:
```
> devtools::session_info('blogdown')
Session info ----------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2017-07-05                  

Packages --------------------------------------------------------------------------------------
 package   * version date       source                           
 backports   1.1.0   2017-05-22 cran (@1.1.0)                    
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.0)                   
 bitops      1.0-6   2013-08-17 cran (@1.0-6)                    
 blogdown  * 0.0.49  2017-07-05 Github (rstudio/blogdown@f7734a8)
 bookdown    0.4     2017-05-20 cran (@0.4)                      
 caTools     1.17.1  2014-09-10 cran (@1.17.1)                   
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0)                   
 evaluate    0.10.1  2017-06-24 cran (@0.10.1)                   
 graphics  * 3.4.0   2017-04-21 local                            
 grDevices * 3.4.0   2017-04-21 local                            
 highr       0.6     2016-05-09 cran (@0.6)                      
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)                   
 httpuv      1.3.5   2017-07-04 CRAN (R 3.4.0)                   
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.0)                   
 knitr       1.16    2017-05-18 cran (@1.16)                     
 magrittr    1.5     2014-11-22 CRAN (R 3.4.0)                   
 markdown    0.8     2017-04-20 cran (@0.8)                      
 methods   * 3.4.0   2017-04-21 local                            
 mime        0.5     2016-07-07 CRAN (R 3.4.0)                   
 Rcpp        0.12.11 2017-05-22 CRAN (R 3.4.0)                   
 rmarkdown   1.6     2017-06-15 cran (@1.6)                      
 rprojroot   1.2     2017-01-16 cran (@1.2)                      
 servr       0.6     2017-05-12 cran (@0.6)                      
 stats     * 3.4.0   2017-04-21 local                            
 stringi     1.1.5   2017-04-07 CRAN (R 3.4.0)                   
 stringr     1.2.0   2017-02-18 CRAN (R 3.4.0)                   
 tools       3.4.0   2017-04-21 local                            
 utils     * 3.4.0   2017-04-21 local                            
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.0)   
```

But now I'm getting the following error during `build_site()` and `serve_site()`. 

```
ERROR: 2017/07/05 08:40:34 hugo.go:365: Current theme does not support Hugo version 0.18.1. Minimum version required is 0.2
Started building sites ...
ERROR: 2017/07/05 08:40:34 template.go:495: Failed to add template theme/partials/footer.html in path /Users/bryanwhiting/github/blog/themes/hugo-tranquilpeak-theme/layouts/partials/footer.html: template: theme/partials/footer.html:3: function "now" not defined
ERROR: 2017/07/05 08:40:34 template.go:529: template: theme/partials/footer.html:3: function "now" not defined
ERROR: 2017/07/05 08:40:34 general.go:236: theme/partials/footer.html is an incomplete or empty template
```
Strangely, now the `blogdown::hugo_version()` is less than the installed hugo version:

```
> blogdown::update_hugo()
The latest Hugo version is 0.24.1
Already up-to-date.
==> Reinstalling hugo 
==> Downloading https://homebrew.bintray.com/bottles/hugo-0.24.1.sierra.bottle.tar.gz
Already downloaded: /Users/bryanwhiting/Library/Caches/Homebrew/hugo-0.24.1.sierra.bottle.tar.gz
==> Pouring hugo-0.24.1.sierra.bottle.tar.gz
==> Using the sandbox
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/hugo/0.24.1: 32 files, 17.6MB
NULL
> blogdown::hugo_version()
[1] ‘0.18.1’
```

I can't find hugo version 0.18.1 on my machine (i checked `/usr/local/Cellar/hugo/` and only 0.24.1 is installed). Why does the blogdown hugo_version not match the installed version?

**Comment by bryanwhiting** [comment]
Yet I just pushed to GitHub/Netlify again and it seems to have worked! Why would `build_site()` and `serve_site()` not work on my local machine, but successfully generate a site that Netlify can build? And should I create a separate issue for my most recent comment?

Thanks for the help!

**Comment by yihui** [comment]
Can you check the output of

```r
Sys.which('hugo')
blogdown:::find_hugo()
```

?

**Comment by bryanwhiting** [comment]
```
> Sys.which('hugo')
                 hugo 
"/usr/local/bin/hugo" 
> blogdown:::find_hugo()
[1] "/Users/bryanwhiting/Library/Application Support/Hugo/hugo"
```

Under `usr/local/bin/hugo`, the hugo command is a pointer to 0.24.1: 
`hugo -> ../Cellar/hugo/0.24.1/bin/hugo`

**Comment by bryanwhiting** [comment]
That did it. Thanks!
