### ISSUE TITLE
blogdown is not available (for R version 3.4.1)

### ISSUE THREAD

**Issue by logan-connolly** [rstudio/blogdown#135]
My base R updated today to 3.4.1, and afterwards when I tried to serve my site using blogdown, I received the error:

**Error in loadNamespace(name) : there is no package called ‘rmarkdown’
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
Error in render_page(f) : Failed to render '2015-07-23-r-rmarkdown.Rmd'**

I thought it may be an issue of my .libPaths() not being able to find my personal package library, but that wasn't the case. Then I decided to remove the blogdown package and try to reinstall it, when I got the the error "blogdown is not available (for R version 3.4.1)" After checking the available packages using View(available.packages()), it was indeed nowhere to be found.

Could you please help me resolve this issue because I really like the blogdown package and am looking forward to publishing my site using Hugo.

**Comment by yihui** [comment]
Please either read [README](https://github.com/rstudio/blogdown#blogdown) or the [**blogdown** book](https://bookdown.org/yihui/blogdown/installation.html).
