### ISSUE TITLE
more tag not working in rmarkdown

### ISSUE THREAD

**Issue by dmaupin12** [rstudio/blogdown#142]
Is there a way of limiting the post length on the homepage of a blogdown website in rmarkdown? The tag below works with markdown, but not for rmarkdown. 
`<!--more-->`

**Comment by yihui** [comment]
It should work. Where is your website? And is the source repo public?

**Comment by dmaupin12** [comment]
I'm using tranquil peak on netlify. I just noticed there was another post about this in the issues. Sorry for duplicating. I'm assuming it's an issue with the Tranquil peak theme?

**Comment by jemus42** [comment]
I've had a similar issue, but I didn't try to debug it further and just switched to a hacked alternative of `.Summary`, see [this section in my theme](https://github.com/jemus42/hugo-redlounge-jemsu/blob/master/layouts/index.html#L25). 

My blog is located [here](https://github.com/jemus42/blog.jemu.name), yet with my current theme the `.Summary` tag, which _should_ respect the `<!--more-->`-tag, is not used, but could be easily reinstated changing the line linked above.

**Comment by yihui** [comment]
Okay, I'll take a look at #92. Thanks!
