### ISSUE TITLE
github page not working 

### ISSUE THREAD

**Issue by brunaw** [rstudio/blogdown#144]
I was working on my blog locally, and everything worked just fine. Then I tried to publish it on github, 
at the repo https://github.com/brunaw/brunaw.github.io, but when I access the url `https://brunaw.github.io/`, I get `404 - File not found`, even if I have:
 "Your site is published at https://brunaw.github.io/"
on the `settings` page of the repo.

**Comment by yihui** [comment]
If you choose not to take my recommendation (https://bookdown.org/yihui/blogdown/deployment.html) and it appears you didn't read https://bookdown.org/yihui/blogdown/github-pages.html, either, you have to dig deeper in Github Pages. Basically username.github.io does not support the `gh-pages` branch. You must use the master branch for your HTML files.

More on Github pages vs Netlify: https://yihui.name/en/2017/06/netlify-instead-of-github-pages/

**Comment by brunaw** [comment]
Now I know that is easier to deal with Netlify. Already hosted my blog there and it works perfectly. Thank you!

**Comment by yihui** [comment]
Great! You are welcome!
