### ISSUE TITLE
blog post only shows up if url is entered

### ISSUE THREAD

**Issue by pssguy** [rstudio/blogdown#15]
[this entry](http://premiersoccerstats.com/mainWebSite/public/post/cranLogs/)
![cranlogs_1](https://cloud.githubusercontent.com/assets/2775918/20586803/85b9fc2c-b1bc-11e6-8ed2-5fa96f220bcc.png)

As you, hopefully, see there is some text "/BLOGDOWN-BODY-BEFORE -->" occurring at the top
and the sidebar has some vacant entries - one of which should be where this shows up

Its blog category also fails to appear as does the plot I would expect to see from the code

The same problem occurs locally

**Comment by yihui** [comment]
How did you build the website? You should not simply run `system('hugo')` when you have Rmd posts. You have to use `blogdown::build_site()` instead, or publish the `public` directory after you call `blogdown::serve_site()`.

**Comment by pssguy** [comment]
I run the serve_site() function and this is what I see locally as well. It has now happened with another page which had been working fine i.e. only accessible if full url is put in and does not appear in recent posts. Also the plot expected to appear no longer does

![2016-11-24](https://cloud.githubusercontent.com/assets/2775918/20610394/dcddd154-b24d-11e6-9d79-0d7fe721040b.png)

here is code
```
---
title: "Hansard"
author: "Andrew Clark"
date: 2016-11-17
categories: ["packages"] 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# UK 2015 Election

I like to check out new and enhanced R packages, particularly those relating to socio-economic issues and sports

A recent new entry is [hansard](https://github.com/EvanOdell/hansard), which pulls data from the UK Parliament API.


Other required packages, which I will make extensive use of in future code extracts, are [tidyverse](https://github.com/hadley/tidyverse), for data preparation and processing, and
[plotly](https://plot.ly/r/), for a wide set of interactive graphics    



The election_results() function retrieves all the results. It takes about 10 seconds to process so I have saved it in a csv file for retrieval in any future manipulation

```{r 01_Collection, warning = FALSE, message = FALSE}


library(hansard)
library(plotly)
library(tidyverse)

# This function retrieves all the election results and takes a few seconds and has been saved previously

#election_results <- election_results()
#write_csv(election_results,"data/election_results.csv")

#read the saved file
results <- read_csv("../../data/election_results.csv")
# view data.frame
results
```

Let's say we were interested in how the size of majority is associated with the level of turnout. It might be hypothesised that those constituencies where a tight race was anticipated would have the highest turn-outs - where every vote might count

```{r 01_presentation, warning = FALSE, message = FALSE}

# filter out unwanted rows and calculate a couple of percentages

df <- results %>%
filter(election.label._value == "2015 General Election") %>% #650
mutate(
to_pc = round(100 * turnout / electorate, 1),
margin_pc = round(100 * majority / turnout, 1)
)

# plot the data, adding a custom info-action
df %>%
plot_ly(
x =  ~ to_pc,
y =  ~ margin_pc,
color = ~ resultOfElection,
hoverinfo = "text",
text = ~ paste0(
constituency.label._value,
"<br>",
resultOfElection,
"<br>Turnout:",
to_pc,
"%<br>Margin:",
margin_pc,
"%"
)
) %>%
layout(
title = "2015 UK General Election Winners Margin and Turnout Percentage",
xaxis = list(title = "% Turnout"),
yaxis = list(title = "% Winner Margin")
) %>%
config(displayModeBar = F, showLink = F)

```



Well maybe.. but for those of you wanting to model it feel free. What is highlighted is the 'wasted' votes in Labour strongholds. 

Hover over any point, if desired after selecting and zooming, for more details

---

There are plenty more functions within the package and the creator, [Evan Odell](@evanodell) is actively developing it
```

I'll recreate the posts under another name to see if that helps

**Comment by yihui** [comment]
Can I see the source repository of this website? I cannot think of anything only by looking at this single post.

**Comment by pssguy** [comment]
I had already deleted the files and recreated under another name and am no longer getting this error. If it reappears, I will reopen with screenshots
