### ISSUE TITLE
Invalid regular expression

### ISSUE THREAD

**Issue by fernandomayer** [rstudio/blogdown#150]
Hello, using blogdown for the first time.

When running `new_site()` in an empty directory, I get the following error:

```
Error in grep(knitr::all_patterns$md$inline.code, yaml) : 
  invalid regular expression '(?<!(^|
)``)`r[ #]([^`]+)\s*`', reason 'Invalid regexp'
```

Even if I try `serve_site()` after this, the same error occurs. 

I'am using the latest version of **knitr** and **blogdown**:

```
> packageVersion("knitr")
[1] ‘1.16.5’
> packageVersion("blogdown")
[1] ‘0.0.51’
```

and Hugo version 0.25.1 (installed by hand).

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
