### ISSUE TITLE
serve_site() crashes Rstudio

### ISSUE THREAD

**Issue by verajosemanuel** [rstudio/blogdown#153]
installed blogdown and hugo with no issue, pulled my site from GitHub, and when tried to serve site with blogdown::serve_site() command, Rstudio crashed and closed.
it's a fresh install on my Linux laptop with Mint 18.2 Sonya 64bits

Rstudio log:

16 Jul 2017 10:48:49 [rsession-jvera] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:2697

**Comment by yihui** [comment]
Please see footnote 8: https://bookdown.org/yihui/blogdown/rstudio-ide.html Before we can reproduce and fix this issue, you need to run `serve_site()` in a separate R session outside RStudio, but you can still edit files in RStudio.

**Comment by verajosemanuel** [comment]
Thanks yihui
I run site from outside Rstudio and everything ok

**Comment by yihui** [comment]
Thanks for confirming. I'll probably change how `serve_site()` works in the next couple of weeks to fix this.

**Comment by yihui** [comment]
Now you may see https://bookdown.org/yihui/blogdown/livereload.html for an alternative approach to serving the site.

**Comment by verajosemanuel** [comment]
Thanks

**Comment by cjvanlissa** [comment]
Same problem here: serve_site() instantly crashes RStudio 1.1, same problem after updating to 1.2.169. Running serve_site() from a separate instance of R works.

**Comment by yihui** [comment]
@cjvanlissa Please see https://community.rstudio.com/t/blogdown-serve-site-aborting-r-session/2579/16?u=yihui
