### ISSUE TITLE
Hi, blogpost with rmarkdown and images does not appear.

### ISSUE THREAD

**Issue by raffdoc** [rstudio/blogdown#160]
Hi, 
I have created my site using `blogdown` package, great package. I have created three post, two very simple, and they work fine. Third one is quite complicated with many chunks. After using `blogdow::build_site()` and followed `blowdown:::serve_site()` blogpost appear but there are non images (see [here](https://raffdoc.github.io/post/reproducing-article-from-plos-one-using-given-data-and-instructions-how-reproducable-is-it/gbmImp-1.png)). In my local directory the folder does exist, but there is no `figure-html` folder where should be stored all images created from the chunks. 
How can I solve this?
Thanks

**Comment by yihui** [comment]
The documentation says:

> It is not recommended to change the knitr chunk options fig.path or cache.path in R Markdown. The default values of these options work best with blogdown.

https://bookdown.org/yihui/blogdown/output-format.html

I think you changed `fig.path` somehow in your Rmd document.

**Comment by raffdoc** [comment]
I haven't change the `fig.path` argument. You can have a look [here](https://github.com/raffdoc/raffdoc.github.io/blob/sources/public/post/2017-07-17-reproducing-article-from-plos-one-using-given-data-and-instructions-how-reproducable-is-it.Rmd).

**Comment by yihui** [comment]
You didn't change it, but `Hmisc:: knitrSet()` is likely to have changed it. You can verify by printing `knitr::opts_chunk$get('fig.path')` in a code chunk. It should be of the form `*_files/figure-html/`.

**Comment by raffdoc** [comment]
It does fix the problem, you were right. 
Thank you @yihui

**Comment by thedivtagguy** [comment]
I'm currently facing the same problem. The output for the line `knitr::opts_chunk$get('fig.path')` is `## [1] "index_files/figure-html/"`
How do I fix the problem and reset the `fig.path` to default? Currently I see no output being displayed at all, only code chunks.
