### ISSUE TITLE
blogdown website and shiny

### ISSUE THREAD

**Issue by JianWang2016** [rstudio/blogdown#161]
Hi, I just started to use blogdown and I am amazed with the tremendous flexibility it offers.  I wonder if the website it creates can be integrated into a shiny app.  I know shiny can accommodate html pages but how about a small blogdown website within a shiny app, leveraging shiny's web server and login features.

Thanks much for any insight.

**Comment by yihui** [comment]
If you put the `public` directory under the `www` directory of a Shiny app, say, `www/web/`, you should be able to see the website via `your-shiny-app-url/web/`.
