### ISSUE TITLE
Incorrect URL for img when rendering Rmd file in top level

### ISSUE THREAD

**Issue by jar1karp** [rstudio/blogdown#163]
How to reproduce: create a new Rmd post and set subdirectory to empty so that the Rmd goes into top level of content directory. In the new post add any R chunk that plots something, e.g.

     ```{r}
     curve(sin(x), from=-pi, to=+pi)
     ```

Then serve the site.

What happens is that the rendered images are correctly copied into the static directory and also correctly to the toplevel of public directory, but the generated HTML has incorrect URL:

    <pre class="r"><code>curve(sin(x), from=-pi, to=+pi)</code></pre>
    <p><img src="content/2017-07-22-demo_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>

In particular, the leading `content/` should not be there.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
