### ISSUE TITLE
Shiny Dashboard

### ISSUE THREAD

**Issue by vikram-rawat** [rstudio/blogdown#166]
is it possible to integrate a shiny dashboard in the Blogdown... if not then Are you planning to add it

**Comment by yihui** [comment]
The only way to embed a Shiny app is through `<iframe>` (you need to publish the app in advance elsewhere, e.g. on ShinyApps.io). blogdown is for static websites only, which means there won't be an R session in the backend.

**Comment by vikram-rawat** [comment]
I heard a talk where you mentioned that r markdown can be used as php tool to get data or so.

I mean even in future can you or this project ever allow us to create a dynamic webpage. Like python or golang does. Just curious don't want to learn any new language if something can be done in R programming.

Please any comment would do

**Comment by yihui** [comment]
Yes, I mentioned that in one of my rstudio::conf talks early this year. R Markdown has something in common with PHP, and you can certainly use it just like PHP. For example, you can combine R Markdown with Shiny: http://rmarkdown.rstudio.com/articles.html Then every time someone visits your R Markdown page, the code will be dynamically executed.

I don't quite recommend you to build a whole website as a gigantic Shiny app unless you can afford it (hosting Shiny apps will be more expensive than static HTML pages). As I said above, I recommend `<iframe>` on static HTML pages.
