### ISSUE TITLE
Hugo new post not available

### ISSUE THREAD

**Issue by g4challenge** [rstudio/blogdown#167]
with hugo 0.25.1 installed following R command does not work anymore:

`new_post("Creating a Post)`

The Error is as follows:

```
Error: unknown shorthand flag: 'f' in -f

Usage:
  hugo new [path] [flags]
  hugo new [command]
...
```

Could this be fixed with a different command or should it just be removed?

**Comment by yihui** [comment]
This has been fixed a month ago 8a0af2135a255a520106d594649d1ddd2b01177c. Please reinstall the package:

```r
devtools::install_github('rstudio/blogdown')
```
