### ISSUE TITLE
Page renders successfully using rmarkdown::render but not blogdown::build_site

### ISSUE THREAD

**Issue by chapmandu2** [rstudio/blogdown#17]
I'm having a strange issue where the same file is rendering successfully using rmarkdown::render but not blogdown::build_site.  The problem function is the getFrame function from the [EBImage package](https://github.com/aoles/EBImage) from @aoles .  I think it could be something to do with the environment the rendering is happening with, or perhaps it's something peculiar to the EBImage package but I thought I'd raise it as an issue here.  What's the best way to debug failing code in Rmd documents being rendered by blogdown? 

[example code](https://github.com/rstudio/blogdown/files/614747/test_image.txt)

Error message at build time:

```
Quitting from lines 24-25 (test_image.Rmd) 
Error in eval(expr, envir, enclos) : could not find function "slot"
Calls: local ... eval -> eval -> [ -> [ -> eval.parent -> eval -> eval
Execution halted
```

But fab package, I've been wanting to blog using Rmd for a while and this looks like a really easy way to do it!

**Comment by yihui** [comment]
`slot()` is a function in the **methods** package. I don't see it be imported in **EBImage**: https://github.com/aoles/EBImage/blob/aa902cbb/NAMESPACE so you have to either ask the author to import it, or you `library(methods)` by yourself.

**Comment by aoles** [comment]
Thanks @yihui, I've added the suggested import.

**Comment by chapmandu2** [comment]
Thanks both of you!
