### ISSUE TITLE
emoji in Rmarkdown

### ISSUE THREAD

**Issue by nancym** [rstudio/blogdown#171]
If I put this in `config.toml`:

    enableEmoji = true

An emoji like `:smile:` in a markdown file will be rendered as :smile: in the HTML output. Is there anything I can put in  `_output.yml` to get emoji to work in an Rmarkdown file, e.g. something like this:

    blogdown::html_page:
      md_extensions: +emoji

Thanks!

**Comment by yihui** [comment]
#165 has been implemented. Please see the documentation about `.Rmarkdown` files at https://bookdown.org/yihui/blogdown/output-format.html

**Comment by ProQuestionAsker** [comment]
Just for clarification, does this mean that emojis can't be rendered in either .Rmd or .Rmarkdown files if the output is like this?

```
output:
    blogdown::html_page:
        toc:true
```

And the workaround is to render the output like this?

```
output:
    md_document:
        toc:true
```

**Comment by yihui** [comment]
@ProQuestionAsker The life cycles of .Rmd vs .Rmarkdown:

- .Rmd -> knitr -> .md (intermediate) -> pandoc -> .html
- .Rmarkdown -> knitr -> .markdown -> Hugo/Blackfriday -> .html

Emoji is a Markdown extension only in Blackfriday. Pandoc does not support it. As a result, you must use .Rmarkdown if you must have emojis.

For TOC in .Rmarkdown, you have to use the Hugo variable `.TableOfContents`: https://bookdown.org/yihui/blogdown/templates.html#how-to

**Comment by ProQuestionAsker** [comment]
Ah, that makes sense. Thank you!!

**Comment by andry-tino** [comment]
@yihui: Is there a way to extend the generation pipeline so that I can process the generated HTML and enable emojis? It is such a shame that we cannot use Hugo features with `.Rmd` files as I need all the features there plus Hugo :(

**Comment by aosmith16** [comment]
@andry-tino I may be missing what you are asking for, but you can put emojis in `.Rmd` files via the [emo package](https://github.com/hadley/emo).

The code would look something like `` `r emo::ji("grinning")` ``, which you can add directly within the plain text of a post.
