### ISSUE TITLE
Tabbed RMarkdowns

### ISSUE THREAD

**Issue by elliottmorris** [rstudio/blogdown#175]
Hi, 

I'm attempting to get tabbed markdowns working inside the hugo-future-imperfect theme, but am not having any success. I have these working in my regularly-knitted RMarkdown reports, but for some reason, they don't work on my blog. Here's some code. 

    # <br> {.tabset}
 
    ## Tab 1

    Some text

    ## Tab 2

    Some text

    ### <br>

**Comment by yihui** [comment]
I think this is duplicate of #69.

**Comment by elliottmorris** [comment]
You're right, sorry. Closing

**Comment by yihui** [comment]
Here is one possible implementation: https://yihui.org/en/2023/10/section-tabsets/
