### ISSUE TITLE
the change of line break type in config.toml cause service shutdown

### ISSUE THREAD

**Issue by Miachol** [rstudio/blogdown#178]
Hi,
It seems that sometimes the change of line break type  (LF => CRLF, CRLF => LF) in the config.toml will cause service of blogdown unexpected shutdown. 
Other infomation:
- Version 1.0.143 Rstudio of windows
- Windows 10
- version 0.0.53 of blogdown

**Comment by yihui** [comment]
Please reinstall blogdown and retry. Thanks!
