### ISSUE TITLE
Add update section to Blogdown doc TOC

### ISSUE THREAD

**Issue by nancym** [rstudio/blogdown#179]
Section 1.1 of https://bookdown.org/yihui/blogdown/ is **Installation**. In that section, it says you can update Hugo with

    blogdown::update_hugo()

It would be useful if the TOC included a section called **Update** (maybe 1.1.1) and that section included the above command and how to update Blogdown itself. At the moment I have no idea how to update Blogdown. Also it took me a while to figure out where updating Hugo was documented.

Thanks for Blogdown!

**Comment by yihui** [comment]
Added. Thanks for the suggestion!
