### ISSUE TITLE
htmlWidgets show up on individual pages, but not on main page

### ISSUE THREAD

**Issue by cmhh** [rstudio/blogdown#18]
I have a Rmd file in `/blog/public/content/post/routing.Rmd` and it includes two leaflet charts.  After building, these show up just fine when I browse to `/blog/post/routing/`, but when that post is the newest one and displayed on the main page, `/blog/`, the leaflet charts are missing.  Looking in the javascript console, I see errors such as: `GET http://localhost/rmarkdown-libs/htmlwidgets-0.8/htmlwidgets.js`.

Cool package, by the way, though.

**Comment by cmhh** [comment]
Maybe this is something specific to the templates in the `hugo-future-imperfect` theme?  I probably should familiarise myself with hugo a bit more...

**Comment by yihui** [comment]
Right, the hugo-future-imperfect theme is a bit incompatible with R Markdown, and I'm looking for a different theme.
