### ISSUE TITLE
<img> tags are incorrect after rendering

### ISSUE THREAD

**Issue by jstaf** [rstudio/blogdown#183]
Having a bit of a weird issue where the `<img>` html tags used to display plot images point to the wrong location:

Bad tag:
`<img src="content/ggplot2_files/figure-html/unnamed-chunk-4-1.png" />`

What it should be:
`<img src="../ggplot2_files/figure-html/unnamed-chunk-4-1.png" />`

The directory structure of my `docs/`(publishDir) folder looks like the following (for the files in question):
```
ggplot2.Rmd
ggplot2/index.html
ggplot2-files/figure-html/unnamed-chunk-4-1.png
```

The bad `<img>` tags are in `ggplot2/index.html`. My current workaround is to run a find-and-replace with `sed` to fix the tags after running `blogdown::serve_site()` to create the website.

**Comment by yihui** [comment]
First, you should not reference files under `content/`. The `static/` folder was designed exactly for that purpose: https://bookdown.org/yihui/blogdown/static-files.html

Second, I wonder why you need the `<img>` tag at all. That image seems to be dynamically generated from a code chunk, and should be automatically inserted to the HTML output. Normally you don't even need to know where the images are generated; `serve_site()` will take care of everything.

**Comment by jstaf** [comment]
Just to be super clear, I'm not referencing external images, all of these are autogenerated files from `blogdown::serve_site()`. The autogenerated `<img>` tags (created via `blogdown::serve_site()`) are pointing to the wrong location.

**Comment by yihui** [comment]
Okay, in that case, it sounds like a bug, and I'll need your `devtools::session_info('blogdown')` and a reproducible example.

**Comment by jstaf** [comment]
Sounds good, I check back and see if I can package this into a small example.

**Comment by yihui** [comment]
Could you delete `content/ggplot2.html`, install the latest version of blogdown, and retry `serve_site()`?

**Comment by jstaf** [comment]
Whatever you've changed in the latest update solves the issue! Thanks!

**Comment by yihui** [comment]
Perfect!
