### ISSUE TITLE
knitr::include_graphics in blogdown

### ISSUE THREAD

**Issue by xie186** [rstudio/blogdown#184]
I'm trying to use `knitr::include_graphics`. But it seemed that in the html file generated by `blogdown::build_site()`. The src value is the absolute value on the linux server which is not I want. Is this a bug? Or there is a better way to do this? Thanks in advance.
Rmd code:
```
knitr::include_graphics("../../static/img/test.jpg")
```
Html output:
```
<img src="/home/xie186/github_repo/xie186_perlsonal_websrt/static/img/test.jpg" alt="(ref:test)"  />
```

**Comment by yihui** [comment]
Could you try `knitr::include_graphics("/img/test.jpg")` instead? See https://bookdown.org/yihui/blogdown/static-files.html

**Comment by ulyngs** [comment]
This didn't work for me - following the usual advice, I get an error when `blogdown` tries to build the html file to pass on to hugo.

```r
Error in knitr::include_graphics("/img/test.jpg") : 
  Cannot find the file(s): "/img/test.jpg"
```

The solution for me was to add `error  = FALSE` to include_graphics - that way the html gets generated correctly, even if knitr is momentarily confused that the files it refer to doesn't at the moment live in the path it expects.

```r
# this works
knitr::include_graphics("/img/test.jpg", error = FALSE)
```

**Comment by cderv** [comment]
For reference, this is a major change in knitr 1.28
https://github.com/yihui/knitr/blob/master/NEWS.md#changes-in-knitr-version-128

And there is now a way in knitr 1.29 to change the new default behavior globally
https://github.com/yihui/knitr/blob/master/NEWS.md#new-features
That would be interesting for bookdown.
