### ISSUE TITLE
Blogdown servr don't render well in viewer with Modern and Sky Rstudio Theme

### ISSUE THREAD

**Issue by Bakaniko** [rstudio/blogdown#186]
Hi,

I'm currently using Rstudio preview 1.1.336 which is great. I like the Modern theme it proposed.
But with Modern (and Sky theme), the viewer is totally black so it is terrible to preview the output.

Please see screenshots below.

With Modern Theme:

![basic_modern_ui](https://user-images.githubusercontent.com/17683898/29485606-c5455378-84d4-11e7-9e5c-7b2d58cb1ae2.png)

With Classic Theme:

![basic_normal_ui](https://user-images.githubusercontent.com/17683898/29485607-c549a32e-84d4-11e7-9bb4-263a724d7643.png)

Everything else is working, I just have to change the settings, not a big deal, but if it can be improved that'd be great.

I don't know if it is purely / solely a blogdown issue, but I see it  using blogdown so I post the issue here.

Anyway, thanks for blogdown, it is terrific !!

**Comment by yihui** [comment]
It seems I need to hardcode the background color of the hugo-lithium theme to white. You can also do that by yourself in a certain CSS file.

**Comment by Bakaniko** [comment]
Hi,

I edited `/themes/hugo-lithium-theme/static/css/main.css`

Adding `background-color` to html, body{}

See:

```css
html,
body {
  margin: 0;
  padding: 0;
  position: relative;
  background-color: rgba(255, 255, 255, 1.0);
}
```

![image](https://user-images.githubusercontent.com/17683898/29493804-db584066-859d-11e7-9e7c-2d80285f8fba.png)


Worked pretty well, thanks !

I'm making a PR of it.
