### ISSUE TITLE
Pre-installed Hugo and install_hugo()

### ISSUE THREAD

**Issue by Bakaniko** [rstudio/blogdown#187]
Hi,

I tried gitlab pages a few weeks ago (before discovering blogdown), so I followed their tutorial and installed Hugo from the ubuntu repositories (16.04 actually). Which was hugo 0.19.

Reading your documentation I tried to install Hugo from the R command (silly me) provided by blogdown.
Curiously it works and installed Hugo. But the called version was still the 0.19.

So I remove Hugo 0.19 from the main system, but Hugo wasn't found.

I reused the R command, which reinstalled Hugo. 

But Hugo wasn't found too. 

So I used snap to get a newer version:

```bash
sudo snap install hugo
```
And now I have Hugo 0.26 \o/ and blogdown is pretty well working !!

Not a major issue, but blogdown installed hugo twice but can't use it, which is useless.

I'm posting it to see if an improvement can be made, or at least, show another way for people having the same issue.

I might have forget some informations from the documentation too.

**Comment by yihui** [comment]
I believe it should work if you:

1. Uninstall the system's Hugo (snap or apt-get);

1. Start a new R session or restart the current R session, and `blogdown::install_hugo()`.

Then you can verify the installation by `blogdown::hugo_version()`.

**Comment by Bakaniko** [comment]
It works.

Thanks :)
