### ISSUE TITLE
Option for compiling only posts with changed *.Rmd's*?

### ISSUE THREAD

**Issue by aurora-mareviv** [rstudio/blogdown#190]
Would it be possible/feasible (in a future when I have *lots* of posts in my blogdown blog) to build only those *.Rmd* that have not changed?   
I am thinking in heavy posts with `R` code which, depending on the situation, can take longer to compile.  So many thanks for `blogdown`!

**Comment by yihui** [comment]
That is exactly what `serve_site()` does: https://bookdown.org/yihui/blogdown/local-preview.html

**Comment by aurora-mareviv** [comment]
I understand, thanks!
