### ISSUE TITLE
Small suggestion: Add description to New Post add-in

### ISSUE THREAD

**Issue by smach** [rstudio/blogdown#193]
Small thing, but it would be helpful to have the `description:` field auto-appear along with title, author, etc. in a new post's YAML. Description is a really useful thing to have for search engines. (I am now adding it manually in my header, but many people don't realize they should have that.)

Thanks for the blogdown package!

**Comment by yihui** [comment]
Thanks! That is a good suggestion. There are two issues that make me hesitant:

1. The `description` field may not actually be used: it is up to the Hugo theme whether it supports the `<meta>` tag that contains the description.

1. I should probably use a textarea for the description if I were to put it in the New Post addin. I think the current addin is big enough in height and I may not have enough space for a textarea.

It may be a good idea to mention this somewhere in the book (https://bookdown.org/yihui/blogdown/), and perhaps an even better idea to talk about SEO in a section, e.g. in Appendix A. I don't have enough time for this at the moment. If you want to contribute a section, I'll very much appreciate it!

Or perhaps @apreshill / @ProQuestionAsker could do it.

**Comment by smach** [comment]
Not sure I should be offering overall SEO advice, but I do know that the description tag is pretty key. You may want to add this Google SEO starter guide to your book's resources 

https://static.googleusercontent.com/media/www.google.com/en//webmasters/docs/search-engine-optimization-starter-guide.pdf 

and then maybe add a section in your appendix something like 

**Helping people find your site**

Once your site is up and running, you probably want people to find it. SEO -- Search Engine Optimization -- is the art of making a Web site easy for search engines like Google to understand what your site is about and, hopefully, presenting links to your site high in results when someone searches for those topics.

Entire books have been written about SEO, not to mention the many companies that are in the business of offering (paid) technical and strategic advice to help get sites atop search-engine rankings. If you're interested in finding out more, a good place to start is the [Google Search Engine Optimization Starter Guide.](https://static.googleusercontent.com/media/www.google.com/en//webmasters/docs/search-engine-optimization-starter-guide.pdf)

A couple of key points: 

1) The title that you select for each page and post is a very important signal to Google and other search engines telling them what that page is about.

2) Description tags are also key to explaining what a page is about -- plus the description may end up as text under the page title in a search-engine result. If your page's YAML doesn't include a description, you can add one with `description: 'Your text here' `. Not all themes will supporting adding the description to your HTML page (although they should!)

3) URL structure also matters. You want your post's slug to have informative keywords to give another signal what the page is about. Have a post with interesting things to do in San Francisco? `san-francisco-events-calendar` might be a better slug than `my-guide-to-fun-things-to-do.`

-- Sharon Machlis

**Comment by yihui** [comment]
@smach That is a great summary. I assume you are happy (i.e. no copyright issues) with us reusing the text you typed above in the blogdown book?

**Comment by smach** [comment]
Absolutely, feel free to use it in the blogdown book (I'd appreciate it if you could keep my name in the credit line if possible -- we journalists always love a byline :-) -- but that's not mandatory). And thanks again for the package.

**Comment by yihui** [comment]
Of course. We will definitely attribute you. Thanks!

**Comment by apreshill** [comment]
@yihui Can you let me know your preference for adding an attribution here- in text versus footnote, or something else?

**Comment by yihui** [comment]
I will do it in acknowledgements after you finish incorporating the above text.
