### ISSUE TITLE
Add deployment with GitLab and GitLab Pages to documentation

### ISSUE THREAD

**Issue by rgaiacs** [rstudio/blogdown#195]
Would be great to have deployment instructions for GitLab and GitLab Pages.

**Comment by yihui** [comment]
I have never used GitLab Pages by myself, but I believe it should be very similar to Github Pages.

**Comment by rgaiacs** [comment]
You need to write a `.gitlab-ci.yml` file that include the compilation rules. If this contribution is welcome I can submit a pull request when I have time?

**Comment by yihui** [comment]
Yes, a PR is welcome, and I hope this section won't be too long. Thanks!

**Comment by rgaiacs** [comment]
> I hope this section won't be too long.

It won't. I'm just trying to get other pieces at the right place first, see https://gitlab.com/pages/pages.gitlab.io/issues/53.
