### ISSUE TITLE
Image via shortcode in RMarkdown file not showing up in webpage

### ISSUE THREAD

**Issue by petzi53** [rstudio/blogdown#196]
I cannot display an image via hugo shortcodes in .Rmd files. The full description of my problem can be found on [StackOverflow](https://stackoverflow.com/questions/46111870/image-via-shortcode-in-rmarkdown-using-blogdown-not-showing-up).

**Comment by kahultman** [comment]
I responded to your StackOverflow post, but I was able to fix the problem by enclosing the source path in single and double quotes. So long as quotes are included in the Hugo shortcode path, I was able to view the figure. Seems like the args_string function in blogdown will only include quotes if values contain spaces.

**Comment by yihui** [comment]
@kahultman Thanks for the investigation. I think you are correct, and I just pushed a fix to always quote strings (unless already quoted).
