### ISSUE TITLE
HTML Widgets not displaying 

### ISSUE THREAD

**Issue by ProQuestionAsker** [rstudio/blogdown#20]
On one of my pages, I've used blogdown to generate an HTML file with a built in [highcharter](http://jkunst.com/highcharter/index.html) graph, but the graph doesn't show (it just leaves a white space where it should be).  
<img width="685" alt="screen shot 2016-12-15 at 8 13 56 pm" src="https://cloud.githubusercontent.com/assets/11020849/21251527/4b29d2be-c303-11e6-9e5b-2e66b9c9e228.png">

If I inspect the page, it looks like the page recognizes that an html widget should be there:
<img width="1108" alt="screen shot 2016-12-15 at 8 14 14 pm" src="https://cloud.githubusercontent.com/assets/11020849/21251551/6c1c3e08-c303-11e6-9126-cb51ee032549.png">

And the needed .js files are also in the same repository, so it should have all the information it needs to display.
<img width="551" alt="screen shot 2016-12-15 at 8 14 39 pm" src="https://cloud.githubusercontent.com/assets/11020849/21251565/82191366-c303-11e6-84ba-1b928f667a9b.png">

**Comment by walkerke** [comment]
I've had some issues with CSS conflicts between htmlwidgets and various Hugo themes.  I'm not 100% sure but this may be something that would have to be resolved theme by theme.  

A good workaround is to use `htmlwidgets::saveWidget()` to save your chart to an HTML file then embed in your blog as an iframe.  @bhaskarvk is also working on a solution for this with his __widgetframe__ package (https://github.com/bhaskarvk/widgetframe)

**Comment by ProQuestionAsker** [comment]
Great, I'll look into those options.  Thanks!

**Comment by ProQuestionAsker** [comment]
I just got around to trying this, and you're totally right.  Using `htmlwidgets::saveWidget(figure, file = "figure.html", selfcontained = TRUE)` to output the widget and then adding each file as an iframe within the .md or file of the project works like a charm!

It is worth noting (for others with this issue), that Hugo will rename the html file when transferring it to the public folder.  So, if you had a figure in this location: "figures/fig.html", your iframe should actually read <iframe src="figures/fig/index.html></iframe> in the .md file when working with Hugo.

**Comment by bhaskarvk** [comment]
I'm working on automating this step via https://github.com/bhaskarvk/widgetframe. But there are some issues that I still need to resolve. Stay tuned.

**Comment by palfalvi** [comment]
Hi all, I am experiencing similar issues with ```highcharter```, ```wordcloud2``` and (sometimes?) ```plotly```. I tried to use @bhaskarvk 's ```widgetframe::frameWidget()``` but it deos not solve the issue. I am using the [```hugo-academic```](https://github.com/gcushen/hugo-academic) theme btw.

Is there any progress in this issue or anyone experienced similar things?

**Comment by jozefhajnala** [comment]
I had similar issues with `highcharts` charts not rendering on a recent [blogdown post](https://jozefhajnala.gitlab.io/r/r005-import-csvs/), and after trying a few solutions I solved it in a bit of a workaround that potentially could be more automated, here is how I approached it:

1.  within an R chunk create a `highchart` `htmlwidget` object as one normally would 
2. export the object using `highcharter::export_hc(benchBoxPlot, "filename.js")`
3. use `htmltools::includeHTML("filename.js")` to inject the `js` into the page source, wrap it between `<script>` tag and place it in a `<div>` like so:

```<script type="text/javascript">
# included js here 
</script>
<div id="container"></div>
```

This can get tedious if you want more than 1 chart on a page as `export_hc` automatically calls it `container` -> one may spend some time to add a bit more flexibility to the function in terms of the export if this proves useful.

Note that you of course need the javascript resources provided on the page, for example using something like
```{r, echo=FALSE}
htmltools::includeHTML("include_highcharts.html")
```
where that `include_highcharts.html` contains the needed links, such as
```
<script type="text/javascript" src="https://code.highcharts.com/highcharts-more.js"></script>
```

**Comment by feddelegrand7** [comment]
Just use the amazing widgetframe package.

**Comment by alecrsf** [comment]
Even when using the widgetframe package, the html are not rendered to the post. 
I have tried also to integrate the file using the html tag <iframe>.
Is it due to my hugo theme?

**Comment by nvelden** [comment]
I have the same issue with the Hugo Apero theme. echart4r canvas elements are not rendered.

**Comment by everettttt** [comment]
Don't use the amazing `widgetframe` package, as it's [abandonware](https://github.com/bhaskarvk/widgetframe) and [had a security vulnerability since 2018](https://rud.is/b/2018/02/16/pym-js-library-vulnerability-in-widgetframe-package/).
