### ISSUE TITLE
Add an introduction to R Markdown

### ISSUE THREAD

**Issue by yihui** [rstudio/blogdown#207]
No need to be detailed. A few pages would suffice.

I'll write the draft by myself, and @apreshill you can help improve it later, given that you don't have as much time as me.

**Comment by yihui** [comment]
Here is my attempt: https://bookdown.org/yihui/blogdown/r-markdown.html Please feel free to edit / improve it when you have time @apreshill.

**Comment by apreshill** [comment]
Notes to myself:

- [ ] Mention some resources for learning Markdown formatting

- [ ] More explanation of what YAML is (also versus TOML?)
