### ISSUE TITLE
A few minor comments

### ISSUE THREAD

**Issue by yihui** [rstudio/blogdown#208]
## Preface

- how blogdown is different *with* existing popular website platforms: with -> from?

- footnote 2: Amber’s homepage is at https://proquestionasker.github.io. Similarly, you can find her
blog and project pages. -> how about: Amber’s homepage is at https://proquestionasker.github.io,
where you can find her blog and project pages.

## Chapter 1

- 1.3 RStudio IDE: You can select the date from a calendar widget provided by Shiny. Shiny has not
been introduced yet. Readers, especially those not familiar with Shiny may be confused. I would suggest
either to remove "provided by Shiny" or say a little bit more about Shiny.

- 1.5: subscripts and superscripts. It would be great to also give examples about how to do that. I.e
subscripts (`H~2~O`) and superscripts (`r^2^`).

## Chapter 2

- 2.5.1 The purpose of the partial template foot_custom.html is the same as head_custom.html.
(Which is? It would be great to rewrite it out.)
- 2.5.1 Lastly, we use the variable `.Site.Params.footer` to generate a page footer. Note we used the
with function again. (It would be great to write why use `with` out again, just in case readers need to go
back and check why)
## Appendix
- A.2 Now, let’s say we want to highlight our favorite teas again, so we’ll use a class attribute. `<ul>` (To
be consistent, should not this still be `<ul id="tea-list">`?)

**Comment by apreshill** [comment]
@yihui can you clarify the edit to the appendix needed?

**Comment by yihui** [comment]
I think the issue in Appendix B.2 has already been corrected. You are all set.
