### ISSUE TITLE
Add more bibliography entries and an index

### ISSUE THREAD

**Issue by yihui** [rstudio/blogdown#211]
I didn't pay much attention to citations when I wrote the book and just realized we only had three entries in bibliography.

@ProQuestionAsker Could you go through the book one more time, and add

1. Citations of at least R packages? We didn't really refer to many packages in this book, so it is okay if you can only fine one or two more packages to cite. At least pkgdown should be cited. These entries are automatically generated in https://github.com/rstudio/blogdown/blob/master/docs/10-references.Rmd I'm not sure if there are any other publications to be cited.

1. An index. You can take a look at the Rmd source files of the bookdown book, in which you may occasionally find `\index{}`. That is how you add index entries. This only works for PDF output. Watch out for special characters such as underscores -- they may need to be escaped by backslashes. See the last page of the bookdown book for an example: https://bookdown.org/yihui/bookdown/bookdown.pdf

The readme file has explained how to compile the book to PDF: https://github.com/rstudio/blogdown/tree/master/docs

**Comment by ProQuestionAsker** [comment]
Added [references](https://github.com/rstudio/blogdown/pull/212) and an [index](https://github.com/rstudio/blogdown/pull/213) in the last two pull requests. 

For the index, I added things that I thought beginners would be looking for, but that made the full index 1.5 pages long. If that's too long, @yihui, let me know and I'll shorten the list.

**Comment by yihui** [comment]
1.5 pages is good (actually the more detailed, the better). Thank you!
