### ISSUE TITLE
update documentation for RStudio v1.1.383

### ISSUE THREAD

**Issue by BarkleyBG** [rstudio/blogdown#220]
Documentation should be updated now that there is an official release of RStudio >= v1.1.28.

I will fix & open PR soon

**Comment by mivalek** [comment]
sorry gus, I was using # to indicate line number where I made changes to my code. Wasn't expecting it to link to issues. Can you please delete?

**Comment by yihui** [comment]
No worries! Unfortunately the references can't be deleted.
