### ISSUE TITLE
render_page does not work with custom library paths

### ISSUE THREAD

**Issue by eisioriginal** [rstudio/blogdown#222]
If one uses a custom library path like .libPaths(c("C:/YOUR/PATH/TO/SOMETHING")) the render page function does not read the custom path and passes it to the render_page Rscript call.

```
render_page = function(input, script = 'render_page.R') {
  args = c(pkg_file('scripts', script), input, getwd())
  if (Rscript(shQuote(args)) != 0) stop("Failed to render '", input, "'")
}
```

This results in loadNamespace(name) : no package with name 'blogdown' because the default path is simply not right

**Comment by yihui** [comment]
I don't know what "use" exactly means in "one uses a custom library" (i.e. how exactly you set `.libPaths()`), but a per-project `.Rprofile` should work: https://bookdown.org/yihui/blogdown/global-options.html

**Comment by eisioriginal** [comment]
Is Rscript really executed in the same project context so that .Rprofile would work? I use a workaroud by setting the R_LIBS_USER variable. I have a custom directory where all my packages are installed. I do not use the stadard user path.

**Comment by yihui** [comment]
Good question. I intended to fix this issue (call Rscript with .Rprofile in the project root) but forgot to. I'll fix it soon. Thanks!

For me, I always use `R_LIBS_USER` in `~/.Renviron`.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
