### ISSUE TITLE
Possible bug parsing a `config.toml` which contains inline comments

### ISSUE THREAD

**Issue by gcushen** [rstudio/blogdown#224]
Say we have a `config.toml` where the first line contains a comment after the variable:
```
baseurl = "/"  # End your URL with a `/` trailing slash, e.g. `https://example.com/`.
```
This is valid TOML and works fine in Hugo (as expected), however, when using the Blogdown wrapper, an error appears complaining about the `#` symbol. I have not had time to fully investigate the root cause, but it would appear that it is a bug relating to Blogdown not correctly parsing the `baseurl` TOML.

Blogdown reports in Console:
```
Serving the directory test at http://127.0.0.1:4321/"/"  # End your URL with a `/` trailing slash, e.g. `https://example.com/`.
```

Blogdown reports in Viewer:
```
Not found:
./"/"  
```

The error can be produced with the latest public release of Blogdown, Hugo v0.30.2, and the latest version of Academic theme (gcushen/hugo-academic).

**Comment by yihui** [comment]
Yes, it is a bug that I have fixed two months ago in d66727bf98b4297aac6dacf472319b59086a4e0c. Either installing the development version here or `install.packages("RcppTOML")` should fix it.

**Comment by gcushen** [comment]
@yihui thanks for the work around! I just presented a talk to R data scientists in London about integrating Academic with RStudio using Blogdown and there's been a lot of interest in this - it would be great to have this bug fix included in a public release soon :) In the meantime, I'll try to add some documentation to Academic so that our RStudio users are aware of the workarounds.

**Comment by yihui** [comment]
Okay, I'll consider making a CRAN release soon. Thanks!

**Comment by yihui** [comment]
@gcushen I have released the new version to CRAN. The problem should be gone after users update their R packages.

**Comment by gcushen** [comment]
@yihui thank you 😃
