### ISSUE TITLE
Bookdown.org unable to connect

### ISSUE THREAD

**Issue by wessport** [rstudio/blogdown#226]
I think the documentation site at https://bookdown.org/yihui/blogdown/ may be down. I've tried multiple devices, browsers, and networks to no avail.  

Not a big deal, but I miss the smooth bookdown layout : ] 

Regards,
Wes

**Comment by yihui** [comment]
Yes, it is down and I don't know why. I'll check with our team later. Thanks!

**Comment by wessport** [comment]
Looks like it's back up. Thanks!
