### ISSUE TITLE
--smart/-S is removed in Pandoc 2.0 w/ v0.2

### ISSUE THREAD

**Issue by batpigandme** [rstudio/blogdown#227]
This is the same glitch as that in the [rmarkdown issue thread](https://github.com/rstudio/rmarkdown/issues/1120), and has the same solution (installing the dev version of rmarkdown 🎉). 

However, since I update pandoc almost daily with homebrew, and hadn't encountered the error when rendering blogdown posts before today (after updating to `blogdown 0.2`), I thought I'd mention it here as well.

#### Error message
```r
blogdown::serve_site()
#> Rendering content/post/2017-11-05-learning-out-loud-slides-from-earl-boston.Rmd
#> --smart/-S has been removed.  Use +smart or -smart extension instead.
#> For example: pandoc -f markdown+smart -t markdown-smart.
#> Try pandoc --help for more information.
#> Error: pandoc document conversion failed with error 2
#> Execution halted
#> Error in render_page(f) : 
#> Failed to render 'content/post/2017-11-05-learning-out-loud-slides-from-earl-boston.Rmd'
```
#### Solution

```r
devtools::install_github("rstudio/rmarkdown")
```

**Comment by yihui** [comment]
Thanks!
