### ISSUE TITLE
how to add a background image or header on Xmin theme

### ISSUE THREAD

**Issue by verajosemanuel** [rstudio/blogdown#231]
Seems that nobody answered on SO
https://stackoverflow.com/questions/47114299/add-background-image-to-title-for-every-post-in-hugo-xmin-theme

using Hugo 0.30.2 with Xmin theme. I'm trying to add a subtle background image to every post title (instead the gray color box) but couldn't find the file where I can do such thing.

is there any way of replacing the gray color with a transparent image repeated scheme? like a watermark

if not, which file must I modify in order to make the same image as header for every post?

Thanks in advance

**Comment by yihui** [comment]
Please take some time (I recommend 2 hours if you are not familiar with Hugo templates) to read Section 2.5 of the blogdown book: https://bookdown.org/yihui/blogdown/templates.html

The file to modify is [`layouts/_default/single.html`](https://github.com/yihui/hugo-xmin/blob/master/layouts/_default/single.html). I don't have time to post a full answer (I spent a year on writing the blogdown book, and you probably should read it), but `.Params` is totally flexible.

**Comment by verajosemanuel** [comment]
thanks. It's very useful your help. Couldn't find by myself .
