### ISSUE TITLE
Links between .Rmd files not rendering, but .md does?

### ISSUE THREAD

**Issue by achamess** [rstudio/blogdown#241]
Hi,
I want to make hyperlinks between .Rmd files. On my local machine, I would just make a regular markdown style link `[link](/path/to/file)`. I know with Hugo, you need to use the shortcode `{{< ref "my_file.Rmd" >}}`. This works for `.md`files, but not for `.Rmd`. With markdown files I get clickable links, but for the `.Rmd` I just get the text output of the link. It's not a link. Is this something particular about .Rmd files?

**Comment by yihui** [comment]
Please see Section 2.3.3 in the blogdown book: https://bookdown.org/yihui/blogdown/content.html#shortcode

BTW, please do me a favor to [ask questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) in the future, and let me know the link to your post if you don't get an answer in a few days. Thanks!

**Comment by achamess** [comment]
Thank you! I will ask on StackOverflow for now on.

**Comment by yihui** [comment]
Excellent. Thanks!

**Comment by pat-s** [comment]
@achamess Could you share how you got it working? I am trying with

`[ref](' r blogdown::shortcode('ref', 'post/post1.html')')`

but this does not work in my site preview.

**Comment by achamess** [comment]
It didn’t work for me actually. I was not about to get other .Rmd files linked. Images worked, but not other pages. I gave up for the time being.

**Comment by RodrigoZepeda** [comment]
@pat-s  You can run the following function at the start of your Rmd file:
```
linkpage <- function (text, link){
  paste0('<a href=', link, '>\n<span>',text, '</span>\n<a>')  
}
```
and link to the other Rmd files inline as follows: `` `r linkpage("click here for an awesome post", "/post/post1/")` ``. There's probably a better way but I haven't figured out how to do it with Hugo (the `shortcode` option didn't work for me either)
