### ISSUE TITLE
Blogdown book suggestions related to updating

### ISSUE THREAD

**Issue by nancym** [rstudio/blogdown#242]
I do not (yet) use blogdown but I keep thinking that it might be the best way for me to manage a Hugo site. Periodically I fire up RStudio, which I installed in 2017 when I first experimented with Blogdown, and hit these stumbling blocks:

* How do I update R?
* How do I update RStudio?
* How do I update Blogdown?

In August, I figured out how to update Hugo from within RStudio, thanks to the
[blogdown book](https://bookdown.org/yihui/blogdown/), and I posted issue https://github.com/rstudio/blogdown/issues/179 suggesting that the book have a separate section about updating. Thank you for creating section **1.1.1 Update**. I have another suggestion: Please discuss or give links in the book about how to update R, RStudio, and blogdown. My guess is that most of your audience knows this, but some of us have zero experience with R and RStudio and don't know these basic things. It would be useful to have this info in the book so I don't have to go off on a web search to learn these things.

In case you're wondering why I want to use R and RStudio considering that I know nothing about them, it's because 1) blogdown seems cool and 2) I'm a math nerd and have dreams of including graphs and fractals and other math nerdery in a Hugo blog.

**Comment by yihui** [comment]
@ProQuestionAsker @apreshill What do you think?

I feel this topic would be a little tangential to this book, but I can definitely see the usefulness to absolute beginners of R.

On the other hand, actually I don't feel the urgent need to update R, RStudio, or blogdown in the future. I believe the current versions are stable enough and will continue to work for a fairly long time.

**Comment by apreshill** [comment]
I agree it can be tangential. But, blogdown is intended to possibly be the first "project" a new R learner could work on, then it might be useful to consider at least pointers to other resources. Although it feels like this topic could balloon, see: [https://ismayc.github.io/rbasics-book/index.html](https://ismayc.github.io/rbasics-book/index.html) for what full coverage of these topics might include.

**Comment by nancym** [comment]
I went on a web search and found these:

* r-project.org FAQ: [2.8 What’s the best way to upgrade \[R\]?](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#What_0027s-the-best-way-to-upgrade_003f)
* rstudio.com Support: [Getting the newest RStudio builds](https://support.rstudio.com/hc/en-us/articles/203842428-Getting-the-newest-RStudio-builds)

For now, I'm probably going to uninstall R and RStudio and start over, which will get me the latest blogdown (which is really all I want to do), but it would be useful if the next time I want to update blogdown, there were instructions for how to do that in the book.
