### ISSUE TITLE
Error when run install_hugo()

### ISSUE THREAD

**Issue by wenbo5565** [rstudio/blogdown#244]
I was trying to install hugo by install_hugo() but got an error as shown in the snapshot. I have no problem downloading or installing other packages.

![capture](https://user-images.githubusercontent.com/7663395/34922689-55ac8a34-f961-11e7-8fba-13a08306f35f.JPG)

My os is windows 8.1. My R is 3.2.2 and RStudio is 3.2.2

Newly added after post (1/14/2018)
I looked into the source code. Then I changed the argument version from 'latest' to '0.31'. I didn't get the same error but a new one. The program is able to find a valid link now but failed to download the file. I am not sure why.

![capture](https://user-images.githubusercontent.com/7663395/34923726-6cc366ce-f96c-11e7-83cc-9e91396625fd.JPG)

![capture1](https://user-images.githubusercontent.com/7663395/34923725-6cba6eca-f96c-11e7-9758-5f653494616c.JPG)

Thank you.

**Comment by yihui** [comment]
Your R version is more than 2 years old. [Please upgrade it.](https://yihui.name/en/2017/05/when-in-doubt-upgrade/)

**Comment by wenbo5565** [comment]
Hi Yihui, I still got the same error after re-installing R and RStudio. Thanks for help.
![capture1](https://user-images.githubusercontent.com/7663395/34965260-c85e51ba-fa20-11e7-8829-3c59a7f030d7.JPG)
![capture](https://user-images.githubusercontent.com/7663395/34965261-c8655870-fa20-11e7-84dd-a84bd9a1012c.JPG)

**Comment by yihui** [comment]
I don't know why it fails. Sounds like an SSL issue on Windows R. Anyway, you may install the dev version of blogdown `devtools::install_github('rstudio/blogdown')` and manually install Hugo:

1. Download the zip file manually and unzip it, e.g., https://github.com/gohugoio/hugo/releases/download/v0.31/hugo_0.31_Windows-64bit.zip
2. Call `blogdown:::install_hugo_bin("path/to/hugo.exe")` (change the path here to the actual path to hugo.exe).

**Comment by wenbo5565** [comment]
@yihui 
Hi Yihui, seems I could manually install hugo based on your instruction. However, I still cannot connect to github correctly when I use the new_site() function. I think it is because of the same error (you said maybe SSL issue)

![image](https://user-images.githubusercontent.com/7663395/35011652-f11d99c6-fad4-11e7-8368-2db0400b4ffb.png)

**Comment by yihui** [comment]
I cannot reproduce your issue on Windows, but pushed a possible fix anyway. Please restart R, `devtools::install_github('rstudio/blogdown')`, and retry.

**Comment by wenbo5565** [comment]
@yihui 
Now it seems working. It was "trying URL" twice. Both failed but the third time it connected successfully. Looks like you found the reason. Thank you a lot for the help.
![image](https://user-images.githubusercontent.com/7663395/35020784-bf0b19be-fafb-11e7-9970-0064270a9719.png)

**Comment by yihui** [comment]
Good to know. Thanks for the confirmation!

**Comment by fbetteo** [comment]
Hey. Same issue here. Using latest blogdown version.
I have tried libcurl method without luck,
![imagen](https://user-images.githubusercontent.com/13087655/44319927-514bf100-a415-11e8-8d23-a0abecceb925.png)

Any other idea? W10. R 3.4.2
Thanks!

**Comment by DataStrategist** [comment]
I think this is a problem with windows 8.x... I'm returning to an old desktop running windows 8 and indeed, `blogdown::install_hugo()` doesn't work, while `blogdown::install_hugo(version =0.53)` does. I've looked into  Internet Explorer being default or not (to no avail), set offline-mode (to no avail). Not sure how to check SSL certificates, but anyway, hardcoding the version number worked.

**Comment by cderv** [comment]
@fbetteo and @DataStrategist I think the issue with `install_hugo()` is with guessing the _latest_ version. Can you try `readLines("https://github.com/gohugoio/hugo/releases/latest", warn = FALSE)` on your specific OS ? 
I think there is an issue while reading this https url on some specific OS or specific R version. I can't reproduce on my windows machine so I need you to test as you have the error;

**Comment by yihui** [comment]
@fbetteo Your R version is too old. Please upgrade: https://yihui.name/en/2017/05/when-in-doubt-upgrade/ Older versions of R on Windows had some known problems with fetching web resources through SSL.

@DataStrategist  You didn't report your session info. The rule "when in doubt, upgrade" may apply to you.

**Comment by DataStrategist** [comment]
@yihui and @cderv thanks, I think my case is a weird example anyway, there was more stuff malfunctioning. For the record though, I had installed fresh blogdown (the cran version) and a bunch of other packages... but yeah, there's something wrong w/ my PC. I just wanted to provide the feedback that specifyying the version did work for me on my messed up PC

**Comment by yihui** [comment]
@DataStrategist Thanks! It would be more helpful if you could run the code @cderv mentioned above and let us know the result.

It will be even more helpful if you could run this and see if it can succeed:

```r
f = tempfile()
xfun::download_file('https://github.com/gohugoio/hugo/releases/latest', f)
str(readLines(f))
unlink(f)
```

**Comment by DataStrategist** [comment]
Hi @yihui sorry I was travelling. I have run the snippet above, and it seems to have worked:

```
> f = tempfile()
> xfun::download_file('https://github.com/gohugoio/hugo/releases/latest', f)
trying URL 'https://github.com/gohugoio/hugo/releases/latest'
downloaded 95 KB

[1] 0
> str(readLines(f))
 chr [1:1053] "" "" "" "" "" "" "<!DOCTYPE html>" "<html lang=\"en\">" "  <head>" ...
> unlink(f)
> 
```

There's something up w/ this pc... now it can install libraries and hugo well, but not `install_github` from either `remotes` or `devtools`. what a mess

**Comment by yihui** [comment]
@DataStrategist No worries. How about @cderv's code above? https://github.com/rstudio/blogdown/issues/244#issuecomment-471172607 Does that also work?

**Comment by archita0725** [comment]
I am having problem to download hugo theme on r studio ,my version is R-4.0.0 and 32 bit system on windows 8..please help me fix this problem.

> blogdown::install_hugo()
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  InternetOpenUrl failed: 'An error occurred in the secure channel support'

**Comment by cderv** [comment]
Hi @archita0725 , 

For such questions, you should asked on https://community.rstudio.com/c/R-Markdown/10 . The RStudio Community as a broad community ready to help. 

It is also easier to start helping you in a new discussion than an old closed issue on Github.  Thanks!
