### ISSUE TITLE
improve the doc, when is `R/build.R` executed?

### ISSUE THREAD

**Issue by dongzhuoer** [rstudio/blogdown#247]
D.9 talks about the possibility of custom building process. But for people who want to full utilize the power of `R/build.R`, the relative order of steps is important. I hope it would be explained more concretely in the documentation.

the source code of `build_site()` is as follows, so I guess the order is 
1. render `.Rmd` files 
1. `R/build.R` 
1. run hugo

```r
function (local = FALSE, method = c("html", "custom"), run_hugo = TRUE) 
{
    if (missing(method)) 
        method = getOption("blogdown.method", method)
    method = match.arg(method)
    on.exit(run_script("R/build.R", as.character(local)), add = TRUE)
    if (method == "custom") 
        return()
    files = list_rmds("content", TRUE)
    if (local && length(files)) {
        files = files[mapply(require_rebuild, output_file(files), 
            files)]
    }
    build_rmds(files)
    if (run_hugo) 
        on.exit(hugo_build(local), add = TRUE)
    invisible()
}
```

**Comment by yihui** [comment]
Thanks! I have added it to the last paragraph: https://bookdown.org/yihui/blogdown/methods.html
