### ISSUE TITLE
unknown flag: --force when trying to run new_site()

### ISSUE THREAD

**Issue by darokun** [rstudio/blogdown#25]
Hi! I am trying to set up a webpage using Blogdown, Hugo and GitHub, following @ProQuestionAsker's [blog post](https://proquestionasker.github.io/blog/Making_Site/#initializing-github-pages-to-work-with-hugo-and-blogdown), but I get an error when I try to run the function `new_site()`.

I am trying to run the function in an empty directory (apart from the `.Rproj`, `.gitignore`, and `.Rhistory` files). This is what I've run:
`> devtools::install_github("rstudio/blogdown")`
`> library(blogdown)`
`> install_hugo()`

So far, so good. 
And then, I get the following error:
`> new_site()`
`unknown flag: --force`

`Usage: `
  `hugo new site [path] [flags]`
`Flags:`
 ` -f, --format="toml": config & frontmatter format`

`Global Flags:`
  `-b, --baseUrl="": hostname (and path) to the root eg. http://spf13.com/`
 ` -D, --buildDrafts=false: include content marked as draft`
 ` -F, --buildFuture=false: include content with datePublished in the future`
     ` --cacheDir="": filesystem path to cache directory. Defaults: $TMPDIR/hugo_cache/`
      `--config="": config file (default is path/config.yaml|json|toml)`
  `-d, --destination="": filesystem path to write files to`
      `--disableRSS=false: Do not build RSS files`
      `--disableSitemap=false: Do not build Sitemap file`
      `--editor="": edit new content with this editor, if provided`
 ` -h, --help=false: help for site`
      `--ignoreCache=false: Ignores the cache directory for reading but still writes to it`
      `--log=false: Enable Logging`
      `--logFile="": Log File path (if set, logging enabled automatically)`
      `--pluralizeListTitles=true: Pluralize titles in lists using inflect`
  `-s, --source="": filesystem path to read files relative from`
     ` --stepAnalysis=false: display memory and timing of different steps of the program`
  `-t, --theme="": theme to use (located in /themes/THEMENAME/)`
     ` --uglyUrls=false: if true, use /filename.html instead of /filename/`
  `-v, --verbose=false: verbose output`
      `--verboseLog=false: verbose logging`

![screen shot 2017-01-02 at 21 01 42](https://cloud.githubusercontent.com/assets/5553078/21595502/d181d670-d12e-11e6-940e-b28197f093a7.png)

These are my settings:
`> sessionInfo()`
`R version 3.3.2 (2016-10-31)`
`Platform: x86_64-apple-darwin13.4.0 (64-bit)`
`Running under: OS X Mavericks 10.9.5`
`locale:`
`[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8`

`attached base packages:`
`[1] stats     graphics  grDevices utils     datasets  methods  `
`[7] base  `   

`other attached packages:`
`[1] blogdown_0.0.9`

`loaded via a namespace (and not attached):`
`[1] httr_1.2.1      R6_2.2.0        tools_3.3.2     withr_1.0.1`    
`[5] curl_2.3        memoise_1.0.0   digest_0.6.10   devtools_1.11.1`

I don't really understand the error, or how to solve it.
What am I missing?
Any help will be highly appreciated!

**Comment by yihui** [comment]
You probably have already installed an old version of Hugo. You can check the version via:

```
> blogdown::hugo_cmd('version')
Hugo Static Site Generator v0.18 BuildDate: 2016-12-19T08:38:10-06:00
```

If you see a lower version, you can reinstall Hugo:

```r
devtools::install_github('rstudio/blogdown')
blogdown::install_hugo(force = TRUE)
```

**Comment by darokun** [comment]
Thanks for your input, @yihui!

Indeed, I had a previous version of Hugo installed.

However, running `blogdown::install_hugo(force = TRUE)` only returned a warning, and did not update it:
`> blogdown::install_hugo(force = TRUE)
Warning: hugo-0.13 already installed
> blogdown::hugo_cmd('version')
Hugo Static Site Generator v0.14-DEV BuildDate: 2015-02-22T09:10:37+01:00`

I then proceeded to update Homebrew, unlink the old version of Hugo, and reinstall Hugo, all from the command line. That solved my problem (:

Thanks for pointing me in the right direction!
