### ISSUE TITLE
Site changes only to 404.html

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/blogdown#251]
When I make changes to config.toml, hero.md, etc. No changes are showing even after running `build_site()` followed by `serve_site()`. 

For example I added a new menu item to verify if it can see the change by adding :

```
[[menu.main]]
    name = "TEST"
    weight = 5
```

The menu item won't show up. However if I navigate to `../404.html` the menu item appears.

**Comment by yihui** [comment]
1. You almost never need to run `build_site()` (https://bookdown.org/yihui/blogdown/workflow.html);
2. You almost always need to provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/) when reporting issues, with your session info:

```r
devtools::session_info('blogdown')
```

**Comment by JosiahParry** [comment]
Please excuse the above example.

Trying to follow [reproducible example](https://github.com/rstudio/blogdown/issues/197).

When trying to reproduce the issue seems more apparent, the index.html page is not being built.

To reproduce:

```
git clone https://github.com/JosiahParry/josiah_parry.git
```

Serving the site produces `Index of ./` but no site.

**Comment by JosiahParry** [comment]
I created a new site and copied the files over from the old site and builds resolved. Not sure why, but hey, it worked. Thank you for your time!

**Comment by yihui** [comment]
Excellent! The best thing to know is that problems are scared of me and automatically disappear before I investigate them! 😉
