### ISSUE TITLE
serve_site() could automatically preview the file open in RStudio

### ISSUE THREAD

**Issue by hadley** [rstudio/blogdown#253]
If the user is using RStudio, we could use rstudioapi to figure out which file is currently open, and then automatically navigate to that page when the site is previewed

**Comment by yihui** [comment]
Yep, that is definitely a good idea. Actually I mentioned this possibility in my rstudio::conf talk. Basicaly you need to set two options: https://slides.yihui.name/2018-blogdown-rstudio-conf-Yihui-Xie.html#19
