### ISSUE TITLE
blogdown::new_site() issues inoperable command - execution failure

### ISSUE THREAD

**Issue by mkrasmus** [rstudio/blogdown#255]
Using recently installed R and R Studio.
R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Running on Windows 10.

Installed blogdown succesfully using:
`devtools::install_github("rstudio/blogdown")`

Then as per the blogdown book attempted:
`blogdown::new_site()`

This resulted in:
`> blogdown::new_site()
Error: C:\Users\mkras\Documents already exists and is not empty
Error: C:\Users\mkras\Documents already exists and is not empty
'C:\Users\mkras\AppData\Roaming\Hugo\hugo.exe" new site ".' is not recognized as an internal or external command,
operable program or batch file.
Error in shell(cmd, mustWork = TRUE, intern = intern) : 
  '"C:\Users\mkras\AppData\Roaming\Hugo\hugo.exe" new site "." -f toml' execution failed with error code 1
In addition: Warning messages:
1: In blogdown::new_site() : The directory '.' is not empty
2: running command '"C:\Users\mkras\AppData\Roaming\Hugo\hugo.exe" new site "." -f toml' had status 65535 
3: running command '"C:\Users\mkras\AppData\Roaming\Hugo\hugo.exe" new site "." -f toml' had status 65535 
4: running command 'C:\Windows\system32\cmd.exe /c "C:\Users\mkras\AppData\Roaming\Hugo\hugo.exe" new site "." -f toml' had status 1 `

I found that the command:
`'C:\Users\mkras\AppData\Roaming\Hugo\hugo.exe" new site ".'`

Brought to Windows command prompt raises the same error:
```
is not recognized as an internal or external command,
The filename, directory name, or volume label syntax is incorrect.
```
Checked the hugo executable for arguments and found that:
`C:\Users\mkras>C:\Users\mkras\AppData\Roaming\Hugo\hugo.exe new site '.'`

was successful. Does your:
`blogdown::new_site()`
Have incorrect placement of apostrophes (typo error?). 
Seems I cannot build and progress with:
`blogdown::new_site()`

After installing, reinstalling blogdown, closing and reopening R Studio the problem persists. 

Should I create a 'Hugo' project first? Not clear in the documentation, but can clearly create blogdown Hugo project.

**Comment by aj2duncan** [comment]
Hi @mkrasmus, just saw this and wondered two things:

1. Are you using RStudio?
2. Did you try `blogdown::new_site()` in an empty directory?

I ask because @yihui provided slightly different instructions for each. Either create a new RStudio project  (in a new directory) or make sure you are in an empty directory before you start. I'm reading from the quick example - [https://bookdown.org/yihui/blogdown/a-quick-example.html](https://bookdown.org/yihui/blogdown/a-quick-example.html)

I get the equivalent error if I try in My Documents but not if I switch to an empty directory.

**Comment by mkrasmus** [comment]
1. Yes
2. Pretty sure I tried creating a new project with new directory named Yui_example. But I think that project was a Hugo project. So maybe I'll try again a new project that is not a Hugo project. I've tried just running blogdown::newsite() as a standalone command in rstudio console after installing the blogdown package but no go.

**Comment by mkrasmus** [comment]
Thank you @aj2duncan . 

I tried your second method. I didn't create a new project, but as you suggested setwd into the empty folder. Then blogdown command. It was sooooooo close! An error popped up stating I needed to install the 'later' package. Installed it, refreshed, emptied the folder, started again - got my plain markdown in the view window.

**Comment by aj2duncan** [comment]
No worries @mkrasmus, glad you got it sorted.
