### ISSUE TITLE
Blogdown setting incorrect fig.path for knitr chunks

### ISSUE THREAD

**Issue by jonathan-g** [rstudio/blogdown#256]
# Simple description

`build_site()` sets knitr `fig.path` to `*_files/figure-html4/` instead of `*_files/figure-html/` and this causes blogdown to move figure files to the wrong destination within the `static` directory.

# Minimal reproducible example

1. I create a new blogdown web site project from RStudio.
1. I build the default site, as blogdown creates it.
1. The "pie-1.png" figure ends up in `static/rmarkdown-libs/figure-html4/pie-1.png` instead of `static/post/2015-07-23-r-markdown_files/figure-html/pie-1.png`.

## Further info:

* I use the RStudio blogdown add-in to create a new `.Rmd` post and make a code chunk called `pie`, which creates a figure. When I build the site, there is a collision between the two posts writing different `pie-1.png` files to the same path `static/rmarkdown-libs/figure-html4/pie-1.png`

* If I edit the `setup` chunk of the default post to be:
    ```
    {r setup, include=FALSE, message=FALSE}
    knitr::opts_chunk$set(collapse = TRUE)

    message("Dep path = ", blogdown::dep_path())
    message("fig.path = ", knitr::opts_chunk$get("fig.path"))
    ```
    then the output is
    ```
    Dep path = 2015-07-23-r-rmarkdown_files/figure-html4/setup
    fig.path = 2015-07-23-r-rmarkdown_files/figure-html4/
    ```
   From the documentation, the path should end with `figure-html/`, not `figure-html4`, 

* If I manually set `knitr::opts_chunk$set(fig.path="2015-07-23-r-rmarkdown_files/figure-html/")`
   then the `pie-1.png` figure is correctly moved to `static/post/2015-07-23-r-rmarkdown_files/figure-html/pie-1.png`

# Session Info

I am using RStudio 1.1.423 and have run update.packages(). Here is my session info:
```
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.0.5  blogdown_0.5

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15          bookdown_0.6          digest_0.6.15         rprojroot_1.3-2       mime_0.5              R6_2.2.2              jsonlite_1.5         
 [8] xtable_1.8-2          backports_1.1.2       magrittr_1.5          evaluate_0.10.1       stringi_1.1.6         rstudioapi_0.7.0-9000 miniUI_0.1.1         
[15] rmarkdown_1.8         tools_3.4.3           stringr_1.2.0         httpuv_1.3.5          xfun_0.1              yaml_2.1.16           RcppTOML_0.1.3       
[22] compiler_3.4.3        htmltools_0.3.6       knitr_1.19           
```

**Comment by yihui** [comment]
Please test `devtools::install_github('rstudio/rmarkdown')`. I have submitted the new version of rmarkdown to CRAN three weeks ago, but it seems to be lost in an unknown place...

**Comment by jonathan-g** [comment]
I got the same problem with the github version (0.5.3).

**Comment by yihui** [comment]
I didn't mean blogdown. I meant rmarkdown.

**Comment by jonathan-g** [comment]
Sorry that I didn't read your comment carefully. When I install the github version of rmarkdown, the site builds correctly. I am closing this issue.
