### ISSUE TITLE
More informative failed to serve/render messages

### ISSUE THREAD

**Issue by deann88** [rstudio/blogdown#257]
I have been trying to do a custom theme in Hugo using blogdown. 
Whenever there is a conflict with some of the css classes or I have made a minor mistake in the html syntaxis, the function blogdown::build_site() fails to build .html file in the /public dir, but there is no message to note that nothing happened or that there was an issue. Furthermore, if I have not erased the previous .html file, it is still in the directory and one may not even understand that the rendering failed.

My sugestion is to first erase all files in the /public folder when blogdown::build_site() is called, and then rebuild the new files. 
Additionally, it would be very helpful if console messages are transfered to R console.

**Comment by deann88** [comment]
Another issue I experienced was the following:
After creating a repo with a template, I cloned it to another computer and noticed that blogdown::build_site does not render the .html file in the publishDir. Blogdown kept failing silently. No message or a warning.
After thorough investigation, I realized the issue was that the empty "content" dir was not commited to the remore repo, because it was empty. The solution was to create an empty dir named "content" in the cloned repository. 
I guess this is something that could be checked by blogdown::build_site.

**Comment by wenlong-liu** [comment]
I agree with @deann88's comments regarding the messages of failure.  It is very painful if you made changes, but ::serve_site() does not change without throwing out any error information.  It will be wonderful if there is something informative, at least saying which line is wrong if the building fails. 

Wenlong

**Comment by yihui** [comment]
I just tried to reproduce this issue, and I'm relatively sure it is an RStudio IDE issue: https://github.com/rstudio/rstudio/issues/2248

For now, you can call `blogdown::serve_site()` in a terminal, and you should see the error messages, like this:

![image](https://user-images.githubusercontent.com/163582/36497803-fa40c98a-1701-11e8-90fc-b02698325e42.png)

**Comment by wenlong-liu** [comment]
Thank you @yihui for providing the solution.  I can identify the error messages in terminal.

**Comment by yihui** [comment]
This issue has been fixed in the daily build of RStudio: https://dailies.rstudio.com Please test it if you are interested. Thanks!
