### ISSUE TITLE
Avoid local visit from Google Analytics

### ISSUE THREAD

**Issue by wenlong-liu** [rstudio/blogdown#259]
Thank you for reading my question.

I set up my personal website using R Blogdown and hugo-academic theme. It works like a charm. However, when I tried to install visitor tracking feature, such as Google Analytics, I came up with a question. When I test and preview the website in my local computer, Google Analytics seems to consider it as a visit. In this case, local testing and preview messed up all the tracking in Google Analytics.

Here is what I tried:
* Try to set up a filter in Google Analytics to exclude traffic from local computers. However, the IP of my computer changes due to the nature of my Internet provider.

* Install an ad blocker in the browser, but it does not work.

Any suggestions or ideas to fix this problem are appreciated.

**Comment by yihui** [comment]
This question is not directly relevant to blogdown. It is a pure Google Analytics question. Please ask in other places, such as StackOverflow or Google's forums. Thanks!

**Comment by jemus42** [comment]
You can wrap your GA javascript with an if-statement to prevent it from loading on localhost, e.g. 

```html
<script type="text/javascript">
  if (window.location.hostname != "127.0.0.1") {
  <GA js here>
  }
</script>
```

At least that's what I do for my piwik code on my blog.

**Comment by wenlong-liu** [comment]
@jemus42 thanks for the reply.  I installed a chrome extention to block google analytics.  For now, it works.  

-Wenlong
