### ISSUE TITLE
new_post() when using `kind` and `ext` only works with .md extensions for both the archetype and the blog post

### ISSUE THREAD

**Issue by lcolladotor** [rstudio/blogdown#261]
Hi again,

I noticed that `new_post()` works with a supplied `kind` argument only when `ext = '.md'` and not when `ext = '.Rmd'`. Also, the `kind` template has to end in `.md` even if the `ext = '.Rmd'`. This could be related to https://github.com/rstudio/blogdown/issues/173#issuecomment-367888459 and is ultimately related to https://stackoverflow.com/questions/48844340/is-it-possible-to-create-a-rmd-file-template-for-the-blogdown-new-post-addin.

I'm posting this here because I'm not sure that the current behaviour is the intended one. In any case, it can lead to some confusion as to why it appears that `blogdown` is not using a specified archetype (say `archetypes/default.md`) when using a `ext` value different from `'.md'`. 

Also, even in the case that it works (`.md` extension for the archetype and `ext = '.md'`) the user still needs to change the file extension manually of the new post file if they wanted to use `.Rmd` or `.Rmarkdown`. Plus add any YAML lines exclusive to `.Rmd` that are not used in `.md`.

Things work, just not in all cases. From https://github.com/rstudio/blogdown/blob/a079068000fe86512503454f28dee49b486b3057/R/hugo.R#L193 and https://github.com/rstudio/blogdown/blob/a079068000fe86512503454f28dee49b486b3057/R/hugo.R#L7 this looks like it's outside the real of `blogdown`. Though maybe `blogdown` could internally replace the archetypes that end with non `.md` terminations so that they use that termination (or just show an error telling the user to use a `.md` archetype), and then switch the new blog post file termination from `.md` to whatever was supposed the user wanted. I'm not 100% sure that `new_post()` https://github.com/rstudio/blogdown/blob/a079068000fe86512503454f28dee49b486b3057/R/hugo.R#L273-L276 then adds the YAML that is only used in `.Rmd` blog posts. I'm referring to parts like this:

```
output:
  blogdown::html_page:
    toc: no
    fig_width: 5
    fig_height: 5
```

Thanks again for the great package and tools!

Best,
Leo

## Tests

Using the `hugo-academic` `posts.md` archetype, I created two identical files `archetypes/posts.md` and `archetypes/jojo.Rmd` (the main difference is that one has a `.md` file termination and the other one `.Rmd`) where I added some extra R markdown code from [here](http://lcolladotor.github.io/2018/02/17/r-markdown-blog-template/). I then ran several tests where I use each archetype twice, once with `ext = '.md'` and one with `ext = '.Rmd'`. 

The case that works well is when I use `posts.md` with `ext = '.md'`.

```R
> blogdown::new_post('hola7', kind = 'posts.md', slug = 'hola', ext = '.Rmd')
/Users/lcollado/Dropbox/Code/hugoblog/content/post/2018-02-22-hola7.Rmd created
[1] "content/post/2018-02-22-hola7.Rmd"
> blogdown::new_post('hola8', kind = 'posts.md', slug = 'hola', ext = '.md')
/Users/lcollado/Dropbox/Code/hugoblog/content/post/2018-02-22-hola8.md created
[1] "content/post/2018-02-22-hola8.md"

> blogdown::new_post('hola9', kind = 'jojo.Rmd', slug = 'hola', ext = '.Rmd')
/Users/lcollado/Dropbox/Code/hugoblog/content/post/2018-02-22-hola9.Rmd created
[1] "content/post/2018-02-22-hola9.Rmd"
> blogdown::new_post('hola10', kind = 'jojo.Rmd', slug = 'hola', ext = '.md')
/Users/lcollado/Dropbox/Code/hugoblog/content/post/2018-02-22-hola10.md created
processing 4 content files
[1] "content/post/2018-02-22-hola10.md"

> dir('archetypes')
[1] "default.md" "jojo.Rmd"   "posts.md"
```

It took me a bit longer to diagnose this issue because I have in my `.Rprofile` two options set to help reduce time when using the RStudio addin.

```R
options(blogdown.author = 'L. Collado-Torres')
options(blogdown.ext = '.Rmd')
```

## Screenshots

Here I include screenshots that show how the `hola7`, `hola8` and `hola9` test fail but the `hola8` works.

#### hola7 test: posts.md with .Rmd

<img width="641" alt="screen shot 2018-02-22 at 9 42 31 pm" src="https://user-images.githubusercontent.com/2288213/36575540-76c38afc-1819-11e8-8f5d-22e79b58ed9e.png">

#### hola8 test: posts.md with .md

Yay, this worked! Well, almost. The file ends with `.md` and not `.Rmd` so I'd have to manually change the file extension.

<img width="819" alt="screen shot 2018-02-22 at 9 43 03 pm" src="https://user-images.githubusercontent.com/2288213/36575542-7888d45a-1819-11e8-9fe1-ea26364b71c3.png">

#### hola9 test: jojo.Rmd with .Rmd

<img width="307" alt="screen shot 2018-02-22 at 9 50 41 pm" src="https://user-images.githubusercontent.com/2288213/36575749-93be2f94-181a-11e8-9847-9c243a87055c.png">

#### hola10 test: jojo.Rmd with .md

This actually generates a slightly different YAML by including

```
header:
  caption: ''
  image: ''
```

<img width="451" alt="screen shot 2018-02-22 at 9 50 49 pm" src="https://user-images.githubusercontent.com/2288213/36575752-962db5d8-181a-11e8-96fe-8070b9135b68.png">

## `archetypes/posts.md` content

```
+++
title = "{{ replace .TranslationBaseName "-" " " | title }}"
date = {{ .Date }}
draft = false

# Tags and categories
# For example, use `tags = []` for no tags, or the form `tags = ["A Tag", "Another Tag"]` for one or more tags.
tags = []
categories = []

# Featured image
# Place your image in the `static/img/` folder and reference its filename below, e.g. `image = "example.jpg"`.
[header]
image = ""
caption = ""

+++

## Doesn't really have the next + sign, but just so I could show some edits I made
+ ```{r bibsetup, echo=FALSE, message=FALSE, warning=FALSE}
## Load knitcitations with a clean bibliography
library('knitcitations')
cleanbib()
cite_options(hyperlink = 'to.doc', citation_format = 'text', style = 'html')

bib <- c('knitcitations' = citation('knitcitations'),
         'blogdown' = citation('blogdown')[2])
+```
```

## R session info

Same as in https://github.com/rstudio/blogdown/issues/173#issuecomment-367888459

**Comment by yihui** [comment]
Thanks for the detailed investigation! It sounds like a bug to me. If you are able to fix it, I'd welcome a PR (I don't have the time at the moment; sorry).

**Comment by lcolladotor** [comment]
I just finished my PR ^^. I had to remember to change `<-` symbols to `=` :P

**Comment by jananiravi** [comment]
### StackOverflow
I do not have enough credits to comment/follow-up on the [StackOverflow post](https://stackoverflow.com/questions/48844340/is-it-possible-to-create-a-rmd-file-template-for-the-blogdown-new-post-addin) but adding `default.md` to the `<home>/archetypes/` folder doesn't seem to get implemented in the new_site() creation. Am I missing something?

![image](https://user-images.githubusercontent.com/8397074/40204942-361ccb14-59f8-11e8-817d-5ba8c8ef4615.png)

### .Rmd
Related Q to the default .Rmd vs .md post files mentioned by @lcolladotor : the tags that appear in `content/tags` seem to be the ones created only in .md posts and not the .Rmd ones but these do appear in the tag clouds at the bottom of the webpage. Anyway to make them both work? I assume that these `tags` are aggregated from projects, posts pages across the website.

If either deserve a separate post, I will repost as needed. Thanks!
