### ISSUE TITLE
Python Syntax Highlighting for Hugo

### ISSUE THREAD

**Issue by wenbo5565** [rstudio/blogdown#262]
Possibly this is not a issue but a question that I was wondering if there is any way to highlight python code rendered by R Blogdown in a post?  Thanks.

Python blocks in R Markdown is like
```python
expression A
expression B
```

**Comment by RodrigoZepeda** [comment]
The default blogdown theme (as well as several other hugo themes) use [highlight.js](https://highlightjs.org/) which allows you to highlight code in 176 languages (including Python).  You can follow [this blog](https://amber.rbind.io/blog/2017/11/15/syntax-highlighting/ ) (it applies to R but the instructions are the same for any language).

Finally, please ask this questions in [stackoverflow](https://stackoverflow.com/) instead.

**Comment by wenbo5565** [comment]
@RodrigoZepeda  Thank you. Well, I actually had asked this question on stackoverflow but haven't got informative answer. So that's why I asked here again.

**Comment by wenbo5565** [comment]
@yihui  Hi Yihui, I have a new but related question. I followed the [link ](https://amber.rbind.io/blog/2017/11/15/syntax-highlighting/) Rodrigo provided. It works well locally (I use blogdown::serve_site() ). However, when I publish it to anther folder (use build_site) and push it to my remote repository, I cannot see the syntax highlighting on my blog. I guess there must be something I have to do manually? from serve_site() to build_site()?
