### ISSUE TITLE
Consider a host argument for install_theme()?

### ISSUE THREAD

**Issue by ijlyttle** [rstudio/blogdown#264]
I'd be happy to make a PR for this.

I have GitHub Enterprise (GHE) at work, and I have an ambition to produce a hugo theme for my company. I would like to be able to host this on our instance of GHE.

Further, I would like to offer a company-specific function `acmetools::install_theme_acme()` that would wrap `blogdown::install_theme()`, but it would require a host argument that might look something like:

```R
install_theme <- function(theme, ..., host = "github.com"){
  ...
}
```

This way, I could design `acmetools::install_theme_acme()` to look like:

```R
install_theme_acme <- function(theme, ..., host = "github.acme.com"){
  blogdown::install_theme(theme, ..., host = host)
}
```

What do you think?

If acceptable, perhaps `new_site()` could be adapted, as well? Others?

**Comment by yihui** [comment]
This definitely makes sense. Please go ahead and add a `host` argument to `new_site()` and `install_theme()`.

I think it also makes sense to let the `theme` argument also accept a full URL (of the zip archive), but you can leave it to the future till someone really asks for it.
