### ISSUE TITLE
TOC position and exclusion from widget

### ISSUE THREAD

**Issue by stanstrup** [rstudio/blogdown#267]
Hi,

I have started converting my blog to blogdown but I am having an aesthetics problem.

When I use `toc: true` in a post the toc is inserted at the very top of the post. This creates two problems:

1. I cannot add a heading saying "Table of contents"
2. In the post widget (academic theme) the toc content is put in the summary, This is not very nice.

Any way around either of these? If you could specify the position of the toc with some keyword you could work around it. And if you could exclude the toc from the widget summary you could avoid "2".

**Comment by yihui** [comment]
Sorry, I don't have much time for this issue. You probably need to provide your own Pandoc template: https://bookdown.org/yihui/blogdown/default-template.html (assuming you meant Rmd posts; if you meant md posts, that is [another story](https://bookdown.org/yihui/blogdown/templates.html)) And it is probably not worth it (as you said, it is an aesthetics issue, which one often [feels extremely tempting](https://slides.yihui.name/2018-blogdown-rstudio-conf-Yihui-Xie.html#11) to solve but the gain is not substantial).

**Comment by stanstrup** [comment]
Thanks for the answer. I guess I can add the heading there. But what about the widget preview? Any way to exclude the toc? I guess that would mean excluding a div with id="TOC"?

**Comment by yihui** [comment]
I have no idea. I haven't studied the academic theme in detail.

**Comment by gadenbuie** [comment]
@stanstrup I've wanted something similar for other reasons so I wrote a function you can use in an Rmd document to parse the markdown and create a TOC. That way you can manually put the TOC wherever you need. I wrote up the details [in this blogdown post](https://www.garrickadenbuie.com/blog/2018/02/28/add-a-generated-table-of-contents-anywhere-in-rmarkdown/) if you're interested. This solution only works for `.Rmd` formats and requires hashtag-style headers, but it does let you put a TOC anywhere you want in your blogdown post (or any other Rmd document).

**Comment by stanstrup** [comment]
@gadenbuie Thanks! 
I am so sorry I didn't look at this before now. I didn't realize you wrote a whole thing for me. 
It is great and works very nicely.

Thanks again. It solved my problem for now.
One improvement could be to include numbering if enabled in the header.
