### ISSUE TITLE
Widgets appear a little lower on home screen

### ISSUE THREAD

**Issue by AtharKharal** [rstudio/blogdown#268]
The widgets on home page appear a little lower in Academic Theme. That is they leave an empty space above them which is unpleasant to see. Secondly speed of showing up the widgets is slower. Is there any work around for both these issues? I have checked StackOverflow but to no avail.

**Comment by yihui** [comment]
This is the better place to ask questions about the Hugo Academic theme: https://github.com/gcushen/hugo-academic/issues
