### ISSUE TITLE
Question about config function 

### ISSUE THREAD

**Issue by nstrayer** [rstudio/blogdown#27]
Hi, I've run into issues changing the output directory (to `docs` to allow easy posting on github pages). When you try and switch it messes up figures and just generally doesnt work. I've attempted to track it down but was wondering if some clarification could be provided about this line in `R/utils.R` 117-119
```r
publish_dir = function(config = load_config()) {
  get_config('publishdir', 'public', config)
}
```

The `get_config()` function is rather confusing to me, is `'public'` hardcoded in this case?

**Comment by yihui** [comment]
`'public'` is not hardcoded; it is the fallback value -- if `publishDir` was not set in config.toml, `'public'` is used.

I just tried to set `publishDir = "docs"` in config.toml, and it seems to work for me with the latest dev version of blogdown here. Could you reinstall and retry?

**Comment by nstrayer** [comment]
Just redownloaded the newest version and started a new project and it worked. Thanks a ton!

**Comment by yihui** [comment]
Great. Thanks for confirming!
