### ISSUE TITLE
Failed to serve new site.

### ISSUE THREAD

**Issue by abidjanr** [rstudio/blogdown#273]
Hello

This is the issue i face. Trying to create a new site following Amber Hill instruction get me here: 

![image](https://user-images.githubusercontent.com/37144699/37094429-ca2c14b6-220a-11e8-8d64-498c64520bf2.png)

The error underlined is 

    trying URL 'https://github.com/yihui/hugo-lithium-theme/archive/master.zip'
    downloaded 116 KB

    Serving the directory /home/ediman/Documents/Projects/r/abidjanr-site at http://127.0.0.1:4321
    To stop the server, run servr::daemon_stop("89622640") or restart your R session
    Warning message:
    In find_exec("hugo", "Hugo", "You can install it via blogdown::install_hugo()") :
     Found hugo at "~/bin/hugo" and "/home/ediman/bin/hugo". The former will be used. If you don't need the former, you may delete it.
     Error in setwd(site.dir) : cannot change working directory`

     > devtools::session_info('blogdown')
     Session info -----------------------------------------------------------
     setting  value                       
     version  R version 3.4.3 (2017-11-30)
     system   x86_64, linux-gnu           
     ui       RStudio (1.1.383)           
     language en_US                       
     collate  en_US.UTF-8                 
     tz       Atlantic/St_Helena          
     date     2018-03-07                  

     Packages ---------------------------------------------------------------
     package   * version date       source        
     backports   1.1.2   2017-12-13 CRAN (R 3.4.3)
     base64enc   0.1-3   2015-07-28 CRAN (R 3.4.0)
     blogdown  * 0.4     2017-12-12 CRAN (R 3.4.3)
     bookdown    0.5     2017-08-20 CRAN (R 3.4.2)
     digest      0.6.14  2018-01-14 cran (@0.6.14)
     evaluate    0.10.1  2017-06-24 CRAN (R 3.4.0)
     graphics  * 3.4.3   2017-12-01 local         
     grDevices * 3.4.3   2017-12-01 local         
     highr       0.6     2016-05-09 CRAN (R 3.4.0)
     htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)
     httpuv      1.3.5   2017-07-04 CRAN (R 3.4.0)
     jsonlite    1.5     2017-06-01 CRAN (R 3.4.2)
     knitr       1.18    2017-12-27 CRAN (R 3.4.3)
     magrittr    1.5     2014-11-22 CRAN (R 3.4.2)
     markdown    0.8     2017-04-20 CRAN (R 3.4.0)
     methods   * 3.4.3   2017-12-01 local         
     mime        0.5     2016-07-07 CRAN (R 3.4.0)
     Rcpp        0.12.15 2018-01-20 CRAN (R 3.4.3)
     rmarkdown   1.8     2017-11-17 CRAN (R 3.4.2)
     rprojroot   1.3-2   2018-01-03 CRAN (R 3.4.3)
     servr       0.8     2017-11-06 CRAN (R 3.4.2)
     stats     * 3.4.3   2017-12-01 local         
     stringi     1.1.6   2017-11-17 CRAN (R 3.4.2)
     stringr     1.2.0   2017-02-18 CRAN (R 3.4.2)
     tools       3.4.3   2017-12-01 local         
     utils     * 3.4.3   2017-12-01 local         
     yaml        2.1.16  2017-12-12 CRAN (R 3.4.3)

@ebedthan try one to get answers but his question stay an answer so as we face the same issue can you help?

Thanks you.

**Comment by yihui** [comment]
What does `blogdown::hugo_build()` return?

**Comment by yihui** [comment]
I just pushed a fix for the spurious warning. You can install the development version via

```r
devtools::install_github('rstudio/blogdown')
```

Then please restart R and retry `blogdown::hugo_build()` or `blogdown::serve_site()`.
