### ISSUE TITLE
How do I upload jupyter notebooks using blogdown, rstudio, netlify?

### ISSUE THREAD

**Issue by kishvanchee** [rstudio/blogdown#277]
Stackoverflow link to question - https://stackoverflow.com/questions/49208192/how-to-upload-jupyter-notebooks-using-blogdown-on-netlify

**Comment by gadenbuie** [comment]
@kishvanchee I added a comment on your SO post. This question is really about Hugo and not blogdown. I don't know the answer to your question, but I know you'll find it in the Hugo documentation (or will have to make a specific page template for your jupyter notebooks). This page could be a good starting point: <https://gohugo.io/templates/output-formats#link-to-output-formats>.

**Comment by cderv** [comment]
I posted an answer with a link toward a python 📦 for this : 
https://pypi.python.org/pypi/hugo_jupyter/1.0.2

You need to try and see how it works with blogdown. It may goes really well if the html for your notebook are already generated. Then hugo will know how to handle theme. However, you may need to play with some options and [custom rendering method](https://bookdown.org/yihui/blogdown/methods.html) - but I don't think so. 

As @gadenbuie said: not a blogdown issue I think.
