### ISSUE TITLE
Feature suggestion: remove tempory `html` files generated by `.Rmd` posts

### ISSUE THREAD

**Issue by psychelzh** [rstudio/blogdown#278]
Currently, for every `.Rmd` post, `blogdown` generates one `.html` file. I do think these `.html` files are temporary, and it is plausible to remove them after building the site. But it will remain there by default. I wonder if it is possible to autoremove them?

**Comment by cderv** [comment]
Hi, 
I am not sure the html file for every Rmd post is temporary. I believe this is the file that is used by `hugo build` to generate the website. It is use in a caching mechanism explained in [D.3](https://bookdown.org/yihui/blogdown/local-preview.html#local-preview) of blogdown book. 
If you delete it every time, when you want to preview your site, all the Rmd are recompiled to html whereas if you leave them, only the one that need to recompile. It can save you time. It is my understanding that when running `build_site(FALSE)`, every Rmd file will he rerendered to html though. 

Moreover, If you deploy to netlify, you will need those html as netlify can only use hugo not R, so it won't be able to deal with Rmd files. There are some explanation on deployment and about ignored files for hugo. 

Hope it helps.

**Comment by psychelzh** [comment]
Thanks for your explanation.

I think you are right and careful. So it would better to leave those html files if you want to save time and deploy it on netlify automatically.

**Comment by yihui** [comment]
@cderv was absolutely correct. The .html files are not temporary but required, so should not be deleted.
