### ISSUE TITLE
Trying new default lithium and hitting errors right away

### ISSUE THREAD

**Issue by pssguy** [rstudio/blogdown#28]
As recommended have switched to the default lithium theme within a new R project

```
library(blogdown)
new_site()
```
Appears fine.

I add one word to the provided .Rmd file

```
serve_site()
```
result
![mtsissue](https://cloud.githubusercontent.com/assets/2775918/21702608/546c51da-d361-11e6-8aef-93e348a4918f.png)

```
sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] blogdown_0.0.11

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8     bookdown_0.3    digest_0.6.11   rprojroot_1.1   mime_0.5        backports_1.0.4 magrittr_1.5   
 [8] evaluate_0.10   stringi_1.1.2   rstudioapi_0.6  rmarkdown_1.3   tools_3.3.1     servr_0.5       stringr_1.1.0  
[15] httpuv_1.3.3    htmltools_0.3.5 knitr_1.15.1 
```

**Comment by njtierney** [comment]
Do you have a github repository with this website in it? It might be helpful for debugging.

**Comment by pssguy** [comment]
Thanks for response
[Here it is](https://github.com/pssguy/mts

**Comment by yihui** [comment]
It seems there is some weirdness on Windows. I'll investigate.

**Comment by pssguy** [comment]
Yes the config.toml expanded again as well

If you are having a look at Windows then I have included a changed version of the previous site. I would definitely prefer to stick to that theme - especially as I had used it on a published site

If it is any help, everything was working smoothly up and until 27th November
[mainWebSite.zip](https://github.com/rstudio/blogdown/files/688819/mainWebSite.zip)

**Comment by yihui** [comment]
I can reproduce the issue on Windows by myself, so this time it should be easier to figure out what's wrong.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
