### ISSUE TITLE
anyone prefer to refresh serve_site manually?

### ISSUE THREAD

**Issue by dracodoc** [rstudio/blogdown#281]
The auto refresh of `serve_site` is supposed to be reduce user's effort and see changes immediately. However I met these problems:
- With `serve_site` on, the file browser in RStudio is very slow. Every folder change take about 2 seconds.
- It often take a long time to save a file.
- If site rendering met some problem, the next refresh is scheduled by a wait time, and it will increase by each failure. This could mean I need to wait half minute if I took 2 attempts to fix the problem.

A manual refresh will work for me and avoid all the problems above. I'm wondering if there is more users feel this way.

I looked at the code about the possible changes:
- We can add a `auto_fresh = TRUE` parameter and still use live preview as default
- For manual refresh, maybe we just need to call `serve_it` again without using `servr:::watch_dir`?
 I'm not totally sure about the best approach here.
- Once we have a function to refresh the site, we can have a rstudio addin and bind some keyboard shortcut.

**Comment by yihui** [comment]
For the slowness, have you tried the alternative approach for LiveReload? https://bookdown.org/yihui/blogdown/livereload.html

**Comment by dracodoc** [comment]
I didn't try it because the web page said it's better for markdown posts while my post will be rmarkdown. Still I tried it and it's indeed better. I didn't see the slowness in rstudio browser anymore.
