### ISSUE TITLE
Confusing warning message

### ISSUE THREAD

**Issue by ThierryO** [rstudio/blogdown#284]
The [message](https://github.com/rstudio/blogdown/blob/21f14af67b836356aeadf7e20bb606aa6bda1329/R/install.R#L158) tells the user that it is OK to delete the path that is actually being used. Which seems a bit strange to me. If this is OK, then I would reformulate it.

**Comment by yihui** [comment]
The message says "If you _don't need_ the former, you may delete it", so it is up to you whether you need the former. You need to figure out why two versions of Hugo were installed by yourself, and decide which copy to keep. It could be okay to delete either one, but the latter copy is (likely to be) installed system-wide, so will require `sudo` if you are to delete it.

Please feel free to improve the message via a pull request. Thanks!
