### ISSUE TITLE
Incompatible with dev version of glue

### ISSUE THREAD

**Issue by jennybc** [rstudio/blogdown#293]
The `evaluate()` function has been removed from glue in https://github.com/tidyverse/glue/commit/b39ed150b8dc301a05f11830e9594e1fd101a109.

At the moment, if you have a dev version of glue installed,`blogdown:::serve_site()` errors.

cc @jimhester

**Comment by jennybc** [comment]
After various upgrades and downgrades and upgrades, I no longer see this and am working with glue v1.2.0.9000 (https://github.com/tidyverse/glue/commit/7230ed216109bacbd3fc714a44d13a2d99e16d88) and blogdown v0.6 (CRAN). I will just be glad.

**Comment by yihui** [comment]
**blogdown**'s `evaluate()` is from the **evaluate** package (not **glue**), so it should not matter whether there is an `evaluate()` function in **glue**. **blogdown** does not use `evaluate()` directly, either (**knitr** calls `evaluate::evaluate()`).

**Comment by jennybc** [comment]
Yeah, I had gotten into some bad state. glue is an indirect dependency (through many routes, I see) and some version of some intermediate dependency seemed to be calling `glue::evaluate()`. Perhaps I should have tried to nail that down, but it's too late now.

**Comment by yihui** [comment]
No problem. We can investigate it when the problem comes back (hopefully not).

**Comment by dfalbel** [comment]
I am having this issue too when building my site:

`Error: object 'evaluate' is not exported by 'namespace:glue'`

My session info:

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] usethis_1.3.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17    rstudioapi_0.7  knitr_1.20      servr_0.10      magrittr_1.5    devtools_1.13.6 R6_2.2.2        stringr_1.3.1  
 [9] httr_1.3.1      tools_3.4.3     xfun_0.3        git2r_0.23.0    withr_2.1.2     htmltools_0.3.6 rprojroot_1.3-2 digest_0.6.15  
[17] bookdown_0.7.15 later_0.7.3     promises_1.0.1  curl_3.2        glue_1.3.0      mime_0.5        memoise_1.1.0   evaluate_0.11  
[25] rmarkdown_1.10  blogdown_0.8.1  stringi_1.2.3   compiler_3.4.3  backports_1.1.2 httpuv_1.4.5 
```

**Comment by yihui** [comment]
@dfalbel Do you have a minimal reprex?

**Comment by dfalbel** [comment]
@yihui sorry. I found out that the problem was that I had an old version of the `emo` package that used `evaluate` from `glue`. That was hard to debug!

**Comment by yihui** [comment]
So once again: [when in doubt, update all your packages](https://yihui.name/en/2017/05/when-in-doubt-upgrade/). Updating is a lot easier than debugging, and often solves problems automatically.

**Comment by dfalbel** [comment]
You are right! Thanks again!
