### ISSUE TITLE
Add theme_version()

### ISSUE THREAD

**Issue by rgayler** [rstudio/blogdown#298]
Would it be possible to add a function theme_version() to return the address&version of the most recently installed theme?

I was recently trying to see if I had the most current version of hugo-academic and I couldn't see that there was any marker which allowed this to be determined.

**Comment by yihui** [comment]
Hugo themes do not really have the notion of versions. The best thing I could think of is the SHA string _if the theme was installed as a GIT repo or submodule_, which I believe is not how most users would install a theme.

**Comment by rgayler** [comment]
> Hugo themes do not really have the notion of versions.

Yes. I found that confusing because various sources advised "make sure you
have the latest version of the theme" and George Cushen (author of the
academic theme) was referring to V2.2.0 but I couldn't find anything online
which associated a version number with a specific commit.

> The best thing I could think of is the SHA string *if the theme was
installed as a GIT repo or submodule*

Yes. If the user has the theme as a GIT submodule they can see the SHA in
git, and are probably the smaller fraction of more sophisticated users.

What I had in mind was something like, have new_site() or install_theme()
create a hidden file (say .installed_theme) in the site root directory,
with a timestamp, URL of theme repo, URL and SHA of installed commit.
theme_version() would just return that information. Obviously this doesn't
cover any changes made to the theme after installation, but it gives the
typical naive user a starting point for knowing what was installed.

**Comment by yihui** [comment]
I don't think I'll ever have time to implement it, so all I could say for this issue is a pull request will be welcome! Thanks!
