### ISSUE TITLE
Error in blogdown serve_site() when updating a file

### ISSUE THREAD

**Issue by rhobis** [rstudio/blogdown#302]
I asked a question on StackOverflow about an error I encounter when updating my `config.toml` file while `serve_site()` is running. 
The question is [here](https://stackoverflow.com/questions/50790987/error-in-blogdown-serve-site-when-updating-a-file)

The user `aosmith` suggested to use `options(blogdown.generator.server = TRUE)`, which actually solved the problem.

I'm wondering if this is a bug or if I there is something wrong with my settings.

**Comment by yihui** [comment]
Could you try `remove.packages('RcppTOML')` and see if the problem will be gone?

https://stackoverflow.com/questions/50790987/error-in-blogdown-serve-site-when-updating-a-file#comment88788503_50790987

**Comment by rhobis** [comment]
Yes, the problem is gone after removing that package
