### ISSUE TITLE
Could buildsite() erase the content of the public folder?

### ISSUE THREAD

**Issue by jcolomb** [rstudio/blogdown#303]
Hi and thanks for the package. It is terrific.

I think it would be good if the buildsite() command would erase all content of the public folder. I am for example sometimes not seing some bugs because part of earlier version of the build are compensating for files not produced. And thinking about manually erasing the folder is difficult (I am lazy I know...)

Thanks again.

(Even while using netlify to deploy, I am using the public folder deployement. The hugo deployment does not seem to work when the public folder is in another folder, like in my case.)

**Comment by jcolomb** [comment]
This won't solve my problem, as you wrote: "If the contents of your blogdown site are not in the root directory of your GIT repository, Netlify will not build"

**Comment by yihui** [comment]
For the record, you were quoting from https://bookdown.org/yihui/blogdown/netlify.html.

Well, that is not strictly true. You can use the `-d` argument to override `publishDir` in `config.toml`, e.g., use the command `hugo -d public` on Netlify, and specify `public` as the publish directory on Netlify.

More on the hugo command-line: https://gohugo.io/commands/hugo/

**Comment by jcolomb** [comment]
it does not seem to change anything, hugo cannot find the elements to build the site:

    Error: Unable to locate Config file. Perhaps you need to create a new site.

I also tried to work with hugo -b command, but could not have it to work...

**Comment by yihui** [comment]
Show me your example please.

When you run `hugo`, it will expect `config.toml` under the current directory. If it is not under the current directory, `cd` to the directory of `config.toml` (or use other command-line arguments like `-s`).

**Comment by yihui** [comment]
Great!
