### ISSUE TITLE
TOC generation is different in blogdown from Hugo's default via blackfriday

### ISSUE THREAD

**Issue by neeldhara** [rstudio/blogdown#304]
When the markdown files are parsed by Blackfriday, then Hugo apparently automatically generates IDs for heading elements. As mentioned [in this thread](https://discourse.gohugo.io/t/hugo-is-generating-css-ids-for-heading-elements-should-it/3284/2), they are:

> used for lots of cool stuff, anchor identities for the autogenerated table of contents, to give one example.

Blogdown appears to have it's own toc generation mechanism, but I believe that uses wrapper div classes with IDs attached to them. This seems to be a small difference between the way markdown is rendered by blackfriday v/s the default blogdown way.

I'm raising this issue to suggest that it may be a good idea to mention this in the [documentation](https://bookdown.org/yihui/blogdown/) in the chapter explaining the [differences between RMarkdown and Markdown](https://bookdown.org/yihui/blogdown/output-format.html).

I realize it's not a big deal, but it took me a while to figure out what was up with the TOC of my Hugo theme ([Er](https://github.com/lingxz/er)) not working - because it was relying on the h1 classes being generated in a particular way. I don't think blogdown needs to change in anyway, just a heads up in the documentation would be helpful. [In my situation](http://blog.neeldhara.com/post/2018/june/firstdjangoapp/), I simply turned off Er's TOC and switched to blogdown's. 

Thanks for considering this!

**Comment by yihui** [comment]
I definitely agree it is a good idea to mention this difference in Section 1.5 of the blogdown book. Do you want to try a pull request? Thanks!
