### ISSUE TITLE
Feature Proposal: Default Rmd to draft

### ISSUE THREAD

**Issue by mwaldstein** [rstudio/blogdown#305]
## Feature overview

Add a configuration parameter (`blogdown.draftDefault`) to make Rmd's render out as drafts unless explicitly overridden in their frontmatter.

## Usecase

For more complex analysis, I use a dedicated git repository, with a typical project folder structure - e.g. data, posts, scripts, etc. To add posts from these, I add them as git submodules to my site. The trouble is that I often have non-post Rmd files I don't want rendered to the site - Articles, Presentations, Introductions for collaborators, status reports, etc.

I'd like to be able to easily not include Rmd's not intended as posts (or sharing).

## Alternatives

 * Manually adding 'draft: true' to all Rmd's - besides being more work, this poses the risk of missing a file and having it published without being intended.
 * Making a change to hugo - I think this use case is specific enough to analysis that is is appropriate to add here.
 * Clever use of hugo ignoreFiles - frankly I can't quite think of how to make this work, but there might be something doable...

## Implementation

I'd suggest adding the logic to 'prepend_yaml'. I'm happy to do the work and submit a pull request, but wanted to make sure it was a reasonable proposal before doing the work.

**Comment by yihui** [comment]
I don't quite understand how this would work.

If you want new posts to default to drafts, you can add `draft: yes` to `archetypes/default.md`: https://gohugo.io/content-management/archetypes/ Then when you create new posts from blogdown, they will be in the draft mode by default (having `draft: yes` in the YAML).

If you want existing posts to be drafts, how can blogdown know which ones should be drafts?

**Comment by mwaldstein** [comment]
I'll try to elaborate on my use case:

I have 2 repositories: site.blogdown and data.analysis.project. site.blogdown is a typical blogdown repository created with `blogdown::new_site()`. data.analysis.project has the following structure:

```.
└── data
    └── my.data.csv
└── scripts
    └── fetch.R
    └── process.R
└── posts
    └── intro.Rmd
    └── followup.Rmd
└── presentation
    └── my-beamer-slides.Rmd
└── publication
    └── article.Rmd
└── etc...
```

I then add data.analysis.project as a git submodule of site.blogdown because I want the posts to show on my site. The trouble is that there are a lot of other non-post Rmd's in the repository. While I could add 'draft: true' to the non-post Rmd's, there is a large risk of adding a new presentation or article and inadvertently leaving it out. Plus, semantically, those files are not drafts, they just aren't blog posts.

Here's my current override that does what I'm looking for (without the niceties of a configuration parameter, etc)

```
prepend_yaml.new <- function(from, to, body = read_utf8(to)) {
  yml <- blogdown:::fetch_yaml2(from)
  if (!any(startsWith("\\s*draft:", yml))) {
    warning("setting draft")
    yml <- append(yml, "draft: true", length(yml) - 1)
  }
  x = c(yml, '', body)
  xfun::write_utf8(x, to)
}
```

Hope that clarifies the problem and what I'm trying to do

**Comment by yihui** [comment]
Done. You may try `options(blogdown.draft.output = TRUE)`.

**Comment by mwaldstein** [comment]
Nice! 

Really appreciate it - thanks!
