### ISSUE TITLE
Bug: Don't build draft RMD's

### ISSUE THREAD

**Issue by mwaldstein** [rstudio/blogdown#306]
# Problem

While there are performance considerations to not building 'draft' Rmd's, the larger and more pressing issue is that all build documents have their by-products (images, etc) get copied so even though hugo won't build pages for drafts, all the images are still made and placed in the built site.

# Proposal

In `build_site`, when local = FALSE, add a step to filter out files where draft is true (or corresponding `blogdown.draft.output` setting) 

I'm happy to perform the coding and create a pull request if this is acceptable.

**Comment by yihui** [comment]
You can search for `Rmkd` on this page: https://bookdown.org/yihui/blogdown/output-format.html

**Comment by mwaldstein** [comment]
While that works for files temporarily there, it doesn't address files that are ignored from `blogdown.draft.output` you added. In that case, renaming the files to keep them from being compiled isn't an option.

**Comment by yihui** [comment]
`blogdown.draft.output` only does one thing, which is adding `draft: yes`. Skipping the compilation sounds like a different task to me, and perhaps belongs to a different option (e.g. `blogdown.skip.draft`).

Basically you have two choices, and I'm not sure which one is more practical:

1. Use `.Rmkd`. You said no, but I don't see why it is not an option.

2. Send a pull request, but I cannot promise I'm able to review it soon.

**Comment by mwaldstein** [comment]
Rmkd is not an option because, as I mentioned in #305, there are Rmd's in the path which are generating articles or presentations (from the git submodules), and therefore cannot be renamed as proposed in the Rmkd proposal.

I'll make a pull request, but want to make sure we agree on the logic first:

`local` parameter | `skip.draft` | `draft.output` | `draft` frontmatter | **Include?**
------|-----|-----|-----|-----
TRUE |  * | * | * | *Y*
FALSE | FALSE | * | * | *Y*
FALSE | TRUE | * | true | *N*
FALSE | TRUE | * | false | *Y*
FALSE | TRUE | TRUE | not set | *N*

It is the last line which I'm most interested in and want the OK on before implementing.

**Comment by yihui** [comment]
That sounds more complicated than I imagined. What I had on my mind was to skip the compilation of an Rmd when `options(blogdown.skip.draft = TRUE)` and `draft: true`  in the frontmatter.

**Comment by mwaldstein** [comment]
I think we're in agreement - Most of the lines in the table are times when compilation is *not* skipped. 

A few notes:

 * The `local` parameter to `build_site` overrides the check, as when local everything gets compiled including drafts.
 * The only other difference from what you were thinking is the last line - which says if 'draft' has not been set, assume it is 'true' if 'draft.output' has been set.

What I'm going to do is write a `R/build.R` that implements this logic - That way it will be working for me and you can see if it is something worth integrating. I do believe this is a valuable feature other power R users would find beneficial.

**Comment by mwaldstein** [comment]
I have a build.R I'm fairly happy with - I also wanted to clarify the problem statement:

# Reproduction

1. Create a new blogdown site
```
Rscript -e 'blogdown::new_site()'
```
2. Edit ` content/post/2015-07-23-r-rmarkdown.Rmd` to add 'draft: true' to the frontmatter
3. Build the site
```
Rscript -e 'blogdown::build_site()'
```

## Observed issue

No by-products of `2015-07-23-r-rmarkdown.Rmd` are expected in the public folder. In actuality, `./post/2015-07-23-r-rmarkdown_files/figure-html/pie-1.png` is created.

## Proposed Solution

I implemented a change as we discussed, delta here:
https://github.com/rstudio/blogdown/compare/master...mwaldstein:patch-1

If you approve, I'll clean it up, add documentation and create a pull request.

**Comment by yihui** [comment]
What is your workflow when using blogdown? Do you use `blogdown::serve_site()`?

I'm asking because your implementation means `serve_site()` will still compile the Rmd no matter if it contains `draft: yes` or `no`.

If you don't use `serve_site()`, [you won't benefit from caching.](https://bookdown.org/yihui/blogdown/local-preview.html)

You said you had a script `R/build.R` that did what you wanted (skipping the compilation of certain Rmds). I wonder how you made it, because I don't know how to achieve it through `R/build.R`. Anyway, if your `R/build.R` gives you what you need, I tend not to implement it in **blogdown**.

**Comment by mwaldstein** [comment]
Yes, I do use serve_site for editing and you are correct, that is does compile all Rmd's. To deploy though, I remove the existing public directory and use `build_site`.

`R/build.R` is a fantastic solution to completely change the behavior of the package and I have implemented the change using it, I'm of the belief that this is an issue other people would see and like to have a solution for. If you disagree, you're welcome to close this - just trying to help make blogdown as good as possible for everyone.

**Comment by yihui** [comment]
Okay. I'll close it for now, but will also be happy to re-open it if we have a second vote on this feature. Thanks!

**Comment by edornshuld** [comment]
I realize this is an old thread but I was wondering what the build.R script needs to have in order to not build `.Rmd` files with `draft: yes` in the YAML.

**Comment by cderv** [comment]
@edornshuld with last **blogdown** version, the Rmd files are no more rendered by default. the `build_rmd` in `build_site` is FALSE by default. 

I believe this is now the best way to achieve this "don't build draft Rmd" as no RMD will be build by default. 

* Interactively, Use the knit button of Rmd file you want to build - just don't knit the draft file.
* Using `build_site`, you can pass a vector of file paths to the `build_rmd` argument. Or you can pass a function that would take Rmd files under content `content/` and output the path to update. You can then create function that would filter out the draft post. 


See `?build_site`

Hopes it helps.

**Comment by yihui** [comment]
@edornshuld In addition to what @cderv said, here is one way to skip files that have `draft: yes`:

```r
blogdown::build_site(build_rmd = function(files) {
  # apply a newfile filter first, to skip files that have been built before
  files = blogdown::filter_newfile(files)
  # now check if `draft: true` is present in these files
  x = NULL
  for (f in files) {
    if (length(grep('^draft: (yes|true)\\s*$', xfun::read_utf8(f)))) x = c(x, f)
  }
  x
})
```
