### ISSUE TITLE
Vectorizing shortcode?

### ISSUE THREAD

**Issue by maelle** [rstudio/blogdown#307]
First of all, thanks for a great package!

In my post [here](https://masalmon.eu/2018/06/26/storrrify-satrdaycdf-2018/) I tried to use `shortcode` on a vector of tweet IDs. I couldn't figure which chunk options would help me get the shortcodes as I needed them, so I ended up writing

```r
library("magrittr")
# Good than one can choose glue limits!
glue::glue("{{< tweet [my_satrday_tweets$status_id] >}}",
             .open = "[", .close = "]") %>%
    htmltools::HTML()
```

Would a vectorized version of `shortcode` be useful?

**Comment by yihui** [comment]
Yes, and done. You may use `shortcodes()` now, e.g.,

```r
blogdown::shortcodes('tweet', my_satrday_tweets$status_id)
```

**Comment by maelle** [comment]
Wow that was fast, thanks a lot @yihui!
