### ISSUE TITLE
figures not being generated

### ISSUE THREAD

**Issue by thedatacollective** [rstudio/blogdown#31]
I've recently come across `blowdown` after reading and searching for how to include `htmlwidgets` with `jekyll`+`knitr` to no avail.

I've been able to do a basic build using the instructions in the Readme.MD file, however I am struggling to understand why some charts don't end up with a figure being placed in the `../public/...` folder.

The chart gets created in the `../blogdown/post/mypost_files/figure-html/` folder however they don't end up in at all in the `../public` location.

I've got a repo [here](https://github.com/thedatacollective/blogtest) that hopefully demonstrates the issue at hand.

Let me know if you need any `sessionInfo`

**Comment by pdelboca** [comment]
Changing the name of the r chunk so it doesn't contain blank spaces solves the problem. From **Rainfall chart** to **rainfall_chart** should work ok. 

I don't know why an image with a blank space doesn't work, it is created with the correct name and the html src has its %20 in the url. Maybe others can help understanding why it is failing with the whitespace.

**Comment by thedatacollective** [comment]
That seems to have fixed the problem.

**Comment by yihui** [comment]
Yes, `%20` is the culprit. Before I copy figures to public/, I should have restored the actual image paths from the encoded paths (a space is encoded as `%20`).

Before I come up with a fix, you will have to make sure the chunk labels contain no spaces.
