### ISSUE TITLE
Keep comments when using hugo_convert(unsafe = TRUE)

### ISSUE THREAD

**Issue by petzi53** [rstudio/blogdown#314]
I am using the academic theme which uses the TOML syntax `+++`. With the conversion `hugo_convert(unsafe = TRUE)`, all the comments are deleted.  I would be nice if the conversion routine would keep the comments, as they contain important hints on how to use the academic framework (e.g. how to fill in the parameters).

**Comment by yihui** [comment]
That would be a feature request to Hugo. I don't think I'm able to do anything here. Sorry.
