### ISSUE TITLE
Starting with version 2.2.0 hugo-academic does not work with RMarkdown/blogdown anymore

### ISSUE THREAD

**Issue by petzi53** [rstudio/blogdown#315]
After updating blogdown and the hugo academic theme I noticed after a while that with `"Build" -> "More…" -> "Clean All" blogdown:::serve_site()` blogdown did not produce a preview of the website but created the index of the site. I have reported all the details with error messages, sessionInfo etc. at the [forum of the RStudio Community](https://community.rstudio.com/t/serve-site-creates-index-of-site-rather-than-site-preview-blogdown/11120).

At first it was difficult to provide a reproducible example with my website but then I noticed that a new installation with blogdown & the academic theme produced this error immediately after installation with the first `serve_site()`.

I started the rollback to previous version with blogdown but this didn't help. So it appears that your package blogdown is not the cause. Finally it turned out that with version 2.2.0 of the academic theme this error emerged. I reported it to @gcushen but he thinks that the problems must be in blogdown.

> ... it appears unrelated to the Academic code. Academic works fine when used directly with Hugo. Since the problem only occurs with Blogdown and based on your comments and the fact that Blogdown acts as a wrapper around Hugo, it would appear that there may be a bug in Blogdown.

Frankly speaking, I do not know where the problem could be. I am a little surprised (and worried) that I am the first user to notice this problem as I know many people are using your blogdown package with the academic theme. A possible explanation may be that not so many people did recently update and – more important – the error does only appear in a working website after you are using the menue button "Build" -> "More…" -> "Clean All". As this is not a common procedure, so maybe this is the reason that people have not yet noticed this problem.

**Comment by yihui** [comment]
I'm going to kick the ball back to @gcushen soon :)

**Comment by tcgriffith** [comment]
I confirm that the same error appears even when I use the `examleSite` from the theme, strange!

**Comment by yihui** [comment]
I'm pretty sure blogdown is innocent in this case. The problem is somewhere between Hugo and the academic theme.

---

To future users who may come here, please follow the issue https://github.com/gcushen/hugo-academic/issues/594.
