### ISSUE TITLE
blogdown本地预览与netlify部署后的显示不一致

### ISSUE THREAD

**Issue by ShixiangWang** [rstudio/blogdown#316]
你好，

我在使用blogdown时发现本地一切显示正常，但放到netlify部署（<www.shixiangwang.top>）后，很多rmd文档写的博文（<https://github.com/shixiangwang/shixiangwang>）都显示不出来，请问这是什么原因呢？

祝好，
诗翔

**Comment by tcgriffith** [comment]
看 #312 

升级一下blogdown到dev版：

devtools::install_github('rstudio/blogdown')

**Comment by yihui** [comment]
CRAN 版就够用了，当然开发版也没问题。

总之，升级后，需要删除从 .Rmd 生成的 .html 文件，再在本地重编网站。

**Comment by ShixiangWang** [comment]
@tcgriffith  @yihui 谢谢两位，最近写博文一直遇到这问题，百思不得其解来着。

**Comment by yihui** [comment]
嗯，你只是碰巧撞上了一个八阿哥，我已经在 CRAN 允许的条件下（一周之内只能更新一次）用最快的速度更新了。

**Comment by lymlin** [comment]
为什么netlify 部署总是错误  报225 ‘’‘’Error running command: Build script returned non-zero exit code: 255‘’‘’‘’
