### ISSUE TITLE
Is it possible to define global variable for a blog?

### ISSUE THREAD

**Issue by gezmi** [rstudio/blogdown#317]
Hi,

I am using blogdown to keep track of the results of my research. It would be nice to define a few global variables. Is it possible somehow?

Thank you for the answer!

**Comment by yihui** [comment]
You may try .Rprofile, in which you can do anything you want when R starts up (not only `options()`): https://bookdown.org/yihui/blogdown/global-options.html

---

For general questions, please ask them on StackOverflow first, using at least the tags `r` and `blogdown`: http://stackoverflow.com/questions/ask Please come back here only if nobody answers your question there in at least 24 hours, and let us know the URL of your StackOverflow post. If you are not sure whether you should use StackOverflow or Github issues, use Stackoverflow first. We do watch StackOverflow questions as actively as Github issues.
