### ISSUE TITLE
SCSS handling?

### ISSUE THREAD

**Issue by jcdepth** [rstudio/blogdown#319]
Are there any quirks about how blogdown calls Hugo, or how it handles SCSS?
I've attempted to serve a site with this theme https://github.com/htr3n/hyde-hyde. I've created a blank folder, and then tried calling:
```
new_site(theme = "htr3n/hyde-hyde")
```
The content will load, but it's a plain text page with no styling or CSS elements. That theme seems to use SCSS files.

I've noticed that `new_site` or `install_theme` are not downloading the `static-src` file from that repo, so I've manually added those files to the repo, but still get a page with no styling.

However, when serving the site with `hugo server -D` directly from the terminal/command line, the site loads just fine, complete with CSS styling. I've noticed that this SCSS issue seems to be happening with this theme as well: https://github.com/enten/hyde-y.

Any help would be greatly appreciated.

I'm running Hugo 0.45.1 on an Ubuntu 18.04.1 machine. I'm running R version 3.5.1, and RStudio version 1.1.456.

**Comment by tcgriffith** [comment]
I digged into this theme and find that it's ill formed. Basically they use something like

```
<link rel="stylesheet" href="{{ .Site.BaseURL }}/css/hyde-hyde.css">
```
to point to the css files in 
`themes/hyde-hyde/layouts/partials/header/styles.html`

This is ok with hugo serve, but in blogdown, My understanding is that blogdown grabs the  `./public` dir and drop it in some local server (not the hugo one), so it will not find the css files.(I didn't read the code, It might be wrong)


Solution: 

Change that line to

```
<link rel="stylesheet" href="css/hyde-hyde.css">
```

will render the site correctly in rstudio.

**Comment by yihui** [comment]
The portable way to include a resource is to use the `relURL` function, e.g.,

```html
<link rel="stylesheet" href="{{ "/css/hyde-hyde.css" | relURL }}">
```

instead of using `.Site.BaseURL`:

```html
<link rel="stylesheet" href="{{ .Site.BaseURL }}/css/hyde-hyde.css">
```
