### ISSUE TITLE
Responsive css for htmlwidgets 

### ISSUE THREAD

**Issue by pdelboca** [rstudio/blogdown#32]
Hello! 

First of all, thanks for the work! This package is amazing. As others, I've started using blogdown for an easy integration of htmlwidgets. I've tested several themes and in all of them, the htmlwidgets doesn't look good in mobile.

The problem I have is that the width of the htmlwidgets, when browsing from a phone, is always in pixels and they doesn't adjust correctly to the screen. To solve this, I need to set the parameter width="100%" when initializing all the htmlwidgets so they can have a "responsive behaviour". 

Sorry if the question is not for this package but: **Which is the best way to solve this issue?** I want that by default, all the htmlwidgets to have a more mobile-friendly style without manually inserting width=100% when creating the htmlwidget. 

Should I look for a Hugo Theme with specific css? Should I config some global parameter of blogdonw/knitr?

Thanks!

**Comment by bhaskarvk** [comment]
I'm working on supporting responsive widgets via responsive iframe in https://github.com/bhaskarvk/widgetframe. But there are some issues that I still need to resolve. Stay tuned.

**Comment by yihui** [comment]
I have not tried, but perhaps the chunk option `out.width='100%'`?

**Comment by pdelboca** [comment]
Yes @yihui, that option in the chunk option gives the htmlwidgets the responsive behaviour I was looking for! 

Thanks for the reply!

**Comment by jp1312** [comment]
Hi,
I have got the same problem as @pdelboca but I am not sure I understood the suggestion of @yihui . Where can I add the chunk option out.width='100%'? In R when I call saveWidget() or somewhere in the javaScript? Or should I try with frameableWidget?
Thanks!
J

**Comment by yihui** [comment]
```{r out.width='100%'}
