### ISSUE TITLE
Code for ggplot2 not rendering properly

### ISSUE THREAD

**Issue by lambdamoses** [rstudio/blogdown#321]
Whenever I do something like 

``` r
foo <- ggplot(...) +
  geom_*()
foo
```
The code does not render properly. I get something like this in the preview in my browser when I serve site (haven't deployed my site yet, so this is run locally):
<img width="679" alt="screen shot 2018-07-30 at 11 57 44 am" src="https://user-images.githubusercontent.com/32186361/43417663-719abec6-93f0-11e8-8500-18c6dec896ca.png">
I only get this problem when I use `ggplot2`. The plot renders correctly.

Furthermore, for the first chunk, the comments are not highlighted (they're gray in other chunks).
<img width="207" alt="screen shot 2018-07-30 at 12 06 20 pm" src="https://user-images.githubusercontent.com/32186361/43417922-40ff6ebe-93f1-11e8-8b04-a3cc08fa8610.png">

I'm using the RStudio 1.2 preview version and the most recent `blogdown` from CRAN, and the Tranquilpeak theme with default code highlighting from the theme. I tried other code highlighting styles and this problem persists, so I don't think it's the problem with code highlighting style.

**Comment by tcgriffith** [comment]
could you provide your repo?

**Comment by lambdamoses** [comment]
Here it is: https://github.com/lambdamoses/blog
One of the "posts" was added to reproduce the code rendering problem. You may also see the problem in one of the real posts, in which I used `gganimate` to make Lorenz attractor animations.

**Comment by tcgriffith** [comment]
Your problem is that code highlighting by `highlight.js` is incorrect in the final html page:

`<code class="codeblock hljs shell">......`

`<code class="codeblock hljs xml">......`

`<code class="codeblock hljs perl">......`

By searching I found that highlightjs will auto-determine what language your code is using and highlight by that, but I'm not familiar with highlightjs, hope somebody else could help.

**Comment by lambdamoses** [comment]
Thanks for your response! Which html file is that? I can't find it in my repo. For the toy example, in the html file generated from the Rmd file in the content/post directory, I saw this:

    <pre class="r"><code>foo &lt;- ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) +
      geom_point()
    foo</code></pre>
So it knows that my code is R.

**Comment by tcgriffith** [comment]
@lambdamoses 

I ran `hugo serve`  and view the site in chrome,  then `right-click` -> `inspect` to view the source in the developer tools.

**Comment by tcgriffith** [comment]
I think I found the problem,  It's related to the theme.

[highlightjs is configured from here](https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/layouts/partials/script.html#L21-L31)

delete it or modify the configuration according to [highlightjs doc](http://highlightjs.readthedocs.io/en/latest/api.html#configure-options)

Another found is that this theme has a shortcode `{{< codeblock >}}` to do the [fancy codeblock highlighting](https://tranquilpeak.kakawait.com/2015/03/highlighted-code-showcase/), but you can't use it unless you write pure md.

**Comment by lambdamoses** [comment]
I added the languages option, and it worked. Thanks!

    <script>
    $(document).ready(function() {
      hljs.configure({ classPrefix: '', useBR: false, languages: ['r', 'bash', 'python', 'c++'] });
      $('pre.code-highlight > code, pre > code').each(function(i, block) {
        if (!$(this).hasClass('codeblock')) {
          $(this).addClass('codeblock');
        }
    hljs.highlightBlock(block);
  });
});
</script>

**Comment by yihui** [comment]
I always disable highlight.js's auto detection of languages myself: https://github.com/yihui/hugo-ivy/blob/4d642eb577dea4a4f3836fe9c838d9ec3034e644/layouts/partials/footer_highlightjs.html#L10

**Comment by ktiu** [comment]
Same problem here.

It seems to me that [highlight.js expects the class attribute in the `code` tag](https://highlightjs.org/usage/)

`<pre><code class="html">...</code></pre>` 

while blogdown auto-generates  the class attribute in the `pre` tag (when knitting HTML from Rmd):

`<pre class="r"><code>...</code></pre>` 

I'm just not sure if this is an issue with blogdown, or knitr, or pandoc...

> I always disable highlight.js's auto detection of languages myself: https://github.com/yihui/hugo-ivy/blob/4d642eb577dea4a4f3836fe9c838d9ec3034e644/layouts/partials/footer_highlightjs.html#L10

This only disables highlighting completely.
