### ISSUE TITLE
Unable to update Hugo within RStudio Blogdown

### ISSUE THREAD

**Issue by jananiravi** [rstudio/blogdown#324]
Hello,
I’m using RStudio v1.2.616 (R: v3.4.4) on macOS (High Sierra) with Hugo+blogdown (hugo academic theme).

When I check the version of Hugo, it says I’m at 0.30
```
> blogdown::hugo_version()
[1] ‘0.30’
```

I update it using blogdown and then repeat the above to see the same message!
```
> blogdown::update_hugo()
The latest Hugo version is 0.46
Already up-to-date.
==> Reinstalling hugo 
==> Downloading https://homebrew.bintray.com/bottles/hugo-0.46.high_sierra.bottle.tar.gz
Already downloaded: /Users/janani/Library/Caches/Homebrew/hugo-0.46.high_sierra.bottle.tar.gz
==> Pouring hugo-0.46.high_sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/hugo/0.46: 32 files, 54.9MB
NULL
```
Screenshot of the cycle:
![image](https://user-images.githubusercontent.com/8397074/44114639-cbbf645c-9fd9-11e8-85c6-474f716ac121.png)

I need a minimum of 0.38 to generate my Hugo website blogdown::build_site()
```
> blogdown::build_site()
Rendering xxx 
ERROR 2018/08/14 15:50:59 Current theme does not support Hugo version 0.30. Minimum version required is 0.38
Error: Error building site: Failed to load translations in file "Icon\r": no language found in "Icon\r"
```

Any suggestions? Thanks!
Also posted on https://discourse.gohugo.io/t/unable-to-update-hugo-within-rstudio/13587

PS: Both @archerc5 and I are facing the same issues here.

**Comment by yihui** [comment]
Please restart R after you update Hugo.

**Comment by jananiravi** [comment]
Sorry, @yihui, I'd forgotten to mention that I restarted the RStudio session right after the blogdown Hugo update. Is there anything else I should check to enable the Hugo update? Thanks!

**Comment by yihui** [comment]
When you run `blogdown::hugo_version()`, do you see any warnings?

What does `blogdown:::find_hugo()` return?

**Comment by jananiravi** [comment]
Sorry, I fixed it before I read this message.
### How I fixed it
Deleted all existing copies of Hugo (incl. the `bin` version again)
- ` ~/Library/Application\ Support/Hugo/`
- `/usr/local/Cellar/hugo`
- `/usr/local/bin/hugo` (I had deleted this yesterday, but seemed to have no effect)
removed all three copies now and then reran `blogdown::install_hugo(version="latest", force=TRUE)`

### Response to find_hugo()
> > blogdown:::find_hugo()
[1] "hugo"

Now my Hugo version is at `0.46`! 💯 
The new Hugo+blogdown throws some new errors I didn't encounter while rendering my previously undisturbed webpage content. I've posted the errors thrown in #326 

Is there a way to ensure that there's an internal check for all hugo versions (i found these locations from the error messages) to point to a single location and update the corresponding one? That might be helpful. Thanks for your help with #325

**Comment by yihui** [comment]
No, currently there isn't a way. When you have Hugo in two places, you should see the warning.

**Comment by jananiravi** [comment]
Yes, I do see the warning. That certainly helps! 👍Thanks.
I didn't know about the third `/usr/local/Cellar/hugo` location, though! Is that what triggered the update issue? Do you think it would help to add the third location to the error message too, in addition to `usr/local/bin/hugo` and `~/Library/Application\ Support/Hugo/`? That way, people can attend to all the hugo versions/locations before updating?

**Comment by yihui** [comment]
`/usr/local/bin/hugo` is actually a symlink created by Homebrew (which points to `/usr/local/Cellar/...`. If you want to get rid of the Hombrew version of Hugo, you can do `brew remove hugo`, which will remove both the symlink and the actual "bottle" in the "cellar". If you want to get rid of `~/Library/Application\ Support/Hugo/`, you can delete it.

You did make a good point that `update_hugo()` probably should update the one at `~/Library/Application\ Support/Hugo/` if a previous version has been installed there, instead of using Homebrew. I'll tweak the `update_hugo()` function.

I guess it is relatively unlikely to run into this state. `install_hugo()` will install to `~/Library/Application\ Support/Hugo/` only if Homebrew was not installed, or you explicitly chose to `install_hugo(use_brew = FALSE)`. Then for some reason, you installed Homebrew later, and ran `install_hugo()` again or ran `update_hugo()`.

**Comment by yihui** [comment]
With the current development version, `update_hugo()` should update Hugo in the right place.

**Comment by jananiravi** [comment]
Thank you, @yihui. This commit would be helpful. 👍🏼 Hopefully, we won't encounter hugo update issues anymore.

**Comment by marcemiraval** [comment]
Downgrading Hugo to version 0.33 solved this problem for me.
blogdown::install_hugo(version = "0.33", force = TRUE)

**Comment by achamess** [comment]
I had to remove my local Hugo on Mac OS. Then the blogdown version worked for me.

**Comment by TanjaKec** [comment]
If you get a problem of this kind you can simply resolve it by using the following command
blogdown::install_hugo(force = TRUE)
