### ISSUE TITLE
Using the blogdown function

### ISSUE THREAD

**Issue by mutigaj1** [rstudio/blogdown#325]
> blogdown::new_site()
Error: C:\Users\jesse\Documents already exists and is not empty
Error: C:\Users\jesse\Documents already exists and is not empty
'C:\Users\jesse\AppData\Roaming\Hugo\hugo.exe" new site ".' is not recognized as an internal or external command,
operable program or batch file.
Error in shell(cmd, mustWork = TRUE, intern = intern) : 
  '"C:\Users\jesse\AppData\Roaming\Hugo\hugo.exe" new site "." -f toml' execution failed with error code 1
In addition: Warning message:
In blogdown::new_site() : The directory '.' is not empty

help me fix this

**Comment by cderv** [comment]
Hello, 

for this kind of question to help get going with a 📦 , you should ask on Q&A site like https://community.rstudio.com. You'll find a broader community and lots of people willing to help. I know them of them know blogdown very well.

Here are some hints that could help you: 

> blogdown::new_site()
Error: C:\Users\jesse\Documents already exists and is not empty

It seems that you are not in an empty directory. Did you follow the [_Get Started_](https://bookdown.org/yihui/blogdown/a-quick-example.html) of bookdown ? it says  
_There are many things you may want to tweak for the website later, but the first step is actually fairly simple: create a new project under a new directory in the RStudio IDE (File -> New Project), and call the 
function in the R console of the new project: `blogdown::new_site()`_

If you have RStudio IDE version >= 1.1.383, you can create a new blogdown project directly through the _New project_ menu. See in the book [about RStudio IDE integration](https://bookdown.org/yihui/blogdown/rstudio-ide.html) 

You also find several great blogdown tutorial on the web.
