### ISSUE TITLE
Blogdown: System cannot find the specified path

### ISSUE THREAD

**Issue by INyabuto** [rstudio/blogdown#328]
## Not able to solve, after updating my packages. 
I am using Icarus theme. My site has been working on well until I installed a new RStudio IDE. 

Building sites â€¦ ERROR 2018/08/18 14:42:38 Error while rendering "home" in "": template: index.html:2:7: executing "main" at <partial "article_lis...>: error calling partial: template: partials/article_list.html:2:19: executing "partials/article_list.html" at <$paginator.pages>: can't evaluate field pages in type *hugolib.Pager
Building sites â€¦ ERROR 2018/08/18 14:42:38 Error while rendering "home" in "": template: index.html:2:7: executing "main" at <partial "article_lis...>: error calling partial: template: partials/article_list.html:2:19: executing "partials/article_list.html" at <$paginator.pages>: can't evaluate field pages in type *hugolib.Pager
The system cannot find the path specified.
Error in shell(cmd, mustWork = TRUE, intern = intern) : 
  '"C:\Users\Isaiah\AppData\Roaming\Hugo\hugo.exe" -b / -D -F -d "public" -t hugo-icarus-theme' execution failed with error code 1

**Comment by yihui** [comment]
This is probably not related to the RStudio IDE upgrade. Did you upgrade Hugo? That is more likely to be the reason. Anyway, since you didn't follow the issue guide to provide a reproducible example, there is no way I could help you.
