### ISSUE TITLE
Error: evaluation nested too deeply when updating "stringi", "tinytex", "digest" packages 

### ISSUE THREAD

**Issue by Fabbiologia** [rstudio/blogdown#329]
Hello, 
i am experiencing a problem with blogdown. 
i run R version 3.5.1 (2018-07-02) -- "Feather Spray" with R studio Version 1.1.456

I had no problems up until recently (couple of days ago)
It started when tried building my website using blogdown v. 0.8, that gives the Error 
evaluation nested too deeply: infinite recursion / options(expressions=)?
Execution halted

I tried changing option(expression=) to different values, but didn't solved the issue. 
Now i have the same error on startup. 
I deleted the .Rdata file, i don't load any file on startup. However the error is still there. 
I tried deleting R, R studio and all the packages (except base and reccommended), now when i try to reinstall blogdown it give the same issue when triyng to install the following packages: 
 ‘stringi’, ‘tinytex’, ‘digest’

this is what comes up in the console: 
`The downloaded binary packages are in
	C:\Users\zephi\AppData\Local\Temp\RtmpqQ8eEU\downloaded_packages
installing the source packages ‘stringi’, ‘tinytex’, ‘digest’

trying URL 'https://cran.rstudio.com/src/contrib/stringi_1.2.4.tar.gz'
Content type 'application/x-gzip' length 17916239 bytes (17.1 MB)
downloaded 17.1 MB

trying URL 'https://cran.rstudio.com/src/contrib/tinytex_0.7.tar.gz'
Content type 'application/x-gzip' length 19205 bytes (18 KB)
downloaded 18 KB

trying URL 'https://cran.rstudio.com/src/contrib/digest_0.6.16.tar.gz'
Content type 'application/x-gzip' length 123969 bytes (121 KB)
downloaded 121 KB

Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Execution halted
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘stringi’ had non-zero exit status
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Execution halted
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘tinytex’ had non-zero exit status
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Execution halted
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘digest’ had non-zero exit status
`

all the other task in R works fine. All the other packages can be installed and updated with no problem. I guess that is an issue i have in compiling from source those packages when i try to install blogdown. 

any solution that might help with my problem? 
thanks in advance for your time and support
Fabio

**Comment by yihui** [comment]
https://stackoverflow.com/q/51977069/559676

When you [cross-post issues](https://yihui.name/en/2017/10/cross-posting/), please mention it. Let's keep everyone in the same thread. Thanks!
