### ISSUE TITLE
Figures generated by Rmd not found when publishdir != "public"

### ISSUE THREAD

**Issue by hturner** [rstudio/blogdown#33]
Following advice [here](http://disq.us/p/1exwlca) we're using separate source and publication repos. Unfortunately when publishdir was set to the publication repo (i.e. publishdir = "../forwards.github.io") the figures created when compiling the .Rmd files were not copied to the correct place, so the links in the final .html files didn't work.

We're currently getting around this by publishing to the "public" directory, then copying over when we're ready to publish (see [our hack](https://github.com/forwards/website_source#publishing-the-website)).

**Comment by yihui** [comment]
I think this is a bug, and I'll fix it in the next couple of days. Thanks for the report!

Actually I think you can also clone the `forwards.github.io` repo into `public/` (it is okay to have one GIT repo inside another), so you don't have to copy `public/` to `../forwards.github.io`.

**Comment by hturner** [comment]
Thanks for the tip, I will try that out!

**Comment by yihui** [comment]
Should be fixed now. You can use arbitrary `publishdir`.
