### ISSUE TITLE
<!--more--> dose not work at .Rmd

### ISSUE THREAD

**Issue by TonyFly3000** [rstudio/blogdown#330]
dose not work at .Rmd  for theme hyde-hyde
same as 
https://github.com/rstudio/blogdown/issues/21

it can be slightly modified in .md documents by adding a  tag below content you wish to be included. This tag doesn't seem to work on blogdown-generated .Rmd files, causing the default summary to be the first 70 words of the post (which often includes the table of contents and other materials that aren't appropriate for a summary).

**Comment by cderv** [comment]
There are some other related issue on this point #142 and #92  with some interesting answer.
In fact, there is also a blogpost on this specific subject of summary and the approach I believe has been recommended for blogdown
https://yihui.name/en/2017/08/hugo-post-summary/

**Comment by TonyFly3000** [comment]
Thanks Yihui ,Christophe for the great package and respond .
I did read yihui blog. and follow the same guideline . But the .Rmd still show first 70 words of the post (which often includes the table of contents and other materials that aren't appropriate for a summary).
 
And I found out that  work on .Rmarkdown .for now I may just use .Rmarkdown instead of .Rmd

in .Rmd I changed to 
---
title: test002
author: ''
date: '2018-08-30'
slug: test002
categories: []
tags: []
lastmod: '2018-08-30T01:24:02+08:00'
layout: post
type: post
highlight: no
description: 'Wonder how I set up this website using just GitHub pages Hugo'
---

in themes\hyde-hyde\layouts\_default\list.html  I changed to 

{{ define "header" }}
    {{ partial "header.html" . }}
{{ end }}

{{ define "content" }}
    {{ partial "page-list/content.html" . }}
{{ end }}

{{ define "footer" }}
    {{ partial "page-list/footer.html" . }}
{{ end }}

{{ with .Description }}
	{{ $.Scratch.Set "summary" (markdownify .) }}
{{ else }}
	{{ $.Scratch.Set "summary" ((delimit (findRE "(<p.*?>(.|\n)*?</p>\\s*)+" .Content) "[&hellip;] ") | plainify | truncate (default 200 .Site.Params.summary_length) (default " &hellip;" .Site.Params.text.truncated ) | replaceRE "&amp;" "&" | safeHTML) }}
{{ end }}
{{ $.Scratch.Get "summary" }}

**Comment by cderv** [comment]
> {{ with .Description }}
{{ $.Scratch.Set "summary" (markdownify .) }}
{{ else }}
{{ $.Scratch.Set "summary" ((delimit (findRE "(<p.?>(.|\n)?
\s*)+" .Content) "[…] ") | plainify | truncate (default 200 .Site.Params.summary_length) (default " …" .Site.Params.text.truncated ) | replaceRE "&" "&" | safeHTML) }}
{{ end }}
{{ $.Scratch.Get "summary" }}

It is not exactly the same as in [the example in #92](https://github.com/yihui/hugo-xmag/blob/master/layouts/_default/list.html) - some `*` characters and a `</p>` are missing for example. 
```html
    {{ with .Description }}
      {{ $.Scratch.Set "summary" (markdownify .) }}
    {{ else }}
      {{ $.Scratch.Set "summary" ((delimit (findRE "(<p.*?>(.|\n)*?</p>\\s*)+" .Content) "[&hellip;] ") | plainify | truncate (default 200 .Site.Params.summary_length) (default " &hellip;" .Site.Params.text.truncated ) | replaceRE "&amp;" "&" | safeHTML) }}
    {{ end }}
{{ $.Scratch.Get "summary" }}
```` 
Did you try exactly as proposed ? I assumed it should work as is before any modification.

`.Rmarkdown` is a solution as it uses the default Hugo generator and not pandoc, the generator for rmarkdown package. I assume Hugo knows how to deal with your `<!--more-->` tag. 
See [blogdown chapter](https://bookdown.org/yihui/blogdown/output-format.html) for differences.

**Comment by TonyFly3000** [comment]
'''
    {{ with .Description }}
      {{ $.Scratch.Set "summary" (markdownify .) }}
    {{ else }}
      {{ $.Scratch.Set "summary" ((delimit (findRE "(<p.*?>(.|\n)*?</p>\\s*)+" .Content) "[&hellip;] ") | plainify | truncate (default 200 .Site.Params.summary_length) (default " &hellip;" .Site.Params.text.truncated ) | replaceRE "&amp;" "&" | safeHTML) }}
    {{ end }}
{{ $.Scratch.Get "summary" }}
'''

**Comment by TonyFly3000** [comment]
```r
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```
