### ISSUE TITLE
Tilde (~) in baseurl crashes RStudio

### ISSUE THREAD

**Issue by ktiu** [rstudio/blogdown#332]
I just started using this package and I love it! Great idea, and thank you so much.

I ran across an issue however. To reproduce:

1. Start a new blogdown website in RStudio with default settings
2. In `config.yaml`, change the first line to any string containing the tilde character at the beginning of a directory, e.g.:

```
baseurl = "/~myusername"
```

3. Serve the website: `blogdown::serve_site()`
4. Watch RStudio go down in flames.

The error log reads:

```
13 Sep 2018 16:29:01 [rsession-xxx] ERROR system error 2 (No such file or directory); OCCURRED AT: rstudio::core::Error rstudio::session::source_database::getId(const std::string &, std::string *) /Users/rstudio/rstudio/src/cpp/session/SessionSourceDatabase.cpp:861; LOGGED FROM: SEXP rstudio::session::source_database::<anonymous namespace>::rs_getDocumentProperties(SEXP, SEXP) /Users/rstudio/rstudio/src/cpp/session/SessionSourceDatabase.cpp:960
```

I'm using OS/X 10.13.6 / RStudio 1.1.456 / R 3.5.1

Any pointers would be appreciated!

**Comment by yihui** [comment]
Have you tried the preview version of RStudio? https://www.rstudio.com/products/rstudio/download/preview/

**Comment by ktiu** [comment]
I was not aware of such a thing! This seems to resolve the issue, thanks a lot!
