### ISSUE TITLE
"Number of words" and "time read" text wrong when using htmlwidgets

### ISSUE THREAD

**Issue by DataStrategist** [rstudio/blogdown#334]
Hi, please take a look at this blogpost: 
https://www.amitkohli.com/2018/09/23/2018-07-07-crime-statistics-in-london/

coming from ogithub repo: https://github.com/DataStrategist/amitkohli.com/blob/master/content/post/2018-07-07-crime-statistics-in-london.Rmd

My question. Clearly this isn't a 130 minute read... I think what's happening is that perhaps the htmlwidget is making the article look beffier than it is?

Is there any way to avoid this behavior?

**Comment by yihui** [comment]
HTML widgets often generate large `<script>` tags. Hugo does not seem to exclude `<script>` when counting words. I cannot do anything for you in blogdown. You have to ask the question in the upstream project, i.e., Hugo. Thanks!

**Comment by DataStrategist** [comment]
Will do! Thanks!
