### ISSUE TITLE
Latex Math in RMarkdown - Rendering problems for braces in FF Quantum / Chrome

### ISSUE THREAD

**Issue by harlecin** [rstudio/blogdown#338]
Hey there,

I noticed that on Chrome (version 67.0.3396.99) and on Firefox Quantum (version62.0.3 (64-Bit)) on Windows (could not try it on a Mac yet, but iPad/iPhone with Safari has no problems) rendering of braces (\underbrace, \left{ ...\right} etc) is not working correctly.

You can see the screenshot from Chrome/FF here:
![underbrace-not-working](https://user-images.githubusercontent.com/11078385/46917287-a6475600-cfc5-11e8-8611-968ba0ba3b95.PNG)

And the working version from Microsoft Edge/Safari here:
![underbrace-working-edge-safari](https://user-images.githubusercontent.com/11078385/46917291-b5c69f00-cfc5-11e8-933b-06054be5a2f7.PNG)

Is it possible that this can be fixed from blogdown or should I open an issue with Mozilla?

Sry for clogging your issue list! Feel free to close the item, if it is not relevant!

Here is a link to my webpage, in case you want to check the generated html code: https://harlecin.netlify.com/post/neural-nets-from-scratch-in-r/

Thanks a lot for any help in advance and for building blogdown:) This package is amazing!

Best

**Comment by yihui** [comment]
In the future, please post the link to the source repo of your website. It took me a while to find it from your Github profile. You have posted the link to the problematic output page, which is great.

The solution is to replace

https://github.com/harlecin/hugo-site/blob/master/themes/hugo-black-and-light-theme/layouts/partials/footer_mathjax.html

with

https://github.com/yihui/hugo-lithium/blob/master/layouts/partials/footer_mathjax.html

(more info in the commit message: https://github.com/yihui/hugo-lithium/commit/c21cd9952c24ba3a87591fbb569ce0631042cd27)
