### ISSUE TITLE
Enhancement: Use file hashes to determine which Rmd files to knit

### ISSUE THREAD

**Issue by jonathan-g** [rstudio/blogdown#341]
I have a site that programmatically generates Rmd files from a database (I use it for teaching, and it does this to automatically update homework assignments, post answers, etc., using the database to automate moving a syllabus from one semester to the next and cross-referencing between assignments).

Because I regenerate .Rmd files, using timestamps to determine what needs to be knit doesn't work. I wrote a small script that I use that hashes source and output files (using `blogdown:::list_rmds()` and `blogdown:::output_file()` to get source and output files, respectively) and maintains a tibble of filenames and hashes in an `.Rds` file in the project root directory.

If this would be of interest to the blogdown maintainers, I could create a PR from this.

```
needs_rebuild <- function(current_digest, current_dest_digest,
                          old_digest, old_dest_digest) {
     current_digest != old_digest | current_dest_digest != old_dest_digest %>% 
     replace_na(TRUE)
}

digest_if_exists <- function(file) {
  # SHA256 is extreme overkill. CRC32 would be fine.
  # But it takes almost no time to hash a semester's worth of 
  # files.
  if (file.exists(file)) digest(file, file = TRUE, algo = "sha256")
  else as.character(NA)
}

files_to_rebuild <- function(files) {
  base <- here::here()
  files <- unique(files) %>% keep(file.exists)
  df <- tibble(file = files, dest = blogdown:::output_file(files)) %>%
    mutate(cur_digest = map_chr(file, digest_if_exists),
           cur_dest_digest = map_chr(dest, digest_if_exists))

  digest_file <- here::here("digests.Rds")

  if (file.exists(digest_file)) {
    # message("reading digest file")
    digest <- read_rds(digest_file) %>%
      mutate(file = str_replace_all(file, ("^~"), base)) %>%
      select(-dest)
    df <- df %>% left_join(digest, by = "file")
  } else {
    # message("no digest file")
    df <- df %>% mutate(digest = NA, dest_digest = NA)
  }

  df <- df %>%
    mutate(rebuild = needs_rebuild(cur_digest, cur_dest_digest,
                                   digest, dest_digest))

  # For debugging
  # g_files <<- df

  df %>% filter(rebuild) %$% file
}

update_rmd_digests <- function(files) {
  base <- here::here()
  digest_file <- here::here("digests.Rds")
  files <- unique(files) %>% keep(file.exists)
  digests <- tibble(file = files, dest = blogdown:::output_file(files)) %>%
    mutate(digest = map_chr(file, ~digest(.x, file = TRUE, algo = "sha256")),
           dest_digest = map_chr(dest, digest_if_exists),
           file = str_replace_all(file, fixed(base), "~"),
           dest = str_replace_all(dest, fixed(base), "~"))
  write_rds(digests, digest_file)
}

update_site <- function(dir = here::here("content"), quiet = FALSE) {
  files <- blogdown:::list_rmds(dir)
  to_build <- files_to_rebuild(files)
  if (! quiet) {
    message("Building ", length(to_build), " out of date ",
            ifelse(length(to_build) == 1, "file", "files"),
            "; site has ", length(files), " ",
            ifelse(length(files) == 1, "file", "files"),
            " in total.")
  }
  blogdown:::build_rmds(to_build)
  update_rmd_digests(files)
}
```

**Comment by yihui** [comment]
I think the idea is fantastic here. I just wonder how many dependency packages you are able to get rid of in the code above (here, magrittr, stringr, tibble, ...).

**Comment by jonathan-g** [comment]
Great. I will pare this down to reduce the number of dependencies and then prepare a PR.

**Comment by jonathan-g** [comment]
A quick question: @yihui 

What is the motivation for reducing dependencies?

blogdown imports rmarkdown, which in turn imports stringr and rprojroot.

If the goal is to minimize bloat on installed packages there would not be a problem importing these two packages since they would already be installed by rmarkdown.

It's easy to remove a bunch of dependencies on tidyverse (dplyr, tibble, tidyr, and purrr) from my code, but it would be simpler to keep my stringr string manipulations if that's not a problem.

On the other hand, if you have a reason for not wanting a dependency on stringr, even though it's imported by rmarkdown, then it would not be hard for me to replace stringr functions with base functions like gsub and grep.

**Comment by yihui** [comment]
Oh, actually stringr is fine for now. I wish to get rid of it in knitr, but it's actually way more challenging than I imagined: https://github.com/yihui/knitr/pull/1552. For the tidyverse dependencies, yes, if you could remove these dependencies, that will be great, because they were not used anywhere in this package.

**Comment by jonathan-g** [comment]
OK. I managed to eliminate all dependencies except the "digest" package. I've submitted a PR.

**Comment by yihui** [comment]
Sorry, but I feel this issue is getting more and more complicated (#342 #343), so I just decided to give you an option to decide which Rmd files to rebuild by yourself: 86ea620d6dfbe0f745ad89dc131b0dc6662e572c. This way, you will no longer need my support. In fact, I have also tried to implement the above idea using pure base R without any dependencies, so all you need to do is set `options(blogdown.files_filter = blogdown:::md5sum_filter)` in your `.Rprofile` (the triple-colon is fine here). If you are not happy with my version of `md5sum_filter`, you could use your own custom filter. Thanks again for bringing the idea!

**Comment by jonathan-g** [comment]
That's fine. I did not want to make trouble for you.

**Comment by yihui** [comment]
FYI I just exported and documented `blogdown::md5sum_filter`.
