### ISSUE TITLE
R Code chunks mis-align when a left-handed arrow is present; not responding to tidy option

### ISSUE THREAD

**Issue by xiaobitou** [rstudio/blogdown#345]
Dear Yihui,

I recently started playing with blogdown and have been having trouble with R code chunks that contain a left-handed arrow "<-".  I tested the following two chunks in a blog post:

```{r eval = F, tidy = T}
plot <- ggplot(df, 
               
   aes(x = x, y = y))
```

```{r eval = F, tidy = F}
plot <- ggplot(df, 
               
   aes(x = x, y = y))
```

You can see the result here ([link](https://xiaobitou.github.io/2018/11/test/))
Turning on and off the tidy option did not seem to make a difference, either.  

Did I miss something here or is this a bug with blogdown?

Thank you very much!

Warmly,  Chunyun

**Comment by tcgriffith** [comment]
I've seen this issue before, for the Tranquilpeak theme in particular. See #321 

The problem is that R code chunks are mistakenly treated as xml code chunks by the default highlightjs from the theme.

The final solution we came up is to re-configure the highlight js as in here 
https://github.com/rstudio/blogdown/issues/321#issuecomment-409075782

**Comment by xiaobitou** [comment]
Thank you very much for your quick reply! @tcgriffith  I followed the solution you referenced and finally got it working! Here is what I did:
- Commented out `syntaxHighlighter = "highlight.js"` in `confit.toml`
- Followed step two described [here](https://amber.rbind.io/blog/2017/11/15/syntax-highlighting/). The tutorial was very comprehensive. The only part not very clear to me was where to add that three lines of code.  I added them inside `head.html` starting at line #43

**Comment by tcgriffith** [comment]
> Thank you very much for your quick reply! @tcgriffith I followed the solution you referenced and finally got it working! Here is what I did:
> 
> * Commented out `syntaxHighlighter = "highlight.js"` in `confit.toml`
> * Followed step two described [here](https://amber.rbind.io/blog/2017/11/15/syntax-highlighting/). The tutorial was very comprehensive. The only part not very clear to me was where to add that three lines of code.  I added them inside `head.html` starting at line43

You are doing it alright.

if you edited the theme files directly, they may be lost if you need to update the theme. A better way is to override the theme files.

In your case:

- Copy  `head.html` from  `/*blogrepo*/themes/hugo-tranquilpeak-theme/layouts/partials/head.html`
to `/*blogrepo*/layouts/partials/head.html`
- Copy the downloaded `highlight.js` to `/*blogrepo*/static/js/highlight.js`

Source: https://gohugo.io/templates/base/#override-the-base-template
