### ISSUE TITLE
serve_site fails when trying to save .Rmd files

### ISSUE THREAD

**Issue by tdamiano** [rstudio/blogdown#346]
serve_site() works correctly when first called, but starts to behave abnormally after I try to save an updated version of the .Rmd file.  The RStudio IDE slows to a crawl, I am unable to save the .Rmd and have to force quit and restart R Studio.

```sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.1  backports_1.1.2 bookdown_0.7    rprojroot_1.3-2 htmltools_0.3.6 tools_3.5.1     yaml_2.2.0     
 [8] Rcpp_1.0.0      rmarkdown_1.10  blogdown_0.9    knitr_1.20      xfun_0.4        digest_0.6.18   evaluate_0.12  
```

**Comment by tdamiano** [comment]
Thank you for your prompt response. I downloaded the preview version of RStudio to no avail, I also updated all of my packages. When that didn't work I did a clean install of R and RStudio and still encountered the problem. I will try posting on the Rstudio forum and see if anyone else is having this issue or its just me.

**Comment by tcgriffith** [comment]
Did this happen to other Rmd files?

**Comment by tdamiano** [comment]
@yihui I'm happy to try, but I have to confess I'm not sure how to do that outside of R-Studio.

**Comment by tdamiano** [comment]
@yihui I have not tried that, largely because I am not sure what that looks like from the RGUI as opposed to Rstduio

**Comment by yihui** [comment]
You can find R (instead of RStudio) from the Start menu of your Windows.

**Comment by tdamiano** [comment]
I tried running it in the RGui with similar effects. The function works
fine on my personal mac laptop. I'm noticing most of my memory being used
by antimalware processes so I will contact IT at my work and see if they
have any ideas.
----------------------------
*Anthony Damiano*
Public Affairs PhD Candidate | Humphrey School of Public Affairs
Research Assistant | Center for Urban and Regional Affairs (CURA)
University of Minnesota Twin Cities
W - 612/625-0347
C - 319/530-3532

**Comment by tdamiano** [comment]
Just as an FYI, the directory from my site was located on a network drive
(K:), I moved the directory containing my site to the C: drive and the
performance issues went away. I'm not sure exactly what was going on, but
doing that resolved the issue.
----------------------------
*Anthony Damiano*
Public Affairs PhD Candidate | Humphrey School of Public Affairs
Research Assistant | Center for Urban and Regional Affairs (CURA)
University of Minnesota Twin Cities
W - 612/625-0347
C - 319/530-3532

**Comment by yihui** [comment]
Good to know. Thanks a lot for posting back! You may try the alternative server mentioned in the **blogdown** book, which should be much faster because it doesn't involve file input/output (which seems to be slow in your case on the network drive): https://bookdown.org/yihui/blogdown/livereload.html
