### ISSUE TITLE
In New post Addin, changing filename resets slug

### ISSUE THREAD

**Issue by eliocamp** [rstudio/blogdown#347]
As the title says, when using the New Post addin, changing the filename resets the slug field to the default one instead of respecting any change made by the user. 
This comes about also when changing the format (from Markdown to Rmd, for example) because that option also changes the filename. 

I think a better way would be for the slug to be autogenerated at post creation time and only if the user has not entered any text in the slug field. 

Probably this line 
https://github.com/rstudio/blogdown/blob/e5f4317600ea0ec04faf2d73122834a79776dea5/inst/scripts/new_post.R#L69
should be moved to after this part
https://github.com/rstudio/blogdown/blob/e5f4317600ea0ec04faf2d73122834a79776dea5/inst/scripts/new_post.R#L78
And with a check to see if `input$slug` is not `''`. 

I'm not super sure if that's correct since I don't have so much experience with Shiny, but if you'd like I can give it a try :)

**Comment by yihui** [comment]
Sounds like a good suggestion. I admit sometimes this issue bothers myself, too. I'll follow your suggestion and change its behavior (only auto-generate the slug when the user hasn't changed it).

**Comment by yihui** [comment]
Done. Thanks for the suggestion!
