### ISSUE TITLE
Not seeing hugo-academic archtypes in new_post_addin dropdown?

### ISSUE THREAD

**Issue by astewart-twist** [rstudio/blogdown#350]
Hello.  When I use the `blogdown:::new_post_addin` UI to create a new post, I don't see any of the `hugo-academic` [archetypes](https://github.com/gcushen/hugo-academic/tree/master/archetypes) in the dropdown menu besides `default`.

Is this likely an issue with the way archtypes are organized in `hugo-academic`, or is it possibly just not supported by `blogdown` ?

Thanks!

edit:  Possibly related issues...

- https://github.com/rstudio/blogdown/issues/261

**Comment by yihui** [comment]
It seems you didn't follow the issue guide to test the dev version of this package. I have fixed it two weeks ago via 6b2ba305956c4cb2dc85354f5a7375d96ec5d2db.

**Comment by astewart-twist** [comment]
Amazing!  Sorry I didn't check the issue guide, I only searched the issues by keywords.  

Is the Dev version safe to use?  And if so, how does one install it? (`devtools::install_github()`?)

Thanks again!

**Comment by tcgriffith** [comment]
yes it's safe to use, and yes install it by `devtools::install_github("rstudio/blogdown")`

**Comment by astewart-twist** [comment]
Thank you!

**Comment by astewart-twist** [comment]
Nice, I see the Archtypes dropdown is populated now:

![image](https://user-images.githubusercontent.com/14282772/50306854-77c57b80-044b-11e9-8cfd-599747a4b32c.png)

So I'm assuming that the archetype lookup is only looking for `*.md` files under the theme's `archtypes/` directory, and not subdirectories that contain `index.md` files?

For example: https://github.com/gcushen/hugo-academic/tree/master/archetypes

**Comment by yihui** [comment]
@astewart-twist Should be fixed now. Please reinstall and restart your R session. Thanks!

**Comment by astewart-twist** [comment]
Whoa that was fast!  Can confirm: 

![image](https://user-images.githubusercontent.com/14282772/50309945-697c5d00-0455-11e9-920c-b3b16ed7bb89.png)

Thanks again.

**Comment by yihui** [comment]
Glad to know that. You are welcome!
