### ISSUE TITLE
highlight `{{` in code chunk (such as C++) in `.Rmd` would cause hugo error: template for shortcode "span" not found

### ISSUE THREAD

**Issue by dongzhuoer** [rstudio/blogdown#352]
I have created a repo on GitLab: https://gitlab.com/dongzhuoer/blogdown-demo

**Comment by dongzhuoer** [comment]
For a `.Rmd` file

````md
---
output: 
  blogdown::html_page:
    highlight: haddock
---

````
```cpp
map<int, float> d = {{1, 1.0f}, {2, 2.0f}, {5, 3.2f}};
```

```

`blogdown::build_site()` would get the following error:

```
Error: Error building site: "/media/computer/work/Git/blogdown-demo/content/post/r-rmarkdown.html:65:135": failed to extract shortcode: template for shortcode "span" not found
To stop the server, run servr::daemon_stop("140534484046360") or restart your R session
Serving the directory /media/computer/work/Git/blogdown-demo at http://127.0.0.1:4321
```

**Comment by dongzhuoer** [comment]
Possible solution is encode `{{` as `&#123;&#123;`

**Comment by yihui** [comment]
Sorry but I don't have a solution. The tag `<span>` is generated by Pandoc, and there isn't much I can do about it.

Personally I strongly recommend syntax highlighting via highlight.js instead of Pandoc.
