### ISSUE TITLE
Hugo library issue

### ISSUE THREAD

**Issue by antaldaniel** [rstudio/blogdown#354]
Originally I thought that this was a devtools issue [#835](https://github.com/r-lib/testthat/issues/835), but I think it is either RStudio or blogdown, or both, since they are integrated. After re-installing R and RStudio, the problem persisted, because I did not locate a copy of .Renviron file. 

Given that on Windows 10 the spaces in path create a problem, I was following the blogdown instructions, and I certainly had no intention to add .Last to it. 
[D1 More global options](https://bookdown.org/yihui/blogdown/more-global-options.html)

Checking with options() this is the global option

```
$blogdown.hugo.dir
[1] "C:/Hugo"
```

I do not find  away to get rid of this setting, which causes the following problem.

A global option prevents devtools::check () to run, and even it gives a false positive report on the checks.

```
-- R CMD check ---------------------------------------------------------------------
   Error: 2:39: unexpected symbol
   2: options(blogdown.hugo.dir = 'C:/Hugo').Last
                                             ^
   Execution halted
-- R CMD check results ------------------------------------ eurobarometer 0.1.0 ----
Duration: 365ms

0 errors √ | 0 warnings √ | 0 notes √

```

**Comment by yihui** [comment]
I guess **blogdown** is very unlikely to be the culprit in this case.

I'll continue in https://github.com/r-lib/testthat/issues/835. Thanks!

**Comment by antaldaniel** [comment]
Thank you, @yihui.  For anybody who may come back here, I think that the culprit was a malformatted ..Renviron file which contained the new hugo directory, which in turn is not necessary on Windows10, either.  I created the problematic .Renviron file after a misleading error from Hugo. 

The hugo.exe gave an error pointing to a whitespace error on a Windows path, but in my case the whitespace error was in an .md file, in fact, it was a simple error of an unclosed quote.  Even though it is not a very good practice that Window 10 creates spaces in system paths, RStudio and Hugo work fine on a path with spaces, but whitespacer errors can cause very subtle messages while being parsed by hugo.exe.
