### ISSUE TITLE
Zebra stripes on rendered R code

### ISSUE THREAD

**Issue by jhuntergit** [rstudio/blogdown#357]
```
OS: Windows 7 and Ubuntu (happens in both)
R Version: 3.5.1
Blogdown Version: 0.9
Theme: hugo-lithium
```

When I render my blogdown site with `blogdown::serve_site()` my code chunks typically render with proper syntax highlight and they look like this, as expected. This is a `.png` screen capture below.

![no zebra stripes](https://i.postimg.cc/J7DJcTxm/zebra2.png)

Randomly I'll `blogdown::serve_site()` and the code chunks will render in a zebra stripes fashion without syntax highlighting. It's intermittent and I assume it's a bug, so didn't bother with StackOverflow. Here's another `.png` screen capture to show what it looks like.

![zebra stripes](https://i.postimg.cc/G9nbk3QB/zebra.png)

Here's the actual code chunk below. What could be wrong? I can render the same code back to back and it's random which way it'll show up (regular grey background or zebra stripe background without syntax highlight).

\```r
#> PART NUMBER  DEFECT  QTY   INITIALS  JAN  FEB  MAR
#> -----------  ------  ---   --------  ---  ---  ---
#> 1010SIA      Rust    32    BL        2K   4K   3.2
#> 1010OPX      Rust    2     CW        4K   2.2  2K
#> 1010XMM      Rusty   9     Rick      1K   3K   2K
#> Bearing4     6 Rust  6     ST        0    0K   0.3
#> XMM1010      Rust    Two   CR        0K   2K   4K
\```

**Comment by jhuntergit** [comment]
1) I just updated my packages. Let's assume that this will solve the issue, and if it does not I will report back.

2) I meant the included table as the reproducible example. Next time I'll include the full *.Rmd text (in minimal form).

Thanks for this great package blogdown.

**Comment by yihui** [comment]
Closing this since it was not reproducible to me and I haven't heard back yet. Once a reproducible example is provided, I'll be happy to reopen it. Thanks!
