### ISSUE TITLE
Citations...

### ISSUE THREAD

**Issue by chriscastille6** [rstudio/blogdown#358]
I have followed the guidance for inserting citations, but neither the citations or the references are printed. 

I'm currently using RMarkdown to write entries into my blog and the most recent version of hugo (0.53) and the academic theme. Has anyone else had this problem or resolved it?

**Comment by yihui** [comment]
Could you provide [a minimal and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/)?

**Comment by chriscastille6** [comment]
Will this work?

My YAML header is:

`---
title: What can open science learn from how we fight pollution?
author: Chris
date: '2019-01-13'
slug: what-can-open-science-learn-from-how-we-fight-pollution
categories:
  - open science
tags:
  - Open science
image:
  caption: ''
  focal_point: ''
bibliography: [/Users/chriscastille/Documents/GitHub/Website/references.bib]
link-citations: TRUE
bilbio-style: "apalike"
---`

Here is an excerpt from the post I'm trying to fix:

`Which helps to make a point: the government can take care of this mess. Of the many proposals that can be discussed, I'm particularly interested in incentives to institutions and researchers for making their work essentially "born open" [see @rouderWhatWhyHow2016].

```{r create_r-references}
library(papaja)
r_refs(file = "/Users/chriscastille/Documents/GitHub/Website/references.bib")
```
`

My bib file contains this reference:

}
@Article{rouderWhatWhyHow2016,
  title = {The What, Why, and How of Born-Open Data},
  volume = {48},
  issn = {1554-3528},
  doi = {10.3758/s13428-015-0630-z},
  language = {en},
  number = {3},
  journal = {Behavior Research Methods},
  author = {Jeffrey N. Rouder},
  month = {sep},
  year = {2016},
  pages = {1062-1069},
  file = {/Users/chriscastille/Zotero/storage/JRHT7B9U/rouder2015.pdf;/Users/chriscastille/Zotero/storage/SCNJSG6F/Rouder - 2016 - The what, why, and how of born-open data.pdf},
}

**Comment by yihui** [comment]
1. Please read the Github issue template carefully when you file an issue to make sure your issue is correct formatted (in particular, please check out [the four-backtick rule](https://yihui.name/en/2017/05/four-backticks-github/)).

2. Could you provide [an example that I can just run](https://yihui.name/en/2018/06/copy-and-run/) instead of putting all the pieces together by myself? Thanks!

BTW, I don't which guidance you followed, but @apreshill has prepared one in 2017: https://blogdown-demo.rbind.io/2017/08/28/adding-citations-to-posts/

**Comment by apreshill** [comment]
Hi @chriscastille6,

I'm guessing your issues relate to file paths, as you are using absolute paths and blogdown/Hugo expect project-oriented relative file paths (which is illustrated in the post @yihui linked to). If you need further help, have you heard of [community.rstudio.com](https://community.rstudio.com/)? That site is more appropriate for help requests, and for initial help with debugging if indeed you run into a bug. You could ask for help in the R Markdown category and tag it with blogdown: https://community.rstudio.com/tags/c/R-Markdown/blogdown. They will also ask you to provide a [reproducible example](https://community.rstudio.com/t/welcome-to-the-rstudio-community/8).

Alison

**Comment by apreshill** [comment]
Just to complete this circle, I believe this thread on community is the same issue posted here. I responded there:
https://community.rstudio.com/t/inserting-citations-and-blogdown/22556/2

**Comment by apreshill** [comment]
Update: I don't believe this is a blogdown problem...
https://community.rstudio.com/t/inserting-citations-and-blogdown/22556/4

**Comment by yihui** [comment]
That is expected. `.Rmarkdown` is compiled to `.markdown`, which is processed by Hugo (BlackFriday), which doesn't support bibliography. `.Rmd` is processed by Pandoc, which does support bibliography.

https://bookdown.org/yihui/blogdown/output-format.html

**Comment by tcgriffith** [comment]
> That is expected. `.Rmarkdown` is compiled to `.markdown`, which is processed by Hugo (BlackFriday), which doesn't support bibliography. `.Rmd` is processed by Pandoc, which does support bibliography.
> 
> https://bookdown.org/yihui/blogdown/output-format.html

I feel that on that page, there's a need to make it more plain& clear to the users regarding the differences among rmd/rmarkdown/md

something  like a table will do:

|options      |Rmd |Rmarkdown |md |
|:------------|:---|:---------|:--|
|bibliography |yes |no        |no |
|run r code         |yes  |yes        |no |
|task list         |no  |yes        |yes |
|mathjax         |yes  |no        |yes |
|html widgets         |yes  |no        |no |

**Comment by apreshill** [comment]
I would tend to agree- and I would add that you can also get a Hugo respected table of contents with Rmarkdown but not Rmd.

**Comment by tcgriffith** [comment]
I remember that TOC is supported in pandoc(therefore Rmd), no?

**Comment by apreshill** [comment]
See this discussion: https://github.com/sourcethemes/project-kickstart-r/issues/2

**Comment by tcgriffith** [comment]
That hurts, I wish for a hero who could combine pandoc and Hugo together so that all hassles can be solved.
And world peace, I wish for that too.

**Comment by yihui** [comment]
We just need a JS hacker for the TOC issue. I don't think it is too complicated.

**Comment by chriscastille6** [comment]
Thanks for your help, folks! I think I have figured it out now!

**Comment by yihui** [comment]
The `.Rmarkdown` file format also supports citations now (although personally I'd still recommend using `.Rmd` for such advanced features). You can test the development version via

```r
remotes::install_github('rstudio/blogdown')
```

For the TOC issue mentioned above, that's a separate issue, and I'll take a look while working on #476. As I said, I don't feel it's a huge challenge for the `.Rmd` format.
