### ISSUE TITLE
Hugo version 0.53 restructures `config.toml` --> exampleSite won't render

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#359]
Hi @yihui,

Someone else alerted me to a refactoring of Hugo exampleSites, as with the hugo-academic theme. I reproduced the issue with Hugo version 0.53 using `gcushen/hugo-academic` theme. 

Here is the author's [commit that changed the structure](https://github.com/gcushen/hugo-academic/commit/ae8a86a04794ce5489b9686957045ef1f70ac859).

And here is the new `exampleSite`:
https://github.com/gcushen/hugo-academic/tree/master/exampleSite

The most significant change is that multiple `.toml` files now exist (`languages`, `params`, and `menus` are pulled out separately), instead of one `config.toml` file. 

For reference, here was the old `exampleSite` `config.toml` file:
https://github.com/rbind/apreshill/blob/master/themes/hugo-academic/exampleSite/config.toml

Here is the beginning of the OLD main menus:
```
# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1
```

In the new `exampleSite` `menu.toml` this same section looks like this:
```
# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
weight = 1
```

However, no naive quick fixes worked me (I tried created a master `config.toml` file by pasting the multiples into one and updating the names of the params, I also tried using the old example config file and just pasting that in). Not sure if you have seen this recently with any other themes, but it seemed like a pretty drastic restructuring so wanted to make sure you are aware of it.

**Comment by yihui** [comment]
I just fixed it in `new_site()`.

**Comment by bgall** [comment]
@yihui @apreshill  Should this still be a problem after install for moving back to the old menu structure? I copied all of the individual .toml files (`params`, `menus`, `languages`) into the root directory config.toml and blogdown::serve_site() [won't work and throws many errors](https://discourse.gohugo.io/t/invalid-taxonomy-state-cannot-find-path-execution-failed-error-code-1/19215/5). Tried reverting lots of these changes but had to pin it down to this.

**Comment by clauswilke** [comment]
It doesn't work for me either. I just installed a brand-new Hugo (0.55.6), blogdown (0.13), and the current academic repo (https://github.com/sourcethemes/academic-kickstart). When I run `serve_site()`, I get:
``` r
> serve_site()
Error in site_root(config) : 
  Could not find config.toml / config.yaml under
   /Users/clauswilke/github/clauswilke_blog
   /Users/clauswilke/github
   /Users/clauswilke
   /Users
   /
```

After moving `config/_default/config.toml` to the project root, things work. According to the [installation instructions](https://sourcethemes.com/academic/docs/install/) of Academic, that's this bug.

**Comment by apreshill** [comment]
@clauswilke I just did the same thing last night and all was well- I would not use the `academic-kickstart` repo though- it takes more understanding of the theme to get it working that way. I would do [this instead](https://summer-of-blogdown.netlify.com/01/#31).

To the original poster @bgall , from your thread, there is lots that could have gone wrong. You may want to post on [community](https://community.rstudio.com/tags/blogdown), but in the mean time you can view a repo made this week with `blogdown` and the academic theme here- I would compare your file structure to this one:

https://github.com/apreshill/kellykapowski

(it is just a demo site, but I made it on Monday and just updated the theme from GitHub last night- still able to serve site locally and deploy to Netlify).

**Comment by clauswilke** [comment]
@apreshill Thanks, I used the command from your slides and it worked.
