### ISSUE TITLE
Documentation for syntax highlighting in Rmd posts

### ISSUE THREAD

**Issue by mikemc** [rstudio/blogdown#360]
Thanks for this project and the great documentation! I recently worked through the blogdown book and built my first website. I wanted to suggest an improvement to the documentation regarding syntax highlighting in Rmd posts that I think would be helpful for new blogdown users. A stumbling point was that I knew `knitr` has built in syntax highlighting, but it doesn't seem to work by default in blogdown Rmd posts. Eventually I figured out that it wasn't on by default in the blogdown::html_page doc type and could be turned on in the Yaml header of the post, 
```
output:
  blogdown::html_page:
    highlight: tango
```
But [discussion of syntax highlighting in the book](https://bookdown.org/yihui/blogdown/templates.html#how-to) doesn't mention this and instead suggests that `highlight.js` and template customization is needed. It isn't really clear if Rmd or plain md posts are being considered there, but in other parts of the book Rmd posts are recommended and the distinctions between md and Rmd posts are clearly made. I think it could be very helpful to clarify in the docs/book that syntax highlighting can be turned on in Rmd posts and (if I'm understanding correctly) that the highlight.js and template-modding is only needed for code not in Rmd r-chunks.

Perhaps it is only with recent versions of blogdown / Hugo that this is possible? The theme I'm using is https://github.com/ribice/kiss which as far as I can tell does not include highlight.js but maybe has some other syntax highlighting support built in.

**Comment by tcgriffith** [comment]
Good point.  
However, if you have a mixture of Rmd/md/Rmarkdown posts, highlight.js should be more consistent in highlighting the code lines.

Rmd-only blogs should be fine.

**Comment by mikemc** [comment]
@tcgriffith After some googling I saw that there is inbuilt syntax highlighting [as of Hugo 0.28](https://gohugo.io/content-management/syntax-highlighting/). Adding `pygmentsCodeFences  = true` to `config.toml` gets syntax highlighting working in github-style code blocks in plain .md posts. Perhaps getting this to work on Rmd posts as well would be a good alternative to `highlight.js`?

**Comment by yihui** [comment]
highlight.js is my personal favorite syntax highlighting library. It works for both Rmd and md. In general, I don't prefer built-in syntax highlighters (Pandoc or Hugo or Pygments) because they pre-generate static HTML tags for tokens. Syntax highlighting dynamically in browser on the client side is a cleaner (I mean the HTML source is clean) and more general approach (you don't need to think about Rmd or md).

[And I tend not to spend much time on syntax highlighting :)](https://yihui.name/en/2017/07/on-syntax-highlighting/)
