### ISSUE TITLE
Hugo Hermit theme compatibility 

### ISSUE THREAD

**Issue by bartling** [rstudio/blogdown#361]
I am having problems with post formatting when using the Hugo Hermit theme.

Markdown posts work fine, but R Markdown posts are not formatted to the theme.

My repo is here: [https://github.com/bartling/blog](https://github.com/bartling/blog)

The R Markdown posts also have date compatibility issues that cause problems on index pages: [https://www.hughbartling.com/post/](https://www.hughbartling.com/post/)

Example of an R Markdown post: [https://www.hughbartling.com/post/2019-01-24-testing-markdown/](https://www.hughbartling.com/post/2019-01-24-testing-markdown/)

**Comment by yihui** [comment]
For goodness' sake, don't knit: https://twitter.com/jent103/status/1085304300258115584

And please read at least Chapter 1 of the blogdown book: https://bookdown.org/yihui/blogdown/workflow.html
