### ISSUE TITLE
Error in blogdown with .DS_Store

### ISSUE THREAD

**Issue by sbacelar** [rstudio/blogdown#364]
I am trying a fresh start with `blogdown` and `hugo`, using `academic` theme in my MacOS 10.14.2. I followed the instructions in [https://sourcethemes.com/academic/docs/install/#install-with-git](https://sourcethemes.com/academic/docs/install/#install-with-git) begining with Netlify and creating an `academic-kickstart`.
What am I doing wrong?
```
> blogdown:::serve_site()
Error: "/Users/sergiobacelar/SB_website/config/_default/.DS_Store:1:1": "/Users/sergiobacelar/SB_website/config/_default/.DS_Store" is not a valid configuration format
To stop the server, run servr::daemon_stop("4324619576") or restart your R session
Serving the directory /Users/sergiobacelar/SB_website at http://127.0.0.1:4321
```

**Comment by tcgriffith** [comment]
Sounds similar to #359  

Basically, it is because that hugo-academic split the config.yaml into multiple files and moved them to a subdirectory and blogdown got panicked when config.yaml is missing. This has been fixed, Try to upgrade your blogdown pkg to the dev version on GitHub with the following command:

```
remotes::install_github('rstudio/blogdown')
```

**Comment by sbacelar** [comment]
Well I tried to follow ONLY the instructions in [https://themes.gohugo.io/academic/](https://themes.gohugo.io/academic/) put the `config.toml` in the root and it worked. Nevertheless, I am going to upgrade de blogdown pkg as you wrote.

**Comment by yihui** [comment]
You may want to delete `.DS_Store` like me using a cron job: https://yihui.name/en/2017/09/ds-store-crap/

That said, I think Hugo should definitely ignore `.DS_Store`.

**Comment by yihui** [comment]
I recommend that you file an issue to the Hugo repo or report it to the Hugo forum, and ask Hugo to ignore `.DS_Store` when reading config files, because `.DS_Store` is apparently not a config file intended for Hugo.
