### ISSUE TITLE
kable produces malformed reference links after HTML calls in blogdown

### ISSUE THREAD

**Issue by oganm** [rstudio/blogdown#367]
This is a replicate of yihui/knitr#1669 but it should be easier to digest since I created a repo to reproduce the issue.

In [this](https://github.com/oganm/bgtest) blogdown repository there is [a post](https://github.com/oganm/bgtest/blob/master/content/post/2019-02-06-test.rmd) which includes a few tables. The repository is created upon running `blogdown::new_site()` and the test post is created by doing `blogdown::new_post("test", ext = ".rmd")`. No other files have been modified in any way. The contents of the file are as follows:

    ---
    title: test
    author: ~
    date: '2019-02-06'
    slug: test
    categories: []
    tags: []
    ---
    
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(collapse = TRUE)
    ```
    
    ```{r test1}
    library(knitr)
    library(magrittr)
    library(kableExtra)
    library(shiny)
    data.frame(a= c(1,2,3)) %>% kable(caption = 'test',format = 'html')
    ```
    
    ```{r test2}
    lapply(1:2,function(x){
        data.frame(a= c(1,2,3)) %>% kable(caption = 'test2',format = 'html') %>% HTML()
    }) -> tables
    tables[[1]]
    tables[[2]]
    ```
    
    
    ```{r test3}
    for(i in 1){
      table = data.frame(a= c(1,2,3)) %>% kable(caption = 'test3',format = 'html') %>% HTML()
    }
    table
    ```
    
    ```{r test4}
    {data.frame(a= c(1,2,3)) %>% kable(caption = 'test4',format = 'html') %>% HTML()}
    ```

And this is how blogdown renders this post

![](https://user-images.githubusercontent.com/6352379/52385703-a0bfc100-2a37-11e9-9e00-e974958c5541.png)

The main problem is that whenever kable is in a `{` block the reference tag is created in a wrong way making it visible to the reader of the post in the form of `(\#tag:codeBlockLabel)`.

A lesser problem is that the first table with the proper reference tag is named `Table 1: test` instead of just `test` without my consent.

I want to understand why kable is behaving differently in different contexts within the same file and I want to know how I can control this behaviour ideally getting rid of any helpful attempts by kable to reformat my captions

And to finish, session_info:
```r
> devtools::session_info('blogdown')
─ Session info ───────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 os       Ubuntu 16.04.5 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language en_CA:en                    
 collate  en_CA.UTF-8                 
 ctype    en_CA.UTF-8                 
 tz       America/Vancouver           
 date     2019-02-07                  

─ Packages ───────────────────────────────────────────────────────
 package   * version  date       lib source        
 base64enc   0.1-3    2015-07-28 [1] CRAN (R 3.4.0)
 BH          1.69.0-1 2019-01-07 [1] CRAN (R 3.4.4)
 blogdown    0.10     2019-01-09 [1] CRAN (R 3.4.4)
 bookdown    0.9      2018-12-21 [1] CRAN (R 3.4.4)
 digest      0.6.18   2018-10-10 [1] CRAN (R 3.4.4)
 evaluate    0.12     2018-10-09 [1] CRAN (R 3.4.4)
 glue        1.3.0    2018-07-17 [1] CRAN (R 3.4.4)
 highr       0.7      2018-06-09 [1] CRAN (R 3.4.4)
 htmltools   0.3.6    2017-04-28 [1] CRAN (R 3.4.0)
 httpuv      1.4.5.1  2018-12-18 [1] CRAN (R 3.4.4)
 jsonlite    1.6      2018-12-07 [1] CRAN (R 3.4.4)
 knitr       1.21     2018-12-10 [1] CRAN (R 3.4.4)
 later       0.7.5    2018-09-18 [1] CRAN (R 3.4.4)
 magrittr    1.5      2014-11-22 [1] CRAN (R 3.4.4)
 markdown    0.9      2018-12-07 [1] CRAN (R 3.4.4)
 mime        0.6      2018-10-05 [1] CRAN (R 3.4.4)
 promises    1.0.1    2018-04-13 [1] CRAN (R 3.4.4)
 R6          2.3.0    2018-10-04 [1] CRAN (R 3.4.4)
 Rcpp        1.0.0    2018-11-07 [1] CRAN (R 3.4.4)
 rlang       0.3.1    2019-01-08 [1] CRAN (R 3.4.4)
 rmarkdown   1.11     2018-12-08 [1] CRAN (R 3.4.4)
 servr       0.11     2018-10-23 [1] CRAN (R 3.4.4)
 stringi     1.2.4    2018-07-20 [1] CRAN (R 3.4.4)
 stringr     1.3.1    2018-05-10 [1] CRAN (R 3.4.4)
 tinytex     0.9      2018-10-23 [1] CRAN (R 3.4.4)
 xfun        0.4      2018-10-23 [1] CRAN (R 3.4.4)
 yaml        2.2.0    2018-07-25 [1] CRAN (R 3.4.4)

[1] /home/omancarci/R/x86_64-pc-linux-gnu-library/3.4
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library
```

**Comment by oganm** [comment]
It seems like it is related to the HTML call I appended after kables. The issue occurs at the point of coercing into a character and has nothing to do with `{`s. If I replace
```
data.frame(a= c(1,2,3)) %>% kable(caption = 'test',format = 'html')
```

with

```
data.frame(a= c(1,2,3)) %>% kable(caption = 'test',format = 'html') %>% as.character()
```
I get
```html
## [1] "<table>\n<caption>(\\#tab:test1)test</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> a </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n</tbody>\n</table>"
```
as the output which is what appears in my previous malformed tables. If I replace that `as.character` with `HTML`, I get the same malformed table caption. This suggests the issue has nothing to do with `{`s. I suspect in blogdown and bookdown, knitr outputs the files with the malformed captions which are later processed by something else to add the table numbers. I don't know why using the `HTML` function bypasses this post processing. But in general getting rid of this processing step will probably solve both my problems

Also in my use case I need the `HTML` calls as I use `shiny`'s tags to get the tables together

**Comment by tcgriffith** [comment]
In your test2, test3 and test4,  there's  `%>% HTML()`, removing this piece of code will generate captions as test1.

Regarding the caption, sadly I've searched through bookdown/blogdown manuals and found nothing. @yihui , Can we disable automatic numbering for figures &tables?

**Comment by oganm** [comment]
Yes removing does solve the malformed captions issue but my use case requires the `HTML` call as I end up doing something like 

```r
div(
    fluidRow(
        column(6, table[[1]]),
        column(6, table[[2]])
    )
)
```
to stick the tables together nicely. For this to work they need to be HTML objects. Also at an academic level I am curious why the HTML function causes blogdown or knitr, whichever is responsible, to skip finishing the processing.

In general having a way to get turn of numbering seems to be the solution though. Hopefully it can prevent adding the `#tab:`s all together which also means no table numbers should be added.

**Comment by tcgriffith** [comment]
Do you want to put multiple tables together [like this?](https://bookdown.org/yihui/bookdown/tables.html)

```
knitr::kable(
  list(
    head(iris[, 1:2], 3),
    head(mtcars[, 1:3], 5)
  ),
  caption = 'A Tale of Two Tables.', booktabs = TRUE
)
```
Using shiny functions to set the layout of knitr::kable seems like an overkill for me, I would suggest to go for some other packages like xtable, kableExtra and DT.

**Comment by oganm** [comment]
As a temporary alternative, this can be used to get rid of table numbers

```r
remove_table_numbers = function(table){
  table %<>% as.character() %>% gsub("\\(\\\\#tab:.*?\\)","",.)
  return(HTML(table))
}

data.frame(a= c(1,2,3)) %>% kable(caption = 'test',format = 'html') %>% remove_table_numbers
```

**Comment by oganm** [comment]
The kable solution to get the tables together seems like a good option. But I also use `kableExtra::scroll_box` to give each table their own scroll box which doesn't seem to be possible after a quick examination

**Comment by yihui** [comment]
To disable figure/table numbering, set this option in the Rmd document:

```r
knitr::opts_knit$set(bookdown.internal.label = FALSE)
```

And tables without captions won't be numbered, of course.

`HTML()` is indeed the culprit in this case. HTML objects produced from the **htmltools** (or **shiny**, same thing) will be protected from Pandoc's conversion. They will be hidden (deleted from the document) and restored later. That will cause the trouble here.
