### ISSUE TITLE
hugo-tranquilpeak-theme does not render in rstudio nor on Netlify

### ISSUE THREAD

**Issue by enricodata** [rstudio/blogdown#369]
When using hugo-tranquilpeak-theme it does not render in rstudio nor on Netlify.
This is how it looks like:
![image](https://user-images.githubusercontent.com/47527626/52856178-f37a3680-3123-11e9-9b26-6500efac7404.png)

The same happens for other hugo themes like hugo-future-imperfect.
What should be done to fix it?

**Comment by gadenbuie** [comment]
It's very hard to diagnose your issue from a screenshot. It would be helpful if you could upload your code to a [repository](https://github.com/new) or [gist](https://gist.github.com) and share the link.

**Comment by enricodata** [comment]
The code is available here:
https://gitlab.com/enricodata/ir
and here there is the page where it is deployed:
https://themetest.netlify.com/

**Comment by gadenbuie** [comment]
First thought is that you need to adjust the [base url](https://gitlab.com/enricodata/ir/blob/master/config.toml#L15) in `config.toml`.

```
baseURL = "https://example.org/"
```

See [A quick example](https://bookdown.org/yihui/blogdown/a-quick-example.html) in the Getting Started chapter of the blogdown book for a good introduction. The section on [Configuration](https://bookdown.org/yihui/blogdown/configuration.html) is another good, in-depth resource.

**Comment by gadenbuie** [comment]
Actually, to be more specific, the book addresses this in [Configuration - Options](https://bookdown.org/yihui/blogdown/configuration.html#options):

> - `baseURL`: Normally you have to change the value of this option to the base URL of your website. **Some Hugo themes may have it set to `http://replace-this-with-your-hugo-site.com/` or `http://www.example.com/` in their example sites, but please make sure to replace them with your own URL** (see Chapter 3 and Appendix C for more information on publishing websites and obtaining domain names). Note that this option can be a URL with a subpath, if your website is to be published under a subpath of a domain name, e.g., `http://www.example.com/docs/`.

**Comment by yihui** [comment]
@enricodata In fact, **blogdown** will warn you if your `baseURL` is `https://example.org/`:
https://github.com/rstudio/blogdown/blob/5e07e32e5ecd153b1cbded7965b30f855499f2e7/R/utils.R#L188-L192

It seems you ignored the warning.

**Comment by enricodata** [comment]
thanks. I solved it
