### ISSUE TITLE
Warning: Ignoring unknown aesthetics: frame // Use for gganimate

### ISSUE THREAD

**Issue by gresch** [rstudio/blogdown#37]
I use [gganimate](https://github.com/dgrtwo/gganimate/blob/master/README.md) to animate a ggplot2 graph. However, blogdown generates separate pictures (as many pics as given in the frame input) instead of **one** animated GIF.

**Comment by yihui** [comment]
Is this issue specific to blogdown? i.e. is it reproducible in a normal R Markdown document?

**Comment by gresch** [comment]
1. please find a working R Markdown/ notebook under [1]; cf. section **animated plots**
2. the same for a blogdown version under [2]; cf. section **animated plots**

in the R markdown it is working as expected (animated GIF), for blogdown a number of static images is generated.

[1] https://cdn.rawgit.com/gresch/r_playground/52ebec03/gganimate/201611_gganimate_Packages%20functionality%20examples%20using%20Gapminder%20data.nb.html
[2] https://gresch.github.io/2016/11/22/201611_gganimate_packages_functionality_examples_using_gapminder_data/

**Comment by RobertMyles** [comment]
I've got this problem too, although it doesn't seem to be restricted to blogdown, it's also happening whenever I try to knit the document or when I published it as an RPub. When I try `build_site()` or `serve_site()`, I get an error:  

```
Execution halted
Error in render_page(f) : 
  Failed to render '2017-05-22-earth.Rmd'
```

**Comment by yihui** [comment]
I'm not very familiar with the codebase of gganimate, so I'll defer this issue to @dgrtwo. Before he chimes in, here is another method you can use, which requires the installation of FFmpeg:

````
```{r gapminder, fig.show='animate', ffmpeg.format='gif', dev='jpeg'}
library(gapminder)
library(ggplot2)
theme_set(theme_bw())
p <- ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, color = continent, frame = year)) +
  geom_point() +
  scale_x_log10()

library(gganimate)
gganimate(p)
```
````
