### ISSUE TITLE
New post addin should disable "slug" when page bundles are activated

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#370]
Hi @yihui,

I started using the page bundles option recently and noticed an annoying issue with links generated if the New Post Addin works "as usual" and this option is set in your .Rprofile. If you use this option, the default Addin behavior is to populate the post "slug" for you- you cannot *NOT* have a post slug. 

<img width="621" alt="screen shot 2019-02-21 at 6 35 59 am" src="https://user-images.githubusercontent.com/12160301/53176487-0321d100-35a3-11e9-801e-cf77ada21936.png">

But, if you *do* use a slug on a bundled post, what populates into your public directory is this:

```
public/
  |- 2019-02-20-slug
      |- slug
          |- index.html
```

This means that links to your bundled posts (if there is a slug) will double up 😢 . I added [redirects](https://github.com/rbind/apreshill/blob/master/static/_redirects) to fix my two instances of it, but originally the link to a single post looked like this:

https://alison.rbind.io/post/2019-02-19-hugo-netlify-toml/hugo-netlify-toml/

And if I tried this link of course it produced a page not found error (since the index file was in a folder):

https://alison.rbind.io/post/2019-02-19-hugo-netlify-toml/

But when I removed the slug from the post, the link is correct:

https://alison.rbind.io/post/2019-02-19-hugo-netlify-toml/

So I am wondering if the default behavior of the Addin can be changed so that when you have the page bundle option turned on, the slug is deactivated somehow so the user cannot set it? Maybe grayed out?

Thanks for considering,
Alison

see issue #351

**Comment by yihui** [comment]
I agree that is annoying. To avoid surprises and stabilize permanent links, I recommend you to set `permalinks` in `config.toml` (footnote 24): https://bookdown.org/yihui/blogdown/configuration.html (here is [my own `config.yaml`](https://github.com/rbind/yihui/blob/master/config.yaml)) By default, Hugo seems to use `:filename/:slug` as the permalink for page bundles.

Anyway, I think it is a good idea to disable slugs for page bundles by default. I'll see what I can do.

**Comment by yihui** [comment]
Slugs will no longer be automatically generated for posts when `options(blogdown.new_bundle = TRUE)` and no `permalinks` is set in `config.toml`.
