### ISSUE TITLE
Rvest XPath problem R

### ISSUE THREAD

**Issue by Pawel-AI** [rstudio/blogdown#376]
Hello Everyone,

I have a problem with rvest. I am trying to scrap a dropdown list based on previous choise from other dropdown list. Here is the problem:

from this webpage -> https://www.otomoto.pl/osobowe/volkswagen/"

I want to extract all the car models that belongs to volkswagen for example using html_nodes() and XPath

```
//[@id="param571"]/option <- XPath for car brands (BMW, Audi, Volkswagen etc.)
//[@id="param573"]/option <- XPath for car models ( only Volkswagen models etc.)
```

For the brands works perfect but with models it doesn't at all resoults:

> character(0)

Code I used:

```
brand <- read_html("https://www.otomoto.pl/osobowe/volkswagen/")
modelsv2 <- html_nodes(brand, xpath = '//*[@id="param573"]/option') %>%
  html_text()

modelsv2

```
Much apprecieted for any help I am fighting with this over a week! Thanks

**Comment by cderv** [comment]
hi @Pawel-AI, 

what is the relationship with blogdown 📦 which is where you open the issue ? 

For generic question and help from the community, please consider https://community.rstudio.com.  There is a broad community ready to help you there. You can aim at a related 📦 repo for a specific bug with a reproductible example or a feature request.

**Comment by gadenbuie** [comment]
This issue was cross-posted here about 5 minutes after being submitted to RStudio Community at https://community.rstudio.com/t/rvest-xpath-problem/27425.

**Comment by yihui** [comment]
I feel this is a question about web-scraping and has nothing to do with **blogdown**. Thanks @cderv and @gadenbuie!
