### ISSUE TITLE
Error in render_page(f) : Failed to render 'content/about/index.Rmd'

### ISSUE THREAD

**Issue by davidodongojr** [rstudio/blogdown#378]
Hi, I am trying to create a pagedown: :html_resume() in my blogdown website but i keep getting this issue whenever i try to blogdown: :serve_site
I am using RStudio Version  1.2.1502
> blogdown:::serve_site()
Rendering content/about/index.Rmd
Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
Execution halted
Error in render_page(f) : Failed to render 'content/about/index.Rmd'
Rendering content/about/index.Rmd
Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
Execution halted
<simpleError in render_page(f): Failed to render 'content/about/index.Rmd'>

Any help will be higly appreciated. Thanks

**Comment by cderv** [comment]
> Error: pandoc version 1.12.3 or higher is required and was not found

It seems you don't have a recent version of pandoc. If you have last version of RStudio, it should be included. Check `Sys.getenv("RSTUDIO_PANDOC")` for where RStudio looks for pandoc. If you have another version in PATH, you may need to change it.
