### ISSUE TITLE
Support for widgetframe

### ISSUE THREAD

**Issue by bhaskarvk** [rstudio/blogdown#38]
Similar to rstudio/bookdown#271 I need a way to move the child widget HTML and lib files over to the `bookdown` directory and subsequently to `public` directory under the proper sub directory.

Current behavior is the child html is copied under directory 'public/1/01/01/index.html' and widget_libs folder is copied under `public/post/. Both these behaviors are not correct.

The child widget and its widget_libs directory should be copied over to where the parent HTML is.

**Comment by bhaskarvk** [comment]
Btw solving this issue will lead to a much simpler and better solution for #32 / #20 / #7

**Comment by bhaskarvk** [comment]
widgetframe now works with almost all other HTML based output formats including bookdown, but not with blogdown, due to the complexities involved in how hugo moves static HTML files to final destination. I'll still working to see if I can fix anything in widgetframe knitting to make it work, but for now keeping this issue open.

**Comment by p0bs** [comment]
That would be great, @bhaskarvk . To me, blogdown is most useful for the sophisticated hugo themes (as Yihui puts it), using htmlwidgets to provide the best experience. For that reason, your work will be much appreciated by many!

**Comment by bhaskarvk** [comment]
@yihui Any pointers on it. blogdown is the last bastion for widgetframe to conquer :), and a lot of people have asked for proper widget support in blogdown which I believe widgetframe can deliver.

**Comment by yihui** [comment]
Sorry I still haven't had a chance to tackle this problem. I'm close to finishing the first draft of the blogdown book. I might get some time for this after finishing the book.
