### ISSUE TITLE
New versions of hugo and academic theme completely screw my web page

### ISSUE THREAD

**Issue by luca-scr** [rstudio/blogdown#385]
I had a perfectly working web site built with blogdown using hugo-academic theme at http://www.stat.unipg.it/luca/
Now updating hugo and academic theme completely screw my website. It seems that several things changed in hugo and consequently on academic. 
How can I get back to a working environment where my old configuration would work as before?
I'm not sure this is the right place to ask but I'm completely lost and googling I haven't been able to find any solution.
Thanks.

**Comment by luca-scr** [comment]
Update: I was able to restore the correct versions to get my web site build again. 
For those interested here are the commands used in R
```
blogdown::install_hugo(version = "0.49.2", use_brew = FALSE)
blogdown::install_theme("https://github.com/gcushen/hugo-academic/archive/v2.4.0.zip", force = TRUE)
```
Thanks a lot for providing the `install_hugo()` and `install_theme()` functions.

**Comment by yihui** [comment]
Yes, you can (and probably should) lock your site to a specific version of Hugo. Thanks for sharing the solution!

**Comment by melindahiggins2000** [comment]
Thank you @yihui  and @luca-scr ! I had this exact problem today and your issue posting solved my `blogdown::serve_site()` problem with my site not looking correct. My site was originally built under Hugo v.0.41.

**Comment by veroandreo** [comment]
I have the same issue, but I couldn't fix it with the solution provided. My site was built with hugo v.0.55, which I still have, but when I added my Orcid logo and id, my beautiful academic site, esp the home page, now looks awful... everything is small and some items are no longer shown... I appreciate any hints, dunno what to do as to recover my site. 

Thanks in advance
