### ISSUE TITLE
Pushing to GitHub pages

### ISSUE THREAD

**Issue by Alaburda** [rstudio/blogdown#39]
Hey!

I have just tried out the package and it works great! While serve_site() builds the site, is there by chance a command to push the built site via RStudio or do I still have to resort to git for that?

**Comment by janeshdev** [comment]
You can use `blogdown::build_site()` in order to build the site from Rstudio. While pushing to the github pages you should only upload `public` folder and make sure you are uploading to the git-pages branch or make sure your master branch is pointing to the `pages`. Look at this picture. 

![image](https://cloud.githubusercontent.com/assets/3325086/22125763/d201803c-de49-11e6-9e71-b4d6f60972fd.png)

**Comment by MarkEdmondson1234** [comment]
I've been following the [Github pages help for Hugo](https://gohugo.io/tutorials/github-pages-blog/), which suggests using a deploy script and Github submodules.

Once you've made the submodule, I run this script to publish:

```
#!/bin/bash

echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"

# Build the project.
# hugo -t hugo-icarus-theme # if using a theme, replace by `hugo -t <yourtheme>`

RScript -e 'blogdown::build_site()'


# Go To Public folder
cd public
# Add changes to git.
git add -A

# Commit changes.
msg="rebuilding site `date`"
if [ $# -eq 1 ]
  then msg="$1"
fi
git commit -m "$msg"

# Push source and build repos.
git push origin master

# Come Back
cd ..
```
Would be cool as an RStudio Addin :)

I'm struggling a bit using git submodules for the first time, but now its working I'm looking at using Travis to run the script so you just need to push changes to publish like when using Jeykll.

**Comment by Alaburda** [comment]
Thanks Mark, I've been using the same deploy script but I was not aware that RScript exists! Added R to my PATH and now I can build and push the site in one script.

**Comment by MarkEdmondson1234** [comment]
@Alaburda one thing I just found that may also be useful is you can use the RStudio build project tools to custom and point it at the deploy script

<img width="905" alt="screen shot 2017-01-23 at 22 11 01" src="https://cloud.githubusercontent.com/assets/3155884/22222873/e3c55aec-e1b8-11e6-8a1c-f6885a3e56be.png">
