### ISSUE TITLE
Missing rss.xml file?

### ISSUE THREAD

**Issue by TyGu1** [rstudio/blogdown#393]
Issue: Missing rss.xml when bringing a blogdown (Hugo) blog on r-Bloggers?

There is plenty Information on bringing Hugo/blogdown on r-Bloggers.com, suggesting that the rss.xml file has to be modified, see

- https://stackoverflow.com/questions/48997278/how-do-i-get-my-blogdown-blog-on-r-bloggers
- http://thug-r.life/post/2018-02-07-hugo-to-rbloggers/   
- https://gohugo.io/templates/rss/

However, when i create a blog, i am missing that file.

    > dir.create("blogdown")
    > setwd("blogdown/")
    > blogdown::new_site()
    > list.files(pattern = "rss.xml", recursive = TRUE)
    character(0)

[X] Already asked on SO:
https://stackoverflow.com/questions/56726302/missing-rss-xml-while-attempting-to-bring-blogdown-hugo-blog-on-r-bloggers

**Comment by yihui** [comment]
I just replied on SO. Thanks!
