### ISSUE TITLE
Switch themes efficiently in bookdown

### ISSUE THREAD

**Issue by janeshdev** [rstudio/blogdown#41]
Hi, 

Is there an easy way to switch between themes ? I only found `install_theme` function in `blogdown` package. I have few themes that are downloaded in my machine. Only way i can make them work is by using `install_theme`. Since they are already downloaded on the machine, is there any way to use them ? 

![image](https://cloud.githubusercontent.com/assets/3325086/22088073/6e9cb86c-dd96-11e6-9ad0-e29273028d98.png)

**Comment by yihui** [comment]
Yes, in config.toml, set `theme = "the-name-of-the-theme"`: https://gohugo.io/overview/configuration/

**Comment by janeshdev** [comment]
Thank you.
