### ISSUE TITLE
serve_site updating the theme automatically

### ISSUE THREAD

**Issue by Athanasiamo** [rstudio/blogdown#417]
I've been trying to get a blogpost out, but I am struggling because `serve_site` seems to updating my hugo theme to the latest, which is currently _not_ compatible with my setup. 

Is it intended behaviour that the themes folder should get updated when serving the site?

I've `git reset --hard` several times today, to a state where the themes folder has the old theme that works in it, and then `serve_site´ works fine. but when I save the new blogpost (either while a deamon for serve_site is working, or if I initilize serve_site after saving) the theme files get updated and the page no longer works as I'd like.

**Comment by yihui** [comment]
`serve_site()` doesn't run any (`git`?) commands to update themes. There might be something else going on (e.g. a `git` hook?).

**Comment by Athanasiamo** [comment]
I've never set up any git hook (I honestly dont know how). This makes me even more uncertain what is happening. I set the whole thing up with blogdown, over a year ago, and it's the first time it's behaving like this. At this time, I can't even get a copied clone of my repo to serve without the updated theme throwing it all. I even tried taking a clone of my master branch (which is currently deployed via netlify correctly) but the second I try serving, again, the updates and things are all bananas. 

Any tip on how  to figure out if there is a git hook doing something? The terminal and console are quiet, I have absolutely no indication that this is happening before I see the served site suddenly change

**Comment by tcgriffith** [comment]
Would you mind to share your website repo?

**Comment by Athanasiamo** [comment]
sure!

https://github.com/Athanasiamo/DrMowinckels

Thanks for looking into it!

**Comment by yihui** [comment]
With the above GIT repo, I'm unable the reproduce the issue. After I `blogdown::serve_site()` and create a new post, I don't see any changes in the `themes` directory in GIT.

![image](https://user-images.githubusercontent.com/163582/69094507-15d41400-0a16-11ea-98e0-1458ef751c6b.png)

**Comment by Athanasiamo** [comment]
so strange, because I even tried cloning my own repo, and it still happened... I'll keep looking at it on my end and see what the f is going on. Thanks for looking.

**Comment by yihui** [comment]
Usually it is very difficult to debug this kind of non-reproducible issues unless you can bring your computer to another expert to have a look (otherwise we could spend days guessing all possible reasons).

**Comment by Athanasiamo** [comment]
Can I ask a stupid question? 

why are files in the `public` folder modified? there should be nothing to modify in the master branch for this repo. 

If I do a  `git stash` while serving, it reverts to a version where things are fine again.

And I totally get what you are saying, @yihui . This is a kind of desperate call for help, after days of not understanding what is going on.

**Comment by tcgriffith** [comment]
I see that you have modified the theme by creating a bunch of files in /layouts, these files will override the theme template HTML files(/themes/hugo-theme/introduction/layouts/) with the same name. 

I think this might possibly be "theme gets updated". could you confirm by deleting the layouts/ directory and run `hugo serve` ? (you can `git checkout layouts` to get it back.

**Comment by Athanasiamo** [comment]
No, that's not it, @tcgriffith . I get the same result without the layouts folder there, projects and blogpost disappear from home, and files that should not need re-rendering are rendered.

**Comment by Athanasiamo** [comment]
My original question was answered, and I dont believe any of my problems are from blogdown. So closing the issue. Thank you both for taking the time to look into things!

**Comment by yihui** [comment]
When you cannot tolerate this problem any more, we can probably schedule a video chat for you to share your screen with me to figure it out.

**Comment by ericbrewe** [comment]
I have had this same issue, when I run serve_site() it seems to update the public version of almost every file.  This happened when I changed computers.  Don't know if this helps clarify.
