### ISSUE TITLE
Error in deploying through due to build command

### ISSUE THREAD

**Issue by filippogambarota** [rstudio/blogdown#418]
Hi! Usually, I manage my  Hugo website with other tools but I've tried to use blogdown instead. Following the Blogdown documentation, I set the build command to `Hugo` inside netlify settings however the deployment failed. So I use the same command of my previous website `hugo --gc --minify -b $URL` and everything works fine.
Could it be related to my theme (academic theme) that needs a different build command or is a blogdown problem?

**Comment by yihui** [comment]
Please do not ignore the issue guide when filing issues. Thanks!
