### ISSUE TITLE
blogwdown:::parse_toml() doesn't seem to be able to handle hugo-academic's config.toml file

### ISSUE THREAD

**Issue by lcolladotor** [rstudio/blogdown#42]
Hi Yihui,

Thank you again for adding another contribution to R, you are relentless!

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">My <a href="https://twitter.com/hashtag/rstudioconf?src=hash">#rstudioconf</a> slides: 1) Advanced Rmd <a href="https://t.co/etQlXVYgYI">https://t.co/etQlXVYgYI</a> 2) blogdown <a href="https://t.co/huitnIPx8Q">https://t.co/huitnIPx8Q</a> 3) Extending Rmd <a href="https://t.co/j1zVBU86CI">https://t.co/j1zVBU86CI</a></p>&mdash; Yihui Xie (@xieyihui) <a href="https://twitter.com/xieyihui/status/820477439050731521">January 15, 2017</a></blockquote>

It took me a bit to get the Academic _framework_ (not a _theme_) to get going but I love it (see details at https://github.com/gcushen/hugo-academic/issues/93). After getting everything setup, it was time to write a new R blog post, which I tried to do with `blogdown` (with the current latest [commit](https://github.com/rstudio/blogdown/tree/35dd89f68d0eafba36697bf788be4cd7b98552c9)).

My setup is like this:

* Main hugo directory `hugoblog`: https://github.com/lcolladotor/hugoblog
* Customized theme at `hugoblog/themes/academic`: https://github.com/lcolladotor/hugo-academic.
* Public files for rendering the website: `hugoblog/public`: https://github.com/lcolladotor/lcolladotor.github.com

While using R at  the `hugoblog` directory, I used `blogdown::new_post()` to get a Rmd file. Worked well. However, `blogdown::serve_site()` lead the the same error message I initially saw when using `hugo-academic` https://github.com/gcushen/hugo-academic/issues/93. That is:

```
ERROR: 2017/01/19 00:50:57 general.go:236: theme/partials/article_metadata.html is an incomplete or empty template
```

 My best guess is that https://github.com/lcolladotor/hugoblog/blob/master/config.toml is too complicated for https://github.com/rstudio/blogdown/blob/35dd89f68d0eafba36697bf788be4cd7b98552c9/R/utils.R#L97-L112 to parse properly. 

So instead of `blogdown` I modified the TextMate code I described at http://lcolladotor.github.io/2013/11/09/new-Fellgernon-Bit-setup-in-Github/#.WIIMlbYrJoO to write my first blog post with hugo. See https://github.com/lcolladotor/markdown-redcarpet.tmbundle/commit/f043c056ff620299843e9d8ea34144f478aa7965 for details.

You'll notice that I'm using `knitr::render_markdown()` and that it actually works with the smilies. I didn't try using hugo shortcodes yet https://github.com/rstudio/blogdown/issues/40 but it might work.

Best,
Leo

**Comment by yihui** [comment]
I don't think `parse_toml()` is relevant. It is not heavily used in blogdown. It is not smart but it does not need to be smart, either. The ERROR said something about the template file `article_metadata.html`, but I don't see anything wrong with this file.

I just tested a new site with

```r
blogdown::new_site(theme = 'gcushen/hugo-academic')
```

and I didn't see any problems with the latest versions of blogdown and Hugo.

**Comment by lcolladotor** [comment]
Hi,

I can verify that it works now. I don't know which recent change in blogdown (or hugo academic) did it, but thanks for fixing this!

Best,
Leo

PS Tested with  blogdown   * 0.0.16  2017-01-25 Github (rstudio/blogdown@3e85754) with both `blogdown::new_site(theme = 'gcushen/hugo-academic', dir = 'test')` and with a fresh clone of https://github.com/lcolladotor/hugoblog and https://github.com/lcolladotor/lcolladotor.github.com (public/).

**Comment by lcolladotor** [comment]
```
{{% alert note %}}
some note
{{% /alert %}}
```

and

```
{{% alert warning %}}
some alert
{{% /alert %}}
```

work. The following don't although they work with `knitr::render_markdown(TRUE)` using https://github.com/lcolladotor/markdown-redcarpet.tmbundle/commit/f043c056ff620299843e9d8ea34144f478aa7965

```
{{< tweet 817608772000608256 >}}
:wink:
```
