### ISSUE TITLE
Anyone know what cookies use the blogdown's webs?

### ISSUE THREAD

**Issue by Angel441995** [rstudio/blogdown#421]
I have created a web site with blogdown and, in order to fulfill the european normative about personal data protection, i am trying to find the cookies that blogdown uses. Do you know what cookies blogdown uses?

Thanks! (sorry for my poor english)

**Comment by yihui** [comment]
Blogdown itself doesn't use any cookies. Typically a static website doesn't use cookies, but third-party services such as Disqus or Google Analytics do use cookies. There is no definitive answer to your question, and this repo is not the best place to ask this kind of questions. Please consider other places per instructions of the issue guide (which you deleted). Thanks!
