### ISSUE TITLE
install_hugo() installs older version 0.16 - some themes not supported - upgraded to 0.18 to fix

### ISSUE THREAD

**Issue by MarkEdmondson1234** [rstudio/blogdown#43]
Hello, great package going to migrate my blog to it ASAP.

Just a FYI that others may come across: the hugo version available via `blogdown::install_hugo()` installed hugo v0.16, yet the latest version is 0.18.1 and that was needed for me to get a theme to work.  

The original issue on the theme github here: https://github.com/digitalcraftsman/hugo-icarus-theme/issues/70#issuecomment-274175882

I fixed via install newer version on OSX and using brew via:

```
brew unlink hugo
brew update && brew install hugo
hugo env
```

Is there a particular reason to pin the `blogdown::install_hugo()` to that version, i.e. could it break something now I've upgraded?

**Comment by yihui** [comment]
`install_hugo()` always tries to install the latest version of Hugo. I guess there was a certain problem with your Homebrew (perhaps it was too old). Here is my brew version:

```
$ brew --version
Homebrew 1.1.7
Homebrew/homebrew-core (git revision 269b3; last commit 2017-01-20)
```
