### ISSUE TITLE
How is built: Font-settings and Download page features

### ISSUE THREAD

**Issue by frodriguezsmartclip** [rstudio/blogdown#431]
Hi there,

I' ve read the full [documentation here about blogdown](https://bookdown.org/yihui/blogdown/themes.html#the-default-theme) (nice work) 👌 

I see it's built with Hugo CMS generator, so, I like some features from the theme ([hugo-lithium](https://github.com/yihui/hugo-lithium)) 

I don't know how they are implemented within the theme that I would like to add to another personal theme also made with Hugo (another external JS library that takes care of it)

In the github repository of themehugo-lithium, there is no information on these two functionalities:

- **Font-settings**: increase, decrease the text, white, sepia and night ...
- **Download page as**: pdf or epub.

![Anotación 2020-02-27 103341](https://user-images.githubusercontent.com/59822855/75431708-8cee4200-594d-11ea-92e7-49f2d7717f1c.png)

How could I achieve this? Is it possible? Thanks in advance! 🙏 

Regards

**Comment by cderv** [comment]
The screenshot you posted is the one from blogdown book. It has been created using `bookdown` 📦 in R. It is not made using blogdown and hugo-lithium theme. A website with this theme looks like this one: https://blogdown-demo.rbind.io/

For the blogdown online book your screenshot is about, the source is [inside blogdown repo](https://github.com/rstudio/blogdown/tree/master/docs) in the docs folder. The two features you mentioned are from the `gitbook` output format and documented in bookdown book: https://bookdown.org/yihui/bookdown/html.html
There source are in JS in the bookdown package.  They are not part of `themehugo-lithium` so you won't find information there. 

Did I misunderstood you here or is it clearer now ?  

Hope it helps.

**Comment by frodriguezsmartclip** [comment]
@cderv  Ok ok I understand! are different frameworks. But, I searched for the source in JS file in the bookdown package to see the code, but I haven't found it, where is it exactly? 😢 

@yihui Might know how the feature "the functionality of changing the text size, color of the text" and implement it myself in another theme that I created with Hugo is developed? 🙏 

![Anotación 2020-03-02 174300](https://user-images.githubusercontent.com/59822855/75697734-cdcbbb00-5cad-11ea-8ec5-0f48d0b6ab9e.png)

Thanks in advance to both! Regards

**Comment by gadenbuie** [comment]
The font settings selector is a Gitbook plugin and you can find the plugin source in this repo: https://github.com/GitbookIO/plugin-fontsettings

I'm not sure how easy it will be to re-implement for blogdown, but maybe the source can provide some direction. If you run into problems or have further questions about the source, I highly recommend that you ask on [RStudio Community](https://community.rstudio.com/) which is a better forum for these kinds of questions.

**Comment by cderv** [comment]
Thanks @gadenbuie for the upstream link ! And yes, this type of question are better asked on RStudio community ! 

@frodriguezsmartclip, yes this is part of gitbook library as @gadenbuie , but it is indeed included inside bookdown as a resource 
See js file : https://github.com/rstudio/bookdown/blob/master/inst/resources/gitbook/js/plugin-fontsettings.js
The yaml option helps change the default config for gitbook, and it is taken into account by the js plugin. You should find the logic by reading through the code. 

Hope it helps. I let you close this issue if you have all the info you need.

**Comment by frodriguezsmartclip** [comment]
@cderv @gadenbuie Great!!! That's all I wanted it.  👌 

Thanks both for the info. I'll try to implement plugin-fontsettings from GitBook repo to my custom theme!! 💻 

I close this issue. Have a nice day 😃
