### ISSUE TITLE
Using crosstalk in a blogdown document causing weird CSS effect

### ISSUE THREAD

**Issue by pssguy** [rstudio/blogdown#44]
In my blog, I want to use the crosstalk library in my code but it causing the rendered page to behave unexpectedly

This the look I want
![nosdcode](https://cloud.githubusercontent.com/assets/2775918/22217865/7f86f216-e159-11e6-8809-2db5068bb53d.PNG)

and this is what I am getting when I add a couple of lines of code

![sdcode](https://cloud.githubusercontent.com/assets/2775918/22217878/88f6e2de-e159-11e6-8e5b-0c3e389b5725.PNG)

```{r}
library(crosstalk)
sd <- SharedData$new(chickwts)
filter_select("feedtype", "Feed type", sd, ~feed)

```

Inspecting the code in the latter for the h1, i get this

![fontsizesdcode](https://cloud.githubusercontent.com/assets/2775918/22217910/a409cfc8-e159-11e6-96ba-9c2be40431ad.PNG)

I have posted a real life case [here](http://www.mytinyshinys.com/post/badDrivers_538_2/)  if you need to delve deeper

I'm using these versions
crosstalk_1.0.1
blogdown_0.0.14

Should I be posting this on the crosstalk issues as well?

thanks

**Comment by pssguy** [comment]
I should add that I get as  warning (not error) message

```
Warning messages:
1: In unlink(dir, recursive = TRUE) :
  cannot get info on '../content/post/2017-01-23-add-rmd-true_files/crosstalk/js', reason 'Access is denied'
2: In unlink(lib1, recursive = TRUE) :
  cannot get info on 'content/post/2017-01-23-add-rmd-true_files/crosstalk/js', reason 'Access is denied'
> 
```

**Comment by pssguy** [comment]
Just wondered if any one has had a chance to replicate this?

**Comment by yihui** [comment]
It seems there was a more active discussion at https://github.com/rstudio/crosstalk/issues/26. On my side, I'd recommend you to try this approach if you intend to build complex JS-based applications: https://bookdown.org/yihui/blogdown/static-files.html which means you have to build your complex JS-based documents under `static/`, and they will not appear as "posts" but you can only link to them.

I think the tradeoff is unavoidable. As you add more widgets to posts, there will be higher chances of conflicts (in CSS and JS).

**Comment by apreshill** [comment]
Hi- this is a very old thread but for others who stumble upon it: we have worked to remove the Bootstrap dependency of `crosstalk` - please give it a try again in your blogdown site!

https://github.com/rstudio/crosstalk/blob/master/NEWS.md#crosstalk-1119000

```
remotes::install_github("rstudio/crosstalk")
```
