### ISSUE TITLE
support responsive images via <picture> element

### ISSUE THREAD

**Issue by maxheld83** [rstudio/blogdown#46]
Since we're using a lot of images in R (plots, sometimes quite detailed), and since `blogdown` might cover some general websites/blogging use cases with lots of non-R images, it might be worthwhile at some point to support this newfangled thing of "responsive" images via the `<picture>` element.
Specifically, I mean the [non-art-direction use cases](https://www.html5rocks.com/en/tutorials/responsive/picture-element/) of this feature, such as downloading an image in a different resolution depending on the DPI and size of the viewport.

I realise this is a bit of a long shot, and probably primarily a HUGO / HUGO themes issue, but I wanted to log this here anyway, to discuss how this might interact with knitr chunk options etc.

Once this *does* become available in HUGO / HUGO themes, I guess `bookdown` (or perhaps `knitr`?) would also have to learn to provide R plots in a variety of resolutions, so that the browser can download the appropriate one based on `<picture>` viewport size and DPI.

**Comment by jemus42** [comment]
Manipulating the HTML of plot output is possible right now, you could use a similar approach to knitr hooks as I did [here](https://github.com/rstudio/blogdown/issues/168) to wrap the image in `<picture>` with different sources. 

You could append a set suffix at the end of each source, so you have e.g. `image.png` for the original image and `image-medium.png` and `image-small.png` or something, which would make your HTML good to go, but at this point you only have one image actually existing, i.e. `image.png`.  
At this point you could use a post-processing script using something like `imagemagick` or the `magick` package to crawl through your output directory, take every image that doesn't hav one of your predefined suffixes, and have it create the two image versions you references in the `<picture>`-tag.

It wouldn't be pretty, but the more I think about it, the more I'm certain that it's at least doable right now.

**Comment by jemus42** [comment]
I found away to output the `<picture>` tag with arbitrary additional sources, and also a way to convert plot output on the fly while it's being generated to additional formats. I briefly explain and link to the relevant code [in this post](https://blog.jemu.name/2017/07/i-just-wanted-to-serve-images/), and more adventurous folks might be able to build upon that approach.

**Comment by yihui** [comment]
Yeah, on second thought, I think it makes more sense for users to redefine the `plot` hook to do whatever they want just like @jemus42 did. I don't want to go too deep into this rabbit hole myself. I feel the responsive `<picture>` is more for displaying art, and I don't see how beneficial it is to display a scatterplot in multiple versions.
