### ISSUE TITLE
Is there anyway to add search button in the blog? 

### ISSUE THREAD

**Issue by janeshdev** [rstudio/blogdown#47]
Not sure if this issue fits here but is there any way to include the search button in the blog ?

**Comment by yihui** [comment]
Similar question asked here https://twitter.com/JennyBryan/status/817467026801164289 (see Jeff Allen's reply)

**Comment by znmeb** [comment]
You can also embed a DuckDuckGo search: https://duckduckgo.com/search_box but it will take you to their site out from your blog.

**Comment by yihui** [comment]
Here is the official documentation: https://gohugo.io/tools/search/
