### ISSUE TITLE
Error with serve_site()

### ISSUE THREAD

**Issue by pssguy** [rstudio/blogdown#48]
New problem

```
> serve_site()
Error in find_config() : 
  Cannot find the configuration file config.yaml or config.toml of the website
> 
```
![servesiteissue](https://cloud.githubusercontent.com/assets/2775918/22392837/a963ca58-e4b2-11e6-887e-d9e40fda295f.PNG)

I recently updated to blogdown v 0.0.18

**Comment by yihui** [comment]
Your working directory is not the root directory of the website.

**Comment by pssguy** [comment]
Cheers. Not sure how i moved out of it but will know to check in future

**Comment by sue-wallace** [comment]
How do you update the root directory of the website?

**Comment by tcgriffith** [comment]
hi, @sue-wallace 

The project directory(created by `blogdown::new_site()`) is the root directory of the website. Please be more specific regarding your problem so others could help.
