### ISSUE TITLE
blogdown.knit.on_save = FALSE and blogdown.serve_site.startup =TRUE will start a server but it will be killed at startup too

### ISSUE THREAD

**Issue by cderv** [rstudio/blogdown#482]
Following tests on  #481, here is another unexpected behavior I believe. 

Let's start by precising that I did not test with Scoop installed hugo because of  #480 

* Requirements: `options(blogdown.knit.on_save = FALSE)` is set in .Rprofile
* Open a blogdown project - it will run the hugo server at startup
 ```r
> blogdown:::preview_site(startup = TRUE)
Launching the server via the command:
  C:\Users\chris\AppData\Roaming\Hugo\hugo.exe server --bind 127.0.0.1 -p 4321 --themesDir themes -t hugo-lithium -D -F --navigateToChanged
Serving the directory . at http://127.0.0.1:4321
Launched the hugo server in the background (process ID: 22952). To stop it, call blogdown::stop_server() or restart the R session.
```
The website opens in the viewer... but when trying to navigate the preview it fails.
This is because the hugo server has been existed... Don't know why ! 
```r
> ps::ps_handle(blogdown:::opts$get("pids"))
Erreur : No such process, pid 22952, ???
> blogdown::stop_server()
Warning message:
In blogdown::stop_server() :
  Failed to kill the process 22952. You may need to kill it manually.
```

Note sur what happens yet... 

Trying to simulate the startup does not reproduce

* Set also `options(blogdown.serve_site.startup = FALSE)` in .Rprofile
* Restart R or reopen Blogdown project -> No server is run
* Run in console `blogdown:::preview_site(startup = TRUE)` -> process is correctly opened and stayed open
```r
> blogdown:::preview_site(startup = TRUE)
Launching the server via the command:
  C:\Users\chris\AppData\Roaming\Hugo\hugo.exe server --bind 127.0.0.1 -p 4321 --themesDir themes -t hugo-lithium -D -F --navigateToChanged
Serving the directory . at http://127.0.0.1:4321
Launched the hugo server in the background (process ID: 27044). To stop it, call blogdown::stop_server() or restart the R session.
> ps::ps_handle(as.integer(blogdown:::opts$get("pids")))
<ps::ps_handle> PID=27044, NAME=hugo.exe, AT=2020-10-07 16:54:43
```

Don't know yet why this happens... I'll keep looking

**Comment by cderv** [comment]
In fact it happens only with processx. Setting `options(blogdown.use.processx=FALSE)` will not reproduce this error. 

This is a big hint!

**Comment by yihui** [comment]
Were you using a version after 553f0ad559f9220e5c71b5b836405c3b8c99d676? Before that commit, there was a bug on my side.

**Comment by cderv** [comment]
Yes I was using last available version for me yesterday 49291fd1da4060e1722f36eebad5237c7ebb0e94 

I'll retry with new version

**Comment by cderv** [comment]
Still happening with 0.20.14 ca55ed202d045aa4a0745e18f58373e78ccbfd1d 😞

**Comment by cderv** [comment]
Ok too quick. This now works with last version correctly. 
I may have had a lot of uncleaned processed after all tests yesterday.

**Comment by yihui** [comment]
I have manually killed more than a hundred processes on Windows and macOS these days for testing this stuff 😂
