### ISSUE TITLE
Issue on activating the theme

### ISSUE THREAD

**Issue by janeshdev** [rstudio/blogdown#49]
Hi Yihui, 
Thanks for getting back to my issues. I am having the issue when trying to activate any theme other than lithium theme. 

For example, I am using the theme `hugo-theme-casper`. When I use the `serve_site()` command, it gives the following error message: 

```
> serve_site()
Started building sites ...
ERROR: 2017/01/30 13:40:45 general.go:236: theme/partials/semantic.html is an incomplete or empty template
ERROR: 2017/01/30 13:40:45 general.go:236: theme/partials/author.html is an incomplete or empty template
Built site for language en:
0 draft content
0 future content
0 expired content
13 regular pages created
6 other pages created
0 non-page files copied
7 paginator pages created
3 tags created
0 categories created
total in 172 ms
```

Is there anyway to fix this ? 

When I use viewer in Rstudio, then all the pages display. However, if I use public folder and try to view the posts, i cannot see any posts. Only thing I can see is the homepage.

**Comment by yihui** [comment]
Could you provide a reproducible example?
