### ISSUE TITLE
by-products are not moved correctly with leaf bundle and Hugo academic 

### ISSUE THREAD

**Issue by cderv** [rstudio/blogdown#500]
Found during my test of new dev version. 

The files are supposed to move to content directory and then stay if leaf bundle if used, from what I understand
https://github.com/rstudio/blogdown/blob/0e2e33f71adadf3d85aac4fa0fb23584721d4b75/R/render.R#L109-L125

This is not correctly done for hugo academic because I believe it support multilanguage and the files names are `index.en.html` for example. That means the ressource directory is `index.en_files` 

I think the regex should be changed here:
https://github.com/rstudio/blogdown/blob/0e2e33f71adadf3d85aac4fa0fb23584721d4b75/R/render.R#L122

Currently, even with `blogdown.new_bundle = TRUE` (the new default), files for a new post are still inside the `static` directory.

**Comment by yihui** [comment]
Good catch! Should be fixed now. Thanks!
