### ISSUE TITLE
find_hugo all does not find all version on Windows

### ISSUE THREAD

**Issue by cderv** [rstudio/blogdown#503]
FYI @yihui 

* Only a scoop version installed
``` r
blogdown::find_hugo()
#> [1] "hugo.exe"
blogdown::find_hugo('all')
#> NULL
Sys.which("hugo")
#>                                       hugo 
#> "C:\\Users\\chris\\scoop\\shims\\hugo.exe"
```

* With APPDAPA version 
``` r
blogdown::find_hugo()
#> Warning: Found hugo at "C:\Users\chris\AppData\Roaming/Hugo/0.78.0/hugo.exe"
#> and "C:\Users\chris\scoop\shims\hugo.exe". The former will be used. If you
#> don't need both copies, you may delete/uninstall the latterperhaps with
#> system2("scoop", c("uninstall", "hugo")).
#> [1] "C:\\Users\\chris\\AppData\\Roaming\\Hugo\\0.78.0\\hugo.exe"
blogdown::find_hugo("all")
#> [1] "C:\\Users\\chris\\AppData\\Roaming/Hugo/0.78.0/hugo.exe"
Sys.which("hugo")
#>                                       hugo 
#> "C:\\Users\\chris\\scoop\\shims\\hugo.exe"
```

It feels unexpected that `find_hugo()` found it and not `find_hugo("all")`

**Comment by cderv** [comment]
This works ok now
``` r
blogdown::find_hugo()
#> [1] "hugo.exe"
blogdown::find_hugo("all")
#> [1] "C:/Users/chris/scoop/shims/hugo.exe"
```

<sup>Created on 2020-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

We just got one full path, and one binary name (found because on PATH). Should we normalize in both case ?

**Comment by yihui** [comment]
We could normalize. I was mainly concerned about using the full path on Windows (e.g. when it contains spaces), but that might be an imaginary concern. This is probably not a big deal. I'll mention this on the help page.

**Comment by cderv** [comment]
>  I was mainly concerned about using the full path on Windows (e.g. when it contains spaces), but that might be an imaginary concern. 

Hum, you may be right... Spaces can sometimes cause a lot of issues. We have some with TexLive and TinyTeX: 
https://community.rstudio.com/search?q=space%20user%20tinytex

Using the binary filename directly from the PATH is safer indeed.

**Comment by yihui** [comment]
Actually you brought up exactly the problem that I meant to ask you a while ago. I've seen this `CreateProcess failed` message several times in the past because of the spaces in user names on Windows, but I've never been able to reproduce it. It seems you don't know the reason, either: https://community.rstudio.com/t/60003/6 This is really weird.

**Comment by cderv** [comment]
Yes I don't know either for sure. And hard to recreate as each time it seems to be related with space in username. 

I know that CreateProcess and space can be difficult: 
* https://stackoverflow.com/questions/4053241/windows-api-createprocess-path-with-space

I wonder if it is just a quoting issue. I was also not sure which program is calling this "CreateProcess".
