### ISSUE TITLE
Add a uninstall_hugo() function

### ISSUE THREAD

**Issue by cderv** [rstudio/blogdown#504]
Like with `tinytex::uninstall_tinytex`, I think it is good practice to have a cleaning function for what we offer to install through the package. For example, on windows, I find it odd to have to open APDATA folder myself to delete the folder. 

What about adding a `uninstall_hugo()` function so that user can clean an installation made with **blogdown** ?

**Comment by cderv** [comment]
I don't think this will fully work on other installation where the binary is found on PATH: 
https://github.com/rstudio/blogdown/blob/dc026f081f2ce9149f2b2f0b5e6f1c22b57d1e60/R/install.R#L304-L311

Take this: 

I am in temp folder because I am doing a reprex here for the example

``` r
getwd()
#> [1] "C:/Users/chris/AppData/Local/Temp/RtmpAjUvIq/reprex3f861c42895"
```

hugo is found in PATH - so a single binary filename is the result here

``` r
f = blogdown::find_hugo()
f
#> [1] "hugo.exe"
```

directory name will “wrongly” be `.` (but it should be

``` r
d = dirname(f)
d
#> [1] "."
```

this is matched in the `if` clause 
``` r
grepl('^[0-9.]+$', basename(d))
#> [1] TRUE
```
I think it shouldn't... The regex should maybe be version-string like ? 
Something like `"^(\\d+)([.]\\d+)?([.]\\d+)?$"`


This is not very harmful but we will print a message that is not correct

``` r
message("Removing '", f, "'...")
#> Removing 'hugo.exe'...
```

And side effects are not working (and should not be run IMO)

\* `unlink("hugo.exe")` fortunatly won’t work
\* `.` is not empty so `del_empty_dir(".")` won’t do anything.

**Comment by cderv** [comment]
I'll reopen as I think this should be improved. Close again if you think it is fine.

**Comment by yihui** [comment]
Yes, this definitely should be improved. Thanks for the testing!

**Comment by yihui** [comment]
Should be fixed now. Please feel free to add a few tests for the new utility function `is_version()` if you want. Thanks!

**Comment by cderv** [comment]
Tests added.
