### ISSUE TITLE
--atx-header is deprecated in Pandoc 2.11.2

### ISSUE THREAD

**Issue by cderv** [rstudio/blogdown#512]
See https://github.com/rstudio/rmarkdown/issues/1956

**blogdown** uses the argument 
https://github.com/rstudio/blogdown/blob/eeb66fba5f26e333575be31744a1735aea56439a/R/render.R#L226

No harm as it will just be a warning. 

A reminder that it can be removed for Pandoc 2.11.2+

**Comment by yihui** [comment]
Removed for Pandoc 2.11.2+. Thanks!
