### ISSUE TITLE
Update <pre class="name"> to <code class=lang->

### ISSUE THREAD

**Issue by danmrc** [rstudio/blogdown#520]
I was trying to use prism.js for syntax highligthing with blogdown. However, on prism.js website they say:

> Prism does its best to encourage good authoring practices. Therefore, it only works with `<code>` elements, since marking up code without a `<code>` element is semantically invalid. According to the HTML5 spec, the recommended way to define a code language is a language-xxxx class, which is what Prism uses. Alternatively, Prism also supports a shorter version: lang-xxxx.

Looking at the html that blogdown generates, the name of the language goes in `<pre class=> `. This looks like to be due to the way pandoc does (see [this issue](https://github.com/jgm/pandoc/issues/3858)), so one easy fix would be to wait to pandoc be updated.

Is there a way to do it? The topic I linked above suggests using a lua filter, but I could not make it work. I tried using the `pandoc_args` in the yaml header, for example:

```
output:
  blogdown::html_page:
    pandoc_args:
      [
      "--lua-filter=script.lua"]
```
 I also read on the manual that one could configure build tools and it might be the way to do it, but I never did it before. 

One might be tempted to change prism.js itself, however maybe making the files that blogdown generates comply with HTML5 specification might be interesting in itself.

Thanks in advance and thanks for the awesome package

## Checklist

When filing a _feature request_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] searched for an existing feature request to avoid creating duplicate requests? If you find an existing feature request, please give it a thumbs-up reaction, as we'll use these reactions to help prioritize the implementation of these features in the future.

- [x] provided a clear and concise description of the problem this proposed feature would address? For example, I struggle to do `[...]` with blogdown.

- [x] provided a clear and concise description of what you want to happen?

- [x] provided a clear and concise description of alternative solutions or workarounds you've considered?

- [x] added any other context or screenshots about your feature request?

**Comment by yihui** [comment]
I guess this could be more easily solved by JavaScript instead of a Lua filter, e.g., 

```js
document.querySelectorAll('pre').forEach(function(el) {
  if (!el.className) return;
  el.firstElementChild.classList.add('lang-' + el.className);
  el.removeAttribute('class');
});
```

You can apply the above JS code before using prism.js.

**Comment by danmrc** [comment]
> ```js
> document.querySelectorAll('pre').forEach(function(el) {
>   if (!el.className) return;
>   el.firstElementChild.classList.add('lang-' + el.className);
>   el.removeAttribute('class');
> });
> ```

After a while (and after I posted this) [I modified one of the scripts in the pandoc issue to work with blogdown](https://github.com/danmrc/azul/blob/master/content/post/script_number_and_braces.lua). Since I have never worked with lua before, I am pretty sure it is not so good, and I would be glad to use your script. 

However, For some reason your script gives an error:

```
Rendering content/post/2020-11-30-remastered-interpolacao/index.Rmd... Error running filter ../script2.lua:
../script2.lua:1: unexpected symbol near '{'
Erro: pandoc document conversion failed with error 83
```

**Comment by yihui** [comment]
My script is JavaScript, not Lua. As I said above, you can run the JS code before you load and use prism.js.
