### ISSUE TITLE
Improve behavior of RStudio IDE Build Website button

### ISSUE THREAD

**Issue by cderv** [rstudio/blogdown#522]
# Context

This is first from a question in the community: 
https://community.rstudio.com/t/css-formatting-not-showing-when-building-blogdown-new-site/89672/3
then from a discussion with @apreshill 

## Clinking Build Website 

Currently, clicking the Build Website button will 
 * run, `rmarkdown::render_site(encoding = 'UTF-8')`
 * This will run `blogdown:::blogdown_site()[["render"]]`,
 *  that will run `blogdown::build_site()`
It means it will build a blogdown website ready for publishing in the `public/`folder, but it won't be easily previewable. It is a choice. 
But current issue is an undesired behavior IMO: RStudio IDE will the website in the viewer. I don't know exactly where this is done, but I am guessing the IDE will open in the viewer the output of `rmarkdown::render_site()`. 

With **blogdown**, this is problematic as it won't be correctly previewed - it would require running a local server (`servr` as before, or `hugo server`)

It seems there is not current way to deactivate 

### What could be done ? 

Several options I think: 

1. Deactivate the previewing - to see with the IDE team ? 
2. Configure the preview to be run with a custom function in the package - not possible today. This would allow to run a local server for this
3. Combining 1 and 2: On a condition (`preview = TRUE` for example in the site_generator), `rmarkdown::render_site()` would run the `render` function of the site generator and considering the preview will be dealt with so skipping the "open in preview" step. 

Regarding what we could expect from the Build Website button for **blogdown**, I would suggest with @apreshill feedback: 
* To build the website as we would do for publishing (like drag & drop on netlify) AND having the hability to preview before publishing. 
That would mean no draft post, no future post. Something like 
```sh
hugo server --bind <host> -p <port> --themesDir <themeDir> -t <theme> -d <publishdir> --cleanDestinationDir
```

But obviously that would mean being able to customize the behavior of the button more precisely 🤷 

I opened this to discuss it and gather ideas

Related to #518 which is the Clean All button in the IDE

**Comment by yihui** [comment]
I've deactivated the preview, with a message reminding users of previewing the site properly with a server.

It's not very practical for **blogdown** to start a local server in this case to preview the `public/` folder. Two reasons:

1. "Build Website" uses a new R session to build the site. If **blogdown** starts a local web server, the server shouldn't be shut down after the new R session quits, which means it has to leave a background process running, and it will be hard to kill that process (not really hard, but the instruction on how to kill it will also be too technical to average users).

1. The URL to preview the `public/` folder needs to take the `baseURL` setting in `config.yaml` into consideration. This can be complicated when `baseURL` contains a subpath (e.g., `https://example.com/foo/`). Well, not _that_ complicated, but it's definitely not as simple as starting a web server under the `public/` directory and assume it's the root directory of the website.

What I've done for now is that I added a message telling users that they are not supposed to click the `.html` files and open them directly. Now the messages after clicking the "Build Website" button look like this:

```
==> rmarkdown::render_site(encoding = 'UTF-8')

Start building sites … 

                   | EN  
-------------------+-----
  Pages            | 44  
  Paginator pages  |  0  
  Non-page files   | 47  
  Static files     | 31  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 169 ms

==> The site has been generated to the directory 'public'.

** Note that normally you cannot just open the .html files in this directory
to view them in a browser. This directory need to be served before you can
preview web pages correctly (e.g., you may deploy the folder to a web server).
Alternatively, blogdown::serve_site() gives you a local preview of the site.
```

@apreshill Please feel free to suggest a better version of the message. Thanks!
