### ISSUE TITLE
Update recommendations for ignoring files

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#523]
https://bookdown.org/yihui/blogdown/configuration.html#options

New recommendation: don't put `"_files$"` in there!

https://twitter.com/andrew_leach/status/1334250249964032001?s=20
https://twitter.com/andrew_leach/status/1334251603365281794?s=20

**Comment by yihui** [comment]
To avoid further confusion, I just removed `_files$` from the list in the bullet about `ignoreFiles`. The language may still need further improvement, so I'm leaving this issue open here.
