### ISSUE TITLE
Post pages lost hugo layout / icon's issue at home page

### ISSUE THREAD

**Issue by luisotavio88** [rstudio/blogdown#529]
My website is: https://www.luisotavio.pro/ and I am using LIVA theme from Hugo.
My Repo: https://github.com/luisotavio88/luisotavio.pro

In my home page I can´t see the Youtube, Linkedin and Instagram icons anymore. Seems to be a CORS issue.

Also, the post pages lost all the layout and are raw, without any layout.

But I noticed that the/index.html pages are OK. 

Example:
NOT OK: https://www.luisotavio.pro/blog/acompanhamento-dos-perfis-do-instagram
OK: https://www.luisotavio.pro/blog/acompanhamento-dos-perfis-do-instagram/index.html

It repeats for each post.

 xfun::session_info('blogdown')
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363), RStudio 1.3.1093

Locale:
  LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252    LC_MONETARY=Portuguese_Brazil.1252
  LC_NUMERIC=C                       LC_TIME=Portuguese_Brazil.1252    

Package version:
  base64enc_0.1.3  BH_1.72.0.3      blogdown_0.21.50 bookdown_0.21    digest_0.6.27    evaluate_0.14   
  glue_1.4.2       graphics_4.0.3   grDevices_4.0.3  highr_0.8        htmltools_0.5.0  httpuv_1.5.4    
  jsonlite_1.7.1   knitr_1.30       later_1.1.0.1    magrittr_2.0.1   markdown_1.1     methods_4.0.3   
  mime_0.9         promises_1.1.1   R6_2.5.0         Rcpp_1.0.5       rlang_0.4.8      rmarkdown_2.5   
  servr_0.20       stats_4.0.3      stringi_1.5.3    stringr_1.4.0    tinytex_0.27     tools_4.0.3     
  utils_4.0.3      xfun_0.19        yaml_2.2.1 

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [ x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x ] included a minimal, self-contained, and reproducible example?

- [x ] pasted the output from `xfun::session_info('blogdown')` in your issue?

- [x ] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x ] installed and tested your bug with the development version of the blogdown package using `remotes::install_github('rstudio/blogdown')`?

**Comment by yihui** [comment]
This is not a **blogdown** bug, but a CORS issue. You may see more info from the Developer Tools of your web browser. Basically, you need to decide whether you really want to use `https://www.luisotavio.pro/` or `https://luisotavio.pro/` (i.e. to use `www` or not). Then set the `baseURL` in your config file (`config.toml` or `config.yaml`), which you didn't push to your repo: https://github.com/luisotavio88/luisotavio.pro

**Comment by luisotavio88** [comment]
it was listed in my git.ignore files. Now it´s solved. Thank you very much.

**Comment by yihui** [comment]
Good to know, but please remember to mention cross-posting in the future: https://stackoverflow.com/q/65193619/559676 Thanks!
