### ISSUE TITLE
'extra' posts appearing when using leaflet

### ISSUE THREAD

**Issue by thedatacollective** [rstudio/blogdown#53]
I recently use the leaflet htmlwidget on my blog and when testing using `blog down::site_serve()` everything looks fine. However when I built the site `blogdown::build_site()` and deployed to gitlab (to make use of the inbuilt runners) my main index page ends up with three extra posts right at the bottom of the page. They are associated with the `leaflet-providers` `README`, `CONTRIBUTING` and `license` files that exist as part of the leaflet package. 

I'm not too sure how reproducible it is, I just wonder if there might be a way to limit any `.md` files coming from other packages.

**Comment by yihui** [comment]
I cannot say what was possibly wrong without a reproducible example. You may try to add `ignoreFiles` to config.toml like https://github.com/yihui/hugo-lithium-theme/blob/3e145f74d8/exampleSite/config.toml#L8
