### ISSUE TITLE
Use messages that are more like cat() - stdout instead of stderr

### ISSUE THREAD

**Issue by cderv** [rstudio/blogdown#531]
From the workshop, we got the feedback that red messages in console for informative guidances and checks are not well received. Same as error or warning which are seen as bad output. Using cat() output would be better.

From our discussion, we could use `rlang::inform` or get inspiration from to output some messages to user in console without having them as the same color as messages

See doc page: https://rlang.r-lib.org/reference/abort.html

![image](https://user-images.githubusercontent.com/6791940/101938207-3eabe600-3be3-11eb-89c7-b39432e9cb80.png)

From hadley comment, it would be easy to rewrite in pure base R if we don't want to start using r-lib tools like `rlang`

**Comment by yihui** [comment]
This is indeed quite simple to implement with base R. I had done it yesterday but haven't had a chance to push it until now. Thanks!

**Comment by cderv** [comment]
Cool ! 👍 
Another function to share in **xfun** ? 😉

**Comment by yihui** [comment]
Okay, since you have demonstrated for many times that you can read my mind, I think I can hand all packages to you and retire now! 😁 

This can certainly go to **xfun**. I just couldn't think of a proper name for this function (`message_cat()` with an alias `message_kitten()`? Would that be too cute?).

**Comment by cderv** [comment]
That is a cute idea ! 😄

I like the short version `msg_cat` and `msg_kitten`, but I understand if you find that too short. 
As another hidden function, should there be `msg_dog` alias for all the non-cat R users ? 😂
