### ISSUE TITLE
Detect multilingual exampleSites

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#537]
When I start a new site with a multilingual theme, the sample R Markdown post always ends up in the wrong place, see:

https://github.com/apreshill/introduce-yourself/tree/master/content
https://github.com/apreshill/zzo/tree/master/content

Perhaps we could detect the combo of `defaultContentLanguage` and `defaultContentLanguageInSubdir` keys in the YAML?

https://gohugo.io/content-management/multilingual/#configure-languages

```
defaultContentLanguage: en
defaultContentLanguageInSubdir: yes
```

https://github.com/apreshill/zzo/blob/bff76d2d4e5ed5ea07e76f2f770aab06f9a6b469/config.yaml#L4-L5

## Checklist

When filing a _feature request_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] searched for an existing feature request to avoid creating duplicate requests? If you find an existing feature request, please give it a thumbs-up reaction, as we'll use these reactions to help prioritize the implementation of these features in the future.

- [x] provided a clear and concise description of the problem this proposed feature would address? For example, I struggle to do `[...]` with blogdown.

- [x] provided a clear and concise description of what you want to happen?

- [x] provided a clear and concise description of alternative solutions or workarounds you've considered?

- [x] added any other context or screenshots about your feature request?

**Comment by cderv** [comment]
This comes from `new_site()` with `sample = TRUE`. It currently assumes that the website organization will be 
```
content/
  \-- post/
     \-- ...
```
https://github.com/rstudio/blogdown/blob/b860d27fb475eeb7401fbc0542d46962eeac17b7/R/hugo.R#L163-L172

It seems to no be the case for international website at all.

I believe the key to detect would be `languages`, and if `defaultContentLanguage` is set with `defaultContentLanguageInSubdir = TRUE` then, put the post in default language folder. Other is the two latter keys are not defined, `defaultContentLanguage` will be `en` by default, not under a subdir by default.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
