### ISSUE TITLE
Error: C stack usage is too close to the limit

### ISSUE THREAD

**Issue by jimrothstein** [rstudio/blogdown#538]
Welcome to the blogdown GitHub repo 👋

To file a _bug report_, please follow these instructions carefully: <https://yihui.org/issue/#bug-reports>

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [ x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [ x] included a minimal, self-contained, and reproducible example?

- [ x] pasted the output from `xfun::session_info('blogdown')` in your issue?

- [ ] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [ ] installed and tested your bug with the development version of the blogdown package using `remotes::install_github('rstudio/blogdown')`?

##  Do not  think  this is blogdown issue, but occurs during blogdown::serve_site().   
The problem, I think, is recursion.   But it **does run fine in plain R**.

**My code**:

```
a  <- function() {
 if (sys.nframe() == 9) return()
cat("nframe = ", sys.nframe() , "\n")
 a()
}
a()
```

Error: C stack usage  7970900 is too close to the limit
Error: Failed to render content/post/0002_error_nframe.Rmd

This is why I think C stack problem is recursion:
`https://stackoverflow.com/questions/14719349/error-c-stack-usage-is-too-close-to-the-limit`

**console output and Backtrace**
> serve_site()
Launching the server via the command:
  hugo server --bind 127.0.0.1 -p 5235 --themesDir themes -t hugo-lithium
 -D -F --navigateToChanged
Serving the directory . at http://localhost:5235
Launched the hugo server in the background (process ID: 17776). To stop i
t, call blogdown::stop_server() or restart the R session.
Rendering content/post/0002_error_nframe.Rmd... This message is from  ~/.
Rprofile
Error: C stack usage  7970900 is too close to the limit
Error: Failed to render content/post/0002_error_nframe.Rmd

**Backtrace:**
1. blogdown::serve_site()
2. blogdown:::serve(...)
3. blogdown:::rebuild(rmd_files <- filter_newfile(list_rmds()))
 5. blogdown::build_site(TRUE, run_hugo = FALSE, build_rmd = files)
 6. blogdown:::build_rmds(files)
 7. 7. xfun::Rscript_call(...)

**> Cstack_info()**
      size    current  direction eval_depth
   7969177      20768          1          2

> **xfun::session_info("blogdown")**
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
  LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
  LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
  LC_PAPER=en_US.UTF-8       LC_NAME=C
  LC_ADDRESS=C               LC_TELEPHONE=C
  LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

Package version:
  base64enc_0.1.3  BH_1.72.0.3      blogdown_0.21.57 bookdown_0.21
  digest_0.6.27    evaluate_0.14    glue_1.4.2       graphics_4.0.3
  grDevices_4.0.3  highr_0.8        htmltools_0.5.0  httpuv_1.5.4
  jsonlite_1.7.2   knitr_1.30       later_1.1.0.1    magrittr_2.0.1
  markdown_1.1     methods_4.0.3    mime_0.9         promises_1.1.1
  R6_2.5.0         Rcpp_1.0.5       rlang_0.4.9      rmarkdown_2.5
  servr_0.20.2     stats_4.0.3      stringi_1.5.3    stringr_1.4.0
  tinytex_0.27     tools_4.0.3      utils_4.0.3      xfun_0.19
  yaml_2.2.1

Hugo version: 0.79.0

**Comment by yihui** [comment]
This issue is not specific to **blogdown**, but any documents to be compiled by **knitr**. In short, `9` is a too small frame number in **knitr** code chunks, and `if (sys.nframe() == 9) return()` will never happen, so you will end up with infinite recursion.

To understand this problem better, try this code chunk instead:

````md
```{r}
a  <- function() {
  sys.calls()
}
a()
```
````

By the time `a()` is called for the first time, the frame number has already reached 19 (this number is not guaranteed to be 19, because the call stack can change anytime in the future).

I don't know what your goal was. If you were trying to demonstrate the concept of frames, I recommend that you record the initial frame number, instead of assuming the initial number is 0, e.g.,

````md
```{r}
init_frame <- sys.nframe()
a <- function() {
  if (sys.nframe() == init_frame + 9) return()
  cat("nframe = ", sys.nframe() , "\n")
  a()
}
a()
```
````

**Comment by jimrothstein** [comment]
You are absolutely correct!   When using **knitr** my first **nframe is 23**!
(vs nframe = 0, in plain vanilla R)

Thank you for your comments and great work.

(fyi - My original purpose was to show examples of each of the sys.* and related functions)

```
Before do anything, what frame # ?
`cat("nframe = ", sys.nframe(), "\n")`
## nframe = 23
```
sys.calls() shows a lot going on with knitr::
```
# This shows the frames ... Good exercise!
`a  <- function() {
 sys.calls()
}
a()
      ## [[1]]
      ## rmarkdown::render("/home/jim/code/hugo_projects/blog/content/post/0001A_nframe.Rmd", 
      ##     output_format = "html_document", output_file = "~/Downloads/print_and_delete/out.html")
      ## 
      ## [[2]]
      ## knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
      ## 
      ## [[3]]
      ## process_file(text, output)
      ## 
      ## [[4]]
      ## withCallingHandlers(if (tangle) process_tangle(group) else process_group(group), 
      ##     error = function(e) {
      ##         setwd(wd)
      ##         cat(res, sep = "\n", file = output %n% "")
      ##         message("Quitting from lines ", paste(current_lines(i), 
      ##             collapse = "-"), " (", knit_concord$get("infile"), 
      ##             ") ")
      ##     })
      ## 
      ## [[5]]
      ## process_group(group)
      ## 
      ## [[6]]
      ## process_group.block(group)
      ## 
      ## [[7]]`
<SNIP>
```
