### ISSUE TITLE
Date on blog post with `r format Sys.Date()`

### ISSUE THREAD

**Issue by RobertMyles** [rstudio/blogdown#54]
Hi all,

I left a question [here](http://stackoverflow.com/questions/42024618/yaml-current-date-in-blogdown) on SO about some trouble I'm having with using `Sys.Date()` in the YAML front matter. 

I'll quote the question here:  

There's a [question here](http://stackoverflow.com/questions/23449319/yaml-current-date-in-rmarkdown) that deals with the formatting of dates for R Markdown. I'm using the blogdown package, and the answers there lead me to believe I could use: `` '`r format(Sys.Date(), "%Y-%m-%d")`' `` in the YAML front matter. Running `format(Sys.Date(), "%Y-%m-%d")` in the console gives me the date exactly as it would be in a regular Hugo blog post (i.e. "2017-02-03"), but this doesn't work with `serve_site()`. Any ideas for how to get around this? Or is necessary to use `date: "2017-02-03" `?   

The error returned from `build_site()` is:  

```
ERROR: 2017/02/03 13:41:23 page.go:555: Failed to parse date '`r format(Sys.Date(), "%Y-%m-%d")`' in page post/x.html
```

Any help would be much appreciated.

**Comment by taraskaduk** [comment]
I reinstalled everything, but still getting this error. Updated `blogdown`, updated R.

Getting this:
`ERROR 2018/01/07 12:35:31 Failed to parse date '07 January, 2018' in page page/cv_web.html`

**Comment by taraskaduk** [comment]
Actually, the issue seems to be gone after re-installing the huge theme. Never mind, I guess. Strange
