### ISSUE TITLE
Should check_hugo() also warn about HUGO_VERSION in netlify.toml if it exists ?

### ISSUE THREAD

**Issue by cderv** [rstudio/blogdown#542]
Just stumble upon this 

* `check_hugo` did not warn me about the version required by Netlify
```
> blogdown::check_hugo()
― Checking Hugo
| Checking Hugo version...
○ Found 3 versions of Hugo. You are using Hugo 0.79.0.
| Checking .Rprofile for Hugo version used by blogdown...
| Hugo version not set in .Rprofile.
● [TODO] Set options(blogdown.hugo.version = "0.79.0") in .Rprofile.
― Check complete: Hugo
```

* `check_netlify`does warn about it though
```
> blogdown::check_netlify()
― Checking netlify.toml...
○ Found HUGO_VERSION = 0.54.0 in [build] context of netlify.toml.
| Checking that Netlify & local Hugo versions match...
| Mismatch found:
  blogdown is using Hugo version (0.79.0) to build site locally.
  Netlify is using Hugo version (0.54.0) to build site.
● [TODO] Option 1: Change HUGO_VERSION = "0.79.0" in netlify.toml to match local version.
● [TODO] Option 2: Use blogdown::install_hugo("0.54.0") to match Netlify version, and set options(blogdown.hugo.version = "0.54.0") in .Rprofile to pin this Hugo version.
| Checking that Netlify & local Hugo publish directories match...
○ Good to go - blogdown and Netlify are using the same publish directory: public
― Check complete: netlify.toml
```

@apreshill Would it be interested to add a mention to `HUGO_VERSION` being set in `netlify.toml` when checking Hugo ?

**Comment by apreshill** [comment]
Good catch! I think it could also make sense to ask to add a todo to use `check_netlify()` if netlify.toml exists, like:

https://github.com/apreshill/blogdown/blob/5fac7af5b3f0c111017afe3616a516046af064ba/R/check.R#L118

**Comment by apreshill** [comment]
(this one doesn't look to ACTUALLY check if netlify.toml exists 🙈 but probably should!)

**Comment by cderv** [comment]
Great ! Are you doing a PR ? or should I ?

**Comment by apreshill** [comment]
I'm stuck in a lot of meetings today, so wouldn't be able to touch until tomorrow at the earliest. If you have time/inclination, please feel free to add!

**Comment by cderv** [comment]
Will do.
BTW check for netlify.toml existence where added in https://github.com/rstudio/blogdown/pull/534
https://github.com/rstudio/blogdown/blob/f596265c7e66a67c5dc39adb3157de02d56c1c36/R/check.R#L104-L116

**Comment by yihui** [comment]
We certainly could add something like:

```diff
diff --git a/R/check.R b/R/check.R
index d8f168d..cbe6fb2 100644
--- a/R/check.R
+++ b/R/check.R
@@ -176,6 +176,10 @@ check_hugo = function() {
     check_todo(sprintf('Set options(blogdown.hugo.version = "%s") in .Rprofile.', cv))
   }
 
+  if (file_exists('netlify.toml')) {
+    check_todo('Also run blogdown::check_netlify()')
+  }
+
   check_done('Hugo')
 }
```

I just wonder how likely it is for users to run `check_hugo()` without running `check_netlify()`. I guess users are far more likely to run `check_site()` to check for everything, than just running `check_hugo()` alone (and consequently fail to catch possible problems with Hugo related to `netlify.toml`).

If we check `netlify.toml` in `check_hugo()`, we need to make sure this task is skipped when running `check_site()`, otherwise the todo doesn't make sense (since it will be automatically done soon). This will add a little bit more complexity to the codebase. If you truly believe this should be added anyway, I'll be okay with it.

**Comment by cderv** [comment]
> I guess users are far more likely to run check_site() to check for everything, than just running check_hugo() alone

I ran `check_hugo` only and not `check_site` when I add issues with the blog 😅 but it is true that the latter will check all. My thoughts: I wanted to check if my hugo version was the issue with the weird rendering so I ran `check_hugo()`. I just thought it would check for Hugo conflict with netlify config but it is not. 

BTW as `check_hugo()` does not check also netlify we got this when running `check_site()`
```r
― Checking Hugo
| Checking Hugo version...
○ Found 4 versions of Hugo. You are using Hugo 0.79.0.
| Checking .Rprofile for Hugo version used by blogdown...
| Hugo version not set in .Rprofile.
● [TODO] Set options(blogdown.hugo.version = "0.79.0") in .Rprofile.
― Check complete: Hugo
― Checking netlify.toml...
○ Found HUGO_VERSION = 0.54.0 in [build] context of netlify.toml.
| Checking that Netlify & local Hugo versions match...
| Mismatch found:
  blogdown is using Hugo version (0.79.0) to build site locally.
  Netlify is using Hugo version (0.54.0) to build site.
● [TODO] Option 1: Change HUGO_VERSION = "0.79.0" in netlify.toml to match local version.
● [TODO] Option 2: Use blogdown::install_hugo("0.54.0") to match Netlify version, and set options(blogdown.hugo.version = "0.54.0") in .Rprofile to pin this Hugo version.
| Checking that Netlify & local Hugo publish directories match...
○ Good to go - blogdown and Netlify are using the same publish directory: public
― Check complete: netlify.toml
````
So first TODO item from `check_hugo` is to set `options(blogdown.hugo.version = "0.79.0")`, but then as there is a HUGO_VERSION in netlify.toml the advice is to install 0.54.0. That is not incompatible but as a not so experienced user with Hugo and Netlify, I would have expected one advice regarding hugo version. 

Anyway, not so critical as indeed it will be more complexity to the codebase. `check_site()` shows everything so you can't really miss.

Thoughts: If `check_site()` is the recommended way for checking everything, wouldn't it be clearer to only have this function exported ? And the other only as internals ? That way, if someone type `check_` and autocomplete, there will only be one choice. What is the benefit of having all check functions exported if `check_site()` is the best to run to have all checks done at once. All the more considering the explanation is only shown in `check_site` 
```r
--------------------------------------------------------------------
○ A successful check looks like this.
● [TODO] A check that needs your attention looks like this.
| Let's check out your blogdown site!
--------------------------------------------------------------------
```

Personally, I wouldn't mind exporting only `check_site` and advice to use only this one.

**Comment by yihui** [comment]
Personally I tend to export `check_site()` only, too. I exported the rest of functions following @apreshill's suggestion: she said that it could be useful to let users/students run the individual check functions when teaching them `check_site()`.

When `check_hugo()` and `check_netlify()` provide conflicting advice on the Hugo version, I don't know what the best option is. Perhaps I'd respect the Netlify setting, especially in the scenario of a website on which multiple authors collaborated (everyone should use the same version of Hugo specified in `netlify.toml`). For a personal website, changing the `HUGO_VERSION` in `netlify.toml` may not be a bad idea, as long as the local preview looks good.

BTW, you probably ran into this problem with our company blog, and I planned to set `blogdown.hugo.version = "0.54.0"` in the `.Rprofile`.

**Comment by cderv** [comment]
Yes it was with this blog and I installed the correct 0.54 version to have it worked correctly. 
New option to pin hugo version will definitely help !

**Comment by apreshill** [comment]
> Personally, I wouldn't mind exporting only check_site and advice to use only this one.

I really like the implementation here! But to answer your question, yes, I think we all probably will use `check_site()` over the others. I have about 3 different user personas in mind here, which (just a guess) estimate would cover like ~80% of users:

1. Total new beginner. May be in a workshop setting, may be following an online tutorial, but we want to help them by not making them feel like they are trying to sip out of a fire hydrant. Help manage their cognitive load for them- introduce checking functions one at a time, help reinforce mental model of each moving piece. At the end, they run `check_site()` and it is clean with no `TODO`s, which feels *good*.
2. False beginner. Tried blogdown before, coming back to it, wants to understand everything from the ground up. Really actually benefits from starting all over again. May like the option to collect the `TODO`s- doesn't want a whole lot of explanation. Doesn't matter too them what feels good or not- they just want to get to the success point quickly.
3. Experienced users (us!). Uses `check_site()`- aren't put off by all the "vocab" terms and have a mental model of all the moving pieces already 😄 

I do still think some way of collecting `TODO`s would be helpful, or alternatively having an option of verbose = `TRUE` or `FALSE` as an argument (maybe if `FALSE`, hide the progress messages- show only success and TODO messages)?

**Comment by cderv** [comment]
> I do still think some way of collecting TODOs would be helpful, or alternatively having an option of verbose = TRUE or FALSE as an argument (maybe if FALSE, hide the progress messages- show only success and TODO messages)?

So it would look like this ? 
```
● [TODO] Update "baseURL" to your actual URL when ready to publish.
○ "ignoreFiles" looks good - nothing to do here!
○ All set! Found the "unsafe" setting for goldmark.
● [TODO] .gitignore was not found. You may want to add this.
○ Found 4 versions of Hugo. You are using Hugo 0.76.5.
○ blogdown is using Hugo 0.76.5 to build site locally.
○ Found HUGO_VERSION = 0.76.5 in [build] context of netlify.toml.
○ It's a match! Blogdown and Netlify are using the same Hugo version (0.76.5).
○ Good to go - blogdown and Netlify are using the same publish directory: public
○ Found 0 files with future publish dates.
○ Found 0 files marked as drafts.
○ All R Markdown files have been knitted.
○ All R Markdown output files are up to date with their source files.
○ Found 0 duplicate .html output files.
○ Found 0 incompatible .html files to clean up.
```
Doesn't loosing the context of each check a bit disturbing ? 

OR just collecting TODO then ? 

````
― Collecting [TODO] items only...
--------------------------------------------------

― Checking config.yaml
● [TODO] Update "baseURL" to your actual URL when ready to publish.

― Checking .gitignore
● [TODO] .gitignore was not found. You may want to add this.

― Checking Hugo

― Checking netlify.toml...

― Checking content files
````

But is having less context really desirable ? 
I find the dark plain dot helpful to quickly see the [TODO] inside the current printed output. It seems to be 

If the aim to make them stand out more, we could also play with ANSI output like **cli** does to also put them in bold. But that would require redo what **crayon** does for detecting ANSI vs non ANSI support (or using i directly). I guess if we go that way that is for later... Example of what it would look like.

* Bold
![image](https://user-images.githubusercontent.com/6791940/103002439-37fc6780-452f-11eb-81de-a708e331e82a.png)

* Color
![image](https://user-images.githubusercontent.com/6791940/103003172-9544e880-4530-11eb-954b-f5be95bd6cfa.png)

**Comment by yihui** [comment]
Using the UTF-8 characters is close to my limit of tolerance, and I feel the solid dots stand out well enough. I'll definitely not use ANSI escape sequences. Once we start with font weight and color, I'm afraid that we might continue with font size, line height, and perhaps GIFs to get users' attention...

![shout out loud](https://im4.ezgif.com/tmp/ezgif-4-c070fc0c20b6.webp)

Collecting TODOs can be certainly useful, but I'd wait for users' request before actually implementing that, although the implementation shouldn't be hard. Usually I tend to be too conservative not to become the "enemy of good" (i.e. perfect). And there is indeed a downside of only printing TODOs as @cderv mentioned, which is we lose the context. Chances are users will run `verbose = TRUE` first to learn what's going on, and then `verbose = FALSE`. Since I feel currently it's not that overwhelming to eyeball the solid dots, I'm not sure if users really want to run `check_site()` twice (once in verbose mode, and once not).

**Comment by cderv** [comment]
I beleive this is the main reason of why **cli** and **crayons** : to handle all this weird cases and to know when or not use ANSI escape sequence. I wouldn't try to redo all this but just use the tool that I know will do the job. 😄 

Nice GIF BTW - It would certainly retain user attention if once in a while this would show up in the RStudio's viewer ! 😉 
````r
htmltools::browsable(htmltools::img(src="https://camo.githubusercontent.com/7872ec3079bb41a1dd525b94826980c702142129e60fa1e41f78b08344e683dd/68747470733a2f2f696d342e657a6769662e636f6d2f746d702f657a6769662d342d6330373066633063323062362e77656270"))
````

**Comment by yihui** [comment]
> I believe this is the main reason of why **cli** and **crayons** : to handle all this weird cases and to know when or not use ANSI escape sequence.

Yes, I know that. The problem is at the philosophical level, instead of tools, i.e., why do such tools exist in the first place? I was basically lamenting at the fact that we often have to use tools to compete for users' attention nowadays, and [people seem to find messages longer than 140 characters unbearably hard to read](https://yihui.org/en/2017/12/twitter-shaped-us/). I shamelessly consider myself an expert in getting people's attention, but I've been intentionally avoiding using the effective techniques that I know whenever possible. This has been the main theme of conflict in my heart in recent years. I'm still trying to find the proper balance.

**Comment by apreshill** [comment]
> Collecting TODOs can be certainly useful, but I'd wait for users' request before actually implementing that, although the implementation shouldn't be hard. 

Makes total sense- I'm excited to use these functions myself in the book and when teaching/troubleshooting. 

FWIW, I'm really pleased with the symbol structure- for completeness, I'll link to an article @cderv found about checkmarks:

> "In Japan[4] and Korea, the O mark is used instead of the check mark"

https://en.wikipedia.org/wiki/Check_mark

The open circle we show for `check_success()` now, and I like how it stands out but doesn't pop out. And the filled in dots for `[TODO]`s do pop out, as intended. *And* we managed to avoid `x` shapes, which always port you back to 5th grade math.
