### ISSUE TITLE
Recommended way to serve the site?

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#543]
I typically use the Add-in to serve the site, and I just noticed that `serve_site()` appears to be an [exported function](https://github.com/rstudio/blogdown/blob/2b1449d0217aa4348aaa6bf9e0b0d5763921a509/R/serve.R#L16-L55).

Yet, when I use the Add-in, this prints to my console:

```
blogdown:::serve_site()
```

But then sometimes when I'm editing a blog post, this prints to my console:

```
blogdown:::preview_site()
```

Reading the actual function definition [here](https://github.com/rstudio/blogdown/blob/2b1449d0217aa4348aaa6bf9e0b0d5763921a509/R/serve.R#L65-L85), I see why they are different. But I was confused. I think we want to encourage `serve_site()` to start? If so, I cannot see where to change where those `:::` print to the console.

**Comment by cderv** [comment]
> if so, I cannot see where to change where those ::: print to the console.

I think this is a RStudio IDE thing. The addin function is defined here: 
https://github.com/rstudio/blogdown/blob/2b1449d0217aa4348aaa6bf9e0b0d5763921a509/inst/rstudio/addins.dcf#L1-L4

and as you see, we just give the function name. 

I think RStudio IDE assumes this function to run addin may not be exported so it uses `:::` to avoid errors. 🤔

**Comment by yihui** [comment]
The answer is you only call `serve_site()`.

`preview_site()` is an internal helper function that you never need to call by yourself. I've tried to hide this call in 59dd8d1d27a48ced30d9df75f1228efee963ed9a. I don't know why it still shows up. I'll investigate more.

**Comment by apreshill** [comment]
Ah gotcha, thank you so much- that helps! I'm working on learning resources and wanted to make sure I understood. Feel free to close  :)

**Comment by yihui** [comment]
We can close this issue after rstudio/rstudioapi#213 is fixed.

I think `:::` was used because that's the safe way to go (albeit confusing sometimes). For an add-in, the IDE cannot assume the corresponding function is exported from a package. No matter if it is exported or not, `:::` works, but if it is not exported, `::` won't work. The IDE should probably try a little harder to check if the function is exported or not, and decide whether to use `::` or `:::` accordingly.

**Comment by cderv** [comment]
> The IDE should probably try a little harder to check if the function is exported or not, and decide whether to use :: or ::: accordingly.

Yes I think so. I'll open an issue in the IDE about that.

**Comment by yihui** [comment]
Instead of waiting for the RStudio bug to be fixed, I just figured out another way to fix this problem. You should no longer see `preview_site()` in the console.

**Comment by cderv** [comment]
Clever solution! That is awesome! 👍
