### ISSUE TITLE
Correcting fig.path errors

### ISSUE THREAD

**Issue by thedivtagguy** [rstudio/blogdown#548]
It would be helpful to include some guides on how to tackle `fig.path` errors. 

I'm currently facing an issue where my `.Rmarkdown` pages are being rendered fine, except I do not see any output being displayed at all. No plots, no tables, nothing. I think somehow, my `fig.path` has been messed up.

The output for the line `knitr::opts_chunk$get('fig.path')` is `## [1] "index_files/figure-html/"`
How do I fix the problem and reset the `fig.path` to default? Currently, I see no output being displayed at all, only code chunks.

My repo is hosted here: https://github.com/thedivtagguy/website if this helps.
Live website deploy: https://thedivtagguy.netlify.app/

**Comment by yihui** [comment]
I think I know what's wrong, but I'd rather have you install the development version (restart R after installation):

```r
remotes::install_github('rstudio/blogdown')
```

and run `blogdown::check_site()`. It should tell you all potential problems of your site.

BTW, it's not relevant to `fig.path`.

**Comment by thedivtagguy** [comment]
You were right! This is what I got: 

```
| Checking setting for Hugo's Markdown renderer...
| You are using the Markdown renderer 'goldmark'.
● [TODO] Allow goldmark to render raw HTML by adding this setting toconfig.yaml(see https://github.com/rstudio/blogdown/issues/447 for more info):

markup:
  goldmark:
    renderer:
      unsafe: true
Do you want blogdown to set this for you? (y/n) y
```
Thank you so much, I've been struggling with for _days_ now. I also read this page [here](https://github.com/rstudio/blogdown/issues/447) that `check_site()` gave me and it makes so much more sense now. I should have installed the development version first!

**Comment by yihui** [comment]
Great to know! You are certainly not the only one who has struggled with this `unsafe` option for long. If only the Hugo developer could be bribed, I'd be happy to mail him a check to change this forever confusing default :)
