### ISSUE TITLE
urls being made lower case

### ISSUE THREAD

**Issue by RobertMyles** [rstudio/blogdown#55]
Hi,

Does blogdown make urls lower case, by any chance? I have some older posts from before I used the package, and the YAML for these has an url parameter. Some of the posts have upper-case letters in them, which doesn't seem to be the case when I build the site using blogdown. 

For example: 
[http://robertmyles.github.io/ElectionsBR.html](http://robertmyles.github.io/ElectionsBR.html) leads to the right url, whereas the url generated by `build_site()` returns a 404 error:
[http://robertmyles.github.io/electionsbr.html](http://robertmyles.github.io/electionsbr.html). 

The YAML for the post in question is: 

``` 
---
title: "Map-making with R and electionsBR"
date: "2016-10-09"
share: true
categories: [R]
excerpt: "Create summaries and analyses using the R package `electionsBR`"
tags: [R, electionsBR, Brazil]
comments: true
url: /ElectionsBR.html
---

```

I had changed my config.toml file to a full url because of Disqus, but I changed it back to "/" and there is no difference (that is another issue that I have only been able to solve with full urls btw, even following the tips in #52). 

Is there someway I can fix this problem? Thanks.

**Comment by yihui** [comment]
blogdown does not touch the URLs. All URLs are generated by Hugo. You can check the Hugo documentation here: https://gohugo.io/overview/configuration/ (search for `disablePathToLower` on the page)

**Comment by RobertMyles** [comment]
Ah ok! Thanks, Yihui.
