### ISSUE TITLE
Just a dead link 

### ISSUE THREAD

**Issue by defuneste** [rstudio/blogdown#553]
Hello,

You have a dead link in this page  : https://bookdown.org/yihui/blogdown/css.html

it is here : 

`In the Hugo framework (https://gohugo.io/tutorials/creating-a-new-theme/), CSS is one of the major “non-content” files that shapes the look and feel of your site (the others are images, JavaScript, and Hugo templates). `

Thx a lot for the great book !

**Comment by yihui** [comment]
I just delete the dead link from that page. Thanks a lot for the report!
