### ISSUE TITLE
Serve site doesn't reliably detect changes in data/ (?)

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#556]
I am not confident about this, but I can show you how to replicate-

1. If you work with this site locally: https://github.com/apreshill/blogophonic

1. Then serve site

1. Make a change here: https://github.com/apreshill/blogophonic/blob/master/data/theme.yaml

Nothing happens, although the preview "blips" for a second. To see the change, I have to clean out my viewer, restart my R session and re-serve the site, and this doesn't even reliably work. But if I push my changes to GitHub, my Netlify deploy preview does work.

**Comment by maelle** [comment]
what happens if you use Hugo directly? (I think I've had this problem before but with hugo)

**Comment by yihui** [comment]
I guess it would be the same if you use the `hugo server` directly. By default, Hugo uses the "fast render" mode, which does not reliably detect changes in all places (I was aware that it at least doesn't watch for new shortcodes added to the `layouts/` directory). That's the tradeoff for fast preview. If you need to fully re-render the site, I think you need [the `--disableFastRender` argument](https://gohugo.io/commands/hugo_server/).

```r
options(blogdown.hugo.server = c('--disableFastRender', '-D', '-F', '--navigateToChanged')
```

**Comment by apreshill** [comment]
Oof. That is hard. I'm surprised as Academic and other sites use `data/` too. I wonder what the actual load time difference might be in practice building locally? It seems like the balance might be better to have a slightly less fast site build time (I'm assuming we are talking about a small difference in performance), vs shorter build time plus adding in frustration and time spent trying to troubleshoot to figure out this special build flag.

**Comment by apreshill** [comment]
I did try adding this- I still seem to need to explicitly call `blogdown::stop_server()` or restart to see a change. 

https://github.com/apreshill/blogophonic/blob/3c0be230238422f57f724802ac767a8a3b436517/.Rprofile#L15

If I re-serve the site, I see:
```
The site has been served under the directory "/Users/alison/rworkshops/blogophonic". I have tried to reopen it for you with servr::browse_last(). If you do want to start a new server, you may stop existing servers with blogdown::stop_server(), or restart R. Normally you should not need to serve the same site multiple times in the same R session, otherwise you may run into issues like https://github.com/rstudio/blogdown/issues/404.
```

**Comment by yihui** [comment]
Sorry I was wrong above. After my testing, the argument `--disableFastRender ` doesn't solve the problem. Hugo does watch for changes in `data/`, but the CSS is not correctly reloaded when I edit `theme.yaml`. I don't know why. This is too complicated to me...

**Comment by apreshill** [comment]
OK- I'll make sure folks restart often then ⏏️

**Comment by yihui** [comment]
This might be a Hugo bug, a corner case that the hugo server failed to consider. I can see that the intermediate CSS is correctly generated in the `resources/` directory, but it is just not reloaded in browser (not even with a hard refresh `Cmd + Shift + R`).

When in doubt, restart :)

![reboot](https://slides.yihui.org/gif/reboot.gif)

**Comment by apreshill** [comment]
To close the loop, I refactored the theme to use parameters from `config` and live preview works immediately now- thank you for helping me troubleshoot!

https://github.com/apreshill/blogophonic/pull/31

**Comment by yihui** [comment]
Great to know!
