### ISSUE TITLE
check_site list both the source and rendered file

### ISSUE THREAD

**Issue by maelle** [rstudio/blogdown#557]
I am currently following https://alison.rbind.io/post/new-year-new-blogdown/ and https://alison.rbind.io/post/2020-12-27-blogdown-checks/. Awesome updates to blogdown!

I got

```r
● [TODO] Found 2 files marked as drafts:

  content/blog/2021-01-04-hi-hugo/index.markdown
  content/blog/2021-01-04-hi-hugo/index.Rmarkdown
```

And I was expecting something like

```r
● [TODO] Found 1 file marked as draft:

  content/blog/2021-01-04-hi-hugo/index.markdown (source content/blog/2021-01-04-hi-hugo/index.Rmarkdown)
```

And I would expect "To un-draft, change a file's YAML from 'draft: true' to 'draft: false'" to mention knitting might be needed.

## Checklist

When filing a _feature request_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] searched for an existing feature request to avoid creating duplicate requests? If you find an existing feature request, please give it a thumbs-up reaction, as we'll use these reactions to help prioritize the implementation of these features in the future.

- [x] provided a clear and concise description of the problem this proposed feature would address? For example, I struggle to do `[...]` with blogdown.

- [x] provided a clear and concise description of what you want to happen?

- [x] provided a clear and concise description of alternative solutions or workarounds you've considered?

- [x] added any other context or screenshots about your feature request?

**Comment by maelle** [comment]
cc @apreshill

**Comment by yihui** [comment]
Thanks for the suggestion! I thought more about it, and just added a helper function. The message looks like this now:

```r
● [TODO] Found 2 files marked as drafts. To un-draft, run the command:

  blogdown::edit_draft(c(
  "content/blog/2021-01-04-hi-hugo/index.markdown",
  "content/blog/2021-01-04-hi-hugo/index.Rmarkdown"
  ))

  and change a file's YAML from 'draft: true' to 'draft: false'
```

If you run this command in RStudio, it will automatically navigate to the `draft` field of each post, so you can edit right away.

> And I would expect "To un-draft, change a file's YAML from 'draft: true' to 'draft: false'" to mention knitting might be needed.

Compared to changing `draft` from `true` to `false`, knitting can be a more complicated and expensive action, so I'd prefer not having users re-knit the posts.

Does that make sense?

**Comment by maelle** [comment]
Yes this makes sense, thank you! 🙂
