### ISSUE TITLE
Checking functions that rely on .Rprofile should prompt to restart R session

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#558]
For example, `usethis` prints:

```
> library(usethis)
> edit_r_profile()
● Modify '/Users/alison/.Rprofile'
● Restart R for changes to take effect
```

I think this should only affect `check_hugo()`? I can offer PR, just wanted to note this as I ran into it while testing.

**Comment by cderv** [comment]
> I think this should only affect check_hugo()? 

yes it seems so. Maybe not make two bullet but add mention of a restart required in the `sprintf`: 
https://github.com/rstudio/blogdown/blob/1aeaa8affceedd492777c103c0666ec2a743e6ab/R/check.R#L178 

.Rprofile is also mention in `check_netlify()`
https://github.com/rstudio/blogdown/blob/1aeaa8affceedd492777c103c0666ec2a743e6ab/R/check.R#L230

However, this option will not really change the behavior of **blogdown** for the current session - but I guess it it expected to have a `check_site()` with no TODO after adding the option in Rprofile ? For that it requires a restart indeed.

**Comment by apreshill** [comment]
Yes, I think as I was using interactively, you want the check to "clear" so it isn't obvious to do. I feel like it needs to be a new bullet that is simple like the usethis message "Restart R for .Rprofile changes to take effect". All the other checks clear without needing a restart, so that one is weird.

**Comment by cderv** [comment]
> BTW, what's our plan to file the feature request to the RStudio IDE to prompt to restart R when users edit .Rprofile? Should this be a single feature request, or do we want to send the IDE team a list? I feel it could be a standalone request, and I guess it should be relatively easy for them to implement.

The plan is to open a standalone issue - fill one issue per request we have. Then we'll send the IDE team a list with all the issues for them to know they matter for us :) There is already a doc for that @apreshill has shared to us.

**Comment by cderv** [comment]
Opened in https://github.com/rstudio/rstudio/issues/8701
