### ISSUE TITLE
Build_Site and Serve_Site Output Issues.

### ISSUE THREAD

**Issue by jonathande4** [rstudio/blogdown#56]
My current workflow is to set my working directory to the the website directory that is created when using the function new_site. Serve_Site works as expected and I can view my work correctly without issue. However, when I use build_site there's a difference that breaks layout. The index.html file will point to the site's main directory rather than the public directory.
 
Here's an example:

*Serve_Site will correctly link to resources:* "./2017/02/15/an-intro-to-gaussian-mixture-modeling/"
*Build_Site adds an extra folder:* "./**jonathande4.github.io**/2017/02/15/an-intro-to-gaussian-mixture-modeling/"

Serve_site still works as I need it to, but it took a couple problematic git commits to understand the issue. I am wondering if others have experienced this issue, or if it's a problem with my usage.

**Comment by yihui** [comment]
You probably set `baseurl = "jonathande4.github.io"` in config.toml, which is not an absolute URL and really should be `"https://jonathande4.github.io/"` instead. I'd recommend `baseurl = "/"`, though, but it depends on the specific theme you use.

**Comment by jonathande4** [comment]
Ah, that is correct! Thank's for the correction. It was a change I made a while back but didn't think to look into.

Thanks for the help!
