### ISSUE TITLE
Hugo academic website showing deleted publications

### ISSUE THREAD

**Issue by eteitelbaum** [rstudio/blogdown#561]
Hello!

I am building my first website using hugo and blogdown. I have modified the `content\publication` directory to include folders with my publications, each of which has its own cit.bib, index.md and featured.jpg file. I also deleted the example folders such as "example-conference-paper" and "example-journal-article." Yet when I compile the website the example conference paper still shows up in my featured section and in my list of publications. I also get a duplicate listing of another publication from 2007. I think this is because I once had a duplicate folder for this publication, but the old folder has been deleted. All of the changes, including the folder deletes, have been committed and pushed to Github and Netlify shows that everything has been properly deployed. 

You can see the problem on the published version of the site: https://www.emmanuelteitelbaum.com. And here is the link to the github repo: https://github.com/eteitelbaum/academic-website). 

I should probably mention that I am using Dropbox to sync my website folder between my three computers. I should also mention that I have tried `hugo mod clean` using the `hugo_cmd()` function as a shot in the dark. It didn't change anything. 

Thanks for your help!

#########
 `xfun::session_info('blogdown')` info:

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363), RStudio 1.3.959

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3  BH_1.72.0.3      blogdown_0.21.78 bookdown_0.21    digest_0.6.27    evaluate_0.14   
  glue_1.4.2       graphics_4.0.2   grDevices_4.0.2  highr_0.8        htmltools_0.5.0  httpuv_1.5.4    
  jsonlite_1.7.2   knitr_1.30       later_1.1.0.1    magrittr_2.0.1   markdown_1.1     methods_4.0.2   
  mime_0.9         promises_1.1.1   R6_2.5.0         Rcpp_1.0.5       rlang_0.4.10     rmarkdown_2.6   
  servr_0.21       stats_4.0.2      stringi_1.5.3    stringr_1.4.0    tinytex_0.28     tools_4.0.2     
  utils_4.0.2      xfun_0.19        yaml_2.2.1      

Hugo version: 0.80.0

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [ X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [ X] included a minimal, self-contained, and reproducible example?

- [ X] pasted the output from `xfun::session_info('blogdown')` in your issue?

- [ X] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [ X] installed and tested your bug with the development version of the blogdown package using `remotes::install_github('rstudio/blogdown')`?

**Comment by yihui** [comment]
I think you ran into a bug that I fixed last month in d232a35e836236139c5eb79835d78988ec523070. Please close your website project in RStudio, open (or restart) _another_ RStudio session, and install the dev version of **blogdown**:

```r
install.packages('xfun', repos = 'https://yihui.r-universe.dev')
remotes::install_github('rstudio/blogdown')
```

Then open the RStudio project of your website, and run `blogdown::check_site()`. It should tell you the solution. Thanks for the report!
