### ISSUE TITLE
Comments on blogdown::check_site()

### ISSUE THREAD

**Issue by llrs** [rstudio/blogdown#564]
I just installed the latest blogdown version `0.21.84`, due to some problems I'm facing serving my site, so I used `blogdown::check_site()` which reported several things to fix. One of those was:

```
Found 1 duplicated plain Markdown and .html output file:

  content/home/project/external-project/index.html

  To fix, run blogdown::clean_duplicates().
```

Which I run:
```
> blogdown::clean_duplicates()
Found possibly duplicated output files. Run `blogdown::clean_duplicates(preview = FALSE)` if you are sure they can be deleted:

  content/home/project/external-project/index.html
```
But as you can see it redirects me to change the argument. I suggest to reword the `check_site` message when checking for duplicates to look at the documentation first or to run directly `clean_duplicates(preview = FALSE)`.

----

Also not sure if the documentation of `check_site()` could be more explicit that it is a way to run all the `blogdown::check_` listed on that help page. But when I run without looking at the documentation. 

----

I got some warnings about `Cannot parse the YAML metadata`, maybe there's a way to check for it or provide hints why it warns about it. I checked with an online YAMLlint and it said it is valid YAML so I suppose that it is something else what I'm doing wrong.

**Comment by yihui** [comment]
Thanks! All three problems are fixed now. Please `remotes::install_github('rstudio/blogdown')` and run `blogdown::check_site()` again. It should tell you the specific problems of YAML metadata.

**Comment by llrs** [comment]
Hi, thanks for the quick changes! 

The duplicate message now is clearer and straight forward.

I think it is not documented that `check_config()` opens the config.toml file and `check_netlify()` opens the netlify.toml (Sorry just realized now). Perhaps just open them if there is something to do on those files? Otherwise it comes up as a surprise and you just need to close them (perhaps add a parameter so if someone wants to check and open it for edit they can). 

With the newest change I don't get any warnings on yaml metadata, even if I haven't changed anything, so I suppose it was a false positive.

**Comment by yihui** [comment]
@llrs Opening files only when necessary is something that I wished to work on in the (near) future. For the record, @cderv has opened a PR #569 for it. Thanks!
