### ISSUE TITLE
issue with new_site on project created by usethis

### ISSUE THREAD

**Issue by cderv** [rstudio/blogdown#565]
I blindly tried to follow 

and stumble upon this after creating a new RStudio project (`usethis::create_project("~/test-blogdown2")`)
```r
> blogdown::new_site(theme = "wowchemy/starter-academic")
― Creating your new site
Error: C:\Users\chris\test-blogdown2 already exists and is not empty. See --force.
Error: C:\Users\chris\test-blogdown2 already exists and is not empty. See --force.
'C:/Users/chris/AppData/Roaming/Hugo/0.79.0/hugo.exe" new site ".' n'est pas reconnu en tant que commande interne
ou externe, un programme ex‚cutable ou un fichier de commandes.
Error in shell(cmd, mustWork = TRUE, intern = intern) : 
  '"C:/Users/chris/AppData/Roaming/Hugo/0.79.0/hugo.exe" new site "." -f yaml' execution failed with error code 1
De plus : Warning message:
In blogdown::new_site(theme = "wowchemy/starter-academic") :
  The directory '.' is not empty
```

I believe this is a quoting issue. 

I'll have a look into it. 

On a more generic matter, I know we use `system2()` extensively in all the ecosystem. On Windows this is not really safe it seems as it has a different behavior than on Unix so I am not surprised by this issue. However, other way of using hugo with blogdown where working up to now. 

I understood that `system()` if more adviced compared to `system2()` or even that `shell()` should be used on Windows to have a similar effect as `system()` on Unix. **processx** and **sys** are their to offer consistent working way on all OS. 

So it is possible our current code is prone to error sometimes for Windows users.

**Comment by cderv** [comment]
Oh no it is just because the `--force` flags is not set 🤕 
Nothing to do with quoting sorry. 

This is because `usethis::create_project("<path>")` will create an empty `R` directory so `force = length(files) == 0` is FALSE.

I was just following @apreshill post for testing: https://alison.rbind.io/post/new-year-new-blogdown/#tldr

@apreshill it seems what you described won't work. Did it work before ? 

@yihui should we support a project created using this function ? 
It would mean testing for an empty R folder and if so, allowing the `--force` flag.

**Comment by yihui** [comment]
Yes, we should. I just fixed it. Thank you!

**Comment by yihui** [comment]
I also added a `force` argument to `new_site()`. By default, it will ask you if you'd like `force = TRUE` so you can create the site anyway in a nonempty dir:

```
> blogdown::new_site()
― Creating your new site
► The directory '.' is not empty. Create the site anyway? (y/n)
```

**Comment by cderv** [comment]
This was my other idea I did not share ! 😃 at first I looked for it. this force argument could be useful! 
Great addition !
