### ISSUE TITLE
maybe not use unicode characters in `yes_no` ? 

### ISSUE THREAD

**Issue by cderv** [rstudio/blogdown#566]
`yes_no()` uses `readline()` and it seems to not handle well Unicode characters on Windows at least. (not like `cat()`)

I got this in R console
```
― The new site is ready
○ To start a local preview: use blogdown::serve_site(), or the RStudio add-in "Serve Site"
○ To stop a local preview: use blogdown::stop_server(), or restart your R session
<U+25BA> Want to serve and preview the site now? (y/n) 
```

Does it print ok for you ? Is this a R console config issue on Windows ?

**Comment by yihui** [comment]
Okay, I felt we would run into this sooner or later on Windows (macOS and Linux should be fine). The unicode characters seem to work with `cat()`. I'll see what I can do. Thanks!

**Comment by yihui** [comment]
Now it will fall back on `>` if `►` is not supported. Thanks!

**Comment by cderv** [comment]
Thanks ! 

I observed that : `cat()` is fine, `print` also, just not `readline`. Not sure which is the difference. 

```r
[usethis-create-proj*] > cat("\u25ba")
►
[usethis-create-proj*] > print("\u25ba")
[1] "►"
[usethis-create-proj*] > readline("\u25ba")
<U+25BA>
[1] ""
```

**Comment by yihui** [comment]
Here is the hope: https://developer.r-project.org/Blog/public/2020/07/30/windows/utf-8-build-of-r-and-cran-packages/

This problem has existed for long, e.g. https://github.com/r-lib/evaluate/issues/59 and many other issues that referenced to it.

**Comment by cderv** [comment]
Thanks for sharing - I understand now. 

So many things in the history of your work ! It is really interesting for me to learn all this. Thanks for taking the time to share it with me, ... with my questions and ideas that you already encountered years ago 😅
