### ISSUE TITLE
blogdown::install_hugo() not work

### ISSUE THREAD

**Issue by yangepi** [rstudio/blogdown#570]
Thanks for the package. 

I am not sure why blogdown::install_hugo() not work on my PC.

> Sys.info()
          sysname           release           version            machine 
        "Windows"          "10 x64"     "build 18363"      "x86-64" 

R version 4.0.3 (2020-10-10)
‘blogdown’ version 1.0

> blogdown::install_hugo()
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  InternetOpenUrl failed: 'An error occurred in the secure channel support'

**Comment by cderv** [comment]
I cannot reproduce. 

Are you connected to internet ? Can you install packages ? 

This should error right ? 
```
xfun::github_releases("gohugoio/hugo", "latest")
```

Can you share the result of `getOption("download.file.method")` ?

**Comment by yihui** [comment]
Alternatively, you may manually download the installer from https://github.com/gohugoio/hugo/releases/ (for your platform, choose `hugo_extended_0.80.0_Windows-64bit.zip`).

Then pass the downloaded file path to `install_hugo()`, e.g.,

```r
blogdown::install_hugo('hugo_extended_0.80.0_Windows-64bit.zip')
```

See `?blogdown::install_hugo` for more info.

That said, it will be great if we can figure out why this problem occurred on your computer, so please provide the info that @cderv asked for above. Thanks!

**Comment by yangepi** [comment]
> I cannot reproduce.
> 
> Are you connected to internet ? Can you install packages ?
> 
> This should error right ?
> 
> ```
> xfun::github_releases("gohugoio/hugo", "latest")
> ```
> 
> Can you share the result of `getOption("download.file.method")` ?

# --------------
Thanks, This is. 
> getOption("download.file.method")
[1] "wininet"

**Comment by yangepi** [comment]
> Alternatively, you may manually download the installer from https://github.com/gohugoio/hugo/releases/ (for your platform, choose `hugo_extended_x.x.x_Windows-64bit.zip`).
> 
> Then pass the downloaded file path to `install_hugo()`, e.g.,
> 
> ```r
> blogdown::install_hugo('hugo_extended_0.80.0_Windows-64bit.zip')
> ```
> 
> See `?blogdown::install_hugo` for more info.
> 
> That said, it will be great if we can figure out why this problem occurred on your computer, so please provide the info that @cderv asked for above. Thanks!

--------------------------
Thank you. 
The weird thing I have is my R 3.6 works with no issue, but when I use R 4.0 the issue comes back. I have both R 3.6 and 4.0

**Comment by cderv** [comment]
I would need some more infos: 
* Can you install packages using your R4.0 installation ? Installing package must download from CRAN and it uses the same method.
* does `xfun::github_releases("gohugoio/hugo", "latest")` works ? 

Usually changing the download method can help, but wininet on windows should work. 
You can try `options(download.file.method = "libcurl")` to see if it changes something.

I don't recall a change in R3.6 vs R4.0 regarding this... 🤔

**Comment by yihui** [comment]
@yangepi It'll be great if you could provide the output of `xfun::session_info('blogdown')` from both versions of R. In particular, I want to make sure you are using the same version of **blogdown** in the two versions of R.

**Comment by yangepi** [comment]
> @yangepi It'll be great if you could provide the output of `xfun::session_info('blogdown')` from both versions of R. In particular, I want to make sure you are using the same version of **blogdown** in the two versions of R.

--------------------------------------
From R4.0.3
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363), RStudio 1.3.1093

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    
system code page: 65001

Package version:
  base64enc_0.1.3 BH_1.72.0.3     blogdown_1.0    bookdown_0.21   digest_0.6.27   evaluate_0.14   glue_1.4.2      graphics_4.0.3  grDevices_4.0.3 highr_0.8      
  htmltools_0.5.0 httpuv_1.5.4    jsonlite_1.7.2  knitr_1.30      later_1.1.0.1   magrittr_2.0.1  markdown_1.1    methods_4.0.3   mime_0.9        promises_1.1.1 
  R6_2.5.0        Rcpp_1.0.5      rlang_0.4.10    rmarkdown_2.6   servr_0.21      stats_4.0.3     stringi_1.5.3   stringr_1.4.0   tinytex_0.28    tools_4.0.3    
  utils_4.0.3     xfun_0.20       yaml_2.2.1     

Hugo version: 0.69.0

--------------------------------------
From R 3.6.3
> xfun::session_info('blogdown')
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363), RStudio 1.3.1093

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3  BH_1.72.0.3      blogdown_0.21.19 bookdown_0.21    digest_0.6.27    evaluate_0.14    glue_1.4.2       graphics_3.6.3   grDevices_3.6.3  highr_0.8       
  htmltools_0.5.0  httpuv_1.5.4     jsonlite_1.7.1   knitr_1.30       later_1.1.0.1    magrittr_1.5     markdown_1.1     methods_3.6.3    mime_0.9         promises_1.1.1  
  R6_2.5.0         Rcpp_1.0.5       rlang_0.4.8      rmarkdown_2.5    servr_0.20       stats_3.6.3      stringi_1.5.3    stringr_1.4.0    tinytex_0.27     tools_3.6.3     
  utils_3.6.3      xfun_0.19        yaml_2.2.1      

Hugo version: 0.69.0

**Comment by yangepi** [comment]
> I would need some more infos:
> 
> * Can you install packages using your R4.0 installation ? Installing package must download from CRAN and it uses the same method.
> * does `xfun::github_releases("gohugoio/hugo", "latest")` works ?
> 
> Usually changing the download method can help, but wininet on windows should work.
> You can try `options(download.file.method = "libcurl")` to see if it changes something.
> 
> I don't recall a change in R3.6 vs R4.0 regarding this... 🤔

----------
> xfun::github_releases("gohugoio/hugo", "latest")
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  InternetOpenUrl failed: 'An error occurred in the secure channel support'


----------
> options(download.file.method = "libcurl")
> xfun::github_releases("gohugoio/hugo", "latest")
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  InternetOpenUrl failed: 'An error occurred in the secure channel support'

**Comment by yangepi** [comment]
> @yangepi It'll be great if you could provide the output of `xfun::session_info('blogdown')` from both versions of R. In particular, I want to make sure you are using the same version of **blogdown** in the two versions of R.

For R4.0.3, it was blogdown_0.21, but I thought the issue may be caused by the version, so I updated it to 1.0. But the issue still exists.

**Comment by yihui** [comment]
@yangepi Does this work in R 4.0.3?

```r
readLines('https://api.github.com/repos/gohugoio/hugo/releases/latest')
```

If it signals the same error, see if this works:

```r
xfun::download_file('https://github.com/gohugoio/hugo/releases/latest', f <- tempfile())
head(readLines(f), 20)
```

**Comment by yangepi** [comment]
> @yangepi Does this work in R 4.0.3?
> 
> ```r
> readLines('https://api.github.com/repos/gohugoio/hugo/releases/latest')
> ```
> 
> If it signals the same error, see if this works:
> 
> ```r
> xfun::download_file('https://github.com/gohugoio/hugo/releases/latest', f <- tempfile())
> head(readLines(f), 20)
> ```
> 
> BTW, this is what I get when I google for the error message: https://stackoverflow.com/a/62708995/559676

--------
It works! I checked SSL 3.0. Also, check the TLS 1.1 and TLS 1.2.

Thank you so much, both @yihui and @cderv
