### ISSUE TITLE
knit forcing preview_site

### ISSUE THREAD

**Issue by Athanasiamo** [rstudio/blogdown#572]
I just updated to the latest blogdown to check out the new features, and for me its having some unexpected effects.

With the newest version I am experiencing in my opinion somewhat aggressive and unwanted blogdown behaviour.
1. manually knitting no longer keeps md as specified in the yaml
2. manually knitting starts `preview_site`

Nr. 1 _just_ found a solution to, but since it was quite hidden I'm going to write it here anyway, in case someone else is struggling with something similar. Since the change in `method` my workaround specifying in the yaml `keep_md: yes` was ignored. After some trial an error I found that setting `options(blogdown.method = "markdown")` in `.Rprofile` now renders md rather than html (which is what I wanted with my workaround, thank you, now I can scrap that!). Adding `blogdown.knit.on_save = FALSE` to the options was also a great relief to me.  

Nr. 2 makes actually working on the site within RStudio quite annoying, since I already use `hugo serve` in the terminal I end up having two localhosts of the same site running (and I'd prefer keep using the terminal explicitly). Is there a way to choose this to not happen through some unknown option? I would rather not have my manual knitting starting a daemon (which in my opinion is quite unexpected behaviour when manually kntting. I also cannot see the standard R Markdown knitting information in the R markdown pane that I would usually see).

```r
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7, RStudio 1.4.869

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3 BH_1.75.0.0     blogdown_1.1.1  bookdown_0.21   digest_0.6.27  
  evaluate_0.14   glue_1.4.2      graphics_4.0.2  grDevices_4.0.2 highr_0.8      
  htmltools_0.5.1 httpuv_1.5.5    jsonlite_1.7.2  knitr_1.30      later_1.1.0.1  
  magrittr_2.0.1  markdown_1.1    methods_4.0.2   mime_0.9        promises_1.1.1 
  R6_2.5.0        Rcpp_1.0.6      rlang_0.4.10    rmarkdown_2.6   servr_0.21     
  stats_4.0.2     stringi_1.5.3   stringr_1.4.0   tinytex_0.28    tools_4.0.2    
  utils_4.0.2     xfun_0.20       yaml_2.2.1     

Hugo version: 0.76.5
```

**Comment by yihui** [comment]
> 1\. manually knitting no longer keeps md as specified in the yaml

How did you specify that exactly? i.e. what's in your YAML?

> 2\. manually knitting starts `preview_site`

I didn't expect this use case (i.e. having another hugo server running separately), but I could certainly provide an option to disable that. BTW, may I know why you prefer starting hugo in the terminal instead of using `blogdown::serve_site()`? I'm hoping to also address the problem you had, in addition to providing an option to disable the automatic preview. Thanks!

**Comment by Athanasiamo** [comment]
My yaml has this:

````
output:
  html_document:
    keep_md: yes
````

But from my tests today, this part of the yaml seems completely ignored by blogdown (i.e. I could change the output document type to pdf_document, or md_document, or omit the output document specification as a whole and blogdown would anyway render with html)

There are several reasons I like running `hugo serve` in the terminal
1.  I like seeing the hugo terminal output as new stuff is rendered, and see what site changes it has listened to and implemented. 
    - for instance, if I am working on adaptations to sass/scss/css it listens and implements these 
2. I find it easier to start and stop the daemon when I want, and to have it running in the foreground so I cannot forget it is running (I'm terrible at closing instances, so I can end up having a blogdown hugo server running without knowing because I have not closed the Rproj)
3. I am working on a site that uses the config-folder option of hugo, rather than a single config file, I believe this is not supported for blogdown 
4. I generally use the terminal in RStudio (or terminal it self) for a lot of my work
    - I also do this for git, for instance. I never use the git pane in RStudio, I'm too used to the terminal.

**Comment by Athanasiamo** [comment]
I can see why for many, the running of `preview_site()` might be a blessing when inadvertently knitting while creating a blogdown post when that is not part of their workflow. For me, personally, I really dont like it when an action I am used to (here: knitting) results in something completely different happens (here: starting a hugo daemon).

I think having an option to turn this off, with a warning when this is triggered the first time in an instance letting users know how to turn it off through an option (or whatever system you prefer) would be ideal.

**Comment by yihui** [comment]
For the first problem, any output formats specified in the YAML (such as `html_document`) are always ignored. This worked before **blogdown** v0.21, but it only worked by chance. Previously, the only way to generate Markdown output from R Markdown was to use the file extension `.Rmarkdown`. Now, you have a second option, which is what you mentioned: `options(blogdown.method = "markdown")`. We also mentioned this in the announcement the other day: https://blog.rstudio.com/2021/01/18/blogdown-v1.0/#better-support-for-markdown-format

For the second problem:

1. If you want to see the hugo terminal output, you may set `options(blogdown.server.verbose = TRUE)`.
2. The daemon started by `serve_site()` will be automatically stopped when you quit R. With the verbose option in 1, I guess it'll be hard for you to forget that a hugo server is running.
3. That problem should be relatively easy to fix and I did plan to fix it since that is what the hugo academic author has been complaining about blogdown for long.
4. Good to know.

Anyway, I'll definitely provide an option to disable the automatic preview. Thanks!

**Comment by Athanasiamo** [comment]
Thank you for being swift in replying. 

I guess I can sum up my way of working in that I prefer using the R console for only R-things, and stuff that are actually other programs (git, hugo etc) I prefer running in the terminal.

1. thanks for the tip! I'd like to bump Mäelle's request in #365 on having a full list of all blogdown options that are available. 
2. this might indeed help
3. I dont think there is a rush on this, but atleast for multilignual sites, the config-folder has really helped make the config tidier (and more obvious what language specific config options must be created for new language support)
4. I'm not likely to change this way of working, even given the three things above being resolved :P 

I'll look forward to the option to turn off the preview. I really do love this package.

**Comment by yihui** [comment]
Thanks! You have `options(blogdown.knit.serve_site = FALSE)` now :)

Re: the full list of blogdown options, we will definitely document them in the **blogdown** book. In the meantime, RStudio can autocomplete the option names after you type `options(blogdown.`:

![image](https://user-images.githubusercontent.com/163582/105227489-01623e80-5b27-11eb-89ad-192e78638148.png)

**Comment by Athanasiamo** [comment]
thanks. That does the trick, no more previews initiated. 

This is on a related note, The R markdown pane still looks very different than normal knitting, anyway to get it to output more standard knitting information? (this is a wish, not a necessity, I am a creature of habit and enoy watching the verbose knitting in the pane)

**Comment by yihui** [comment]
Sure. I'll support that in a minute.

**Comment by yihui** [comment]
Done. Thanks for the suggestion!

**Comment by Athanasiamo** [comment]
honestly, you are a magician. Thank you. Everything now acts like I am expecting it too and I am _very_ satisfied!

**Comment by yihui** [comment]
It's my honor to serve a **blogdown** VIP (I should say, VVVIP)! 🙇

**Comment by apreshill** [comment]
Ah this is a life-saver. For reference, I was just experiencing intense pain with this when trying to include xaringan slides in `static/` inside a blogdown site. I would explicitly turn off blogdown serve site, but every time I knit a single xaringan deck, my whole site would preview, and I couldn't preview the slides. Excited to see this option to turn that off.

**Comment by yihui** [comment]
@apreshill With a proper Hugo template ([like xaringan's](https://github.com/yihui/xaringan/blob/master/inst/rmarkdown/templates/xaringan/resources/default.html)), I think it's  possible to render xaringan slides in `content/`. The key is to use the [page variable](https://gohugo.io/variables/page/#page-variables) `.RawContent`. I have never tested this myself, though.
