### ISSUE TITLE
config.toml

### ISSUE THREAD

**Issue by mcSamuelDataSci** [rstudio/blogdown#573]
Based on a couple great presentations from the wonderful conference yesterday/today, I decided to make a website using blogdown etc. Just getting started, and I can eventually work everything out, but right in the beginning of your documentation (which you note may be out of date) there is reference to the config.toml file.  No such file is generated as far as I can see. config.yaml and netlify.toml are generated.  Am I doing anything wrong, or should I just proceed with your documentation but using those files?
Thanks.

**Comment by cderv** [comment]
ˋconfig.yaml` is the file you are looking for. 

Chapter here mentions it https://bookdown.org/yihui/blogdown/configuration.html

The options are the same only the syntax is different. 

Thanks for the feedback! We'll be clarifying this while updating the book. 

BTW this blog post is a great intro to start a blog https://alison.rbind.io/post/new-year-new-blogdown/

**Comment by mcSamuelDataSci** [comment]
Thank you!
