### ISSUE TITLE
new_post() with bundle archetype does not work

### ISSUE THREAD

**Issue by maelle** [rstudio/blogdown#577]
My issue might be related to #436 

We had a setup where using the New Post add-in worked, for creating a leaf bundle with a post called index.Rmd, and now it longer does.

Here's a repo reproducing the behavior https://github.com/maelle/addintest 
* I created a blogdown website from RStudio menu
* I tweaked the .Rprofile a bit

```r
options(blogdown.new_bundle = TRUE)
options(blogdown.subdir = "post")
options(blogdown.title_case = TRUE)
```

* I added an archetype https://github.com/maelle/addintest/blob/master/archetypes/Rmd/index.md
* I ran `blogdown::new_post("lala", ext = ".Rmd", kind ="Rmd/")`
    * Hugo creates the post https://github.com/maelle/addintest/tree/master/content/post/2021-01-28-lala
    *  :bomb: 
    
    ```r
	  Error in file(con, "r") : impossible d'ouvrir la connexion
	  De plus : Warning messages:
	  1: In file(con, "r") :
	    'raw = FALSE' but '/home/maelle/Documents/ropensci/addintest/content/post/2021-01-28-lala' is not a regular file
	  2: In file(con, "r") :
	    cannot open file '/home/maelle/Documents/ropensci/addintest/content/post/2021-01-28-lala': it is a directory
	  Backtrace:
	   1. blogdown::new_post("lala", ext = ".Rmd", kind = "Rmd/")
	   2. blogdown::new_content(file, kind, FALSE)
	   3. blogdown:::hugo_convert_one(file2)
	   6. base::readLines(file, 1)
	   7. base::file(con, "r")
   ```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] used `blogdown::check_site()` function to verify your current project and followed all advices ?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('blogdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the blogdown package using `remotes::install_github('rstudio/blogdown')`?

**Comment by yihui** [comment]
The `new_post()` didn't work, and it was also a bug indeed.

The "New Post" addin worked, but it shouldn't have, because `new_post()` was buggy. It was also bug.

Now both bugs should be fixed. Thanks for the report!

**Comment by maelle** [comment]
Yay, thank you! :rocket:
