### ISSUE TITLE
Add option to configure site root directory 

### ISSUE THREAD

**Issue by wjakethompson** [rstudio/blogdown#581]
I am creating a blogdown website for an upcoming workshop. My GitHub repository is structured similar to the [Introduction fo Machine Learning in the Tidyverse](https://github.com/rstudio-conf-2020/intro-to-ml-tidy) repository from rstudio::conf(2020). That is, blogdown source files are in the `site/` sub-directory and other materials for the workshop are in the `materials/` directory. However, when blogdown source files are not in the project working directory, the Serve Site addin fails because it does not know to look in a subdirectory. It would be useful to have an option that could be added to the project's `.Rprofile` that could specify the site root (e.g., `options(blogdown.site_root = "site/")`).

It seems like this could be accomplished by changing the definition of `blogdown::serve_site()` to 

```r
serve_site = function(..., .site_dir = getOption(blogdown.site_root, default = NULL))
```

https://github.com/rstudio/blogdown/blob/7399df2637686a98f665520abca2d15fba0d0151/R/serve.R#L41

This would (I think) preserve the current behavior for any user where the the `blogdown.site_root` option is unspecified, but would allow users to specify a different directory if desired.

Following discussion with @cderv on [RStudio Community](https://community.rstudio.com/t/blogdown-serve-site-from-subdirectory/94658) there are a few alternative solutions, all with some drawbacks. The first is use the Knit button in RStudio. This now serves the site; however, this requires you to first have an `.Rmd` or `.Rmarkdown` file open. If you just open the project, or are working on another file (e.g., `config.toml`), the Knit button is not available to you. A second option is to add `setwd("site")` to the `.Rprofile`. This is my current workaround, as it makes the addin work correctly. However, it feels a bit icky to set my working directory to be different from the project directory (and I'm a little afraid Jenny Bryan might come and set my laptop on fire :smile:).

If the proposed solution is acceptable, I'd be happy to submit a PR with this change.

## Checklist

When filing a _feature request_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] searched for an existing feature request to avoid creating duplicate requests? If you find an existing feature request, please give it a thumbs-up reaction, as we'll use these reactions to help prioritize the implementation of these features in the future.

- [x] provided a clear and concise description of the problem this proposed feature would address? For example, I struggle to do `[...]` with blogdown.

- [x] provided a clear and concise description of what you want to happen?

- [x] provided a clear and concise description of alternative solutions or workarounds you've considered?

- [x] added any other context or screenshots about your feature request?

**Comment by yihui** [comment]
That sounds reasonable. Now you can set `options(blogdown.site_root = "site/")` in your `.Rprofile`. Thanks for the suggestion!

`setwd()` is not a stigma. The fire joke might have gone too far to be misunderstood... I think the points were: 1) don't `setwd()` to an absolute directory that only exists on your own computer, otherwise other people won't be able to run your code; 2) you'd better reset the working directory after you are done, i.e., `owd = setwd('new_dir'); do the work; setwd(owd)` (or better, use `on.exit()`). As long you understand the consequence of `setwd()`, I don't think Jenny will set your laptop on fire. I use `setwd()` all the time (properly, I think), without a fire extinguisher by my side.
