### ISSUE TITLE
Install theme not unzipping theme files in theme directory

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#582]
I'm trying to install a theme into an existing blogdown site.

To repro:

use RStudio project wizard to create a new blogdown site with the default theme.

Then run:
```
library(blogdown)
install_theme(theme ="hugo-apero/hugo-apero", update_config=FALSE, theme_example = FALSE, force = TRUE)
```

I see this in my `themes/` folder:

<img width="507" alt="Screen Shot 2021-02-02 at 5 15 05 PM" src="https://user-images.githubusercontent.com/12160301/106669827-3e442180-657a-11eb-9a06-21db34a58369.png">

And the actual theme files are dumped into the root directory of my website R project. See:

https://github.com/apreshill/hugothemeinstall

```
> xfun::session_info('blogdown')
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.7, RStudio 1.4.1103

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3   BH_1.75.0.0       blogdown_1.1.7    bookdown_0.21    
  digest_0.6.27     evaluate_0.14     glue_1.4.2        graphics_3.6.1   
  grDevices_3.6.1   highr_0.8         htmltools_0.5.1.1 httpuv_1.5.5     
  jsonlite_1.7.2    knitr_1.31        later_1.1.0.1     magrittr_2.0.1   
  markdown_1.1      methods_3.6.1     mime_0.9          promises_1.1.1   
  R6_2.5.0          Rcpp_1.0.6        rlang_0.4.10      rmarkdown_2.6.6  
  servr_0.21.1      stats_3.6.1       stringi_1.5.3     stringr_1.4.0    
  tinytex_0.29      tools_3.6.1       utils_3.6.1       xfun_0.20        
  yaml_2.2.1       

Hugo version: 0.79.0
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] used `blogdown::check_site()` function to verify your current project and followed all advices ?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('blogdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the blogdown package using `remotes::install_github('rstudio/blogdown')`?

**Comment by yihui** [comment]
`install_theme()` assumes that a theme contains a `theme.toml` file (to differentiate real themes with modules like those from wowchemy), which the apero theme doesn't have. I'll think more about what to do in this case.

**Comment by apreshill** [comment]
Aha- that was on my to do list- just didn't occur to me that the installer needed that!
