### ISSUE TITLE
Figures are not correctly shown in Post on RStudio server

### ISSUE THREAD

**Issue by cderv** [rstudio/blogdown#587]
@apreshill mentioned this post https://datawookie.dev/blog/2021/02/setting-up-postref-shortcode-for-remote-blog/ that seems to indicate that the fix for #501 that introduced the custom shortcodes (11fec4c7d59234596501c36ceece72c5f6d2a0a0) is not working as expected on rstudio server.

The issue is described in the post above : 

> The default content for postref.html is
> 
> `{{ .Page.Permalink }}`
>
> With this in place the image path looks like this:
> 
> `<img src="//localhost:4321/blog/test/index_files/figure-html/unnamed-chunk-3-1.png">`

This can be reproduce on RStudio Cloud or on a remote rstudio server.

Was the change aiming to solve only #501 ? Because it is not clear to me what was exactly the issue... 

@yihui are you aware of this ?

I don't know if this is something related to Permalink vs RelPermalink (seems [the later is more used / recommended ](https://discourse.gohugo.io/t/page-permalink-relpermalink-difference/22975) ?)

It could also be an issue in rstudio server that is not correctly translating the url - maybe not handling correctly the `//localhost` ? 

Example: 
````r
> rstudioapi::translateLocalUrl("//localhost:4321/blog/test/index_files/figure-html/unnamed-chunk-3-1.png")
[1] "//localhost:4321/blog/test/index_files/figure-html/unnamed-chunk-3-1.png"
> rstudioapi::translateLocalUrl("localhost:4321/blog/test/index_files/figure-html/unnamed-chunk-3-1.png")
[1] "localhost:4321/blog/test/index_files/figure-html/unnamed-chunk-3-1.png"
> rstudioapi::translateLocalUrl("https://localhost:4321/blog/test/index_files/figure-html/unnamed-chunk-3-1.png")
[1] "p/58ed3c21/blog/test/index_files/figure-html/unnamed-chunk-3-1.png"
````

I think having our package works on rstudio cloud could be nicer to user. But as it as not been reported a lot, it seems everyone is using **blogdown** locally - or not a lot of rstudio server pro user are using **blogdown**

**Comment by yihui** [comment]
> Was the change aiming to solve only #501 ? Because it is not clear to me what was exactly the issue...

Not only #501, but also image paths in RSS feeds (https://github.com/rstudio/blogdown/issues/384#issuecomment-752315702). I'm all for using relative links, and personally I use relative links whenever possible. However, some RSS parsers are just not smart enough to figure out how to resolve relative links in posts. The prominent example is R-bloggers, and this problem has been reported several times before.

I'm okay with changing `.Permalink` to `.RelPermalink`, but this could be a breaking change to other users, too (they may complain that images in RSS stopped working).

> It could also be an issue in rstudio server that is not correctly translating the url

Yes, it could be. It'll be great if you can ask the RStudio IDE team.

---

As I was typing the reply, it occurred to me that I could conditionally use `.Permalink` to `.RelPermalink` based on an environment variable, i.e., if the env var indicates that it's RStudio Server, use relative links, otherwise use full links. I'll try it in a moment.

**Comment by apreshill** [comment]
As is, no figures produced by R show up inside the actual posts on RStudio Cloud:

<img width="1439" alt="Screen Shot 2021-02-10 at 8 19 39 AM" src="https://user-images.githubusercontent.com/12160301/107532685-25e09200-6b8c-11eb-8285-9c97a794e06a.png">
<img width="1439" alt="Screen Shot 2021-02-10 at 7 33 06 AM" src="https://user-images.githubusercontent.com/12160301/107532703-2aa54600-6b8c-11eb-91e6-3572dec0a2e6.png">

**Comment by yihui** [comment]
Should be fixed now. Could you test the dev version? Thanks a lot!

```r
remotes::install_github('rstudio/blogdown')
```

**Comment by apreshill** [comment]
Just tested with lithium, looks like it is fixed

![Uploading Screen Shot 2021-02-10 at 11.09.54 AM.png…]()

**Comment by cderv** [comment]
Fixed with `hugo-prose` also for figures. It shows correctly on RStudio server.

**Comment by apreshill** [comment]
Also works out of the box on Netlify: https://ecstatic-elion-a9b7d7.netlify.app/2020/12/01/hello-r-markdown/

**Comment by datawookie** [comment]
Thanks for fixing this so quickly, @apreshill, @cderv and @yihui. You are all amazing!

**Comment by cderv** [comment]
Thanks for the report @datawookie ! Rather hidden on the web 😉 but we are following closely twitter so it helps 😄 Thanks @apreshill for mentioning the blog post! 

@datawookie do not hesitate to open an issue next time you found an expected behavior !

**Comment by FranciscoPiccolo** [comment]
Hello, this issue can also support users with the same problems but not on Rstudio Server?

I'm facing the same problem where my images are no longer being displayed.

https://github.com/FranciscoPiccolo/franciscopiccolo.github.io

I've already installed the new version of blogdown. Maybe I'm missing something. 

Thanks in advance,

**Comment by cderv** [comment]
Hi @FranciscoPiccolo, 

Can you open a new issue with your specific case ? The problem described here was specific to RStudio server at the time and has been fixed. Your issue could be cause by anything that has been done in the meantime. 

I can't even open your website (blank index page) so it is not only a figure issue it seems. 

Please, open a new issue and follow the issue guide (specifically run the `check_site()` function) thanks. 

In case you missed it, here the blog post for v1.0 https://blog.rstudio.com/2021/01/18/blogdown-v1.0/

Thanks!

**Comment by FranciscoPiccolo** [comment]
Ok, I'll do it, thank you @cderv
