### ISSUE TITLE
More Jekyll support? 

### ISSUE THREAD

**Issue by luispuerto** [rstudio/blogdown#589]
Welcome to the blogdown GitHub repo 👋

Thanks for taking the time to file a feature request! Please start by searching for an existing feature request to avoid creating duplicate requests. If you find an existing feature request, please give it a thumbs-up reaction, as we'll use these reactions to help prioritize the implementation of these features in the future.

Hey! 

I know you already are offering some jekyll support, but it would be great if blogdown could operate equally on Jekyll and on Hugo. 

I think Jekyll has improve speed a lot lately and it deserve some love. I checked how long would take my Jekyll blog to build on a simple Hugo template and the speed was more or less the same. A lot of people already have a jekyll blog and it's difficult to change to Hugo when you already have a workflow and a template you like. 

## Checklist

When filing a _feature request_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] searched for an existing feature request to avoid creating duplicate requests? If you find an existing feature request, please give it a thumbs-up reaction, as we'll use these reactions to help prioritize the implementation of these features in the future.

- [x] provided a clear and concise description of the problem this proposed feature would address? For example, I struggle to do `[...]` with blogdown.

- [x] provided a clear and concise description of what you want to happen?

- [x] provided a clear and concise description of alternative solutions or workarounds you've considered?

- [x] added any other context or screenshots about your feature request?

**Comment by cderv** [comment]
Thanks for opening this feature request. For reference, the jekyll support is described in https://bookdown.org/yihui/blogdown/jekyll.html

> I know you already are offering some jekyll support, but it would be great if blogdown could operate equally on Jekyll and on Hugo.

Do you have a wish-list in mind ? What are the painpoint ? What is missing for a good experience ? 
Are you already using **blogdown** with you Jekyll website ? 

Having more details in a feature request is very welcome to appreciate the expectation and know more about the use case. 

Thank you !

**Comment by tcgriffith** [comment]
A plus is that gh pages supports jekyll pretty well so it's good for users that want to deploy their sites in an all-in-one platform

**Comment by luispuerto** [comment]
@cderv I don't have an incredible wist list, but you can trim it down to basically have the same support for Jekyll and for Hugo. 

I really like Jekyll, it's native to github so a lot of people starts just with Jekyll and then stay there. The community is really thriving now and if you can't do something with what is coming out of the box you can always can find or either an extension or someone has done it before. I understand that performance isn't that great as with Hugo, but sometimes people doesn't mind performance, not to mention that Jekyll has improved a lot on version 4. Not to mention that there is much more themes in Jekyll than on Hugo. I don't really know why. 

Right now, there is only two functions —`serve_site()` and `stop_server()`— that work with Jekyll and all the rest are working just with Hugo. Also, the server site and the script to transform the `.Rmd` to just `.md` files uses the command `jekyll` while I really think it would be much better to use `bundle exe jekyll`. I've tried to change on the build script and I haven't succeed. 

On my really specific case I want to give a try to Hugo and I'm going to to try to port my theme to Hugo because I really like my theme and I've working on it for long time and I'm not going to just throw away all that work. Besides, I haven't found a theme that really appealed to me on Hugo. 

I really understand that you are't going to support every static blog generator out there, but Jekyll is one of the most used with Hugo and Hexo and the support should be equal.

**Comment by yihui** [comment]
> I really think it would be much better to use `bundle exe jekyll`

This has been made possible in the **blogdown** 1.10: https://github.com/rstudio/blogdown/releases/tag/v1.10

Please feel free to file new issues if you want other improvements on the Jekyll support. Thanks!
