### ISSUE TITLE
Relationship of Blogdown to R Markdown Websites

### ISSUE THREAD

**Issue by tinyheero** [rstudio/blogdown#59]
Recently, I watched the presentation on "Making Websites in R" (https://www.rstudio.com/resources/videos/making-websites-with-r/) and have been investigating "blogdown". One particular question I have is the relationship of the blogdown workflow to the current workflow of [making websites using rmarkdown](http://rmarkdown.rstudio.com/rmarkdown_websites.html). 

Is the "overall vision" to replace the current workflow with the blogdown workflow?  To give this more context, I use R markdown websites to string together many different analyses and organize cancer patient reports into one website. Blogdown appears, at first glance, to be more tailored towards "blogging". As such, I am unsure of whether it will be suited for my use cases. Will these "two workflows"  run in parallel or is the plan for blogdown to supersede the current R Markdown website workflow?

**Comment by yihui** [comment]
The major drawback of R Markdown websites is that you can only have a flat directory of Rmd files (all Rmd's under the root directory). Other drawbacks include no RSS feeds, no taxonomies (categories, tags, ...), no way to define permanent links, ... 

Blogdown is for general-purpose websites. It is pretty much a superset of R Markdown websites, and it is not only for blogging. For example, I'm using it for my personal blogs (e.g. https://yihui.name/en/ and https://yihui.name/cn/) and documenting of certain packages (e.g. https://yihui.name/knitr/, https://yihui.name/formatR/, and https://yihui.name/rlp/...). 

There is no plan to deprecate R Markdown websites, and it depends on what you really need. If you just have a handful of Rmd files and would like to link them together (typically through a top menu bar), you can probably just use R Markdown websites. The learning curve should be relatively flat if you are familiar with R Markdown. Blogdown is based on Hugo, which opens up a lot of possibilities, and of course, the more you want, the more you need to learn. In short, there is a "ceiling" for R Markdown websites, and you can do pretty much whatever you want with blogdown + Hugo (there are a few subtle features missing compared to R Markdown websites such as the floating TOC).

**Comment by tinyheero** [comment]
Thanks for the reply. Makes sense to me. I think I will continue to use R markdown websites for my bioinformatics projects, but will plan on switching my personal blog over to using blogdown. 

Great work on blogdown and every other thing you make (i.e. bookdown, DT, rmarkdown)!

**Comment by DjanerEmin** [comment]
A short follow up question on Yihui's answer. I noticed floating TOC is not implemented in blogdown. Is there a way to build it in at a later stage or is there a comparable work around? I liked this feature because it is an easy way to make side menu.
