### ISSUE TITLE
Margin along sides of post disappear after adding section heading.

### ISSUE THREAD

**Issue by austinwpearce** [rstudio/blogdown#591]
**Describe the bug**
Margin along sides of post disappear after adding section heading. I don't think it is the theme, but maybe it is just a problem with the interactions between blogdown and newer version of hugo or markdown flavors.

**To Reproduce**
- Create site using `CaiJimmy/hugo-theme-stack` as theme in blogdown in RStudio.
- Create new post.
- Add body text.
- Render site/page.
- Then add a section heading in the middle of the post.
- Render site again, at which point the margins disappear.

**Expected behavior**
- I would expect that after a section heading, the body text and images would still have a margin.

**Screenshots**

The body text above the section heading preceding the first heading of the post, but after the section heading, the margins disappear.

![image](https://user-images.githubusercontent.com/44807050/108600564-d5282080-7365-11eb-83d6-f1c5ef858f5a.png)

**Desktop (please complete the following information):**
Windows 10
Chrome 88
Hugo 0.81
Latest blogdown version
Latest RStudio version

**Additional context**
Site rendered with blogdown package in RStudio. This behavior is likely not due to the theme choice, as the theme demo page shows posts with margins all the way through even after section headings.

**Comment by austinwpearce** [comment]
I heard back from the Hugo theme creator. He said:

> That's probably something related to Blogdown's Markdown render engine, it should wrap text inside <p> tag.
> 
> hugo-theme-stack/assets/scss/partials/layout/article.scss
> 
> Lines 192 to 195 in 96db925
> 
>  & > p { 
>      margin: 1.5em 0; 
>      padding: 0 var(--card-padding); 
>  }

**Comment by yihui** [comment]
Thanks! I just submitted a fix to the theme: https://github.com/CaiJimmy/hugo-theme-stack/pull/162

**Comment by austinwpearce** [comment]
Works! We all appreciate your responsiveness and attention to details. Thanks, @yihui.
