### ISSUE TITLE
TOC no longer generated

### ISSUE THREAD

**Issue by plantarum** [rstudio/blogdown#599]
## Checklist

Have you:

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [X] used `blogdown::check_site()` function to diagnose your site and corrected potential problems?

- [X] included a minimal, self-contained, and reproducible example?

- [X] pasted the output from `xfun::session_info('blogdown')` in your issue?

- [X] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [X] installed and tested your bug with the development version of the blogdown package using `remotes::install_github('rstudio/blogdown')`?

# Bug?

TOC no longer renders for posts.

# Steps to reproduce

```
new_site()
``` 

Add the TOC option to the YAML header of "Hello R Markdown":

```
title: "Hello R Markdown"
author: "Frida Gomam"
date: 2020-12-01T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
output:
  blogdown::html_page:
    toc: true
```

```
serve_site()
```

Serve the site. The rendered html doesn't have a table of contents, but I think it should. I've tried rebuilding with `build_site()`, still no TOC.

I noticed this when rebuilding my site and a page that previously had a TOC no longer did. I hadn't changed the header, so I suspect something might have changed in updating to a new blogdown version recently? I'm not sure.

```
xfun::session_info('blogdown')
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Locale:
  LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
  LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
  LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
  LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C            
  LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3   BH_1.75.0.0       blogdown_1.2.1    bookdown_0.21    
  digest_0.6.27     evaluate_0.14     glue_1.4.2        graphics_4.0.4   
  grDevices_4.0.4   highr_0.8         htmltools_0.5.1.1 httpuv_1.5.5     
  jsonlite_1.7.2    knitr_1.31        later_1.1.0.1     magrittr_2.0.1   
  markdown_1.1      methods_4.0.4     mime_0.10         promises_1.2.0.1 
  R6_2.5.0          Rcpp_1.0.6        rlang_0.4.10      rmarkdown_2.7    
  servr_0.21        stats_4.0.4       stringi_1.5.3     stringr_1.4.0    
  tinytex_0.30      tools_4.0.4       utils_4.0.4       xfun_0.22        
  yaml_2.2.1       

Hugo version: 0.76.4

```

**Comment by cderv** [comment]
Hi, 

it is working for me for same version 1.2.1

1. Create a new RStudio project 
2. Call `blogdown::new_site()` in the empty directory - site is created, site is served, Rmd is opened
3. Add toc option in Rmd file - and rebuild the Rmd file
4. Preview is updated and I saw a toc.

In step 3, be sure to rebuild the Rmd file. It can be build on save if you use this behavior, otherwise just use the knit button. 

I let you check that. I don't see any issue in **blogdown** currently

**Comment by plantarum** [comment]
I don't use RStudio. Can you tell me what function the `knit` button calls?

**Comment by cderv** [comment]
Oh sorry. I did not catched that. 

Do you have `options("blogdown.knit.on_save")` being set to FALSE in your project , 
By default in should not be, and saving the Rmd file should trigger a build of the Rmd file to HTML, then the preview should update. You can set it to TRUE to be sure to have this behavior by default.

About the knit button, when you click on it in RStudio it will `rmarkdown::render_site('<path to rmd file>')`. You could use that directly and this should mimic the button behavior. But this is how the IDE does for all website generator. For **blogdown**, you can call [`blogdown::build_site()`](https://pkgs.rstudio.com/blogdown/reference/build_site.html) to build your project.  For preview with serve_site, `blogdown::build_site(local = TRUE, run_hugo = FALSE, build_rmd = <path_to_rmd_file>)` will do the job. 


Usually you build a Rmd file using  `rmardkown::render()`, but doing so you'll miss some blogdown features (like relative url set).

So for outside of RStudio use, relying on the Knit on Save behavior is the easiest. Does this not work for you ?

**Comment by cderv** [comment]
BTW I tested outside of RStudio (in VSCODE) and this works correctly: 

* File is build when I serve the site
* When I save the Rmd, file is rebuild (`blogdown.knit.on_save = TRUE`, is correctly set in the .Rprofile created by `new_site()`
*

**Comment by plantarum** [comment]
It's still not working for me. I'm working in Emacs.

I have done:

Open R in the directory created by `new_site()`.

```
blogdown::build_site(local = TRUE, run_hugo = FALSE, build_rmd = TRUE)
serve_site()
```

(I've also tried setting build_rmd to the path to the file in question, same result)

The default option to knit-on-save works as expected, at least after I start serving the site.

The header looks like this:

```
---
title: "Hello R Markdown"
author: "Frida Gomam"
date: 2020-12-01T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
output:
    blogdown::html_page:
        toc: true
---

I've added and removed a few lines in the first section, to confirm that these changes are included in the rendered page after `knit-on-save`. They are. Also, I see that a TOC div is created, but it's empty. The contents of index.html are:

```
---
title: "Hello R Markdown"
author: "Frida Gomam"
date: 2020-12-01T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
output:
    blogdown::html_page:
        toc: true
---


<div id="TOC">

</div>

...
```

**Comment by plantarum** [comment]
After checking, I see that the TOC div is present (but empty) in `content/post/2020-12-01-r-rmarkdown/index.html`, but it is not present in `public/2020/12/01/hello-r-markdown/index.html`.

**Comment by yihui** [comment]
I can't reproduce this problem. What's your `rmarkdown::pandoc_version()`?

For non-RStudio users, normally all you need is `blogdown::serve_site()` in the beginning. Then you only need to edit and save Rmd files. You should get the preview immediately after save, unless you have set `options(blogdown.knit.on_save = FALSE)`. You don't need `blogdown::build_site()` unless you want to manually publish the `public/` directory to a web server.

**Comment by plantarum** [comment]
Thanks for checking. I think that's the problem!

rmarkdown::pandoc_version()
[1] ‘1.19.2.4’

I updated directly from the pandoc website, now running 2.12. I 
forced a rebuild of all pages, and the problem is gone! My TOC 
have returned.

Strange, because I had TOC before, using the previous Pandoc 
version. Maybe I didn't notice a Pandoc version change in the 
Ubuntu repo?

Anyways, problem fixed.

Thanks to both of you!

**Comment by cderv** [comment]
I did not thought about Pandoc version.  That is good to know! 
That is definitely something that could cause differences when you are not using the Rstudio IDE because it ships with one version. 

Glad we found the source of issue. Thanks !

**Comment by yihui** [comment]
I see. We are using the Pandoc template variable `$table-of-contents`, which is supported by Pandoc >= v2.x only: https://github.com/rstudio/blogdown/blob/f324246c8a5ae72b9cd7c6d5b2eac3b65187652a/inst/resources/template-minimal.html#L21

**Comment by cderv** [comment]
interesting. **rmarkdown** default templates still use `$toc$` which seems to backward compatible, even if still not advice.
> Use table-of-contents for contents of toc, make toc a boolean (#2872). Changed markdown, rtf, and HTML-based templates accordingly. This allows you to set toc: true in the metadata; this previously produced strange results in some output formats. For backwards compatibility, toc is still set to the toc contents. But it is recommended that you update templates to use table-of-contents for the toc contents and toc for a boolean flag.

From: https://pandoc.org/releases.html#pandoc-2.0-2017-10-29

**Comment by yihui** [comment]
@cderv Right. We will need to switch to `$table-of-contents$` someday, unless there exists a way to check the Pandoc version or tell if a variable exists inside a Pandoc template, which I don't think is possible (you can't differentiate between a nonexistent variable and a variable that takes an empty string).

```
$if(table-of-contents)$
$table-of-contents$
$else$
$toc$
$endif$
```

This will fail in a future version of Pandoc for the case in which the TOC is empty (e.g. the document doesn't have any headers) and the variable `toc` is a boolean flag.

**Comment by cderv** [comment]
Pandoc MANUAL still only document the `toc` variable though...
https://pandoc.org/MANUAL#variables-set-automatically
> toc
>    non-null value if --toc/--table-of-contents was specified 

> unless there exists a way to check the Pandoc version or tell if a variable exists inside a Pandoc template, which I don't think is possible (you can't differentiate between a nonexistent variable and a variable that takes an empty string).

I don't know of a way either. I would have said a Lua filter could have help us to check Pandoc version and sets the correct variable, but Lua filter if for Pandoc 2.x only too, so it won't help. Only supporting Pando 2.x sometime could be an option 😅 
Or have a template for Pandoc < 2.x that won't move anymore. 🙄 

I wonder if we could do the other way around: use `$toc$` in our template for blogdown which will work with old version and use a Lua filter in Pandoc 2.x to set `toc` variable to `table-of-content` variable content, but not sure we can access from Lua filter. Anyway, a bit complex.

> This will fail in a future version of Pandoc for the case in which the TOC is empty (e.g. the document doesn't have any headers) and the variable toc is a boolean flag.

You mean what they remove the backward compatibility ? Maybe this won't happen at all. 😉

**Comment by yihui** [comment]
That's probably too much effort to support Pandoc 1.x. I'd rather have users upgrade to Pandoc 2.x instead (if upgrading is not possible, we can reconsider this in the future).

**Comment by cderv** [comment]
Yes, fine with me !
