### ISSUE TITLE
build_rmd = "newfile" build a file it should not

### ISSUE THREAD

**Issue by cderv** [rstudio/blogdown#602]
`build_site(build_rmd = "newfile")` was failing because it was trying to render a file it should not have. There's an Rmd in my content that will not knit on a CI because of interactivity issues (using the rorcid pkg), so I really dont want blogdown to try to knit it on GHA. And that specific Rmd does already have a companion  so I dont know why the command was trying to render it also, something it locally was not attempting. So I dont know exactly what was happening there.

_Originally posted by @Athanasiamo in https://github.com/rstudio/blogdown/issues/459#issuecomment-801236528_

**Comment by cderv** [comment]
Hi @Athanasiamo, 

I moved the discussion here to isolate from the previous issue. 


Can you try 
```r
blogdown::filter_newfile(files = blogdown:::list_rmds())
```
it should return the filename of every Rmd file that does not have an output. 

Also can you share the name of this file and its output ? 

It should be 
* Source file: `myfile.Rmd`
* Output file: `myfile.md` ( when using `method = "markdown"`) as I think you are based on what you share in #459)

Is this what you have ? 

Thanks.

**Comment by yihui** [comment]
I can't reproduce the problem:

```r
options(blogdown.method = 'markdown')

d = tempfile()
dir.create(d)
xfun::in_dir(d, {
  blogdown::new_site(sample = FALSE, serve = FALSE)
  # create a new post
  p = blogdown::new_post('Test new file', ext = '.Rmd')
  # create the .md output file
  m = xfun::with_ext(p, '.md')
  file.create(m)
  # print the list of Rmd files that don't have .md output files
  blogdown::filter_newfile(files = blogdown:::list_rmds())
})
## character(0)

# unlink(d, recursive = TRUE)
```

`filter_newfile()` returns an empty vector as expected. Similarly, this won't build the new Rmd post:

```r
xfun::in_dir(d, {
  blogdown::build_site(build_rmd = 'newfile')
})
```

If I remove the `.md` file, then the `.Rmd` will be rebuilt:

```r
file.remove(m)
xfun::in_dir(d, {
  blogdown::build_site(build_rmd = 'newfile')
})
```

```
Rendering content/post/2021-03-24-test-new-file/index.Rmd... Done.
Start building sites … 

                   | EN  
-------------------+-----
  Pages            | 12  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     | 11  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 20 ms
```

My guess is that `options(blogdown.method = 'markdown')` (presumably set in `.Rprofile`) was not recognized in @Athanasiamo's case, but I don't know how that could happen.

**Comment by cderv** [comment]
@Athanasiamo, in case you missed this issue. 
We would like to check again to confirm is this is a real issue or not.

Thank you !

**Comment by Athanasiamo** [comment]
I've not had opportunity to double check, but will try to stake out time in the weekend. In all likelihood, there was something amiss with my git repo (ie. i did sometihng weird in the commits). I'll let you know as soon as I can.

**Comment by Athanasiamo** [comment]
ok, sorry for the delay. I can confirm I did something weird in my commits that made this happen. Does not seem to be an acutal bug, just my git skills :P

**Comment by cderv** [comment]
And that is one less potential bug ! 🎉  Thanks for confirming this. I'll close this now.
