### ISSUE TITLE
Support for Hugo PostCSS pipes in serve_site()

### ISSUE THREAD

**Issue by y1zhou** [rstudio/blogdown#604]
Processing CSS files with PostCSS is [a Hugo feature](https://gohugo.io/hugo-pipes/postcss/) and is commonly used in many themes. The current version of `blogdown` can handle these correctly in `build_site()`, but with `serve_site()` the CSS files don't get processed/generated.  `serve_site()` itself doesn't raise any warnings, but the following error shows up when inspecting the served site with developer tools:

```
Refused to apply style from 'http://127.0.0.1/css/dark.min.9477587f47bdf0c88ea884fa9606aace3416502e6e4700ba25be1f37ae822a60.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

Could it be because `serve_site()` is not correctly finding `postcss`, `postcss-cli` and `autoprefixer` in `PATH`? I haven't read much of the source code yet so as of now I'm not sure how this could be fixed. Thanks for the great work! Apart from this issue everything else works perfectly for my setup.

## Session info
```
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS, RStudio 1.4.1106

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
  LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3   BH_1.75.0.0       blogdown_1.2      bookdown_0.21     digest_0.6.27     evaluate_0.14     glue_1.4.2        graphics_4.0.4    grDevices_4.0.4  
  highr_0.8         htmltools_0.5.1.1 httpuv_1.5.5      jsonlite_1.7.2    knitr_1.31        later_1.1.0.1     magrittr_2.0.1    markdown_1.1      methods_4.0.4    
  mime_0.10         promises_1.2.0.1  R6_2.5.0          Rcpp_1.0.6        rlang_0.4.10      rmarkdown_2.7     servr_0.21        stats_4.0.4       stringi_1.5.3    
  stringr_1.4.0     tinytex_0.29      tools_4.0.4       utils_4.0.4       xfun_0.21         yaml_2.2.1       

Hugo version: 0.82.0
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] used `blogdown::check_site()` function to diagnose your site and corrected potential problems?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('blogdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the blogdown package using `remotes::install_github('rstudio/blogdown')`?

**Comment by yihui** [comment]
I've never used this feature by myself. Looking at the error message, I don't know why the port number was lost, i.e.,

```
http://127.0.0.1/css/dark.min.9477587f47bdf0c88ea884fa9606aace3416502e6e4700ba25be1f37ae822a60.css
```

should be something like

```
http://127.0.0.1:4321/css/dark.min.9477587f47bdf0c88ea884fa9606aace3416502e6e4700ba25be1f37ae822a60.css
```

I feel it is unlikely to be a `PATH` issue. If `build_site()` can find these tools, `serve_site()` should also be able to.

**Comment by y1zhou** [comment]
@yihui Sorry for the confusion -- the port number is there, and I just replaced the `<ip>:<port>` with 127.0.0.1 because I'm developing on a remote machine and didn't want to expose the IP address.

After further inspection, the CSS files *are* built. If I visit `http://127.0.0.1:4321` directly instead of the proxied site from `servr`, then the stylesheets work fine. Could it be `servr` not proxying those CSS files somehow?

**Comment by y1zhou** [comment]
Fixed it! Probably something wrong with the way the relative URL is generated in my theme. The template is something like this:

```html
{- $light_theme := $light_theme | minify | fingerprint | resources.PostProcess -}}
<link rel="stylesheet" type="text/css" href="{{- $light_theme.RelPermalink -}}"
    integrity="{{ $light_theme.Data.Integrity }}" media="(prefers-color-scheme: light)">
```

But the `.RelPermalink` was still generating a absolute URL (`/css/light...`), which caused `servr` not being able to proxy the correct path to the CSS file. Changing the `href` to 

```
href="{{- relURL $light_theme.RelPermalink -}}"
```

fixed the issue. The link looks like `.//css/light...` which seems to work for `servr`.

**Comment by yihui** [comment]
Good to know. Thanks for posting the solution!
