### ISSUE TITLE
update_meta_addin() error in attribute checks

### ISSUE THREAD

**Issue by brshallo** [rstudio/blogdown#605]
I am getting the following error when trying to use `blogdown:::update_meta_addin()` on any of my blog posts:

```r
blogdown:::update_meta_addin()
#> Error in if (!is.null(value) && value) inputTag$attribs$checked <- "checked" : 
#>   missing value where TRUE/FALSE needed
```

Seems like could also be an issue with {shiny}...

Link to blog at [brshallo/brshallo](https://github.com/brshallo/brshallo).

Session Info:
```{r}
xfun::session_info('blogdown')
#> R version 3.5.1 (2018-07-02)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19042), RStudio 1.4.1106
#> 
#> Locale:
#>   LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
#>   LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
#>   LC_TIME=English_United States.1252    
#> 
#> Package version:
#>   base64enc_0.1.3   BH_1.75.0.0       blogdown_1.2.2    bookdown_0.21    
#>   digest_0.6.27     evaluate_0.14     glue_1.4.2        graphics_3.5.1   
#>   grDevices_3.5.1   highr_0.8         htmltools_0.5.1.1 httpuv_1.5.5     
#>   jsonlite_1.7.2    knitr_1.31        later_1.1.0.1     magrittr_2.0.1   
#>   markdown_1.1      methods_3.5.1     mime_0.10         promises_1.2.0.1 
#>   R6_2.5.0          Rcpp_1.0.6        rlang_0.4.10      rmarkdown_2.7    
#>   servr_0.21        stats_3.5.1       stringi_1.5.3     stringr_1.4.0    
#>   tinytex_0.30      tools_3.5.1       utils_3.5.1       xfun_0.22        
#>   yaml_2.2.1       
#> 
#> Hugo version: 0.75.0
```

## Checklist

Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] used `blogdown::check_site()` function to diagnose your site and corrected potential problems?

- [ ] included a minimal, self-contained, and reproducible example?
- **(is not minimal)** 😞 -- tried isolating parts of .Rprofile and "layouts/_default/single.html" but did not fix and have no real idea what is causing so just sent link to repo (and adopted heuristic of "if you've spent more than 10 minutes trying to solve, ask for help")

- [x] pasted the output from `xfun::session_info('blogdown')` in your issue?

- [ ] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?
- **(updated all relevant packages, and IDE, but not version of R)** 😞

- [x] installed and tested your bug with the development version of the blogdown package using `remotes::install_github('rstudio/blogdown')`?

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report! You can install the development version via

```r
remotes::install_github('rstudio/blogdown')
```

Remember to restart R.
