### ISSUE TITLE
No config.toml

### ISSUE THREAD

**Issue by ogansser** [rstudio/blogdown#606]
When I create a new project with "Website using blogdown", there is a possibility to remove "convert all metadata to yaml". Then there is no config.toml. Instead there is a config.yaml.

**Comment by cderv** [comment]
The parameter for keeping `config.toml` is `new_site(format = "toml")` which is different from `new_site(to_yaml = FALSE)` that `"convert all metadata to yaml"` is selecting. The latter means to convert all post metadata headers to YAML if they are TOML (e.g in example site). 

The former about the config file is not available in the menu yet so it defaults to YAML but we could add a selector. 

Thanks for the suggestion
