### ISSUE TITLE
Shortcodes

### ISSUE THREAD

**Issue by ogansser** [rstudio/blogdown#608]
Hi, after updating to blogdown 1.2 my shortcodes des not work anymore. 

In config.yaml:
enableInlineShortcodes: true

In Rmd: 
{{< youtube ZJthWmvUzzc >}}

**Comment by yihui** [comment]
I can't reproduce your problem:

![image](https://user-images.githubusercontent.com/163582/113938627-7a853f80-97c0-11eb-852c-c21c611228fd.png)

Could you provide a reproducible example as requested by the issue guide (which you deleted)?

**Comment by ogansser** [comment]
OK, may be it is the theme which I use.

**Comment by yihui** [comment]
If you can come up with a reprex with your theme, we can also investigate it.

**Comment by ogansser** [comment]
Meanwhile I found out that the videos can only be included in md files via shortcode. But I have Rmd files.

With the new version ofblogdown 1.2 the posts as rmd don't work anymore either. Doctype in the html fileil is missing. Thus the colour theme and the country code is not accepted.

**Comment by ogansser** [comment]
If I go back to version 0.2 everything works fine.

**Comment by yihui** [comment]
> If I go back to version 0.2 everything works fine.

Do you mean 0.2 (zero point two) or 0.20 (zero point twenty)?

Again, do you have a reprex anywhere? Without a reprex, it's really hard to tell what the problem is. In my above example, I was also using `.Rmd` and not `.md`, which worked fine.

**Comment by yihui** [comment]
Please see https://github.com/rstudio/blogdown/issues/610#issuecomment-818264346.
