### ISSUE TITLE
Build a hugo website on github

### ISSUE THREAD

**Issue by mousieur-g** [rstudio/blogdown#61]
I am not familiar with Hugo and the github page.After I create a new Hugo website local via Rstudio IDE, how can  I upload the files onto github and build a website on it ?

**Comment by yihui** [comment]
We are working on the documentation starting from this week. 

Deploying through Github pages is a little complicated for beginners. If you cannot wait for the documentation, you can go ahead and try https://www.netlify.com where you could just drag and drop a folder there, and your website can be published in a few seconds.

**Comment by znmeb** [comment]
Netlify also has a command-line deployment capability - requires "npm" to run it though.

**Comment by mousieur-g** [comment]
Thanks, I will try Netlify and also look forward to your further work on hugo !

**Comment by yihui** [comment]
There is no need to use the command lines and I don't recommend using command lines, either. Netlify support continuous deployment from Github. More in the book: https://bookdown.org/yihui/blogdown/deployment.html

**Comment by coatless** [comment]
With GitHub Pages support for the `/docs` folder directly within the main repository, netlify is not necessarily needed. 

You can add in the `config.toml` the following line:

```
publishDir = "docs"
```

Then, within the repository settings for GitHub pages, scroll to the “GitHub Pages” section, under the “Source” menu select “master branch /docs folder.

For more details -- in addition to a branching option -- see: https://gohugo.io/tutorials/github-pages-blog/

**Comment by yihui** [comment]
Reasons why I no longer recommend Github pages: https://yihui.name/en/2017/06/netlify-instead-of-github-pages/
