### ISSUE TITLE
support config dir

### ISSUE THREAD

**Issue by Athanasiamo** [rstudio/blogdown#611]
Hi.

I have a website running well in hugo that wont run with blogdown currently.
its a complex site with multilingual features, so I've opted to use the [hugo config dir](https://gohugo.io/getting-started/configuration/#configuration-directory) rather than a single config file in order to keep the config more tidy. 

The config dir is currently not supported in blogdown, so I wanted to get a feel for if/when y'all would have the time to look at that. 

I guess, the ideal situation would be something that autodetects the config folder (lke hugo does) or an option to specify that config is in a folder rather than a single file. Either of these options would make sense to me. Default would anyway be a single file, since I think 99% of users have simpler setups.

## Checklist

When filing a _feature request_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [X] searched for an existing feature request to avoid creating duplicate requests? If you find an existing feature request, please give it a thumbs-up reaction, as we'll use these reactions to help prioritize the implementation of these features in the future.

- [X] provided a clear and concise description of the problem this proposed feature would address? For example, I struggle to do `[...]` with blogdown.

- [x] provided a clear and concise description of what you want to happen?

- [x] provided a clear and concise description of alternative solutions or workarounds you've considered?

- [x] added any other context or screenshots about your feature request?

**Comment by yihui** [comment]
The next CRAN release will be v1.3, which will happen in the next few days. I'm hoping to implement this in v1.4. This is something I have wished to support for a long time. Thanks!

**Comment by Athanasiamo** [comment]
sounds great @yihui . Let me know if you would need input/assistance on this.

**Comment by maelle** [comment]
I'd be interested in this feature too. :smile_cat: (:wave: Hugo friend @Athanasiamo :grin: )

**Comment by yihui** [comment]
I said v1.4 last time? And it's November now? Okay, I'm going to try it seriously this time. I guess this shouldn't be too hard. You just need to push me harder (and you are welcome to).

**Comment by maelle** [comment]
One pleading emoji a day? :wink: Just kidding, thank you!

**Comment by yihui** [comment]
Should be fixed now (https://github.com/rstudio/blogdown/blob/main/NEWS.md#new-features). Please help with testing the development version:

```r
remotes::install_github('rstudio/blogdown')
```

Thanks a lot!

**Comment by maelle** [comment]
Thank you, yes I was able to serve rOpenSci website with blogdown!

**Comment by Athanasiamo** [comment]
THank you @yihui ! I am able to serve the RLadies dev website with blogdown!

**Comment by yihui** [comment]
Great! I'll make a new CRAN release this week (hopefully in one day or two). Thanks for the confirmation!
