### ISSUE TITLE
[FR] Make it easier for users to shrink image sizes

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#614]
I would love a function way to do this, built into blogdown, since I struggle with this all the time!

I also have been looking at: https://jmablog.github.io/tinieR/

Also I know this is important: https://bookdown.org/yihui/rmarkdown-cookbook/optipng.html

It would be cool to offer a way to do this based on regex, like all resize & optimize all images in `content/*thumbnail*` 😉 

Similar to: [`hugodown::use_tidy_thumbnail()`](https://hugodown.r-lib.org/reference/use_tidy_post.html)

**Comment by yihui** [comment]
That's a good idea. I used to manually optimize images. I'll look into tinieR. Thanks!

**Comment by cderv** [comment]
For pure shrinking of the size for optimization (like tinieR if I understand correctly), I believe `xfun::optipng()` does it correctly but it is targeted to a whole directory.  `webshot::shrink()` or future `webshot2::shrink()` (they are the same) is another option for _optipng_. 

For resizing there is also, `webshot2::resize()` (or `webshot::resize()`) . They are using system requirement though GraphicsMagick or ImageMagick.

I think we could make one version based on **magick** package.

**Comment by yihui** [comment]
Simply shrinking an image to the desired dimension (i.e. resizing) is easy. Optimizing image losslessly is hard. I just did some quick testing and https://tinypng.com seems to be quite decent in reducing the file size of both PNG and JPG images.

**Comment by yihui** [comment]
The development version of **xfun** has a function `xfun::shrink_images()` now:

```r
remotes::install_github('yihui/xfun')
```

If you call it with the argument `tinify = TRUE`, this function will both resize images (using **magick**) and compress them (using TinyPNG, which requires an API key to be set up). This is briefly documented in the **blogdown** book: https://bookdown.org/yihui/blogdown/useful-resources.html#file-optimization More detailed documentation is on the help pages `?xfun::shrink_images` and `?xfun::tinify`. Thanks!
