### ISSUE TITLE
Quotes become U+201C in HTML generated files

### ISSUE THREAD

**Issue by linogaliana** [rstudio/blogdown#617]
I use blogdown to generate a website with some custom shortcodes to generate some nice boxes. 

You can find an example at the bottom of the page [there](https://linogaliana-teaching.netlify.app/git/introgit/) which is based on a shortcode [here](https://github.com/linogaliana/hugo-theme-techdoc/blob/fe335552659b86640934a14672ba547b6c69931b/layouts/shortcodes/panel.html) that is called like that in a Rmd file (sorry  English speaking people, that's a copy-paste of French content but the text does not matter) :

```r
{{% panel status="tip" title="Tip" icon="fa fa-lightbulb" %}}
`Git` a été conçu, initialement pour la ligne de commande. Il existe
néanmoins des interfaces graphiques performantes
et pratiques, notamment lorsqu'on désire comparer deux versions d'un même
fichier côte à côte. Ces interfaces graphiques couvrent la majorité des
besoins quotidiens. Néanmoins, pour certaines tâches, il faut nécessairement
passer par la ligne de commande.
{{% /panel %}}
```

Up to now, I was knitting the files in local to get the `.md` and committing directly the `.md` file, letting GHA actions build the website from `.md`. I am trying to improve my continuous integration setup by only committing the `.Rmd` file and stop committing the `.md` file. 

This is the point where I noticed a difference.

**I created a MWE [here](https://github.com/linogaliana/blogdown-MWE) to illustrate the problem**. This is the basic blogdown project with an additional shortcode that is used in [this file](https://github.com/linogaliana/blogdown-MWE/blob/master/content/post/2020-12-01-r-rmarkdown/index.Rmd#L40-L47)

When I use `blogdown::build_site(local = TRUE, build_rmd = TRUE)` on the MWE, I end up with the following error:

```r
got positional parameter 'fa-lightbulb'. Cannot mix named and positional parameters
```

It seems weird because I explicitly use named parameters. So I tried removing the names and I got a new error:

```r
unrecognized character in shortcode action: U+201C 'â€œ'. Note: Parameters with non-alphanumeric args must be quoted
```

I looked at the HTML generated by `blogdown:::build_rmds`. I think I found the responsible: `"` becomes `“` (U+201C). This makes hugo fail (because hugo needs quoted named parameters and things between U+201C are not recognized as quoted values).

Is there a way to prevent this `"` -> `“` transformation ?

PS: `blogdown` is a very nice package. As you might have seen, I use it for a `Python` website ! 🐍 

## Environment

`xfun::session_info('blogdown')`

```r
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363), RStudio 1.4.1103

Locale: LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                   LC_TIME=French_France.1252    

Package version:
  base64enc_0.1.3 BH_1.72.0.3     blogdown_1.3.1  bookdown_0.21.4 digest_0.6.25   evaluate_0.14   glue_1.4.1      graphics_4.0.2  grDevices_4.0.2
  highr_0.8       htmltools_0.5.1 httpuv_1.5.4    jsonlite_1.7.0  knitr_1.31      later_1.1.0.1   magrittr_1.5    markdown_1.1    methods_4.0.2  
  mime_0.9        promises_1.1.1  R6_2.4.1        Rcpp_1.0.5      rlang_0.4.10    rmarkdown_2.7.4 servr_0.22      stats_4.0.2     stringi_1.4.6  
  stringr_1.4.0   tinytex_0.23    tools_4.0.2     utils_4.0.2     xfun_0.22       yaml_2.2.1     

Hugo version: 0.64.1
```
 
## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] used `blogdown::check_site()` function to diagnose your site and corrected potential problems?

- [x] included a minimal, self-contained, and reproducible example?

- [ ] pasted the output from `xfun::session_info('blogdown')` in your issue?

- [ ] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the blogdown package using `remotes::install_github('rstudio/blogdown')` ?

**Comment by yihui** [comment]
Two solutions:

1. https://bookdown.org/yihui/blogdown/content.html#shortcode
2. Put your shortcode between ````` ````{=html}````` and ````` ```` `````.

Both solutions should prevent Pandoc from touching your shortcode, and leave it to Hugo.

**Comment by cderv** [comment]
> Up to now, I was knitting the files in local to get the .md and committing directly the .md file, letting GHA actions build the website from .md. I am trying to improve my continuous integration setup by only committing the .Rmd file and stop committing the .md file.

Just to add that by changing workflow (from ".Rmd -> .md" to ".Rmd -> .html"), you also are changing the tools use for conversion and rendering of the site. If you aim at generating `.html` as usual with Rmd file, Pandoc will be used and you need to have special care when you use Hugo only markdown feature (like shortcodes). 

You can follow the book for this as said ☝️ , and also you have some insight about this workflow thing in our last blog post https://blog.rstudio.com/2021/01/18/blogdown-v1.0/

Hope it helps

**Comment by yihui** [comment]
Yes, converting `.Rmd` to `.md` (instead of `.html`) is the third solution.

**Comment by linogaliana** [comment]
Thanks to both of you for your quick answer. I will adapt one of the suggested solutions.
