### ISSUE TITLE
Clicking on knit button with rmd file causes rmd to not be treated right by blogdown

### ISSUE THREAD

**Issue by johngoldin** [rstudio/blogdown#62]
I was trying to diagnose a problem with my rmarkdown file so I clicked on the knit button to see if it would successfully knit the file. It did. Then when I did serve_site discovered it would
not correctly process that rmd file. I reproduced this with the sample rmd that comes with the
default install. It looks like knit button causes an html file to be created in such a way that subsequent serve_site does not properly handle it. A stand alone knit includes the figure in the html file while serve_site creates a separate folder in the blogdown folder. The separate folder in the blogdown folder doesn't get created once the html is created by a standalone knit.

version is blogdown 0.0.21

(I don't know much about html so I don't really know how things work when the figure is included in the html file.)

I tried to search for this problem in issues, but there are so many I wasn't sure this isn't a duplicate. (In general I am getting real work done with blogdown.)

**Comment by yihui** [comment]
Should be fixed now. Please reinstall from Github. Thanks for the report!
