### ISSUE TITLE
All posts page been group into one page call Posts in blogdown-v1.0 

### ISSUE THREAD

**Issue by TonyFly3000** [rstudio/blogdown#622]
How could I display all the post on the main page like it used to ? 

Before, all post will be display on the main page.
![image](https://user-images.githubusercontent.com/40748234/116543445-757b6200-a920-11eb-9545-099583a2e2ef.png)

After I updated new blogdown package , all  posts page been group into one page call Posts in the main page.
![image](https://user-images.githubusercontent.com/40748234/116543369-5da3de00-a920-11eb-8c57-fac6c240e390.png)

After click The Posts,it will show  all the post
![image](https://user-images.githubusercontent.com/40748234/116543388-65fc1900-a920-11eb-9166-3b1f9e375624.png)

Thank you.

**Comment by cderv** [comment]
What is the theme you are using ? This could be link to how your themes behave. 

I believe this could be linked with Page bundle Hugo feature (https://blog.rstudio.com/2021/01/18/blogdown-v1.0/#page-bundles) but not sure - new blogdown will default to page bundle but only for new post unless you ran a conversion. 

Can you share a repo for your site ? it would be helpful.
What is the folder structure in `contents/` folder ? 

Also please run `blogdown::check_site()` to have some advices, if not done already: 
https://blog.rstudio.com/2021/01/18/blogdown-v1.0/#checking-functions

Thanks

**Comment by TonyFly3000** [comment]
Thanks for the reply.I am using hugo themes blackburn. I still can not find the reason behind.
I just recreate a new blogdown project with this themes and the problem solved and I start to immigrate old blog to new one.
For example copy all file/picture from folder [public] to folder[content].
