### ISSUE TITLE
md5sum_filter changed without notice

### ISSUE THREAD

**Issue by kelseygonzalez** [rstudio/blogdown#627]
Raising this since I didn't see it mentioned anywhere else:

A while back I added some options to my .Rprofile in my blogdown site based on recommendations from @apreshill in a workshop, which included the following:
```
options(blogdown.hugo.version = "0.79.0", # fix Hugo version
        blogdown.knit.on_save = FALSE, 
        blogdown.files_filter = blogdown:::md5sum_filter,  # fixes date issues
        # other nice to haves!
        blogdown.title_case = TRUE,
        blogdown.initial_files = FALSE,
        # nice defaults!
        blogdown.new_bundle = TRUE,
        blogdown.warn.future = TRUE,
        blogdown.draft.output = FALSE)
```

When I went to render my website today, I kept getting the following error:
```
Error in options(blogdown.hugo.version = "0.79.0", blogdown.knit.on_save = FALSE,  : 
  object 'md5sum_filter' not found
```

In the intervening months, it seems that `md5sum_filter` changed to now be `filter_md5sum`. This will likely be an issue for anyone who was calling on that old internal function and since it took me a while to figure out what was going on (hard to find anything on it as it's not an exported function!) I thought it was worth posting here.

**Comment by yihui** [comment]
> I thought it was worth posting here.

Yes, much appreciated!

> In the intervening months, it seems that `md5sum_filter` changed to now be `filter_md5sum`

Yes, it was renamed in blogdown 1.0. If you want to learn any changes in different versions of a package, the NEWS file is usually the best place to look at: https://github.com/rstudio/blogdown/blob/master/NEWS.md

It was first renamed with a deprecation message: https://github.com/rstudio/blogdown/commit/a831653b0eb4c3305eda57704fe5d947ce216169#diff-60bef5af43a1bd541299ce9bceeb226afb23deaa5e637b145c85e05ffd552b0cR185 and then removed in blogdown 1.1.

Finally, may I know what problem you were trying to solve with this option? I feel it should be rare that someone would really need to set the `blogdown.files_filter` option.

Thank you!
