### ISSUE TITLE
[FR] clean_duplicates with more control?

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#628]
I love this function, but just noticed that in "full markdown mode"

```
options(
  # build .Rmd to .html (via Pandoc); to build to Markdown, set this option to 'markdown'
  blogdown.method = 'markdown'
)
```

When I use `clean_duplicates`, it is deleting all the md files in favor of html (as documented) because my source files are not `.Rmarkdown`. Would it be possible to add an argument here to `keep = markdown` or `keep = html`? Or perhaps it could read whether this option is present in the `.Rprofile`?

**Comment by cderv** [comment]
Yes I think this function should be aware of `blogdown.method` to know what to do. So I would classify this has a bug from something we did not adapt when introducing `markdown` method. 

https://github.com/rstudio/blogdown/blob/0cde6d6b43d94455a5f9b4470a738b4d22696cd3/R/check.R#L467-L474
