### ISSUE TITLE
Simultaneous TOC and inline maths

### ISSUE THREAD

**Issue by thosgood** [rstudio/blogdown#631]
There are (at least) two things that I would like for my blog post pages to have:

1. _a table of contents_; and
2. _inline maths rendering_.

If I use `.Rmarkdown` files, then the first one is easy (using Hugo's `{{ .TableOfContents }}`), but inline maths rendering doesn't work (and I can't get the JavaScript fix described in §B.3 of the manual to work, but that might be because I'm using KaTeX instead of MathJax).

If I use `.Rmd` files, then the second one works just fine, and the first one _sort of_ works (by using `toc: true` in `blogdown::html_page:`), but the outputted table of contents is a `<ul>` instead of a `<nav>`, and also shows up when I use `{{ .Summary }}` to display a short version of the blog post. For some reason, with `.Rmd` files, the Hugo `{{ .TableOfContents }}` no longer works.

My dream solution would involve finding a way to use Hugo's table of contents instead of the `blogdown::html_page`-generated one so that I could continue to use `.Rmd` files, which work beautifully with KaTeX, but I'd also be happy with the opposite solution, namely fixing inline maths rendering (**without** asking the user to wrap everything in code blocks) so that I could use `.Rmarkdown` files.

Please let me know if I can provide any more information!

**Comment by yihui** [comment]
> fixing inline maths rendering (**without** asking the user to wrap everything in code blocks) so that I could use `.Rmarkdown` files.

Unfortunately I don't think that is possible, because Hugo's Markdown renderer doesn't support LaTeX math, and I doubt if it ever will. `.Rmd` works only because Markdown is rendered through Pandoc, and Pandoc supports math.

Before the Markdown render supports math, I think wrapping math in code is still the only way to go: https://yihui.org/en/2018/07/latex-math-markdown/ I can at most wrap the math in code automatically, but it's probably not going to be robust (detecting math is tricky).

**Comment by thosgood** [comment]
That makes sense, so I suppose the other half of my query is the relevant one: is there a way to get Hugo to generate the table of contents when using `.Rmd` files?

**Comment by yihui** [comment]
No, unfortunately. When you render `.Rmd` to `.html`, Hugo won't generate the TOC again (it can only generate the TOC from `.md` input, not `.html`).

Like the math solution, if you want to make Pandoc's TOC compatible with Hugo's, you can use JavaScript. JavaScript gives you the power to modify anything on the page.
