### ISSUE TITLE
location changes

### ISSUE THREAD

**Issue by IanniMuliterno** [rstudio/blogdown#633]
hello, I was checking the  [bookdown guide](https://bookdown.org/yihui/blogdown/configuration.html#toml-syntax) and it seems that some parameters moved from config.toml to 
'config/_default/params.toml'. If that's the case, could you update the guide?

**Comment by cderv** [comment]
>  it seems that  some parameters moved from config.toml to 'config/_default/params.toml'

Do you mean for a hugo theme you are using that is using a config dir ? 

If so, this is not yet supported by **blogdown** but will be in the future. See #611

**Comment by IanniMuliterno** [comment]
weird, I'm using blogdown and my blog is organized as I mentioned and it's working fine. 
I am experiencing some dificulties to use multilanguage but I don't think the issues are related.

Anyways, I will close the issue then.

**Comment by yihui** [comment]
FYI the config dir is supported now: https://github.com/rstudio/blogdown/issues/611#issuecomment-962044694 Thanks!
