### ISSUE TITLE
install_hugo() on ARM chips

### ISSUE THREAD

**Issue by r-saikat** [rstudio/blogdown#636]
Hi, 

When I use ` blogdown::install_hugo()` on a machine with an ARM processor, it tries to install the x64 version and fails. I downloaded the ARM version from Hugo's release page and followed @yihui 's answer [here](https://stackoverflow.com/questions/61317355/error-installing-hugo-using-blogdownhugo-install) to install Hugo on my Ubuntu 20.04 machine, but it failed. It didn't show me the exact error, but `blogdown::check_hugo()` told me that Hugo was not installed.

The Hugo version on the apt store is old, so using the version from `apt install hugo` won't help while building a site. I had to download the required version of Hugo from GitHub and install it manually using the Ubuntu terminal. It'll be great if you can add support for ARM-based machines since the base R has been ported to support ARM chips.

**Comment by cderv** [comment]
`blogdown::install_hugo()` does not support ARM yet. 

Support should be added in 
https://github.com/rstudio/blogdown/blob/69b5c383a77df3ac6d97f466d0bf98607e887cf2/R/install.R#L45-L71

In the last line above in the `bit` part, we are only looking for 64bits vs 32bits and we don't detect ARM. 

Thanks for the feature request!

**Comment by yihui** [comment]
I need to know how to detect ARM. Could you provide the output of `str(list(.Platform, as.list(Sys.info())))`? You can delete your username in the output. The piece of information that I need is probably in `Sys.info()['machine']`, but I don't have an ARM-based machine so I'm not sure. Thanks!

**Comment by r-saikat** [comment]
Hi, here is the output of `str(list(.Platform, as.list(Sys.info())))`:

```
List of 2
 $ :List of 8
  ..$ OS.type   : chr "unix"
  ..$ file.sep  : chr "/"
  ..$ dynlib.ext: chr ".so"
  ..$ GUI       : chr "RStudio"
  ..$ endian    : chr "little"
  ..$ pkgType   : chr "source"
  ..$ path.sep  : chr ":"
  ..$ r_arch    : chr ""
 $ :List of 8
  ..$ sysname       : chr "Linux"
  ..$ release       : chr "5.8.0-1037-oracle"
  ..$ version       : chr "#38~20.04.1-Ubuntu SMP Fri Jul 16 00:56:44 UTC 2021"
  ..$ nodename      : chr "2a7c9e53d7f3"
  ..$ machine       : chr "aarch64"
  ..$ login         : chr "unknown"
  ..$ user          : chr "username_deleted"
  ..$ effective_user: chr "username_deleted"
```
Please let me know if you need more information.

Oracle Cloud is providing lifetime free 4 core 24 GB memory ARM-based machines.

**Comment by yihui** [comment]
That should be enough. Thank you!

Please try the development version via

```r
remotes::install_github('rstudio/blogdown')
```

Remember to restart R before trying `blogdown::install_hugo()`.

**Comment by r-saikat** [comment]
Thank you for the update. I am using Ubuntu 20.04 on `aarch64`. I tried `blogdown::install_hugo()`, but it gave me the error:

```
>blogdown::install_hugo()
The latest Hugo version is v0.86.0
Error in grepl("^(aarch|arm)64") : 
  argument "x" is missing, with no default
```
I saw the release notes. Is the error is because this is supported on macOS only?

**Comment by r-saikat** [comment]
Thanks, a1253d63851dc7240a3c3120635e627089354469 fixed it.

**Comment by yihui** [comment]
I realized this problem one minute before your previous reply :)

**Comment by yihui** [comment]
Just to verify that the ARM version of Hugo is correctly installed, could you show the output of `blogdown::hugo_cmd('version')`? Thanks!

**Comment by r-saikat** [comment]
```
>install_hugo()
The latest Hugo version is v0.86.0
trying URL 'https://github.com/gohugoio/hugo/releases/download/v0.86.0/hugo_0.86.0_Linux-ARM64.tar.gz'
Content type 'application/octet-stream' length 12589682 bytes (12.0 MB)
==================================================
downloaded 12.0 MB

Hugo has been installed to "/home/test2/.local/share/Hugo/0.86.0". You are recommended to set options(blogdown.hugo.version = "0.86.0") in the .Rprofile file in your website project. See the blogdown book for more info on .Rprofile: https://bookdown.org/yihui/blogdown/global-options.html
```
```
> hugo_cmd('version')
hugo v0.83.1-5AFE0A57 linux/arm64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio
```

Maybe, this is because I already have v0.83.1 installed?

**Comment by yihui** [comment]
Yes, you need to restart R after installing the newer version of Hugo.

**Comment by r-saikat** [comment]
I restarted R.

```
>blogdown::hugo_cmd('version')
hugo v0.86.0-41C6C52E linux/arm64 BuildDate=2021-07-21T09:53:14Z VendorInfo=gohugoio
```

**Comment by yihui** [comment]
Okay. Sounds like it's working well. I'll make a new CRAN release soon. Thank you!
