### ISSUE TITLE
[FR] Rename the default branch from `master` to `main`

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#639]
https://github.com/github/renaming

See also:
+ https://github.com/rstudio/bookdown/issues/1198
+ https://github.com/rstudio/rmarkdown/issues/2181
+ https://github.com/rstudio/distill/issues/390
+ https://github.com/rstudio/blastula/issues/268

**Comment by yihui** [comment]
Done. 

@cderv Remember to rename locally:

```sh
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by cderv** [comment]
Done thanks !
