### ISSUE TITLE
Editing `config/_default/params.yaml` does not make expected changes

### ISSUE THREAD

**Issue by shirdekel** [rstudio/blogdown#644]
I created an academic demo site using `blogdown::new_site(theme = "wowchemy/starter-academic")`.

I would like to edit the "Contact" section. For instance, I removed the email line by commenting it out in `config/_default/params.yaml`:

```yml
# Contact (edit or remove options as required)

# email: test@example.org
phone: 888 888 88 88
```

This does not remove the line (as seen in the `blogdown::serve_site()` preview).

However, commenting out the line both in the above AND in`themes/starter-hugo-academic/config/_default/params.yaml` successfully removes the line in the site preview. Commenting out the line ONLY in`themes/starter-hugo-academic/config/_default/params.yaml` does not work.

My expectation was that all editing should be done in the files that are not in `themes/`, so I assumed editing only `config/_default/params.yaml` should work.

```r
xfun::session_info('blogdown')
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Locale: en_AU.UTF-8 / en_AU.UTF-8 / en_AU.UTF-8 / C / en_AU.UTF-8 / en_AU.UTF-8

Package version:
  base64enc_0.1.3   blogdown_1.4.1    bookdown_0.22.15  digest_0.6.27    
  evaluate_0.14     glue_1.4.2        graphics_4.0.2    grDevices_4.0.2  
  highr_0.9         htmltools_0.5.1.1 httpuv_1.6.1      jsonlite_1.7.2   
  knitr_1.33        later_1.2.0       magrittr_2.0.1    markdown_1.1     
  methods_4.0.2     mime_0.11         promises_1.2.0.1  R6_2.5.0         
  Rcpp_1.0.7        rlang_0.4.11      rmarkdown_2.9.5   servr_0.22       
  stats_4.0.2       stringi_1.7.3     stringr_1.4.0     tinytex_0.32.2   
  tools_4.0.2       utils_4.0.2       xfun_0.24         yaml_2.2.1       

Hugo version: 0.85.0
```

**Comment by yihui** [comment]
Should be fixed for new installations. Thanks for the report! You need to delete the `themes/starter-hugo-academic/config` directory by yourself.
