### ISSUE TITLE
The check_site() function adds vercel.json file judgment

### ISSUE THREAD

**Issue by chuxinyuan** [rstudio/blogdown#648]
When I run the `check_site()` function, the prompt tells me something like this:

```
― Checking netlify.toml...
● [TODO] netlify.toml was not found. Use blogdown::config_netlify() to create file.
```

In fact, my blog is going to be deployed on Vercel, not Netlify. 
So I think the `check_site()` function should add check for vercel.json file.
The prompt [TODO] will only be given if neither netlify.toml nor vercel.json file exists
In addition, there is a `blogdown::config vercel()` function here is even better.

**Comment by cderv** [comment]
Thanks for the suggestion ! 

We welcome a PR to add Vercel support in **blogdown**. Feel free to contribute with a `blogdown::config_vercel()` to help setup like netlify. You may know more than I am about what this file should contain.

We can then see how we could add a `check_vercel()` in `check_site()` and let user configure which hosting provider to choose.

**Comment by chuxinyuan** [comment]
The vercel.json like this <https://github.com/swsoyee/swsoyee/blob/master/vercel.json>

**Comment by yihui** [comment]
Done (since I use Vercel myself). Thanks for the suggestion!
