### ISSUE TITLE
Problems occur when a section title is Chinese

### ISSUE THREAD

**Issue by likanzhan** [rstudio/blogdown#65]
I created a 'rmd' file with the table of contents enabled.

When the section title is English or the first character of the title is English, the table of contents works normally:
when I click the title of the section show in the table of contents, It jumps to that section.

But in the same file, when the title of the section is Chinese, the following problem occurs:
nothing happens after I click the section title.

Any suggestion?

Thanks

**Comment by yihui** [comment]
You have to manually assign an ID to the section title, because Pandoc is unable to generate automatic IDs for pure Chinese titles. For example,

    # 你好世界 {#hello-world}

Relative doc: http://pandoc.org/MANUAL.html#header-identifiers
