### ISSUE TITLE
Update link to "Up & running with blogdown in 2021"

### ISSUE THREAD

**Issue by linogaliana** [rstudio/blogdown#653]
When looking at the blogdown documentation, e.g. [here](https://bookdown.org/yihui/blogdown/output-format.html), I wanted to follow the link given in the box at the top of the page to find @apreshill *Up & running with blogdown in 2021* post.

However, the URL no longer exists. That would be cool to update this box with the new URL: https://www.apreshill.com/blog/2020-12-new-year-new-blogdown/

**Comment by cderv** [comment]
Thanks ! 

@apreshill I guess you knew already it has changed. Seems like there is no redirect in your website ? 
Or is it not correctly working ? 

Anyway, I modified. Book is updated
