### ISSUE TITLE
Citation (Bibliography) feature

### ISSUE THREAD

**Issue by therimalaya** [rstudio/blogdown#66]
Since rmarkdown goes through pandoc, is it possible to add functionality of citation like in bookdown.

**Comment by yihui** [comment]
It is.

**Comment by pzhaonet** [comment]
Great! I just found this exciting feature valid already. [Here](http://www.pzhao.org/zh/post/inresistible-bookdown/) is an example. Why not document it in the blogdown book? I found this trick nowhere and thought this feature had been still in progress until today.

1. Save your bib file(s) in the `content\post\`.

2. Specify your bib files in the yml header of a .Rmd post like: `bibliography: [book.bib, packages.bib]`

3. Build it with blogdown.

**Comment by adrianadermon** [comment]
I'm trying to get this to work with a slightly different setup. I am only using Blogdown to render specific posts into plain markdown (by using the file extension ```.Rmarkdown```), which are then rendered to HTML by Hugo. 

I have this line in my header: ```bibliography: "../../static/bib/references.json"```, and convert to markdown by running Knitr from RStudio. 

When I do this in a regular ```.Rmd``` document, it works perfectly, but it doesn't do anything when I put the same code in my ```.Rmarkdown``` file. 

Am I doing something wrong, or is this functionality not available? If not, is it possible to add it?

**Comment by yihui** [comment]
@ adrianadermon Per documentation at https://bookdown.org/yihui/blogdown/output-format.html

> You cannot use Markdown features only supported by Pandoc, such as citations.

Please read these paragraphs again to know the limitations of `.Rmarkdown`.

**Comment by adrianadermon** [comment]
@yihui Sorry, I realized fairly quickly that I had made a mistake and deleted my question.

**Comment by yihui** [comment]
@adrianadermon Okay, no worries. Glad you figured it out.

**Comment by yihui** [comment]
An example has been added to the demo website: https://github.com/rbind/blogdown-demo

**Comment by cjvanlissa** [comment]
I was able to implement citations effortlessly thanks to this thread, but I can't find any information on formatting using cls. My best guess was to add cls: [apa.cls] to the yml header, and place the apa.cls file from https://github.com/citation-style-language/styles/blob/master/apa.csl in the post directory. This does not work, though. Apologies if this is a naive question, but am I missing something? Thanks!

**Comment by yihui** [comment]
@cjvanlissa That _should_ work, although I'm not sure if `[]` is necessary (i.e. use a scalar instead of array).

**Comment by cjvanlissa** [comment]
@yihui perhaps I should have mentioned that I tried that as well. The references in text look exactly like they do on your demo site, which is pretty APA-like, but the Reference list is formatted like this:

> Chen, Henian, Patricia Cohen, and Sophie Chen. 2010. “How Big Is a Big Odds Ratio? Interpreting the Magnitudes of Odds Ratios in Epidemiological Studies.” Communications in Statistics—Simulation and Computation 39 (4). Taylor & Francis: 860–64.
> 
> Cosmides, Leda, H Clark Barrett, and John Tooby. 2010. “Adaptive Specializations, Social Exchange, and the Evolution of Human Intelligence.” Proceedings of the National Academy of Sciences 107 (Supplement 2). National Acad Sciences: 9007–14.

This is not APA, and looks unchanged from when I omit cls: [apa.cls] or cls: apa.cls

**Comment by yihui** [comment]
@cjvanlissa I see. I'm not an expert on CSL. I recommend you to ask the question on StackOverflow or the pandoc mailing list instead, but with a Markdown (not R Markdown) example that is solely processed by pandoc and not blogdown (I don't think blogdown is relevant in this case -- it calls pandoc and pandoc-citeproc to process citations).

**Comment by njbart** [comment]
Somewhat belatedly – if anyone comes across this troubleshooting `.csl` files not being found:

From https://github.com/jgm/pandoc-citeproc/blob/master/man/pandoc-citeproc.1.md:

>  If the file is not found relative to the working directory, pandoc-citeproc will look in the `$HOME/.csl` directory (or `C:\Users\USERNAME\AppData\Roaming\csl` in Windows 7). If this is left off, pandoc-citeproc will look for `$HOME/.pandoc/default.csl`, and if this is not present, it will use `chicago-author-date.csl`, looking first in `$HOME/.csl` and then in its own data files.
