### ISSUE TITLE
Blogdown not displaying plots

### ISSUE THREAD

**Issue by condwanaland** [rstudio/blogdown#663]
This issue was posted to SO one week ago
https://stackoverflow.com/questions/69685472/blogdown-not-displaying-plots

I have my blogdown site that has been running for a while. When writing a post today I cannot get plots to render when running serve_site().

The plot generates fine when running the .Rmd in interactive mode, it's only when being built by knitting/serve_site/build_site that it doesn't work. The image below shows what I see on the webpage - just that small icon in the bottom.

<img width="573" alt="Screen Shot 2021-10-23 at 6 35 55 PM" src="https://user-images.githubusercontent.com/23396385/139513354-fb1bc9ad-9639-45b8-a2ad-66261c4cd398.png">

I know these questions have come up a lot, so just to list the things I've tried:

1. There is no .gitignore under the static directory
1. I've set [markup.goldmark.renderer]unsafe = true  in the config.toml
1. I've checked that the figures are being generated (I can see the files under index_files/figure-html)

You can see my blog source [here](https://github.com/condwanaland/A-Sky-Full-of-Data)

And the (not working) webpage [here](https://conorneilson.com/post/two-new-data-packages/)

You can reproduce the issue by running 

```
git clone git@github.com:condwanaland/A-Sky-Full-of-Data.git
```
Then within the created directory run `blogdown::serve_site()`

xfun::session_info()
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS  10.16, RStudio 1.4.1103

Locale: en_NZ.UTF-8 / en_NZ.UTF-8 / en_NZ.UTF-8 / C / en_NZ.UTF-8 / en_NZ.UTF-8

Package version:
  askpass_1.1       base64enc_0.1.3   blogdown_1.5.2    bookdown_0.24    
  brew_1.0.6        brio_1.1.2        cachem_1.0.6      callr_3.7.0      
  cli_3.0.1         clipr_0.7.1       commonmark_1.7    compiler_4.0.2   
  cpp11_0.4.0       crayon_1.4.1      credentials_1.3.1 curl_4.3.2       
  desc_1.4.0        devtools_2.4.2    diffobj_0.3.5     digest_0.6.28    
  ellipsis_0.3.2    evaluate_0.14     fansi_0.5.0       fastmap_1.1.0    
  fs_1.5.0          gert_1.4.1        gh_1.3.0          gitcreds_0.1.1   
  glue_1.4.2        graphics_4.0.2    grDevices_4.0.2   highr_0.9        
  htmltools_0.5.2   httpuv_1.6.3      httr_1.4.2        ini_0.3.1        
  jquerylib_0.1.4   jsonlite_1.7.2    knitr_1.36        later_1.3.0      
  lifecycle_1.0.1   magrittr_2.0.1    memoise_2.0.0     methods_4.0.2    
  mime_0.12         openssl_1.4.5     pillar_1.6.4      pkgbuild_1.2.0   
  pkgconfig_2.0.3   pkgload_1.2.3     praise_1.0.0      prettyunits_1.1.1
  processx_3.5.2    promises_1.2.0.1  ps_1.6.0          purrr_0.3.4      
  R6_2.5.1          rappdirs_0.3.3    rcmdcheck_1.4.0   Rcpp_1.0.7       
  rematch2_2.1.2    remotes_2.4.1     rlang_0.4.12      rmarkdown_2.11   
  roxygen2_7.1.2    rprojroot_2.0.2   rstudioapi_0.13   rversions_2.1.1  
  servr_0.23        sessioninfo_1.1.1 stats_4.0.2       stringi_1.7.5    
  stringr_1.4.0     sys_3.4           testthat_3.1.0    tibble_3.1.5     
  tinytex_0.34      tools_4.0.2       usethis_2.0.1     utf8_1.2.2       
  utils_4.0.2       vctrs_0.3.8       waldo_0.3.1       whisker_0.4      
  withr_2.4.2       xfun_0.27         xml2_1.3.2        xopen_1.0.0      
  yaml_2.2.1        zip_2.2.0  
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] used `blogdown::check_site()` function to diagnose your site and corrected potential problems?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('blogdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the blogdown package using `remotes::install_github('rstudio/blogdown')` ?

**Comment by yihui** [comment]
Sounds like a bug of Hugo, or something changed in a recent version of Hugo. I'll investigate it. Thanks for the report!

**Comment by condwanaland** [comment]
Thank you so much for the fix @yihui . Much appreciated
