### ISSUE TITLE
Error while downloading Hugo, incorrect url

### ISSUE THREAD

**Issue by martinolmos** [rstudio/blogdown#664]
Hi,

First of all let me thank you for the wonderful work you do for the R Community.

I found an issue when trying "New Project" --> "Website using blogdown" in RStudio after a fresh install.
I get the following error:

`cannot open URL 'https://github.com/gohugoio/hugo/releases/download/v0.89.0/hugo_extended_0.89.0_macOS-64bit.tar.gz': HTTP status was '404 Not Found'`

After checking the url I see that the correct url is: 
`https://github.com/gohugoio/hugo/releases/download/v0.89.0/hugo_extended_0.89.0_macOS-all.tar.gz`

I guess they changed the pattern for the macOS.

I solved the problem by downloading and installing Hugo myself. 
I looked at `https://github.com/rstudio/blogdown/blob/main/R/install.R` to see if I can propose a fix but I couldn't. Sorry about that.

My `sessionInfo()` is:
`R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.6`

**Comment by cderv** [comment]
Thanks for the report. Seems like they indeed change the pattern for this version with one bundle ARM64 and 64bits. 

https://github.com/rstudio/blogdown/blob/d7ef0f973a75442bc4289cefa775a6b375bd7503/R/install.R#L73-L79

@yihui I let you check this as it could be easier directly from a Mac user that everything is fine. But it could be as easy as just adding a specific rule for version > 0.89 for Mac when extended is TRUE. If they stick to the rule obviously.

**Comment by yihui** [comment]
Yes, they changed the filename in 0.89.0: https://github.com/gohugoio/hugo/issues/9035 I'll fix `install_hugo()` accordingly. Thanks!

**Comment by yihui** [comment]
Should be fixed now. You can install the development version via

```r
remotes::install_github('rstudio/blogdown')
```

Thanks!

**Comment by yihui** [comment]
Note that Hugo 0.89.0 on macOS is buggy: https://github.com/gohugoio/hugo/issues/9131 For now I recommend that you either install a previous version, or wait for 0.89.1.

**Comment by yihui** [comment]
FYI hugo 0.89.1 was just released, and I've updated **blogdown** accordingly (you'll need to install the dev version of **blogdown** again).
