### ISSUE TITLE
Hugo shortcodes are url-encoded prior to hugo processing

### ISSUE THREAD

**Issue by seandavi** [rstudio/blogdown#67]
[Hugo shortcodes](https://gohugo.io/extras/shortcodes/) are rendered with URL encoding, presumably before processing by Hugo, thus breaking their functionality.  This in Rmd:

```
{{< tweet 666616452582129664 >}}
```
becomes this in md and, therefore, in html: 

```
 {{&lt; tweet 666616452582129664 &gt;}}
```

**Comment by lcolladotor** [comment]
Check https://github.com/rstudio/blogdown/issues/40#issuecomment-275142802

**Comment by seandavi** [comment]
Thanks, @lcolladotor. This comment a couple above is also relevant:
https://github.com/rstudio/blogdown/issues/40#issuecomment-275134811

This addresses the issue, so I'll close.

**Comment by lcolladotor** [comment]
Hehe yeah, that's the one I meant to link to.

**Comment by yihui** [comment]
Now please see https://github.com/rstudio/blogdown/issues/40#issuecomment-300997712
