### ISSUE TITLE
Unable to create new post with Academic theme

### ISSUE THREAD

**Issue by dinanajiarch** [rstudio/blogdown#671]
`blogdown::new_post(title = "My first post", ext = '.Rmarkdown',subdir = "post")`

> Error in new_content(file, kind, FALSE) : 
>   Failed to create the file 'post/2021-12-13-my-first-post/index.Rmarkdown'.
> In addition: Warning message:
> In system2(...) :
>   running command '"C:/Users/Dina Arch/AppData/Roaming/Hugo/0.90.1/hugo.exe" new "post/2021-12-13-my-first-post/index.md" --themesDir themes' had status 65535

Not sure how to fix this. Any help is appreciated.

**Comment by yihui** [comment]
The error message contains too little information. Is this problem specific to the academic theme? In other words, does it happen to other themes, too? Could you test a new site with the default theme?

**Comment by dinanajiarch** [comment]
Hi, I restarted the entire process and I think it was a GitHub issue. It works fine now. Thanks for your response.
