### ISSUE TITLE
Error after rendering the serve site

### ISSUE THREAD

**Issue by Nitheshnirmal** [rstudio/blogdown#672]
Rebuild failed:

"C:\eye check\NN1\content\english\post\2020-12-01-r-rmarkdown\index.en.html:9:14": failed to render shortcode "blogdown/postref": failed to process shortcode: "C:\eye check\NN1\layouts\shortcodes\blogdown\postref.html:1:10": execute of template failed: template: shortcodes/blogdown/postref.html:1:10: executing "shortcodes/blogdown/postref.html" at <getenv "BLOGDOWN_POST_RELREF">: error calling getenv: access denied: "BLOGDOWN_POST_RELREF" is not whitelisted in policy "security.funcs.getenv"; the current security configuration is:

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

 7
 8
 9
10
11
---

<script src="{{< blogdown/postref >}}index.en_files/header-attrs/header-attrs.js"></script>

hugo v0.91.0-D1DC0E9A+extended windows/amd64 BuildDate=2021-12-17T09:50:20Z VendorInfo=gohugoio

Reload Page

**Comment by yihui** [comment]
Hugo introduced a new security policy since 0.91.0: https://github.com/gohugoio/hugo/releases/tag/v0.91.0

For now, you may try to install and use a lower version of Hugo, e.g., `blogdown::install_hugo('0.90.1')` and follow instructions.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report! You can install the development version via

```r
remotes::install_github('rstudio/blogdown')
```

**Comment by Nitheshnirmal** [comment]
Thank you
