### ISSUE TITLE
Consider setting `HUGO_CACHEDIR` to use the tmpdir of the R session?

### ISSUE THREAD

**Issue by cboettig** [rstudio/blogdown#678]
Recent versions of hugo use `/tmp/hugo_cache` as a cache file location, which is badly suited to multi-tenant systems and will throw permission errors such as:

```
Error: add site dependencies: create deps: failed to create file caches from configuration: mkdir /tmp/hugo_cache/filea68f64c4f01c0: permission denied
```

See  https://github.com/gohugoio/hugo/issues/7391 for details.  

Hopefully this will be fixed upstream in hugo, but meanwhile, `blogdown` (or the end user) could avert the problem by setting the environmental variable `HUGO_CACHEDIR` to a more appropriate path.  

For instance, as you know, R uses a subdir within `/tmp` as `tempdir()`, which is very reasonable as it avoids permission issues and allows R to purge tmp files between sessions.  Alternately this could be set to the OS-specific user cache dir, as provided by `rappdirs`/`tools`.  Not sure which is better, but either would be preferable to writing directly to `/tmp/hugo_cache`, which seems to go against long-standing conventions for appropriate caching.  (Notably, using the R-set `tempdir()` would case the cache to be purged between R sessions; perhaps that's not desirable in this case, so the application-specific destination is probably correct.

I recognize this is fundamentally a hugo issue, so feel free to close, but as most of us look first to blogdown so maybe this will at least be a pointer to anyone hitting this error.

**Comment by yihui** [comment]
I don't know what the most reasonable default cache dir would be. You have mentioned that R's `tempdir()` is not good since it is not persistent.

Perhaps combining `TMPDIR` and `USER`? You can set `HUGO_CACHEDIR` in the `.Rprofile` of your website project like this:

```r
Sys.setenv(HUGO_CACHEDIR = file.path(dirname(tempdir()), 'hugo_cache', Sys.getenv('USER')))

# or if you want the cache dir to be associated with the project
Sys.setenv(HUGO_CACHEDIR = file.path(blogdown:::site_root(), 'blogdown', 'hugo_cache', Sys.getenv('USER')))
```

Then everyone opening this project will have their own cache dir.

Anyway, I tend not to do this by default in **blogdown** mainly because 1) the solution seems to be simple enough; 2) I guess most users don't use **blogdown** on multi-tenant systems (no one has reported this problem in this repo before), and 3) more importantly, changing Hugo's default cache dir means **blogdown** users' existing cache would be invalidated.

Thanks for the report! Hopefully if any **blogdown** users are affected by this problem, they can find this issue and the possible solutions.

**Comment by cboettig** [comment]
Thanks @yihui !  FWIW, after a little reflection I think the natural choice here is:

```
Sys.setenv(HUGO_CACHEDIR = tools::R_user_dir("blogdown", which = "cache"))
```

which would set cache dir to the appropriate user-specific cache location used for each operating system.  
This will persist, work in multi-user environments, and follow the appropriate standard, and is why `R_user_dir()` exists in the first place.

I do find that setting environmental variables confuses many less experienced R programmers (edit what? which `.Rprofile`?).  Since a cache is intended to be disposable I don't think breaking an existing cache would be considered a breaking change in the blogdown API.

**Comment by yihui** [comment]
Yes, that would be a more natural choice indeed!

A cache should be disposable but not arbitrarily. In this case, Hugo can decide whether to invalidate the cache, but it's not fair for me to do it (only by changing the default cache path).

I'll think about the possibility of migrating existing cache to the `R_user_dir()`.

**Comment by yihui** [comment]
On second thought, I still decide not to do this in **blogdown** and will wait for Hugo to fix the problem. Changing `HUGO_CACHEDIR` in **blogdown** can create an inconsistency if users use both **blogdown** and hugo directly. For example, I know @Athanasiamo prefers starting `hugo server` separately and doesn't use `blogdown::serve_site()`.

> I do find that setting environment variables confuses many less experienced R programmers (edit what? which `.Rprofile`?).

Understood. We can document that. **blogdown** users need to understand `.Rprofile` anyway: https://bookdown.org/yihui/blogdown/global-options.html

---

In case anyone is running into this issue, please follow these two steps:

1. Open the `.Rprofile` file in the website root directory:
 
   ```r
   file.edit(file.path(blogdown:::site_root(), '.Rprofile'))
   ```

2. Copy and paste this line into the file:

   ```r
   Sys.setenv(HUGO_CACHEDIR = tools::R_user_dir("blogdown", which = "cache"))
   ```
