### ISSUE TITLE
Unable to check and built website using Hugo

### ISSUE THREAD

**Issue by DrJohan** [rstudio/blogdown#679]
Dear Yihui

Good day to you. I've been trying to built my website using blogdown for 2 days. However, when I'm trying to verify my Hugo installation, I receive following error code: 
Error in system2(...) : 
 "'CreateProcess' failed to run 'C:\Users\Dr Johan Ibrahim\AppData\Roaming\Hugo\0.91.1\hugo.exe version".

Below are my session info:
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22523), RStudio 2021.9.0.351

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
  LC_NUMERIC=C                           LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3  blogdown_1.7.2   bookdown_0.24    compiler_4.1.2   digest_0.6.29    evaluate_0.14    fastmap_1.1.0   
  glue_1.6.0       graphics_4.1.2   grDevices_4.1.2  highr_0.9        htmltools_0.5.2  httpuv_1.6.4     jquerylib_0.1.4 
  jsonlite_1.7.2   knitr_1.37       later_1.3.0      magrittr_2.0.1   methods_4.1.2    mime_0.12        promises_1.2.0.1
  R6_2.5.1         Rcpp_1.0.7       rlang_0.4.12     rmarkdown_2.11   servr_0.24       stats_4.1.2      stringi_1.7.6   
  stringr_1.4.0    tinytex_0.36     tools_4.1.2      utils_4.1.2      xfun_0.29        yaml_2.2.1 

Please help and guide me please. Thank you.

**Comment by cderv** [comment]
> Error in system2(...) :
"'CreateProcess' failed to run 'C:\Users\Dr Johan Ibrahim\AppData\Roaming\Hugo\0.91.1\hugo.exe version".

Hi @DrJohan , 

is this a new installation and a new error ? Was it working before ? 

This type of error remind me of similar errors where spaces in username were an issue. So I am wondering if this is new error and it was working before, or this is the first time you are using **blogdown** on this environment, and it does not work. Thanks!

**Comment by yihui** [comment]
This reminds me of #82, which I was not able to resolve because I couldn't reproduce the problem. In that case, I know his Windows machine was managed by the university, so there was likely to be permission issues (they were probably not allowed to execute arbitrary commands). I wonder if you are in the same situation.
