### ISSUE TITLE
Unable to access .GitInfo from template when knitting Rmd file

### ISSUE THREAD

**Issue by datawookie** [rstudio/blogdown#681]
Hi!

I have a working `{blogdown}` site which works wonderfully. I'm wanting to enhance one of the templates to use the `.GitInfo` structure. I've got some old posts that are in `.md` files and most of the newer posts are in `.Rmd` files.

With the old `.md` files the rendered post contains the expected values from `.GitInfo`.

However, with the `.Rmd` files the rendered post simply contains `<nil>` where I expect to see `.GitInfo`.

I have a hypothesis for why this happens:

- the `.md` files exist in the Git repository and so Hugo is able to extract the corresponding information from Git; but
- the only the `.Rmd` files exist in the Git repository (and not the interim `.md` files which I understand are being generated by knitting the `.Rmd` files and that are then being processed by Hugo). Since Hugo can't find the `.md` file (and doesn't know to look for a `.Rmd` file) the `.GitInfo` structure doesn't get populated.

Does that sound feasible? And, if so, is there a way to work around this?

My first objective with doing this is to have an "updated" timestamp on each post which will be derived from the latest commit relevant to a file. However, I have other ideas for how this Git information could be used too.

Any suggestions would be appreciated.

Best regards, Andrew.

**Comment by yihui** [comment]
`.GitInfo` should be available to templates as long as the post is under version control. If not, could you please provide a reproducible example and session info as requested by [the issue guide](https://github.com/rstudio/blogdown/issues/new?assignees=&labels=&template=bug-report.md&title=)?

**Comment by datawookie** [comment]
Hi @yihui, thanks for the rapid response. Yes, for sure. It was just quite a bit of work boiling this down to a simple reproducible case. Please take a look at the repository [here](https://github.com/datawookie/blogdown-gitinfo).

This is what I'm doing to reproduce the problem:

1. Launch RStudio and open the project.
2. Run `blogdown::build_site()` in the console.
3. Take a look at `public/index.html` which contains the following (looks like a JSON document):

```
{"hash":"1e18a12fea2ecfda00731f7efbdc9858b39f1b4c","abbreviatedHash":"1e18a12","subject":"feat: Initial commit","authorName":"Andrew Collier","authorEmail":"andrew@fathomdata.dev","authorDate":"2022-01-06T07:02:41Z","commitDate":"2022-01-06T07:02:41Z"}
```

4. Take a look at `public/blog/plain-markdown/index.html` which contains the following (still some Git information but it looks like it has been parsed/stripped in some way because the keys have all gone):

```
{1e18a12fea2ecfda00731f7efbdc9858b39f1b4c 1e18a12 feat: Initial commit Andrew Collier andrew@fathomdata.dev 2022-01-06 07:02:41 &#43;0000 GMT 2022-01-06 07:02:41 &#43;0000 GMT}
```

5. Take a look at `public/blog/r-markdown/index.html` which contains the following:

```
&lt;nil&gt;
```

![Peek 2022-01-06 07-14](https://user-images.githubusercontent.com/6134409/148344071-f9926846-bdc1-41a8-a5c0-06d6b69f02b3.gif)

**Comment by yihui** [comment]
Thanks for the example! I was not accurate in my previous reply: for `.GitInfo` to be available, your project has to be under version control, *and* the post file needs to be committed. Hugo doesn't recognize `.Rmd`, but only `.md` and `.html`. In this case, after you `blogdown::serve_site()`, you need to commit `content/blog/r-markdown/index.html`. BTW, you should ignore `\.Rmd$` in addition to `.Rmarkdown`: https://github.com/datawookie/blogdown-gitinfo/blob/master/config.yaml#L9

**Comment by datawookie** [comment]
Aha! Great, thanks for the clarification, @yihui.

> BTW, you should ignore \.Rmd$ in addition to .Rmarkdown

Absolutely. And were this not a demo repository then I certainly would have done so! Thanks for pointing that out though.

> you need to commit content/blog/r-markdown/index.html

**Comment by yihui** [comment]
You have to commit the artifacts of R Markdown posts. As I said, Hugo doesn't recognize R Markdown posts. It can only accept the artifacts from R Markdown---either `.html` or `.md` output files. If you prefer `.md` output, you may set the `blogdown.method` option: https://bookdown.org/yihui/blogdown/global-options.html

Anyway, it's impossible to get the git info of a post if the post is not under version control, and for Hugo, `.Rmd` is not the post but the source of the post.
