### ISSUE TITLE
Support for tabset

### ISSUE THREAD

**Issue by clausgp** [rstudio/blogdown#69]
Any plans to add support for tabset?

As a tabsetonatic that would be awesome!

**Comment by yihui** [comment]
No plans yet, but I'll definitely try in the future. Thanks!

**Comment by dmi3kno** [comment]
Either this one #175 or #69 need to remain open, please

**Comment by yihui** [comment]
Rest assured that there is a good reason why this issue has not been closed yet (while the other 258 issues have been closed). 😁

**Comment by dmi3kno** [comment]
Just wanted to leave a note for people that 
<details><summary>**summaries**</summary>
<p> *and hidden details* <p>
</details>
work on Hugo with .Rmarkdown

**Comment by instantkaffee** [comment]
@dmi3kno
Can you explain how?

**Comment by nd823** [comment]
@instantkaffee 

The answer is here: https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f#file-readme-md

```
<details><summary>CLICK ME</summary>
<p>

#### yes, even hidden code blocks!

```python
print("hello world!")
```

</p>
</details>
```

Works well in my blog using the Academic theme.

**Comment by BayanHammami** [comment]
This feature would be great to have. Is there a workaround in the interim?

**Comment by yihui** [comment]
Here is one possible implementation of tabbed sections: https://yihui.org/en/2023/10/section-tabsets/

And here is how you could fold code blocks: https://yihui.org/en/2023/09/code-folding/

It's been six years, but better late than never :)

**Comment by BayanHammami** [comment]
Thanks so much Yihui, your work on blogdown more broadly is also greatly appreciated. It's a very powerful package!
