### ISSUE TITLE
Ignore qmd file as Rmd in case quarto is used to produced `.md` for Hugo.

### ISSUE THREAD

**Issue by cderv** [rstudio/blogdown#692]
Quarto can be used to produce Hugo markdown files: https://quarto.org/docs/output-formats/hugo.html

In case this is used within a **blogdown** project, maybe we should help user know these file should be ignored. 
to have 
````toml
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.qmd$", "_cache$"]
````

Probably only in check function : https://github.com/rstudio/blogdown/blob/3588e02fbc8aa6c3a693aae913e3ee539ee036f7/R/check.R#L54-L57
so the conf files are updated. 

Unless I have missed another spot 🤔 

Also, maybe there is more to do for Quarto support (like render a qmd to md using `quarto::quarto_render()` ?) but this is another topic.

**Comment by yihui** [comment]
I wonder why people would use quarto inside **blogdown** projects, i.e., what are the advantages of using `.qmd` and quarto (compared to generating `.md` from `.Rmd` with **blogdown**)? I feel quarto and **blogdown** are quite independent, and I'm not sure if people would mix them.

**Comment by kent-orr** [comment]
Throwing my hat in as another person that would like to see this implemented. I like quarto's syntax (even if it is very, very similar to rmd) and I feel it lowers the bar for getting users of other languages to collaborate on things like internal blogs and reporting.

**Comment by cderv** [comment]
Hi @kent-orr, 

Are you specifically referring to add `.qmd` in the list of ignore file in config (which this issue is about), or are you interested in broader support regarding Quarto  / Blogdown ? 

In the latter case, we would appreciate a new issue where you could detail your workflow and how you are thinking the two should work together. We could then discuss in this new issue. 

You can already use Quarto and Hugo together to manage a website, and **blogdown** is not really useful in this process that does not involve Rmd files. This is why we are interested in how you see things if you think **blogdown** could help R users with this. Thanks !
