### ISSUE TITLE
Unexpected RSS Feed Behaviour

### ISSUE THREAD

**Issue by cgoo4** [rstudio/blogdown#698]
[SimplePie](http://simplepie.org/demo/?feed=https%3A%2F%2Fwww.quantumjitter.com%2Findex.xml) correctly renders my main RSS as full text, but [categories/r](http://simplepie.org/demo/?feed=https%3A%2F%2Fwww.quantumjitter.com%2Fcategories%2Fr%2Findex.xml) only shows the summary. I need that too to be full text.

My Hugo Apero-themed site is [quantumjitter.com](https://www.quantumjitter.com) and is deployed to Netlify via [my Github repo](https://github.com/cgoo4/quantumjitter).

I've set up a `layouts/_defaults/rss.xml` to use `.Content`. When I build the site locally in RStudio with blogdown, I get a full-text `index.xml` in the `public/` folder and a *full-text* `index.xml` in `public/categories/r/`, but the latter is not full-text in SimplePie. I've tried both manual deployment (drag & drop) and continuous Github deployment.

I'm not sure if I'm just misunderstanding how this works or if it might be a theme-specific issue?

**Comment by yihui** [comment]
The `r` category shows the full text in my browser: 

![image](https://user-images.githubusercontent.com/163582/165773629-b29ec226-501f-4382-a634-958a6fd8440e.png)

**Comment by cgoo4** [comment]
Thank you yihui. I should have cleared my cache after the last update!
