### ISSUE TITLE
Support for relref

### ISSUE THREAD

**Issue by kenjisato** [rstudio/blogdown#70]
Thank you for a great package! I'm really enjoying it!

It might be related to #40 but is there any chance that the Hugo shortcodes `ref` and/or `relref` will be supported for .Rmd files? 

Following #40, I tried 

    `r htmltools::HTML("{{< relref \"ma17q2.en.Rmd\" >}}")`

from within ma17q2.en.Rmd itself and I got 

    No page found with path or logical name "ma17q2.en.Rmd"

while a similar code pointed to a regular markdown file works as expected. I hope this works for Rmd files as well.

**Comment by yihui** [comment]
Does `ma17q2.en.html` work?

**Comment by kenjisato** [comment]
Yes, it does! Thank you.
