### ISSUE TITLE
Duplicated YAML bug

### ISSUE THREAD

**Issue by juanitorduz** [rstudio/blogdown#708]
Hi! 👋 ! I just updated blogdown to the latest version and I am having an issue: when I run `blogdown::serve_site()` the generated html gets a copy of the YAML post configuration. For example:

![image](https://user-images.githubusercontent.com/22996444/168892201-e1af7cb4-5a59-4ae1-8b6e-5f1eec7360d4.png)

Concretely here you can see the duplication in the html file.

![image](https://user-images.githubusercontent.com/22996444/168892106-d982f104-6747-468f-9e8a-f75ceee18eb0.png)

```
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.3.1, RStudio 2021.9.0.351

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3   blogdown_1.10     bookdown_0.23     digest_0.6.27     evaluate_0.14     glue_1.4.2        graphics_4.1.2   
  grDevices_4.1.2   highr_0.9         htmltools_0.5.1.1 httpuv_1.6.1      jquerylib_0.1.4   jsonlite_1.7.2    knitr_1.33       
  later_1.2.0       magrittr_2.0.1    markdown_1.1      methods_4.1.2     mime_0.11         promises_1.2.0.1  R6_2.5.0         
  Rcpp_1.0.7        rlang_0.4.11      rmarkdown_2.10    servr_0.23        stats_4.1.2       stringi_1.7.3     stringr_1.4.0    
  tinytex_0.33      tools_4.1.2       utils_4.1.2       xfun_0.29         yaml_2.2.1       

Hugo version: 0.79.1
```

I wonder if it has to do with https://github.com/rstudio/blogdown/commit/9af773314dc03a42aeab303ea6991d5518c42c5d ? 

**Hacky solutoin:** remove this manually from the html

**Comment by juanitorduz** [comment]
Fixed this by updating to R.4.2, so I will close this one. Maybe can serve as a reference for others. Thanks 😊

**Comment by yihui** [comment]
> I wonder if it has to do with [9af7733](https://github.com/rstudio/blogdown/commit/9af773314dc03a42aeab303ea6991d5518c42c5d) ?

Probably.

> Fixed this by updating to R.4.2

Ha, that's really interesting, and I don't know why, but since the fix sounds straightforward, I won't investigate further (unless someone else reports the same problem again). Thank you!
