### ISSUE TITLE
How to include an image-gallery in blogposts?

### ISSUE THREAD

**Issue by henningsway** [rstudio/blogdown#71]
Thank you for the awesome blogdown-package!

I am just getting started to use it and plan to blog about an upcoming holiday trip. Everything works fine so far (publishing on github.io), but I would like to share some images with my readers in an album format. I currently plan to embed an image-gallery such as imgur in the rmd-file.

But it would also be nice to host the pictures myself. I read about Hugo and PhotoSwipe, but this would be a little more complex to include, right? What approach would you recommend for now?

**Comment by yihui** [comment]
I don't have a strong recommendation here. I have used Flickr and imgur. I think imgur is pretty good (it will provide you the JS code to embed a gallery).

**Comment by jemus42** [comment]
I was hoping for an integration with [http://lokeshdhakar.com/projects/lightbox2/](lightbox), a javascript library that would easily allow you to host your images yourself, however there's some assembly required as far as image galleries go if I see that correctly.

**Comment by yihui** [comment]
@jemus42 Yes, you have to DIY if your theme does not support image galleries and you do not want to use existing services like Imgur.
