### ISSUE TITLE
build_site() should accept absolute paths as build_rmd value

### ISSUE THREAD

**Issue by maelle** [rstudio/blogdown#717]
If one uses an absolute path as `build_rmd` value when calling `build_site()`, this line

https://github.com/rstudio/blogdown/blob/904b48bf79f3e4fd1f1bfe83dc89f55728ff0d49/R/render.R#L130

makes blogdown believe the file is outside the content directory.

```r
blogdown:::rel_path(blogdown:::content_file())
# "content"
xfun::is_sub_path(
  "~/Documents/ropensci/WEBSITE/roweb3/content/blog/2022-08-02-working-with-qualtrics-data-importing/index.Rmd",
  "content"
)
# FALSE
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] used `blogdown::check_site()` function to diagnose your site and corrected potential problems?

- [x] included a minimal, self-contained, and reproducible example?

- [ ] pasted the output from `xfun::session_info('blogdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the blogdown package using `remotes::install_github('rstudio/blogdown')` ?

**Comment by yihui** [comment]
Should be fixed now. Thanks for the suggestion!

**Comment by maelle** [comment]
Thank _you_! :rocket:
