### ISSUE TITLE
[FR] Make build_dir() feature complete compared to build_site()

### ISSUE THREAD

**Issue by maelle** [rstudio/blogdown#718]
It seems that `build_dir()` only uses `render_new()`.
I thought calling `build_dir()` on a directory was the same as calling `build_site(build_rmd = "a-path-to-Rmd")`, but it does not use the blogdown.method option for instance so renders the Rmd to HTML even if that option is "markdown".

**Comment by yihui** [comment]
The `blogdown.method` option only applies to R Markdown files under the `content/` directory. For Rmd files in other directories, they are just rendered to the output format specified in them.

What's your use case for `build_dir()`?

**Comment by maelle** [comment]
During my exploration related to the two other issues I opened (the actual problem ended up being index.Rmd), I thought maybe using `build_dir()` for the folder of a blog post so say `content/blog/date-blabla/` might help me build a reprex. This is where I realized `build_dir()` didn't behave like `build_site()`. But maybe that's intended? As one can use the knit button to render a single post anyway? :thinking:

**Comment by yihui** [comment]
Yes, that was intended. And yes, you can use the Knit button. It should be rare that you really need to use `build_dir()`. This function was provided mainly for building content that is not processed by Hugo, e.g., Rmd files under the `static/` directory: https://bookdown.org/yihui/blogdown/static-files.html

**Comment by maelle** [comment]
This makes sense, thanks a lot for the explanation! :pray:
