### ISSUE TITLE
[FR] Could check_site() check index.Rmd

### ISSUE THREAD

**Issue by maelle** [rstudio/blogdown#719]
I had a website Rproj that did not feature an index.Rmd like this

```
---
site: blogdown:::blogdown_site
---

<!-- This file is for blogdown only. Please do not edit it. -->
```

which meant the knit button did not work as expected (thanks @cderv for the fix).

Should `check_site()` check the presence and correctness of this file?

**Comment by yihui** [comment]
Good idea! Done. Thanks!

**Comment by maelle** [comment]
Thank _you_! :tada:
