### ISSUE TITLE
Upside down page when compiling gcushen/hugo-academic

### ISSUE THREAD

**Issue by oushujun** [rstudio/blogdown#728]
Hello,

I tried to start a blogdown new project in RStudio using the hugo theme `gcushen/hugo-academic` but encounter the following errors:
```
― Creating your new site
| Installing the theme gcushen/hugo-academic from github.com
trying URL 'https://github.com/wowchemy/starter-hugo-academic/archive/HEAD.tar.gz'
downloaded 1.8 MB

trying URL 'https://github.com/wowchemy/wowchemy-hugo-themes/archive/HEAD.tar.gz'
downloaded 25.6 MB

Error: module "github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-reveal" not found; either add it as a Hugo Module or store it in "/Users/oushujun/My Drive/study/OSU/test/test/themes".: module does not exist
Error in new_content(f2, open = FALSE) : 
  Failed to create the file 'post/2020-12-01-r-rmarkdown/index.en.Rmd'.
In addition: Warning message:
In system2(...) :
  running command ''/Users/oushujun/Library/Application Support/Hugo/0.102.3/hugo' new 'post/2020-12-01-r-rmarkdown/index.en.md' --themesDir themes -t starter-hugo-academic' had status 255
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
```

I then manually downloaded the template from https://github.com/wowchemy/starter-hugo-academic, unzipped it, and load it into RStudio as an existing project. It loaded normally and then I click `serve site`, the page showed up but upside down and mirrored. My RStudio menu also became upside down and mirrored:
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/5996084/188024884-0599609a-612c-42ab-964d-b6ac900c2711.png">

I can stop the server with `blogdown::stop_server()`, but the addin menu is still shown upside down and mirrored. I have to restart the R session to get things back to normal. Can you help to find out what went wrong and how I can use `gcushen/hugo-academic` in blogdown?

Thanks,
Shujun

**Comment by yihui** [comment]
For the wowchemy theme issue, it's a known one. I pinged its developer two weeks ago but didn't get a response: https://github.com/wowchemy/wowchemy-hugo-themes/commit/b49528cf1e812b0136be7f35540573b357c8c6b9#commitcomment-81429105 I'll see if I could fix it on my side. That said, we have often run into problems with wowchemy themes. You may see if you like the hugo-apero theme: https://github.com/hugo-apero/hugo-apero It should be much more stable.

For the RStudio issue, a quick google search led me to https://community.rstudio.com/t/install-r-studio-on-win8-my-studio-is-upside-down/80325 I'm not sure if it will solve your problem.

**Comment by oushujun** [comment]
Yes, it's fixed. Thank you very much! I heard about the `gcushen/hugo-academic` theme from your earlier CGM presentation. It was very helpful. Thanks!

Shujun
