### ISSUE TITLE
A little typo in README.md

### ISSUE THREAD

**Issue by fenguoerbian** [rstudio/blogdown#73]
I think in the paragraph starting by "The function `blogdown::serve_site()` may be the most" there is a little typo in the later sentence.
It should be "Do NOT use the command line `hugo server` to build or serve the site." instead of "Do NO use the command line `hugo server` to build or serve the site.". There is a missing letter T.

**Comment by yihui** [comment]
Thanks! Please consider a simple pull request next time if possible :)
