### ISSUE TITLE
consider deprecating all mentions/recommendations of Google Analytics

### ISSUE THREAD

**Issue by setgree** [rstudio/blogdown#731]
* the Danish Data Protection Agency has recently concluded that Google Analytics [cannot be used lawfully](https://www.datatilsynet.dk/english/google-analytics/use-of-google-analytics-for-web-analytics)
* It's reasonable to think that other agencies will follow suit (there's been some [early signs in that direction](https://www.androidpolice.com/google-analytics-gdpr-eu-violation/))
* The Blogdown book doesn't precisely _endorse_ Google Analytics, but does describe it as part of the [default flow](https://bookdown.org/yihui/blogdown/themes.html), which might be _read_ as a soft endorsement
* I recently installed [plausible analytics](https://plausible.io/) [on my own blog](https://github.com/setgree/setharielgreen/commit/adf2ed9e1290263ff286b40f779bf5dc0e75d8c8), and it took a bit of searching around but ultimately was not that hard
* Maybe the blogdown project as a whole should consider removing mentions of Google Analytics from its documentation/default templates and switching over to privacy-focused alternatives instead?

Thanks in advance!

**Comment by yihui** [comment]
Thanks for the suggestion! I've deemphasized Google Analytics (together with Disqus Comments, which also has this bad reputation). We didn't mean to endorse it, not even softly.

Personally I've also removed GA on my site two years ago: https://github.com/rbind/yihui/commit/1f82931ade7fc5907a1890397bacf1b7a72610ce
