### ISSUE TITLE
New Hugo version won't install on Windows; case change?

### ISSUE THREAD

**Issue by jonpeake** [rstudio/blogdown#733]
It appears that the newest Hugo versions changed the case of their .zip files for Windows from uppercase ('Windows') to lowercase ('windows'), and it's causing the `install_hugo()` function to fail when attempting to install the latest version (v0.104.0) and the previous version (v0.103.0). I was able to install v0.102.0 by specifying the version number in the function call.

**Comment by yihui** [comment]
Duplicate of #729

**Comment by yihui** [comment]
I have just released a new version of **blogdown** to CRAN.
