### ISSUE TITLE
lastest blogdown on CRAN (1.14) re-renders everything

### ISSUE THREAD

**Issue by pachadotdev** [rstudio/blogdown#739]
I detailed it here, a downgrade fixes it
https://stackoverflow.com/a/74337938/3720258

the affected version is
```
 blogdown    * 1.14    2022-11-04 [1] CRAN (R 4.2.1)
```

**Comment by yihui** [comment]
Sorry about that! For now you can set `options(blogdown.method = "html")` in your `.Rprofile` to fix the problem. I changed the default to `"markdown"` in 1.14. I'll revert this change in a patch version soon.

**Comment by yihui** [comment]
I just submitted a new version to CRAN, but it will need a CRAN maintainer's manual inspection (since the last release was less than 7 days ago), so it may take a day to pass.
