### ISSUE TITLE
Trouble with Formatted Text and Inline Code

### ISSUE THREAD

**Issue by fengkehh** [rstudio/blogdown#74]
Hi guys,

I am pretty new to the whole thing so my apologies for possibly dumb questions!  I am having trouble getting formatted text and inline codes to show up with the proper formatting.  For example, [this page](https://fengkehh.github.io/post/2017-03-16-how-this-blog-is-made-part-ii/) contains a bunch of `inline codes`, **bold texts** and *italic texts*. I see them when I knit them in RStudio.  However I don't see them when I build the website using build_site(). Any ideas on how to fix it? 

The .Rmd source is right here if you want to have a look: [source](https://github.com/fengkehh/blog-source/blob/master/content/post/2017-03-16-how-this-blog-is-made-part-ii.Rmd)

Much appreciated!

**Comment by yihui** [comment]
I think your theme reset the styles for `<code>`, `<strong>`, and `<em>`. I recommend you to ask the author of the theme.

**Comment by fengkehh** [comment]
You are right! I went digging on the theme's css file and removed the relevant elements from the reset block. Now it works much better. Thanks a bunch!
