### ISSUE TITLE
modelDown::modelDown() deleted all files in my output folder??!!

### ISSUE THREAD

**Issue by AbdurrahmanMN** [rstudio/blogdown#746]
First time to try modelDown::modelDown() and i specified output folder to my main folder of resources and textbooks. Now all files in this folder seem to be "disappeared". Any suggestion to rescue?

**Comment by yihui** [comment]
I guess you filed the issue to a wrong repo. This is **blogdown** repo, not **modelDown**. You may want to report to https://github.com/ModelOriented/modelDown/issues instead. Thanks!
