### ISSUE TITLE
Home directory does not exist in HUGO academic-theme

### ISSUE THREAD

**Issue by massonix** [rstudio/blogdown#747]
Hi!

I've been following [this tutorial](https://www.youtube.com/watch?v=68l-oQtkXYw&list=PLpZT7JPM8_GbPiX4ibrP7ogl7GyEofZMj&index=3) to create my personal website with blogdown. However, for some reason I do not have the directory "content/home". You can find the directory structure of my website in [this github repo](https://github.com/massonix/Massomics).

Do you know what might be going on?

Thanks!

Ramon

**Comment by yihui** [comment]
If you really need this directory, you can create it by yourself. The tutorial you mentioned was recorded in June 2021, and the hugo academic theme is still being actively developed, so I'm not surprised that this directory no longer exists in the theme.
