### ISSUE TITLE
Rmd files rendering with formatting issues

### ISSUE THREAD

**Issue by rikudoukarthik** [rstudio/blogdown#749]
I have been facing an issue with `.Rmd` blog posts in my `blogdown` [website](https://kartrick.rbind.io/) using the Hugo Apero theme. There is some discordance between the outputs of `.md` and `.Rmd` posts. I'll outline them below.

I have a series "Czech Birding" consisting of two posts: [the first](https://kartrick.rbind.io/blog/09_czech-birding/01_winter-bohemia/) written in `.md` ([source](https://github.com/rikudoukarthik/rikudou/blob/main/content/blog/09_czech-birding/01_winter-bohemia/index.md)) and [the second](https://kartrick.rbind.io/blog/09_czech-birding/02_pseudo-spring-bohemia/) `.Rmd` ([source](https://github.com/rikudoukarthik/rikudou/blob/main/content/blog/09_czech-birding/02_pseudo-spring-bohemia/index.Rmd)). The latter is resulting in strange formatting issues: 
- Font within headers has very little line spacing
- Although the headers are rendered in bigger and bolder text, they aren't recognised as headers by the sidebar (they should show up under "On this page", like they do in the `.md` post.

I originally had [rendering issues with `.Rmd`s](https://github.com/rstudio/blogdown/issues/169#issuecomment-1196579231) but that was resolved and the header formatting problems remained. I thought [this issue](https://github.com/rstudio/blogdown/issues/610) was similar, but the solutions there didn't help. Here is the output of `check_site()`:

```
> blogdown::check_site()
― Running a series of automated checks for your blogdown website project...
----------------------------------------------------------------------------------------------------
○ A successful check looks like this.
● [TODO] A check that needs your attention looks like this.
| Let's check out your blogdown site!
----------------------------------------------------------------------------------------------------
― Checking config.toml
| Checking "baseURL" setting for Hugo...
○ Found baseURL = "https://kartrick.rbind.io/"; nothing to do here!
| Checking "ignoreFiles" setting for Hugo...
○ "ignoreFiles" looks good - nothing to do here!
| Checking setting for Hugo's Markdown renderer...
○ All set! Found the "unsafe" setting for goldmark.
― Check complete: config.toml

― Checking index.Rmd in the root directory
○ index.Rmd is correctly configured.
― Check complete: index.Rmd

― Checking .gitignore
| Checking for items to remove...
○ Nothing to see here - found no items to remove.
| Checking for items to change...
○ Nothing to see here - found no items to change.
| Checking for items you can safely ignore...
○ Found! You have safely ignored: .DS_Store, Thumbs.db, .hugo_build.lock
| Checking for items to ignore if you build the site on Netlify...
○ Found! You have safely ignored: /public/, /resources/
| Checking for files required by blogdown but not committed...
○ Great! Did not find such files.
― Check complete: .gitignore

― Checking Hugo
| Checking Hugo version...
○ Found 4 versions of Hugo. You are using Hugo 0.111.3.
| Checking .Rprofile for Hugo version used by blogdown...
○ blogdown is using Hugo 0.111.3 to build site locally.
― Check complete: Hugo

― Checking netlify.toml...
○ Found HUGO_VERSION = 0.111.3 in [build] context of netlify.toml.
| Checking that remote & local Hugo versions match...
○ It's a match! Local and remote Hugo versions are identical (0.111.3).
| Checking that Netlify & local Hugo publish directories match...
○ Good to go - blogdown and Netlify are using the same publish directory: public
― Check complete: netlify.toml

― Checking content files
| Checking for validity of YAML metadata in posts...
○ All YAML metadata appears to be syntactically valid.
| Checking for previewed content that will not be published...
○ Found 0 files with future publish dates.
○ Found 0 files marked as drafts.
| Checking your R Markdown content...
○ All R Markdown files have been knitted.
○ All R Markdown output files are up to date with their source files.
| Checking for .html/.md files to clean up...
○ Found 0 duplicate .html output files.
○ Found 0 incompatible .html files to clean up.
| Checking for the unnecessary 'content/' directory in theme...
○ Great! Your theme does not contain the content/ directory.
― Check complete: Content
```
And here is my session info:
```
> xfun::session_info('rmarkdown')
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000), RStudio 2022.12.0.353

Locale:
  LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252    LC_MONETARY=English_India.1252
  LC_NUMERIC=C                   LC_TIME=English_India.1252    

Package version:
  base64enc_0.1.3 bslib_0.4.2     cachem_1.0.7    cli_3.6.1       digest_0.6.31   ellipsis_0.3.2 
  evaluate_0.20   fastmap_1.1.1   fs_1.6.1        glue_1.6.2      graphics_4.1.1  grDevices_4.1.1
  highr_0.10      htmltools_0.5.5 jquerylib_0.1.4 jsonlite_1.8.4  knitr_1.42      lifecycle_1.0.3
  magrittr_2.0.3  memoise_2.0.1   methods_4.1.1   mime_0.12       R6_2.5.1        rappdirs_0.3.3 
  rlang_1.1.0     rmarkdown_2.20  sass_0.4.5      stats_4.1.1     stringi_1.7.12  stringr_1.5.0  
  tinytex_0.44    tools_4.1.1     utils_4.1.1     vctrs_0.6.1     xfun_0.38       yaml_2.3.7     

Pandoc version: 2.19.2

> xfun::session_info('blogdown')
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000), RStudio 2022.12.0.353

Locale:
  LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252    LC_MONETARY=English_India.1252
  LC_NUMERIC=C                   LC_TIME=English_India.1252    

Package version:
  base64enc_0.1.3  blogdown_1.16    bookdown_0.33    bslib_0.4.2      cachem_1.0.7    
  cli_3.6.1        digest_0.6.31    ellipsis_0.3.2   evaluate_0.20    fastmap_1.1.1   
  fs_1.6.1         glue_1.6.2       graphics_4.1.1   grDevices_4.1.1  highr_0.10      
  htmltools_0.5.5  httpuv_1.6.9     jquerylib_0.1.4  jsonlite_1.8.4   knitr_1.42      
  later_1.3.0      lifecycle_1.0.3  magrittr_2.0.3   memoise_2.0.1    methods_4.1.1   
  mime_0.12        promises_1.2.0.1 R6_2.5.1         rappdirs_0.3.3   Rcpp_1.0.10     
  rlang_1.1.0      rmarkdown_2.20   sass_0.4.5       servr_0.26       stats_4.1.1     
  stringi_1.7.12   stringr_1.5.0    tinytex_0.44     tools_4.1.1      utils_4.1.1     
  vctrs_0.6.1      xfun_0.38        yaml_2.3.7      

Hugo version: 0.111.3
```

## Checklist

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] used `blogdown::check_site()` function to diagnose your site and corrected potential problems?

- [ ] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('blogdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

_This issue has existed since a year or so, at which point my R and RStudio were latest._

- [ ] installed and tested your bug with the development version of the blogdown package using `remotes::install_github('rstudio/blogdown')` ?

**Comment by cderv** [comment]
@rikudoukarthik I wonder if this is a Hugo Apéro limitation. 

The theme is using [`page.TableOfContent` Hugo feature](https://gohugo.io/content-management/toc/) for this `On this page` part, and this is working when Hugo itself is rendering Markdown to HTML. (as we can see in HTML [Source](https://github.com/hugo-apero/hugo-apero/blob/17f92f68899f672868c8f1e93a5b7d26232cf11d/layouts/partials/shared/section-sidebar.html#L35-L40) source for the theme)

This means to me that Hugo Apéro website will be only compatible with **blogdown** when using `.md` input, or when using `blogdown.method = 'markdown'` to that Rmd files are converted to `.md` file by **blogdown** and then rendered to HTML by Hugo.  See V1.0 blog post about this method option : https://posit.co/blog/blogdown-v1-0/

Default behavior of **blogdown** is to convert `.Rmd` file to `.html` using Pandoc - and with Hugo Apero I don't think we want this. Hugo Apéro demo website is [using this configuration](https://github.com/hugo-apero/hugo-apero-docs/blob/main/.Rprofile#L11)

**Comment by yihui** [comment]
I also recommend generating `markdown` instead of `html` output: https://github.com/rikudoukarthik/rikudou/blob/f0f865b5bcfa5347097094a52293dc871cf3f084/.Rprofile#L22

Note that **blogdown** itself has changed the default from `html` to `markdown` last year: c90b504c65c672f8b71a8b6a47ffb603bb7a5fe1 But this change only affects new sites created after [blogdown 1.14](https://github.com/rstudio/blogdown/releases/tag/v1.14) (Nov 7, 2022). Older sites still have `html` as the default output format in their `.Rprofile`.

**Comment by rikudoukarthik** [comment]
@cderv Thanks. I was able to resolve the original issue in all posts except for [this one](https://github.com/rikudoukarthik/rikudou/blob/main/content/blog/07_turnofyear/index.md) which is a pure `.md` file. Here, the sidebar should show `On this page` but it doesn't. Is this a bug, or is there something I need to change somewhere?

**Comment by cderv** [comment]
@rikudoukarthik what is the issue with https://kartrick.rbind.io/blog/07_turnofyear/ ? 

I see the single-sidebar layout that you defined in your YAML https://github.com/rikudoukarthik/rikudou/blob/3dcb063682bbd608aeff780ee16393b3fa71bb16/content/blog/07_turnofyear/index.md?plain=1#L7

This page does not seem part of a series like your initial "Czech Birding" one :think

**Comment by cderv** [comment]
> I thought the On this page section appears in the sidebar regardless of whether or not it is a "series" post, and found it weird that it isn't appearing in this post.

No I don't think it does appear anywhere. As mentioned in my previous post (https://github.com/rstudio/blogdown/issues/749#issuecomment-1484730805), this is a hugo apéro feature and I pointed to the source https://github.com/hugo-apero/hugo-apero/blob/17f92f68899f672868c8f1e93a5b7d26232cf11d/layouts/partials/shared/section-sidebar.html#L35-L40 

It seems to me this specific hugo template html is used only in the collection / serie layout for now. You can look more into hugo apéro example to understand. 

At the bottom this is a hugo feature: https://gohugo.io/content-management/toc/ so you can tweak the template if you want some customization. 

Anyhow, not a **blogdown** feature - this is template specific so you should look at it this way.

**Comment by rikudoukarthik** [comment]
@cderv Thanks for pointing me in the right direction!
