### ISSUE TITLE
Different template

### ISSUE THREAD

**Issue by bhaskarvk** [rstudio/blogdown#75]
As per https://github.com/rstudio/blogdown/blob/4e15797ecb2eb29f1710af9184a6524c754316b5/R/format.R the template is fixed and can not be specified.
I wanted to build a custom template using HTML5 semantic tags. How do I go about specifying a diff template? Could knitr hooks help ?

**Comment by yihui** [comment]
Here is the default template: https://github.com/rstudio/blogdown/blob/master/inst/resources/template-minimal.html What else you want to do in the template? I don't get what you mean by "HTML5 semantic tags".

**Comment by bhaskarvk** [comment]
I wanted to tweak the TOC a bit. Here's a link on semantic tags https://www.w3schools.com/html/html5_semantic_elements.asp. The idea is to use elements like `<nav>` , `<section>` etc. instead of divs. So for this particular template I wanted the TOC in a `<nav>` tag.
For now I am happy to just fork blogdown and customize the template, but for long run it would be better if we can provide the template argument as frontmatter option which is picked up by the function instead of the default template.

**Comment by yihui** [comment]
I haven't said no yet :)

**Comment by bhaskarvk** [comment]
Thanks! It would be really nice to be able to supply a custom template. TBH, for markdowns which don't have HTML Widgets I was thinking of using `rmarkdown::github_document` format and let hugo do the conversion using blackfriday.

**Comment by yihui** [comment]
The template argument has been exposed and documented here: https://bookdown.org/yihui/blogdown/default-template.html
