### ISSUE TITLE
Blogdown don’t supports multiple-column rmarkdown 

### ISSUE THREAD

**Issue by ShichenXie** [rstudio/blogdown#751]
The rmarkdown supports multiple columns format, [chapter 5.8](https://bookdown.org/yihui/rmarkdown-cookbook/multi-column.html). However, a multiple-column formatted rmd file cannot export a desired html in blogdown.

**Comment by yihui** [comment]
There are many possible reasons why it doesn't work. Please provide a full example (ideally, a Github repo that I can clone).

**Comment by ShichenXie** [comment]
Please see the Github repo [blogdown_multicolrmd](https://github.com/ShichenXie/blogdown_multicolrmd). The first post doesn't worked as it should be. Thanks.

**Comment by ShichenXie** [comment]
Great! It works, thanks.

**Comment by ShichenXie** [comment]
BTW, It works after I delete those auto-created `.md` files manually.

**Comment by yihui** [comment]
Glad to know it works now!

> BTW, It works after I delete those auto-created `.md` files manually.

This problem can be identified by `blogdown::check_site()`.
