### ISSUE TITLE
Wrong relative links on the pkgdown site

### ISSUE THREAD

**Issue by yihui** [rstudio/blogdown#754]
https://pkgs.rstudio.com/blogdown/

e.g., the "Get started" link should be https://pkgs.rstudio.com/blogdown/articles/blogdown instead of https://pkgs.rstudio.com/articles/blogdown All other relative links are also missing `/blogdown/` in the paths.

Same problems exist on the bookdown site (and perhaps also other pkgdown sites): https://pkgs.rstudio.com/bookdown/

**Comment by cderv** [comment]
Thanks ! 

This is a Netlify issue with pretty url. It seems they are still investigating that. In the meantime, after discussion with @gadenbuie, I deactivated pretty url that we don't use and it should be fixed now. 

All our website with redirects were impacted. 

I let you test on your side too and confirm. It seems to be working on my side now.

**Comment by yihui** [comment]
Thanks! It's indeed fixed now. I think it's a good idea to disable pretty URLs on Netlify.
