### ISSUE TITLE
allow use of hugo.toml for config [FR]

### ISSUE THREAD

**Issue by drmowinckels** [rstudio/blogdown#755]
Hugo 0.110.0 changed the default configuration base file name to hugo, e.g. hugo.toml. 

https://gohugo.io/getting-started/configuration/#hugotoml-vs-configtoml

Hugo will continue supporting config.toml for the time being, but its best practise from now on to use hugo.toml.

**Comment by yihui** [comment]
It should be supported in the latest version of **blogdown**: https://github.com/rstudio/blogdown/releases/tag/v1.18 If not, it is a bug and I'll fix it. Thanks!

**Comment by drmowinckels** [comment]
sorry! I'm juggling two computers at the moment, one which I have update Hugo and the other apparently not! SHould have double checked before reporting in. Update Hugo and all is well!

**Comment by yihui** [comment]
No worries! I didn't test it thoroughly and thought I missed something. Good to know it actually works for you!
