### ISSUE TITLE
blogdown book content request

### ISSUE THREAD

**Issue by pssguy** [rstudio/blogdown#78]
It would be really helpful if you could cover the procedures for the following items

* Disqus
* googleAnalytics
* RSS feeds

Also how to reference in relation to a post images and files which you might wish to both load and save from code

Thanks

**Comment by yihui** [comment]
Thanks for the suggestions. I understand the three bullets, but I'm not sure what you mean by referencing images and files.

**Comment by Lauler** [comment]
Adding to OP: I'd like to see instructions on how to post/host rmarkdown documents with their original theme and layout (for example tufte theme). 

Potentially this could be opened as a separate issue or feature request. Having a blogdown option on whether hugo should process the rmarkdown file or whether the rmarkdown should be published on its own page with its original theme/css. 

I don't know how much work that would entail, but I'd love to be able to post tufte theme markdowns, and have the picture/title on the website link straight to the rmarkdown html which would have its own separate css/js, unprocessed by hugo partials apart from linking the picture and title on the main page to the published document.

**Comment by pssguy** [comment]
@yihui

To clarify, hopefully.

So currently I store a data file in mySite>content>post>data>info.rds

and reference this in page1.rmd via
df <- readRDS("data/info.rds")

Is this the best practice, or should I be storing it in the mySite>static folder. 

Currently, I store images in a mySite>static>img folder and reference them
/img/myImage.png in the text of a rmarkdown file

One additional point, for each blog post I am loading several packages so there is a lot of duplication across the blogdown site e.g library(tidyverse) appears in vetrually every Rmd file. Is there a way to just load them once - similar to use of global.R in a shiny site

**Comment by yihui** [comment]
@pssguy Google analytics and Disqus have been documented at https://bookdown.org/yihui/blogdown/templates.html You will need probably two or three hours to digest this hugo-xmin theme.

RE: `readRDS()` and images, I don't have better suggestions.

RE: global.R, you can use `.Rprofile`: https://bookdown.org/yihui/blogdown/global-options.html

@Lauler Please see https://bookdown.org/yihui/blogdown/static-files.html (you need to read the example Github repo).
