### ISSUE TITLE
repeated blogs when using Rmd file 

### ISSUE THREAD

**Issue by yajiez** [rstudio/blogdown#79]
Hi, the blogdown is so great that I have decided to move my blog from hexo to it, and I found a very clean and beautiful blog template from your GitHub: [https://github.com/yihui/blogdown-yihui-template](https://github.com/yihui/blogdown-yihui-template), however, when I test the usage of Rmd blog post, after I ran `blogdown::serve_site()`, there were two repeated blogs with the same title shown up, and I found there are three files in the "content" directory with the same filename but different format: Rmd, md, and html, I can't figure out how to deal with it, Could you help to tell me what I need do? Thank you very much!

**Comment by xiruizhifu** [comment]
Hi, I have solved this problem by reading the user manual of `blogdown` and the source code of your blog, and I guess the problem may be the use of build.R script inside the `R/` directory, so it's necessary to add some configure params using the `.Rprofile` file and it seems that these actions resolved my problem.

However, I am not sure whether I am right, **so I will leave this issue open hoping that you can tell me about the real reason of this problem**, or maybe you can make some comment about this problem in the user manual of `blogdown`.

Your work has helped a lot of people and more and more people will benefit from it, thanks very much!

**Comment by yihui** [comment]
You were correct. `options(blogdown.method = 'custom')` was the key. I just added it to the template. Thanks for the report!
