### ISSUE TITLE
easy pushing of public folder contents to github with RStudio

### ISSUE THREAD

**Issue by jslingsby** [rstudio/blogdown#81]
Great package Yihui, Amber!

An afternoon's fiddling was enough to come up with a [site that I'm very happy with using the Tracks theme](https://jslingsby.github.io/) (obviously lots of content and tweaks to add etc, including attribution).

This suggestion may reflect my general ignorance and newbeeism when it comes to building and posting static websites (and/or using github with RStudio), but one feature that I thought would be very handy to add is a simple way of pushing just the public folder contents to github from RStudio for a gitpages site. [There are workarounds from command line](https://gist.github.com/cobyism/4730490), but it'd be a final step in an otherwise very smooth process if there were a tab under Addins or similar.

Keep it up!
Jasper

**Comment by yihui** [comment]
I haven't had a chance to complete the documentation yet, but I strongly believe that Netlify is a much better approach than Github pages: https://bookdown.org/yihui/blogdown/deployment.html
