### ISSUE TITLE
new_post() fails in both addin and command line in a  Chinese setting

### ISSUE THREAD

**Issue by Jiangtang** [rstudio/blogdown#83]
Hi Yihui,

One month ago I used the blogdown (in Rstudio with addins) to reformat my blog in Chinese and it went very well: http://jiangtanghu.com/cn/

And the source is in: https://github.com/Jiangtang/writing/tree/master/cn

Last night I opened Rstudio, updated all packages as usual through the GUI. First I tried to use the *New Post* addin, but got errors:
```
Error in readUTF8(f) : 
  File content/post/2006-06-03-??,??????,??????.md does not exist
```
Then I tried to type `blogdown:::new_post()`, then got this one:
```
Error in gsub("[^[:alnum:]]+", "-", string) : 
  argument "title" is missing, with no default
```
I can still use the *Build Website* to render all my existing .md files. 

When switched to my English blog project: https://github.com/Jiangtang/writing/tree/master/blog, I was able to use the *New Post* addin. So, the issue I have is not able to create a new post for my Chinese site.

I will create a new project for my Chinese blog and hope all goes well. I leave such information if it's in your interests:) `devtools::session_info('blogdown')`:
```
Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, mingw32             
 ui       RStudio (1.1.76)            
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2017-04-07                  

Packages ----------------------------------------------------------------------
 package   * version date       source                           
 backports   1.0.5   2017-01-18 CRAN (R 3.3.2)                   
 base64enc   0.1-3   2015-07-28 CRAN (R 3.3.0)                   
 bitops      1.0-6   2013-08-17 CRAN (R 3.3.0)                   
 blogdown    0.0.25  2017-04-07 Github (rstudio/blogdown@1c10d16)
 bookdown    0.3.17  2017-04-07 Github (rstudio/bookdown@327e886)
 caTools     1.17.1  2014-09-10 CRAN (R 3.3.1)                   
 digest      0.6.12  2017-01-27 CRAN (R 3.3.3)                   
 evaluate    0.10    2016-10-11 CRAN (R 3.3.3)                   
 highr       0.6     2016-05-09 CRAN (R 3.3.1)                   
 htmltools   0.3.5   2016-03-21 CRAN (R 3.3.1)                   
 httpuv      1.3.3   2015-08-04 CRAN (R 3.3.1)                   
 jsonlite    1.3     2017-02-28 CRAN (R 3.3.3)                   
 knitr       1.15.19 2017-04-07 Github (yihui/knitr@6f166e2)     
 magrittr    1.5     2014-11-22 CRAN (R 3.3.1)                   
 markdown    0.7.7   2015-04-22 CRAN (R 3.3.1)                   
 mime        0.5     2016-07-07 CRAN (R 3.3.1)                   
 Rcpp        0.12.10 2017-03-19 CRAN (R 3.3.3)                   
 rmarkdown   1.4     2017-03-24 CRAN (R 3.3.3)                   
 rprojroot   1.2     2017-01-16 CRAN (R 3.3.3)                   
 servr       0.5     2016-12-10 CRAN (R 3.3.3)                   
 stringi     1.1.1   2016-05-27 CRAN (R 3.3.0)                   
 stringr     1.2.0   2017-02-18 CRAN (R 3.3.3)                   
 yaml        2.1.14  2016-11-12 CRAN (R 3.3.3)    
```

**Comment by Jiangtang** [comment]
A quick update: 

I created a new project for the same Chinese blog:

* I can still use *Build Website* to render all the existing .md files.
* `new_post()` still failed in using both addin and command line.
* A workaround is to create .md file manually then to use  *Build Website* button.

**Comment by yihui** [comment]
The reason is that your filenames contain Chinese characters but your system locale is English. This could be a bug of R, and unfortunately it is out of my control. Anyway, two possible solutions: 

1. Either change your system locale to Chinese, or at least change the locale in the current R session using `Sys.setlocale(, 'Chinese')`. For the former, I don't remember which option you need to change from the Windows control panel:

    ![image](https://cloud.githubusercontent.com/assets/163582/24826283/a28c710e-1bf7-11e7-9a60-76de24c8a3a8.png)

    ![image](https://cloud.githubusercontent.com/assets/163582/24826287/b680a9b4-1bf7-11e7-90a5-a57985e65f15.png)

2. Rename the markdown files and remove multibyte characters. That is what I do for my Chinese blog: https://github.com/rbind/yihui/tree/master/content/cn

**Comment by Jiangtang** [comment]
Thanks Yihui. I can live with it creating .md file by hand.

**Comment by TianyiShi2001** [comment]
@Jiangtang If you use VS Code, I am writing a [VS Code extension](https://marketplace.visualstudio.com/items?itemName=TianyiShi.rmarkdown&ssr=false#overview) as a wrapper for Rmarkdown, Bookdown and  Blogdown. Its `new post` command works with CJK characters.
