### ISSUE TITLE
wrong relative paths when using other themes

### ISSUE THREAD

**Issue by pzhaonet** [rstudio/blogdown#84]
Hi Yihui. Thanks a lot again for the great package! The default theme works perfectly. Following your online book of blogdown, I am trying to build an academic website with the commands:

    blogdown::new_site(theme = "gcushen/hugo-academic")

The viewer of RStudio IDE looks fine, but when I browse `public\index.html` with chrome or firefox or IE, it seems that all the relative paths are wrong.  css files are not loaded properly, and the links to other pages in the navigation bar such as `posts` are wrong. I have tried `simply-a` theme, and there is  the same problem. 

The comparison between `public\index.html` files produced by the default theme and academic theme shows that the problem comes from the relative paths.  The paths in `index.html` by default theme are such as :

```
<link rel="stylesheet" href="./css/fonts.css" media="all">
<link rel="stylesheet" href="./css/main.css" media="all">
<img src="./images/logo.png"
```

while by academic theme, the paths in `index.html` are such as:

```
  <link rel="stylesheet" href="/css/highlight.min.css">
  <link rel="stylesheet" href="/css/bootstrap.min.css">
  <link rel="stylesheet" href="/css/font-awesome.min.css">
  <link rel="stylesheet" href="/css/academicons.min.css">
  <link rel="stylesheet" href="//fonts.googleapis.com
  <link rel="stylesheet" href="/css/hugo-academic.css">
   <link rel="alternate" href="/index.xml" type="application/rss+xml" title="Academic">
  <link rel="feed" href="/index.xml" type="application/rss+xml" title="Academic">
  <link rel="icon" type="image/png" href="/img/icon.png">
```

If I add `.` before `/css`, then the web browser can display the page correctly.

I am wondering if it is a bug of the package or the theme, or something is wrong with my computer. My sessionInfo():

```
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Chinese (Simplified)_People's Republic of China.936 
[2] LC_CTYPE=Chinese (Simplified)_People's Republic of China.936   
[3] LC_MONETARY=Chinese (Simplified)_People's Republic of China.936
[4] LC_NUMERIC=C                                                   
[5] LC_TIME=Chinese (Simplified)_People's Republic of China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9     bookdown_0.3.17 digest_0.6.12   rprojroot_1.2   mime_0.5       
 [6] backports_1.0.5 magrittr_1.5    evaluate_0.10   blogdown_0.0.26 stringi_1.1.2  
[11] rstudioapi_0.6  rmarkdown_1.4   tools_3.3.3     servr_0.5       stringr_1.2.0  
[16] httpuv_1.3.3    yaml_2.1.14     htmltools_0.3.5 knitr_1.15.19  

```

**Comment by dapengde** [comment]
I believe it is a problem of deployment. Locally browsing index.html of the academic theme needs the support of `blogdown::serve_site()`, while browsing index.html of the default theme does not. I uploaded the `public\` folder of the default theme to my own server and it can be visited successfully, while it failed when I did the same to the academic theme. But I uploaded the `public\` folder of the academic theme to Netlify, and it was deployed successfully. At the moment I have no idea how to deploy it on my own server.

**Comment by yihui** [comment]
In short, you need to set `relativeurls` to `true` in config.toml.

To really understand this issue, you will need to have some knowledge of how absolute and relative paths work locally / remotely / under a subdirectory of a domain / at the top level of a domain. It will take me a good chunk of time to explain all these cases to you, which I prefer not to do at the moment, but I'll remember to document these things eventually.

For now, you only need to remember two things. The first is from https://bookdown.org/yihui/blogdown/methods.html

> If your website is supposed to be placed in a subdirectory under a domain name (e.g., `http://example.com/my-project/`) when it is published, you must use `relativeurls = true` in `config.toml`.

The second is that you'd better not double-click the local HTML files and open them directly in your browser. Use the "Serve Site" addin or equivalently, `blogdown::serve_site()` to start a web server to view your website. This is a better simulation of what you will see when your website is published to a real server.

**Comment by dapengde** [comment]
Thank you for your reply. Sorry for the lack of my knowledge in being a spiderman. There seems a lot to learn, which must already have been available somewhere in Internet. When will the book of blogdown be ready? I am looking forward to it, especially the chapter Migration from Wordpress.

**Comment by dapengde** [comment]
Yes, all I did was uploading the files in the  `public\` folder to a subdirectory of my WordPress blog site. The default theme worked, while the academic theme did not. Now with `relativeurls = true`, both work successfully. Demo pages:

http://dapengde.com/blogdown_demo_default/
http://dapengde.com/blogdown_demo_academic/

A newbee might repeat my stupid experience. One might run `blogdown::new_site()`, immediately upload the folder to a server, and enjoy the fun of visiting it. Then he/she might do the same to  `blogdown::new_site(theme='gcushen/hugo-academic')` but fails. It is very confusing. Thus I have a little suggestion. Could the behavior be consistent between different themes? I mean, the setting of relativeurls could be  always true for all themes, or false for all, after running `blogdown::new_site()`. 

Anyway, the problem has been solved for me! Thanks a lot!

**Comment by ShKlinkenberg** [comment]
@dapengde I see in your example that your avatar (portrait photo on home page) is not working. Mine also isn't working when hosting on GitHub pages. The local rendering is fine but only it does not work.

@yihui I see that a . is missing in the URL for the background image. I've been working the config.toml file like crazy but can't seem to solve this. 

`<div class="portrait" itemprop="image" style="background-image: url('/img/portrait.jpg');">
      </div>`

Should be

`<div class="portrait" itemprop="image" style="background-image: url('./img/portrait.jpg');">
      </div>`

Even if I add an absolute path it still prefixes '/img/my-absolute-path' 

Any suggestions?

**Comment by dapengde** [comment]
@ShKlinkenberg I set up another demo site in the same way and noticed the avatar problem as you mentioned. And I solved it. This is the site:

http://dapengde.com/xuer/

The only thing I did was using the complete url rather than the relative url in config.toml:

```
baseurl = "http://dapengde.com/xuer"
# relativeurls = true
```

Good luck!

**Comment by ShKlinkenberg** [comment]
@dapengde could you also share the config.toml file with me? I followed your steps and it is still not working for me.

**Comment by dapengde** [comment]
@ShKlinkenberg you can find it here: https://github.com/dapengde/netlify_zhao/blob/master/config.toml

It has the same settings as the one I mentioned before.

**Comment by dlebauer** [comment]
@pzhaonet could you please clarify how you got this to work? Did you use `blogdown::new_site(theme = "gcushen/hugo-academic")` in the empty root directory the site that appears in the Rstudio viewer pane without css styling, and `relativeurls = true` does not solve this.

![image](https://cloud.githubusercontent.com/assets/464871/26267662/fed81420-3cb0-11e7-989f-59a63a98d305.png)

**Comment by yihui** [comment]
@dlebauer I can reproduce the issue, and will fix it in a few minutes.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

To all, please ignore whatever I said above, everything should work out of the box now.

**Comment by dlebauer** [comment]
Thanks!!!!!

**Comment by axlehner** [comment]
I think this is an issue again. Profile picture not displaying even though it is online under its url.
(this is true also for @pzhaonet 's page)

**Comment by giabaio** [comment]
Hi all,
I think I too am having this issue. I have set up 
`canonifyURLs = false` and `relativeURLs = true` in my config.toml but unless I hack the `index.html` under the generated public folder to add a "." in the string pointing to my avatar in the img/ folder, it won't show up...
Am I missing something obvious?
Thanks
Gianluca

**Comment by rannbaron** [comment]
I also have this issue. I have `canonifyURLs=true` and `relativeURLs=false` in my config.toml. As above, hacking the `index.html`files makes it work, but otherwise it doesn't show up. Help please!

**Comment by lcolladotor** [comment]
Hi,

I'm seeing this same issue with a `blogdown` blog using the `hugo-academic` theme by @gcushen in RStudio Cloud. It doesn't add the `.` before `/img/female.png` for the `avatar` but it does for the `logo`. @ShanEllis has tried it with RStudio on her laptop and `blogdown::serve_site()` shows the correct preview there.

Here are the relevant bits of the `config.toml` file:

```
baseurl = "/"
relativeurls = true
canonifyurls = false

avatar = "female.png"
logo = "female.png"
```

## `logo` works:

<img width="617" alt="screen shot 2018-09-07 at 4 10 58 pm" src="https://user-images.githubusercontent.com/2288213/45241241-a3b45b00-b2b9-11e8-8a80-adb4904123e1.png">

## `avatar` doesn't:

<img width="680" alt="screen shot 2018-09-07 at 4 11 50 pm" src="https://user-images.githubusercontent.com/2288213/45241263-b6c72b00-b2b9-11e8-8df1-01b1aeeee833.png">

We had to add `relativeurls = true` otherwise it wouldn't work on RStudio Cloud (since the preview opens in a tab with an url like https://jane-doe.rstudio.cloud/0ac30ee59da846df83e6860233bc6ec3/p/6085/). 

I also see that it's more complicated in this case than the HTML `<img>` tag that gets used for the logo. You can see that in the `meta` HTML tag with `content="//localhost:1313/img/female.png"`.

## Version info

```
$ hugo version
Hugo Static Site Generator v0.48 linux/amd64 BuildDate: 2018-08-29T06:33:51Z
$ grep version themes/hugo-academic/data/academic.toml
version = "2.4.0"
> packageVersion('blogdown')
[1] ‘0.8’
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8    
 [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C             
 [9] LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18    bookdown_0.7    later_0.7.4     digest_0.6.16   rprojroot_1.3-2 R6_2.2.2        backports_1.1.2
 [8] magrittr_1.5    evaluate_0.11   blogdown_0.8    stringi_1.2.4   promises_1.0.1  rmarkdown_1.10  tools_3.5.0    
[15] servr_0.10      stringr_1.3.1   httpuv_1.4.5    xfun_0.3        yaml_2.2.0      compiler_3.5.0  htmltools_0.3.6
[22] knitr_1.20 
```

**Comment by yihui** [comment]
@lcolladotor I believe your issue is a duplicate of #124 (RStudio Cloud is based on RStudio Server).

**Comment by lcolladotor** [comment]
Thank Yihui!

 Indeed it looks like it's due to the use of `absURL` in https://github.com/gcushen/hugo-academic/blob/f45e2c0ca518c458cb3b6259ee2ccd1a100e09bd/layouts/partials/widgets/about.html#L13-L14 in the `hugo-academic` theme. I got there based on your comment https://github.com/rstudio/blogdown/issues/124#issuecomment-326111365 (and others) on the issue you linked to.
