### ISSUE TITLE
Labeling R code chunks prevents blogdown from linking pictures correctly

### ISSUE THREAD

**Issue by harlecin** [rstudio/blogdown#85]
Inserting a picture in a chunk like this works fine:

```
```{r}
plot(iris)
```

But if I label the code chunk, the figure is not linked correctly, i.e. the html page shows the missing-image-icon:

```
```{r not working}
plot(iris)
```

Putting quotes around the label does not work for me either:
```
```{r 'not working'}
plot(iris)
```

Thx a lot btw, for this awesome package:)

**Comment by yihui** [comment]
Please see the last paragraph on this page: https://bookdown.org/yihui/blogdown/output-format.html (Yeah I know it is kind of surprising and hard to find)

**Comment by harlecin** [comment]
Thx a lot!

**Comment by yihui** [comment]
FYI, if you reinstall the devel version of blogdown here, this issue should be gone, but I still recommend you not to use spaces in chunk labels.
