### ISSUE TITLE
Consider allowing user the option to specify bin_paths

### ISSUE THREAD

**Issue by cboettig** [rstudio/blogdown#87]
Awesome work on blogdown.  Just wondering if you'd consider modifying `install_hugo()` to take an optional argument for `bin_paths`?  The `bin_paths()` helper routine looks great, but for Linux systems at least it looks like this basically ends up using `~/bin`, whereas one might imagine the user having a difference preference.  

(I do think there's still a compelling use for a linux user to use `install_hugo`, since hugo isn't in older apt sources, or at least not the latest version, and the convenience of the R function to install hugo is nice -- e.g. adding the logic to get the tag number for the latest release makes for a cumbersome bash script on a CI platform or Dockerfile).

**Comment by yihui** [comment]
I think that is a good suggestion. Thanks!

**Comment by yihui** [comment]
Done. You can set `options(blogdown.hugo)` to the path of the Hugo executable now.

**Comment by cboettig** [comment]
@yihui Great, that makes sense.

Though actually I had something else in mind, I'd also like to see an argument added to the `install_hugo()` function that would allow the user to set the path that is currently hardwired in this line: https://github.com/rstudio/blogdown/blob/master/R/install.R#L114


It looks like the recent commit helps the user configure `blogdown` to use an instance of `hugo` that has been installed to an arbitrary path, but currently doesn't address the question of allowing the user to actually use `install_hugo()` to install to a custom path.  Sorry if I'm not making sense.

**Comment by yihui** [comment]
Sorry I missed that. Now I have changed the option to `blogdown.hugo.dir` so that both `install_hugo()` and `find_hugo()` can make use of this global option.

**Comment by cboettig** [comment]
Awesome, thanks much.

Really enjoying blogdown and Hugo so far.  Thanks for the great work.

 Cheers,
