### ISSUE TITLE
DT package not working with hugo-future-imperfect theme

### ISSUE THREAD

**Issue by pssguy** [rstudio/blogdown#88]
I have a blogdown site based on the hugo-future-imperfect theme where a DT output is created correctly in the rmd but the data is not shown (although the headings are) when applying serve_site/build_site

I have created two brand new sites ( so with no other complications) to illustrate the issue.  This is the code and outputs

```{r DT}
library(DT)
library(tidyverse)
glimpse(iris)

iris %>% 
  datatable()
```

a) default theme
![defaulttheme](https://cloud.githubusercontent.com/assets/2775918/25194216/967bd5f8-24ee-11e7-8a4b-8851a859f1e4.png)

b) hugo-imperfect
![imperfecttheme](https://cloud.githubusercontent.com/assets/2775918/25194233/a4ddce4e-24ee-11e7-93e6-c07d192a046d.png)

The problem also occurs with the plotly package and hugo-imperfect

**Comment by pssguy** [comment]
Similar to [issue 20](https://github.com/rstudio/blogdown/issues/20)

[Hack solution](http://stackoverflow.com/questions/43594039/dt-package-not-working-with-blogdown-using-hugo-future-imperfect-theme)

Pending a long-term solution, it would be helpful to know which widgets and themes this issue occurs with

**Comment by ThierryO** [comment]
the issue occurs with hugo-tranquilpeak theme and DT as well

**Comment by pssguy** [comment]
@ThierryO 
FYI, I switched to Icarus - with no problems so far

**Comment by yihui** [comment]
Sorry I don't have time to investigate this issue in hugo-tranquilpeak or hugo-future-imperfect. If I were to do it, I'd first look at the JavaScript console of my browser to see if there are any errors.

**Comment by andrie** [comment]
For reference, the JavaScript console error is:

```javascript
Uncaught TypeError: $table.DataTable is not a function
    at Object.renderValue (datatables.js:269)
    at htmlwidgets.js:625
    at Array.forEach (<anonymous>)
    at forEach (htmlwidgets.js:55)
    at htmlwidgets.js:551
    at Array.forEach (<anonymous>)
    at forEach (htmlwidgets.js:55)
    at Object.window.HTMLWidgets.staticRender (htmlwidgets.js:549)
    at HTMLDocument.<anonymous> (htmlwidgets.js:638)
```

The [StackOverflow](https://stackoverflow.com/questions/31227844/typeerror-datatable-is-not-a-function) question is related, and it seems the most likely underlying root cause is that `jQuery` should be loaded before `jQuery datatables`.

**Comment by yihui** [comment]
Appendix D.6 might be helpful: https://bookdown.org/yihui/blogdown/html-widgets.html

**Comment by andrie** [comment]
I switched to use the Icarus theme.

**Comment by jarrodscott** [comment]
Can anyone please tell me if there is a good fix for this? Aside from switching themes? I have the same problem in Hugo-Academic &  Tranquilpeak. [This Stackoverflow](https://stackoverflow.com/questions/43594039/dt-package-not-working-with-blogdown-using-hugo-future-imperfect-theme) solution sort of works but the datatable doesn't look good and the container is not responsive.
