### ISSUE TITLE
Preview of Post in Tranquilpeak Theme Not Working for Rmd (does for md)

### ISSUE THREAD

**Issue by rlucas11** [rstudio/blogdown#92]
Great package! This is really useful. I'm trying to set up a new site and everything is mostly working. I decided to try the tranquilpeak theme, which also mostly works. But I noticed that the previews of the individual posts on the home page don't work the same when I use Rmd versus md. Specifically, when I use md, just the first element of the post shows up (whether that is a title or a paragraph), but when I use Rmd, the preview seems to continue on until it reaches a certain length. For example, the image below shows one of the posts from the tranquil peak example site, saved as an Rmd (top) versus md (bottom). You can ignore the fact that the shortcodes are showing up wrong, I saw the other issue about fixing that, and the problem I'm describing happens even just for regular text.

![tranquil](https://cloud.githubusercontent.com/assets/670024/25394283/80b82124-2992-11e7-8868-96232a274532.png)

Any thoughts about why this is happening and how I can get the style from the md files for the Rmd files?

**Comment by yihui** [comment]
I'm not sure, but from my experience, the preview text here is probably generated from the variable `.Summary`. Hugo's automatic summary is often problematic ([see documentation](https://gohugo.io/content/summaries/)), and I'd replace it with `(default .Summary .Description)`. That way, if the automatic summary is not good, I can define an option `description` in the YAML to override it.

**Comment by rlucas11** [comment]
Great, thanks! I'm just learning how to use hugo, so I'm not entirely sure what to do with that. I found a "summary.html" template in the theme directory, which seems to take .Summary and formats it for use on index pages, etc. I tried replacing that with .Description, which seems to work; but I'm not sure this is the best approach. Do you recommend something different?

**Comment by yihui** [comment]
Here is what I claim to be the only sensible approach to generate a summary of a post:

https://github.com/yihui/hugo-xmag/blob/008049574/layouts/_default/list.html#L32-L37

It is flexible (there are several options you can set), and does a much better job than Hugo's default summary method in the sense that the text is often more human-readable.

**Comment by yihui** [comment]
I just explained the template code in this post: https://yihui.name/en/2017/08/hugo-post-summary/

**Comment by pchhina** [comment]
Thanks Yihui, this is really helpful!
