### ISSUE TITLE
URLs for Disqus and FB/Twitter/LI shares do not contain full path

### ISSUE THREAD

**Issue by gsimchoni** [rstudio/blogdown#93]
Hi,

In my config.toml I specify:

`baseurl = "http://my-site.com/"`

However when the various index html files are created via `new_post` or `serve_site` the URLs for Disqus are not the full URLs and Disqus won't work. Only if I manually change the URL to the full one, it works. Same goes with the URLs for sharing on Facebook/Twitter/etc, if I manually change them it's OK but it's a bad workaround because blogdown will run over my manual changes every time I re-serve the site, and the Share functionality won't work.

Example:

For Disqus I get: `var disqus_url = '\/2017\/04\/25\/2017-04-25-name-of-post\/';`
Instead of: `var disqus_url = 'http:\/\/my-site.com\/2017\/04\/25\/2017-04-25-name-of-post\/';`

For Facebook I get: `<a class="icon-facebook" href="https://www.facebook.com/sharer/sharer.php?u=%2f2017%2f04%2f25%2f2017-04-25-name-of-post%2f"`
Instead of: `<a class="icon-facebook" href="https://www.facebook.com/sharer/sharer.php?u=my-site.com%2f2017%2f04%2f25%2f2017-04-25-name-of-post%2f"`

Am I missing something?

Theme: `https://github.com/jbub/ghostwriter`

> R version 3.3.3 (2017-03-06)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] shiny_1.0.0
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.8     bookdown_0.3.18 digest_0.6.12   rprojroot_1.2   mime_0.5        R6_2.2.0       
>  [7] jsonlite_1.4    xtable_1.8-2    backports_1.0.5 magrittr_1.5    evaluate_0.10   blogdown_0.0.27
> [13] stringi_1.1.2   miniUI_0.1.1    rstudioapi_0.6  rmarkdown_1.4   tools_3.3.3     servr_0.5.5    
> [19] stringr_1.2.0   yaml_2.1.14     httpuv_1.3.3    htmltools_0.3.5 knitr_1.15.19

**Comment by yihui** [comment]
`serve_site()` is only for local preview. If you want to publish the site, you need to run `blogdown::build_site()` so that `baseurl` is actually written to all pages.

**Comment by gsimchoni** [comment]
Thanks @yihui . I tried `build_site()`, I get the same result. Didn't change anything in the config.toml except for the `baseurl` parameter.

**Comment by yihui** [comment]
You mean you got the sae HTML files? You'd better restart your R session, or stop the local server you started via `serve_site()` before you `build_site()`.
 
Another thing you should know is that you cannot really load Disqus comments unless the page has really been published. Disques will check if a URL is accessible, e.g. if `http://my-site.com/2017/04/25/2017-04-25-name-of-post` is not a publicly accesible URL, Disqus will fail to load.

**Comment by gsimchoni** [comment]
Update: I realized what went wrong. I used `build_site()` followed by `serve_site()`. Shouldn't do that before publishing. Thanks!

**Comment by yihui** [comment]
No worries. This is a common confusion, and I'll definitely document it in the near future.
