### ISSUE TITLE
Camunda docs theme

### ISSUE THREAD

**Issue by ruaridhw** [rstudio/blogdown#96]
Currently unable to install this theme using `install_theme` on Windows.

Theme and installation instructions can be found [here](https://github.com/camunda/camunda-docs-theme)

Potential fix could be allowing branches other than [`master`](../blob/01fedcd22a3b511de0c718b12770d6107b6c42e0/R/hugo.R#L143) to be used in the install process?

**Comment by yihui** [comment]
Now you can use `install_theme('camunda/camunda-docs-theme@dist')`.

Note that theme has an obvious bug and I don't know why they didn't notice it: `cachedPartial` should be [`partialCached`](https://gohugo.io/templates/partials/) in https://github.com/camunda/camunda-docs-theme/blob/dist/layouts/partials/header.html

**Comment by ruaridhw** [comment]
Great, thanks!

Was wondering how to fix that HTML...
