### ISSUE TITLE
header option to ignore an .Rmd file / or ability to recognize alternate output format?

### ISSUE THREAD

**Issue by cboettig** [rstudio/blogdown#97]
Would it be possible to support an option in the yaml metadata of an .Rmd post which would tell blogdown not to build the file automatically?  

**Rationale**: Sometimes I want .Rmd files in my site repo that have alternative output formats, e.g. a `content/slides` directory that has .Rmd files which already use an `output:` command to specify some slide format (e.g. slides for a lecture).  I can knit these separately, but currently blogdown will compile these .Rmds as if they were regular posts, ignoring the requested output format and overwriting a previously-generated `html`.  It would be simplest and most convenient if blogdown just ignored these .Rmds, and then their original outputs can still be part of the website in unaltered form.  

Alternately, it would be nice if blogdown could recognize requested `output:` formats in yaml and render accordingly via rmarkdown, instead of following the usual knit command.

**Comment by yihui** [comment]
That makes perfect sense. I'll definitely think more about the possibility of ignoring certain Rmd files or respecting existing output formats. The latter is a little tricky, though, when you have R plots and HTML widgets generated from code chunks.

**Comment by RobertMyles** [comment]
This would be a nice option. Sometimes I have posts in development that are not knitting (maybe some error in the code, for example), it would be nice to ignore these when I run `serve_site()` .

**Comment by yihui** [comment]
@RobertMyles In your case, I think you can use the file extension `.Rmarkdown` instead of `.Rmd` before the post is ready to be compiled.

**Comment by RobertMyles** [comment]
@yihui Ah, I didn't know that I could do that! Thanks!

**Comment by yihui** [comment]
@RobertMyles I'm sorry but I want to make a change here and it will break my suggestion above. I'm hoping to reserve the extension `.Rmarkdown` for #165, and I wonder if you could move to other extensions like `.Rmkd` for the R Markdown documents that you do not want blogdown to compile.

**Comment by RobertMyles** [comment]
@yihui sure, no problem for me. I'm moving to the recommended blogdown-netlify workflow, so I'm not sure this would be an issue with that way of doing things anyway.

**Comment by yihui** [comment]
@RobertMyles You should be fine. This won't affect you in the blogdown-Netlify workflow. The only impact is that `.Rmarkdown` files will be compiled to Markdown instead of HTML. Previously they were ignored by blogdown. Thanks for giving me the freedom!

**Comment by yihui** [comment]
@cboettig Please read this section: https://bookdown.org/yihui/blogdown/static-files.html I think it should solve your problems. Note you need the latest version of blogdown here.

**Comment by cboettig** [comment]
What an elegant solution, thanks!

**Comment by yihui** [comment]
I finally came up with this idea last night and was quite happy with it. At the first glance at your issue a couple of months ago, I thought it would be a terrible mess and require quite a bit of changes in blogdown, but eventually it boiled down to one line of code :) So thanks for asking! This has boosted the usefulness of blogdown by 200%! 🎉 🎉 🎉

**Comment by ratnanil** [comment]
Can you guys let me in on the solution? I don't really understand how I can get blogdown to ignore certain .Rmd files by the link in https://github.com/rstudio/blogdown/issues/97#issuecomment-318754985

**Comment by cderv** [comment]
The solution is described in the link, i.e the book 
https://bookdown.org/yihui/blogdown/static-files.html

the `static` folder will allow you to store Rmd file not rendered by blogdown but by whatever other format you need. It allows to easily include a xaringan presentation for example. 
Otherwise, any file .Rmd file will be rendered by blogdown. You can change the extension too to ignore a file. 

Do not hesitate to ask such questions on https://community.rstudio.com. This is more suited than Github, all the more old issues. GH issue are preferred for bug report or feature request . 

Thanks!
