### ISSUE TITLE
serve_site() does not properly recognize changes to R Markdown files with a lowercase file extension

### ISSUE THREAD

**Issue by sharingtom** [rstudio/blogdown#98]
Hi,

When starting blogdown:::serve_site() the site is built as expected, but changes to *.rmd (as opposed to *.Rmd) are not recognized when blogdown:::serve_site() is already running; the Viewer is updated, but the site is not re-built.

I found this when I used the New Post Addin, which says it will create a *.Rmd file, but ends up creating a *.rmd file instead

![file extension issue](https://cloud.githubusercontent.com/assets/344822/25577572/4c537562-2e67-11e7-82fd-837c25d70cbf.png)

```
> blogdown:::new_post_addin()
Loading required package: shiny

Listening on http://127.0.0.1:7365
E:\git\blog\content\post\2017-05-01-file-extension-issue.rmd created
```

System:

- Windows 10
- RStudio 1.0.136
- bookdown 0.3.18
- blogdown 0.0.31

**Comment by yihui** [comment]
Should be fixed now. Please reinstall blogdown. Thanks for the report!
