### ISSUE TITLE
"Error in download" with new_site()

### ISSUE THREAD

**Issue by mtmx** [rstudio/blogdown#99]
Hi,
Thanks for this great package which i'm looking forward to use !

new_site() function returns me this error :
Error in download(method = "curl", extra = "-L") : 
  arguments inutilisés (method = "curl", extra = "-L")
  
Hugo has been installed via homebrew and seems ok.

sessionInfo()   
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Yosemite 10.10.5

**Comment by yihui** [comment]
R 3.4.0 should be fine, but I just fixed it for lower versions of R anyway. Thanks for the report!

**Comment by mtmx** [comment]
Great, works for R 3.3.2 too, thanks for the quick answer.
